Azure/azure-cosmos-dotnet-v3

Microsoft.Azure.Cosmos.Samples/CodeSamples/ServerSideScripts/JS/OrderBy.js
I haven't tested it at all.
BTW, it seems there's still a chance that setBody will fail with the REQUEST_ENTITY_TOO_LARGE error.
=> Fixed code sample

Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj
merge when direct revision version 5 is released
=> bump revision to 5

Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosContainerSettings.cs, Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosDatabaseSettings.cs, Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosStoredProcedureSettings.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/StoredProcedureTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SettingsContractTests.cs
LastModified is added to CosmosDatabaseSettigns, CosmosContainerSettings, ComsosStoredProcedureSettings. Related unitests also included.
=> Adding LastModified to Settings Contracts

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TransportWrapperTests.cs
Transprot wrapper contract test
=> Transport wrapper contract test

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.AggregateMixedTypes_baseline.xml
Fixing TestQueryCrossPartitionAggregateFunctionsWithMixedTypes
Change getting ported from master PR
=> Fixing QueryCrossPartitionAggregateFunctionsWithMixedTypes

Microsoft.Azure.Cosmos.Samples/CodeSamples/AzureFunctions/AzureFunctions.csproj, Microsoft.Azure.Cosmos.Samples/CodeSamples/AzureFunctions/AzureFunctionsCosmosClient.cs, Microsoft.Azure.Cosmos.Samples/CodeSamples/AzureFunctions/Models/Item.cs, Microsoft.Azure.Cosmos.Samples/CodeSamples/AzureFunctions/Startup.cs
Updating Azure Functions sample to use the new Dependency Injection module
=> Updating Azure Functions samples

Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
Refreshing with next SDK version number. 
Direct dependency raised to 3.0.0.27-preview.
SDK and Direct dependency are locked to specific versions.
=> SDK version to 3.0.0.12-preview

Microsoft.Azure.Cosmos/src/Resource/Conflict/CosmosConflict.cs, Microsoft.Azure.Cosmos/src/Resource/Conflict/CosmosContainer.Conflict.cs, Microsoft.Azure.Cosmos/src/Resource/Conflict/CosmosContainerCore.Conflict.cs, Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosAccountSettings.cs, Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosConflictSettings.cs, Microsoft.Azure.Cosmos/src/Resource/Settings/OperationKind.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ResultSetIteratorTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SettingsContractTests.cs
Correcting setter accessor for `CosmosConflicts`
=> Internal setters for Conflicts

Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs, Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
Changes contains adding batch operation when getting the Http method and adding batch operation to make the request a feed request.
Signed-off-by: Rakesh Kumar <rakkuma@microsoft.com>
=> Changes for supporting batch api and direct and client version bump

Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj, Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainerCore.cs, Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainersCore.cs, Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabaseCore.cs, Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabasesCore.cs
The internal Friends dependency requires access to CosmosClientContext to unblock different scenarios. 
=> Making CosmosClientContext internal for Friends

Microsoft.Azure.Cosmos.Samples/CodeSamples/NuGet.config, Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj, Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainersCore.cs, Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabaseCore.cs, Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabasesCore.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTestsNp.cs
The internal Friends dependency requires access to CosmosClientContext to unblock different scenarios.
=> Porting to release branch making CosmosClientContext internal to unblock Friends

Microsoft.Azure.Cosmos/src/Json/JsonNavigator.JsonBinaryNavigator.cs, Microsoft.Azure.Cosmos/src/Json/JsonWriter.JsonBinaryWriter.cs, Microsoft.Azure.Cosmos/src/Json/JsonWriter.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonRoundtripTests.cs
Enabling same format round trip for binary encoding.
=> Roundtrip Optimization For Binary Encoding

Microsoft.Azure.Cosmos/src/Json/JsonNavigator.JsonBinaryNavigator.cs, Microsoft.Azure.Cosmos/src/Json/JsonWriter.JsonBinaryWriter.cs, Microsoft.Azure.Cosmos/src/Json/JsonWriter.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonRoundtripTests.cs
Porting the round trip optimization for binary encoding to release branch.
=> Roundtrip Optimization For Binary Encoding (#258) to release branch

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj
Signed-off-by: Rakesh Kumar <rakkuma@microsoft.com>
Emulator test direct version bump
.
=> Emulator test direct version bump

Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> Raising SDK version to 15 & Direct to 29

Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> Raising SDK version to 16 and direct to 29

Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs, Microsoft.Azure.Cosmos/src/IStoredProcedureResponse.cs, Microsoft.Azure.Cosmos/src/Linq/UserDefinedFunctionProvider.cs, Microsoft.Azure.Cosmos/src/RequestOptions/StoredProcedureRequestOptions.cs, Microsoft.Azure.Cosmos/src/Resource/Settings/ConflictResolutionMode.cs, Microsoft.Azure.Cosmos/src/Resource/Settings/ConflictResolutionPolicy.cs, Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosStoredProcedureSettings.cs, Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosTriggerSettings.cs, Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosUserDefinedFunctionSettings.cs, Microsoft.Azure.Cosmos/src/Resource/Settings/TriggerOperation.cs, Microsoft.Azure.Cosmos/src/Resource/Settings/TriggerType.cs, Microsoft.Azure.Cosmos/src/StoredProcedureResponse.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TriggersTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TestCommon.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientResourceUnitTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SettingsContractTests.cs
Moving script types into Scripts namespace
Closes #167
=> Moving script specific types into script namespace

Microsoft.Azure.Cosmos/src/Fluent/Settings/IndexingPolicyFluentDefinition.cs, Microsoft.Azure.Cosmos/src/Fluent/Settings/SpatialIndexFluentDefinition.cs, Microsoft.Azure.Cosmos/src/Resource/Settings/IndexingPolicy.cs, Microsoft.Azure.Cosmos/src/Resource/Settings/SpatialPath.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IndexingPolicyEqualityComparer.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/SpatialIndexFluentDefinitionTests.cs
Type rename of SpatialSpec to SpatialPath
closes #262
=> Type rename of SpatialSpec to SpatialPath

Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainer.cs, Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainerCore.cs, Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainers.cs, Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainersCore.cs, Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabases.cs, Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabasesCore.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosNotFoundTests.cs
Metadata {Create/Replace}AsStreamAsync updated to take settings as arguments
closes #320
=> Metadata {Create/Replace}AsStreamAsync updated to take settings as arguments

Microsoft.Azure.Cosmos/src/CosmosClient.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosVirtualUnitTest.cs
Add support for mock testing the CosmosClient
fixes #303
=> Add support to mock the cosmos client.

Microsoft.Azure.Cosmos.Samples/CodeSamples/ItemManagement/Program.cs, Microsoft.Azure.Cosmos.Samples/CodeSamples/Shared/Metadata.cs, Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItems.cs
This PR adds a sample and extends the `ReadItemAsync` method to mention system metadata properties:
* ttl
* _ts
* _etag
- [X ] New feature (non-breaking change which adds functionality)
This PR closes #334
=> Documentation: System properties (Json property documentation)

Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Utils/CosmosContainerExtensions.cs, Microsoft.Azure.Cosmos/src/CosmosClient.cs, Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs, Microsoft.Azure.Cosmos/src/CosmosJsonSerializer.cs, Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs, Microsoft.Azure.Cosmos/src/Fluent/Settings/CosmosContainerFluentDefinitionForCreate.cs, Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainer.cs, Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainerCore.cs, Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainers.cs, Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainersCore.cs, Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabase.cs, Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabaseCore.cs, Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabasesCore.cs, Microsoft.Azure.Cosmos/src/Resource/Offer/CosmosOfferResult.cs, Microsoft.Azure.Cosmos/src/Resource/Offer/CosmosOffers.cs, Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosDatabaseSettings.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/DynamicTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosNotFoundTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosReadFeedTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DirectRESTTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/NameRoutingTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/MockCosmosUtil.cs
AccountEndPoint -> EndPoint
throughput (arguments, properties) -> requestUnits
MSDN documentation references made culture neutral
TBD
=> Renaming: AccountEndPoint -> EndPoint, throughput paramaeter -> RequestUnits

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/DynamicTests.cs
Emulator has been fixed, this test should be re-enabled.
This PR will close #289
=> Re-enable TestReducePageSizeScenario

Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Utils/CosmosContainerExtensions.cs, Microsoft.Azure.Cosmos/src/Resource/Conflict/CosmosConflictsCore.cs, Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainer.cs, Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainerCore.cs, Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainers.cs, Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainersCore.cs, Microsoft.Azure.Cosmos/src/Resource/CosmosClientContext.cs, Microsoft.Azure.Cosmos/src/Resource/CosmosClientContextCore.cs, Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabase.cs, Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabaseCore.cs, Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabasesCore.cs, Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItems.cs, Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItemsCore.cs, Microsoft.Azure.Cosmos/src/Resource/Query/CosmosQueryClientCore.cs, Microsoft.Azure.Cosmos/src/Scripts/CosmosScriptsCore.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosHandlersTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosJsonSerializerTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosNotFoundTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosReadFeedTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Benchmarks/DocumentBenchmark.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosItemUnitTests.cs
[AsStream] in methods with both IN/OUT stream is confusing. 
Reverting back to just [Stream].
closes #361
=> Revert [AsStream] back to [Stream]

Microsoft.Azure.Cosmos/src/Fluent/Settings/CosmosContainerFluentDefinitionForCreate.cs, Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainer.cs, Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainerCore.cs, Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainers.cs, Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainersCore.cs, Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabase.cs, Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabaseCore.cs, Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabasesCore.cs, Microsoft.Azure.Cosmos/src/Resource/Offer/CosmosOfferResult.cs, Microsoft.Azure.Cosmos/src/Resource/Offer/CosmosOffers.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/DynamicTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosNotFoundTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosReadFeedTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DirectRESTTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/NameRoutingTests.cs
=> Rename requestUnits to requestUnitsPerSecond

Microsoft.Azure.Cosmos/src/CosmosClientBuilder.cs, Microsoft.Azure.Cosmos/src/CosmosClientConfiguration.cs, Microsoft.Azure.Cosmos/src/DocumentClient.cs, Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj, Microsoft.Azure.Cosmos/src/Query/CosmosQueryExecutionContextFactory.cs, Microsoft.Azure.Cosmos/src/Query/DefaultDocumentQueryExecutionContext.cs, Microsoft.Azure.Cosmos/src/Query/DocumentQueryExecutionContextBase.cs, Microsoft.Azure.Cosmos/src/Query/DocumentQueryExecutionContextFactory.cs, Microsoft.Azure.Cosmos/src/Query/QueryPartitionProvider.cs, Microsoft.Azure.Cosmos/src/Resource/Query/CosmosQueryClient.cs, Microsoft.Azure.Cosmos/src/Resource/Query/CosmosQueryClientCore.cs, Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosContainerSettings.cs, Microsoft.Azure.Cosmos/src/RetryOptions.cs, Microsoft.Azure.Cosmos/src/Routing/AddressResolver.cs, Microsoft.Azure.Cosmos/src/Routing/PartitionRoutingHelper.cs
Port 3.0.0.31 Direct to release
=> Port 3.0.0.31 Direct to release

Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
Raising SDK version to 3.0.0.17
=> Raising SDK version to 3.0.0.17

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.OnePartition.cs
OFFSET LIMIT Pushdown. just adding a test, since the implementation got wired up else where.
=> Offset limit push down hotfix

Microsoft.Azure.Cosmos.Samples/CodeSamples/AzureFunctions/AzureFunctions.csproj, Microsoft.Azure.Cosmos.Samples/CodeSamples/AzureFunctions/AzureFunctionsCosmosClient.cs, Microsoft.Azure.Cosmos.Samples/CodeSamples/AzureFunctions/Startup.cs, Microsoft.Azure.Cosmos.Samples/CodeSamples/ContainerManagement/ContainerManagement.csproj, Microsoft.Azure.Cosmos.Samples/CodeSamples/ContainerManagement/Program.cs, Microsoft.Azure.Cosmos.Samples/CodeSamples/DatabaseManagement/DatabaseManagement.csproj, Microsoft.Azure.Cosmos.Samples/CodeSamples/DatabaseManagement/Program.cs, Microsoft.Azure.Cosmos.Samples/CodeSamples/ItemManagement/ItemManagement.csproj, Microsoft.Azure.Cosmos.Samples/CodeSamples/ItemManagement/Program.cs, Microsoft.Azure.Cosmos.Samples/CodeSamples/NonPartitionContainerMigration/NonPartitionContainerMigration.csproj, Microsoft.Azure.Cosmos.Samples/CodeSamples/NonPartitionContainerMigration/Program.cs, Microsoft.Azure.Cosmos.Samples/CodeSamples/Queries/Program.cs, Microsoft.Azure.Cosmos.Samples/CodeSamples/Queries/Queries.csproj, Microsoft.Azure.Cosmos.Samples/CodeSamples/ServerSideScripts/JS/OrderBy.js, Microsoft.Azure.Cosmos.Samples/CodeSamples/ServerSideScripts/Program.cs, Microsoft.Azure.Cosmos.Samples/CodeSamples/ServerSideScripts/ServerSideScripts.csproj
This PR updates the samples for the new version, plus fixes an issue in one of the ServerScripts samples that caused an infinite loop.
=> Updating samples for 3.0.0.17

Microsoft.Azure.Cosmos/src/CosmosClient.cs, Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs, Microsoft.Azure.Cosmos/src/DocumentClient.cs, Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosClientTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TestCommon.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/MockCosmosUtil.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/RetryHandlerTests.cs
Added support for secure string to be passed in for the account key.
Please delete options that are not relevant
Closes #397
=> Add support for account key as secure string

Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
Raising SDK versions to 18 & Direct to 33
=> Raising SDK versions to 18 & Direct to 33

Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs, Microsoft.Azure.Cosmos/src/RequestOptions/ChangeFeedRequestOptions.cs, Microsoft.Azure.Cosmos/src/RequestOptions/ContainerRequestOptions.cs, Microsoft.Azure.Cosmos/src/RequestOptions/ItemRequestOptions.cs, Microsoft.Azure.Cosmos/src/RequestOptions/QueryRequestOptions.cs, Microsoft.Azure.Cosmos/src/RequestOptions/RequestOptions.cs, Microsoft.Azure.Cosmos/src/RequestOptions/StoredProcedureRequestOptions.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientResourceUnitTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosQueryRequestOptionsUniTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ResultSetIteratorTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/StandByFeedContinuationTokenTests.cs
FillRequestOptions -> PopulateRequestOptions and internal
=> FillRequestOptions -> PopulateRequestOptions and internal

Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Utils/CosmosContainerExtensions.cs, Microsoft.Azure.Cosmos/src/ClientOptions.cs, Microsoft.Azure.Cosmos/src/CosmosClient.cs, Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs, Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs, Microsoft.Azure.Cosmos/src/Resource/CosmosClientContext.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TestCommon.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/ChangeFeedEstimatorCoreTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/ChangeFeedProcessorCoreTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/MockCosmosUtil.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/RetryHandlerTests.cs
CosmosClientOptions -> ClientOptions
ClientOptions as optional argument to CosmosClient
=> ClientOptions changes

Microsoft.Azure.Cosmos.Samples/CodeSamples/ContainerManagement/Program.cs
Change requested during a call.
@chris-bowman 
=> replaced lazy by consistent indexing to get free socks :)

Microsoft.Azure.Cosmos/src/ClientOptions.cs
=> Fixing tests

Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQuery.cs, Microsoft.Azure.Cosmos/src/Resource/CosmosExtensions.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
This is follow up changes of https://github.com/Azure/azure-cosmos-dotnet-v3/pull/461
=> Linq follow up changes on FeedIterator

Microsoft.Azure.Cosmos.Samples/CodeSamples/ContainerManagement/Program.cs, Microsoft.Azure.Cosmos.Samples/CodeSamples/DatabaseManagement/Program.cs, Microsoft.Azure.Cosmos.Samples/CodeSamples/Handlers/Program.cs, Microsoft.Azure.Cosmos.Samples/CodeSamples/ItemManagement/Program.cs, Microsoft.Azure.Cosmos.Samples/CodeSamples/NonPartitionContainerMigration/Program.cs, Microsoft.Azure.Cosmos.Samples/CodeSamples/Queries/Program.cs, Microsoft.Azure.Cosmos.Samples/CodeSamples/ServerSideScripts/Program.cs
This PR will add the tag name to all the methods used on samples so that it can be refer in
docs as per https://review.docs.microsoft.com/en-us/help/contribute/code-in-docs?branch=master
=> Adding repo snippet code name tag for docs

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SampleCodeForDocs/ContainerDocsSampleCode.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SampleCodeForDocs/CustomDocsSampleCode.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SampleCodeForDocs/DatabaseDocsSampleCode.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SampleCodeForDocs/ItemDocsSampleCode.cs
This PR will add new folder and class files from docs code.
Going forward we will use this in all our snippet docs code
=> Added sample code for docs

Microsoft.Azure.Cosmos/src/SqlObjects/SqlFunctionCallScalarExpression.cs
Add missing system function ObjectToArray
=> Add _ObjectToArray system function

Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
Bump the direct and sdk version
=> Release direct version bump 3.0.0.16-preview

Microsoft.Azure.Cosmos.Samples/CodeSamples/AzureFunctions/AzureFunctions.csproj, Microsoft.Azure.Cosmos.Samples/CodeSamples/ContainerManagement/ContainerManagement.csproj, Microsoft.Azure.Cosmos.Samples/CodeSamples/ContainerManagement/Program.cs, Microsoft.Azure.Cosmos.Samples/CodeSamples/DatabaseManagement/DatabaseManagement.csproj, Microsoft.Azure.Cosmos.Samples/CodeSamples/DatabaseManagement/Program.cs, Microsoft.Azure.Cosmos.Samples/CodeSamples/Handlers/HandlerSample.csproj, Microsoft.Azure.Cosmos.Samples/CodeSamples/ItemManagement/ItemManagement.csproj, Microsoft.Azure.Cosmos.Samples/CodeSamples/ItemManagement/Program.cs, Microsoft.Azure.Cosmos.Samples/CodeSamples/NonPartitionContainerMigration/NonPartitionContainerMigration.csproj, Microsoft.Azure.Cosmos.Samples/CodeSamples/NonPartitionContainerMigration/Program.cs, Microsoft.Azure.Cosmos.Samples/CodeSamples/Queries/Program.cs, Microsoft.Azure.Cosmos.Samples/CodeSamples/Queries/Queries.csproj, Microsoft.Azure.Cosmos.Samples/CodeSamples/ServerSideScripts/Program.cs, Microsoft.Azure.Cosmos.Samples/CodeSamples/ServerSideScripts/ServerSideScripts.csproj
Updating samples to 3.0.0-rc1 version
=> Updating samples to 3.0.0-rc1 version

Microsoft.Azure.Cosmos/src/Fluent/Settings/ConflictResolutionDefinition.cs, Microsoft.Azure.Cosmos/src/Fluent/Settings/ContainerBuilder.cs, Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs, Microsoft.Azure.Cosmos/src/Resource/Settings/ConflictResolutionPolicy.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Fluent/ContainerSettingsTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/ContainerDefinitionForCreateTests.cs
Enabling disabled tests based on Emulator regressions
=> Enabling faulty tests

Microsoft.Azure.Cosmos/src/Handler/ResponseMessage.cs
GC.SuppressFinalize(this) should only be called if the class overrides the finalize method.
Put closes #440
=> Remove GC.SuppressFinalize from response message

Microsoft.Azure.Cosmos/src/SqlObjects/SqlFunctionCallScalarExpression.cs
=> add missing system function

Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
=> Making version GA 3.0.0

Microsoft.Azure.Cosmos.Samples/CodeSamples/AzureFunctions/AzureFunctions.csproj, Microsoft.Azure.Cosmos.Samples/CodeSamples/ContainerManagement/ContainerManagement.csproj, Microsoft.Azure.Cosmos.Samples/CodeSamples/DatabaseManagement/DatabaseManagement.csproj, Microsoft.Azure.Cosmos.Samples/CodeSamples/Handlers/HandlerSample.csproj, Microsoft.Azure.Cosmos.Samples/CodeSamples/ItemManagement/ItemManagement.csproj, Microsoft.Azure.Cosmos.Samples/CodeSamples/ItemManagement/Program.cs, Microsoft.Azure.Cosmos.Samples/CodeSamples/NonPartitionContainerMigration/NonPartitionContainerMigration.csproj, Microsoft.Azure.Cosmos.Samples/CodeSamples/Queries/Program.cs, Microsoft.Azure.Cosmos.Samples/CodeSamples/Queries/Queries.csproj, Microsoft.Azure.Cosmos.Samples/CodeSamples/ServerSideScripts/Program.cs, Microsoft.Azure.Cosmos.Samples/CodeSamples/ServerSideScripts/ServerSideScripts.csproj
Updating sample to use 3.0.0 GA nuget
=> Updated to 3.0.0 GA nuget

Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
Direct package version bump for Switzerland hotfix
=> 3.0.0.16 preview6 version bump

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosBasicQueryTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosSpatialTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqAttributeContractBaselineTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqGeneralBaselineTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqSQLTranslationBaselineTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqTranslationBaselineTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/BaseCosmosClientHelper.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Benchmarks/DocumentBenchmark.cs
Microsoft.Azure.Cosmos.Performance.Tests fixed with 404 exception
=> Misc:  404 exception handling fixes

Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
Preview features part of Nightly builds
=> Enabling preview features part of Nightly builds

Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
Nightly package missing date time
=> Nightly package missing date time

Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
Enabling preview and nightly builds SxS
=> Enabling preview and nightly builds SxS

Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.NetFramework.Tests/Microsoft.Azure.Cosmos.NetFramework.Tests.csproj, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Microsoft.Azure.Cosmos.Performance.Tests.csproj, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Microsoft.Azure.Cosmos.Tests.csproj
Bumping the direct version to 3.0.3 to fix the version
=> Bumping direct version to 3.0.3

Microsoft.Azure.Cosmos/src/Handler/RequestMessage.cs
Cross partition batch operation can also contain partition key range id which causes the debug validation to fail. Updated validation to match backend.
=> Updated debug check for batch operation

Microsoft.Azure.Cosmos.Samples/CodeSamples/Queries/Program.cs
I'm suggesting to change a minor typo error from the query example.
=> Fixing typo error.

Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj, changelog.md
Bump the version to 3.1.0 for the next release
=> Bump the version to 3.1.0

Microsoft.Azure.Cosmos.Samples/Usage/AzureFunctions/AzureFunctions.csproj, Microsoft.Azure.Cosmos.Samples/Usage/ContainerManagement/ContainerManagement.csproj, Microsoft.Azure.Cosmos.Samples/Usage/DatabaseManagement/DatabaseManagement.csproj, Microsoft.Azure.Cosmos.Samples/Usage/Handlers/HandlerSample.csproj, Microsoft.Azure.Cosmos.Samples/Usage/ItemManagement/ItemManagement.csproj, Microsoft.Azure.Cosmos.Samples/Usage/NonPartitionContainerMigration/NonPartitionContainerMigration.csproj, Microsoft.Azure.Cosmos.Samples/Usage/Queries/Queries.csproj, Microsoft.Azure.Cosmos.Samples/Usage/ServerSideScripts/JS/OrderBy.js, Microsoft.Azure.Cosmos.Samples/Usage/ServerSideScripts/Program.cs, Microsoft.Azure.Cosmos.Samples/Usage/ServerSideScripts/ServerSideScripts.csproj, Microsoft.Azure.Cosmos.Samples/Usage/Shared/Shared.csproj, PULL_REQUEST_TEMPLATE.md, README.md
Updating samples to use 3.1.0 nuget. Fixed a bug in scripts sample.
=> Updating samples to 3.1.0 nuget. 

CredScanSuppressions.json, azure-pipelines.yml, templates/build-test.yml, templates/emulator-setup.yml
=> Azure dev-ops YML pipelines

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.NetFramework.Tests/Microsoft.Azure.Cosmos.NetFramework.Tests.csproj, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonMicroBenchmarks.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonNavigatorTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonPerformanceTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonRoundtripTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Microsoft.Azure.Cosmos.Tests.csproj, azure-pipelines.yml, templates/build-test.yml
=> YML all GREEN for Unit Tests

azure-pipelines.yml
=> Enabling security scans

azure-pipelines-functional.yml
New functional pipeline which runs all tests
=> New functional pipeline

azure-pipelines-functional.yml, azure-pipelines.yml
Limiting Gated and Functional to Cosmos folder only
=> Limiting Gated and Functional to Cosmos folder only

azure-pipelines-functional.yml, azure-pipelines-nightly.yml, azure-pipelines.yml, templates/static-tools.yml
=> Nightly build refinements

azure-pipelines-nightly.yml
=> Nightly build refresh

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContractEnforcement.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/LocationCacheTests.cs
ContractBreak: Tracing first lines of diff
=> ContractBreak: Tracing first lines of diff

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TriggersTests.cs
Adding a pre-trigger test in an attempt to repo a user's issue.
=> Added pre-trigger test

Microsoft.Azure.Cosmos/contracts/API_3.0.0.txt, Microsoft.Azure.Cosmos/contracts/API_3.1.1.txt, Microsoft.Azure.Cosmos/contracts/API_3.2.0-preview.txt
Including published SDK contract
=> Including published SDK contract

Microsoft.Azure.Cosmos/src/AuthorizationHelper.cs
AuthorizationHelper instrumentation changes
=> AuthorizationHelper instrumentation changes

templates/build-test.yml, templates/static-tools.yml
Including component governance in builds
closes #688
=> Including component governance in builds

Microsoft.Azure.Cosmos/src/Fluent/Settings/ContainerDefinition.cs, Microsoft.Azure.Cosmos/src/Resource/Settings/ContainerProperties.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Fluent/ContainerSettingsTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
Deprecate TimeToLivePropertyPath
=> Deprecate TimeToLivePropertyPath

Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
Updated CosmosClientOptions.Serializer documentation to reflect current implementation. 
=> Update CosmosClientOptions serializer documentation

changelog.md
Fixing the changelog. Some of the items were inserted at the wrong release.
=> Fixed changelog

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Scenarios/GremlinScenarioTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Scenarios/GremlinScenarioTests_Binary.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Scenarios/GremlinScenarioTests_HybridRow.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Scenarios/GremlinScenarioTests_Text.cs
Refactored Gremlin scenario tests for maintainability.
Added Gremlin scenario test that exercises document modification using CosmosElement classes.
=> Added Gremlin scenario test for document modification using CosmosElement

changelog.md
Include deadlock fix details into change-log.
=> Include deadlock fix details into change-log

Microsoft.Azure.Cosmos/src/DocumentClient.cs, Microsoft.Azure.Cosmos/src/Handler/TransportHandler.cs, Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj, Microsoft.Azure.Cosmos/src/Regions.cs, Microsoft.Azure.Cosmos/src/Routing/ClientCollectionCache.cs, Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs, Microsoft.Azure.Cosmos/src/Routing/PartitionKeyRangeCache.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TestCommon.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Microsoft.Azure.Cosmos.Performance.Tests.csproj, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/AsyncCacheTest.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Microsoft.Azure.Cosmos.Tests.csproj, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/MockDocumentClient.cs
Upgrading to Direct 3.2.1 version
=> Upgrading to Direct 3.2.1 version

Microsoft.Azure.Cosmos/src/Serializer/CosmosSerializer.cs
Updating the CosmosSerializer comments to make it clearer on who owns disposing of the stream.
closes #771
=> Fixing CosmosSerializer comments

Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
The wrong protocol is being set for Gateway Mode.
=> Fix wrong Gateway connection protocol 

CODEOWNERS
=> Updating query PR ownership

Directory.Build.props, Microsoft.Azure.Cosmos/Directory.Build.props, Microsoft.Azure.Cosmos/src/Batch/BatchResponse.cs, Microsoft.Azure.Cosmos/src/Batch/PartitionKeyRangeBatchResponse.cs, Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj, Microsoft.Azure.Cosmos/src/Query/OrderByQuery/OrderByConsumeComparer.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Microsoft.Azure.Cosmos.Performance.Tests.csproj, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Microsoft.Azure.Cosmos.Tests.csproj
Internal source consumption related changes
1. Ability to override through Directory.Build.Props
2. Conditional nuget package inclusion
=> Internal source consumption related changes

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncBatcherTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncContainerExecutorTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/ItemBatchOperationStatisticsTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/PartitionKeyBatchResponseTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/PartitionKeyRangeBatchExecutionResultTests.cs
Recent PR merge collision caused tests to fail building.
=> Fixing diagnostics tests

Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs, Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs
Correction in ReadThroughputAsyn api docs
=> Correction in ReadThroughputAsyn api docs

Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs, Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json, changelog.md
Revert of #767 for 3.2.0 release
=> Revert #767

changelog.md
Update changelog for 3.2.0 release.
=> Update changelog for 3.2.0 release

changelog.md
To support using github for the release notes the retirement dates are getting added to the changelog.
https://github.com/MicrosoftDocs/azure-docs-pr/pull/88938
=> Adding release and retirement date to changelog

Microsoft.Azure.Cosmos/src/Query/CosmosQueryContext.cs, Microsoft.Azure.Cosmos/src/Query/CosmosQueryContextCore.cs, Microsoft.Azure.Cosmos/src/Query/PipelinedDocumentQueryExecutionContext.cs, Microsoft.Azure.Cosmos/src/Query/QueryIterator.cs, Microsoft.Azure.Cosmos/src/RequestOptions/QueryRequestOptions.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosQueryUnitTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/MockQueryFactory.cs
Enable GROUP BY queries on the client side. No change made to the public surface area. Backend still needs to enable the config.
=> Enabling client side GROUP BY

changelog.md
Fixing the missing links in the changelog
=> Fixing links in changelog

changelog.md
Adding preview releases to changelog so user can see what new features are enabled in each release.
=> Update change log to include preview releases

Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
Fix VerifyNegativeWebProxySettings
=> Fix VerifyNegativeWebProxySettings

Microsoft.Azure.Cosmos.Samples/Usage/Handlers/HandlerSample.csproj, Microsoft.Azure.Cosmos.Samples/Usage/Handlers/Program.cs, Microsoft.Azure.Cosmos.Samples/Usage/Handlers/SchemaValidationHandler.cs
This PR adds a sample request handler that validates written items against JSON schemas.
=> Added schema validation handler sample

Microsoft.Azure.Cosmos.Samples/Usage/AzureFunctions/AzureFunctions.csproj, Microsoft.Azure.Cosmos.Samples/Usage/ChangeFeed/ChangeFeed.csproj, Microsoft.Azure.Cosmos.Samples/Usage/ContainerManagement/ContainerManagement.csproj, Microsoft.Azure.Cosmos.Samples/Usage/CustomSerialization/CustomSerialization.csproj, Microsoft.Azure.Cosmos.Samples/Usage/DatabaseManagement/DatabaseManagement.csproj, Microsoft.Azure.Cosmos.Samples/Usage/Handlers/HandlerSample.csproj, Microsoft.Azure.Cosmos.Samples/Usage/ItemManagement/ItemManagement.csproj, Microsoft.Azure.Cosmos.Samples/Usage/ItemManagement/Program.cs, Microsoft.Azure.Cosmos.Samples/Usage/NonPartitionContainerMigration/NonPartitionContainerMigration.csproj, Microsoft.Azure.Cosmos.Samples/Usage/Queries/Program.cs, Microsoft.Azure.Cosmos.Samples/Usage/Queries/Queries.csproj, Microsoft.Azure.Cosmos.Samples/Usage/ServerSideScripts/ServerSideScripts.csproj
Updated samples to 3.2.0 and added diagnostics examples
=> Updated samples to 3.2.0 and added diagnostics examples

Microsoft.Azure.Cosmos.Samples/Usage/Cosmos.Samples.Usage.sln, Microsoft.Azure.Cosmos.Samples/Usage/IndexManagement/IndexManagement.csproj, Microsoft.Azure.Cosmos.Samples/Usage/IndexManagement/Program.cs
Porting missing Index Management samples from V2.
Closes #794
=> Adding IndexManagement samples

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Fluent/ContainerSettingsTests.cs
New collection creations return all Spatial Index Types.
=> Spatial Index contract change

Microsoft.Azure.Cosmos/src/BulkPartitionKeyRangeGoneRetryPolicy.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncContainerExecutorTests.cs
Bulk flow should retry on NameStale Cache, this PR modifies the retry policy to cover that case and adds a UT to verify it.
=> Bulk retry on namestale

azure-pipelines-official.yml
Pruning Official pipelines to very basic working part
=> Pruning Official pipelines to very basic working part

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDiagnosticsTests.cs
This fixes the QueryOperationDiagnostic. The backend changed to where it might return the same item on distinct queries. Query only guarantees distinct in a single page.
=> Fixed the QueryOperationDiagnostic test

Microsoft.Azure.Cosmos/Directory.Build.props, changelog.md
Update the version and changelog to 3.3.0
=> Update version and changelog

Microsoft.Azure.Cosmos/contracts/API_3.2.0.txt, Microsoft.Azure.Cosmos/contracts/API_3.3.0.txt
=> 3.3.0 Contracts refresh

Microsoft.Azure.Cosmos.Samples/Usage/AzureFunctions/AzureFunctions.csproj, Microsoft.Azure.Cosmos.Samples/Usage/ChangeFeed/ChangeFeed.csproj, Microsoft.Azure.Cosmos.Samples/Usage/ContainerManagement/ContainerManagement.csproj, Microsoft.Azure.Cosmos.Samples/Usage/CustomSerialization/CustomSerialization.csproj, Microsoft.Azure.Cosmos.Samples/Usage/DatabaseManagement/DatabaseManagement.csproj, Microsoft.Azure.Cosmos.Samples/Usage/Handlers/HandlerSample.csproj, Microsoft.Azure.Cosmos.Samples/Usage/IndexManagement/IndexManagement.csproj, Microsoft.Azure.Cosmos.Samples/Usage/ItemManagement/ItemManagement.csproj, Microsoft.Azure.Cosmos.Samples/Usage/NonPartitionContainerMigration/NonPartitionContainerMigration.csproj, Microsoft.Azure.Cosmos.Samples/Usage/Queries/Queries.csproj, Microsoft.Azure.Cosmos.Samples/Usage/ServerSideScripts/ServerSideScripts.csproj
Update the samples to use the latest 3.3.0 release
=> Bump the samples to version 3.3.0

Microsoft.Azure.Cosmos/Directory.Build.props, changelog.md
Bumping the version to 3.3.1 for hot fix and updated changelog
=> Bump version to 3.3.1 and update changelog

changelog.md
Fixed the changelog version number
=> Fixed 3.3.1 version number

Microsoft.Azure.Cosmos.Samples/Usage/AzureFunctions/AzureFunctions.csproj, Microsoft.Azure.Cosmos.Samples/Usage/ChangeFeed/ChangeFeed.csproj, Microsoft.Azure.Cosmos.Samples/Usage/ContainerManagement/ContainerManagement.csproj, Microsoft.Azure.Cosmos.Samples/Usage/CustomSerialization/CustomSerialization.csproj, Microsoft.Azure.Cosmos.Samples/Usage/DatabaseManagement/DatabaseManagement.csproj, Microsoft.Azure.Cosmos.Samples/Usage/Handlers/HandlerSample.csproj, Microsoft.Azure.Cosmos.Samples/Usage/IndexManagement/IndexManagement.csproj, Microsoft.Azure.Cosmos.Samples/Usage/ItemManagement/ItemManagement.csproj, Microsoft.Azure.Cosmos.Samples/Usage/NonPartitionContainerMigration/NonPartitionContainerMigration.csproj, Microsoft.Azure.Cosmos.Samples/Usage/Queries/Queries.csproj, Microsoft.Azure.Cosmos.Samples/Usage/ServerSideScripts/ServerSideScripts.csproj
Updating samples to 3.3.1 nuget
=> Update samples to 3.3.1

Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs, Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json, changelog.md
Making Bulk related configurations public.
Related to #584
=> Bulk execution mode public

Microsoft.Azure.Cosmos/src/CosmosClient.cs, Microsoft.Azure.Cosmos/src/IDocumentClient.cs, Microsoft.Azure.Cosmos/src/Linq/DocumentClientQueryable.cs, Microsoft.Azure.Cosmos/src/Linq/UserDefinedFunctionProvider.cs, Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs, Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs
Container and database query API's documentation refreshed with remarks for single database/container read scenarios.
=> Container and database query API's documentation refreshed with remarks

Microsoft.Azure.Cosmos/Directory.Build.props
Bumping the direct version to 3.4.1-EN20190919 .
=> Bumped the direct version to 3.4.1-EN20190919

Microsoft.Azure.Cosmos/src/CosmosClient.cs, Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
This PR has changes to expose session container in CosmosClientOptions
=> Exposing SessionContainer in CosmosClientOptions

Microsoft.Azure.Cosmos/Directory.Build.props, changelog.md
Updated the version to 3.3.3 for a hot fix release
=> Updated to version 3.3.3

azure-pipelines-official.yml
Add condition to handle empty version (Ported from v4 branch)
=> Add condition to handle empty version

README.md, changelog.md
Updating vNext README and changelog
=> Updating README and changelog

Microsoft.Azure.Cosmos/contracts/API_3.4.0.txt
=> Including V3.4.0 contract

Microsoft.Azure.Cosmos/Directory.Build.props, changelog.md
=> Bump SDK version to 3.4.0

azure-pipelines-official-v4.yml
Variable needs to be removed in order to be overridable on each build queue.
=> Updating vNext YML release pipeline

azure-pipelines-official.yml
`BlobVersion` needs to be taken out in order to have the expected default value.
=> Release pipeline fix

changelog.md
Adding key differences with V3 based on Azure SDK guidelines
=> V4 changelog - add V3 key differences

changelog.md
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
=> Removing locale for docs build pipeline

Microsoft.Azure.Cosmos/Directory.Build.props, changelog.md
Bump direct version 3.4.2. This removes debug statements from the direct package.
=> Bumped direct version to 3.4.2

Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
=> Query Correct Response Length

Microsoft.Azure.Cosmos/Directory.Build.props, changelog.md
Bumping the SDK version 3.5.0 for the next release
=> Bump version to 3.5.0

Microsoft.Azure.Cosmos/src/CosmosElements/CosmosElementSerializer.cs, Microsoft.Azure.Cosmos/src/Linq/ExpressionToSQL.cs, Microsoft.Azure.Cosmos/src/Query/Core/DistinctMap.UnorderedDistinctMap.cs, Microsoft.Azure.Cosmos/src/Query/Core/QueryPartitionProvider.cs, Microsoft.Azure.Cosmos/src/Query/Core/UInt128.cs, Microsoft.Azure.Cosmos/src/Query/v2Query/DocumentQueryExecutionContextBase.cs, Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs, Microsoft.Azure.Cosmos/src/Serializer/CosmosSerializationFormatOptions.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Removing miscellaneous ToArray calls to avoid allocations.
=> Removed ToArray() Calls

Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
Fixed grammar in stream exception
closes #1052
=> Fixed grammar in stream exception

Microsoft.Azure.Cosmos/src/Query/Core/QueryResponseFactory.cs
Other types of excepted exceptions could have inner exceptions leading to them getting unwrapped and becoming 500s. The fix was to first check if it's a known exception type. If not, then unwrap and retry. 
- [ x] Bug fix (non-breaking change which fixes an issue)
=> Fixed Query Exception To Response with Inner Exception

Microsoft.Azure.Cosmos/Directory.Build.props, changelog.md
Bumping the version to 3.5.1 with several hotfixes.
=> Bumped version to 3.5.1

Microsoft.Azure.Cosmos/contracts/API_3.5.0.txt
=> 3.5.0 API contract addition

Microsoft.Azure.Cosmos/src/Resource/Settings/BoundingBoxProperties.cs, Microsoft.Azure.Cosmos/src/Resource/Settings/SpatialPath.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IndexingPolicyTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json, changelog.md
Updating changelog for geometry client changes
=> Update change log for geometry client changes

Microsoft.Azure.Cosmos/src/CosmosClient.cs, Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQuery.cs, Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQueryProvider.cs, Microsoft.Azure.Cosmos/src/Query/v3Query/FeedIteratorInlineCore.cs, Microsoft.Azure.Cosmos/src/Resource/Conflict/ConflictsInlineCore.cs, Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInlineCore.cs, Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseInlineCore.cs, Microsoft.Azure.Cosmos/src/Resource/Scripts/ScriptsInlineCore.cs, Microsoft.Azure.Cosmos/src/Resource/User/UserInlineCore.cs, Microsoft.Azure.Cosmos/src/Serializer/CosmosSerializerCore.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/SynchronizationContextTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json, changelog.md
Fixed sync deadlock for all the feed iterators, and some database operation on the cosmos client. 
Put closes #1101
=> Fixed sync deadlock for query FeedIterator

Microsoft.Azure.Cosmos/src/CosmosClient.cs, Microsoft.Azure.Cosmos/src/FeedIterator.cs, Microsoft.Azure.Cosmos/src/FeedIteratorOfT.cs, Microsoft.Azure.Cosmos/src/Resource/Conflict/Conflicts.cs, Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs, Microsoft.Azure.Cosmos/src/Resource/Scripts/Scripts.cs, Microsoft.Azure.Cosmos/src/Resource/User/User.cs, README.md
There has been several issues around customer's not properly draining queries. Adding additional samples to the comments on various methods and classes on how to properly drain the query.
=> Adding more comment sample to query

Microsoft.Azure.Cosmos/azuredata/Azure.Cosmos.csproj, changelog.md
Updating changelog and package details for the 4.0.0-preview2 release
=> [vNext] 4.0.0-preview2 release

Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
PublishRepositoryUrl conditonal for public use only
=> PublishRepositoryUrl conditonal for public use only

Microsoft.Azure.Cosmos/src/FeedIteratorCore.cs, Microsoft.Azure.Cosmos/src/FeedIteratorInteralOfT.cs, Microsoft.Azure.Cosmos/src/FeedIteratorInternal.cs, Microsoft.Azure.Cosmos/src/Query/Core/Monads/Either.cs, Microsoft.Azure.Cosmos/src/Query/Core/Monads/ExceptionWithStackTraceException.cs, Microsoft.Azure.Cosmos/src/Query/Core/Monads/TryCatch.cs, Microsoft.Azure.Cosmos/src/Query/Core/Monads/TryCatch{TResult}.cs, Microsoft.Azure.Cosmos/src/Query/Core/QueryClient/QueryResponseCore.cs, Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/PartitionedQueryExecutionInfo.cs, Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/PartitionedQueryExecutionInfoInternal.cs, Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryFeature.cs, Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryInfo.cs, Microsoft.Azure.Cosmos/src/Query/v3Query/QueryIterator.cs, Microsoft.Azure.Cosmos/src/Query/v3Query/QueryResponse.cs
This reverts commit d15be41f40d8299ed45f8bca6c96f6e574223500.
Fix for master bud break
=> Revert "Made Query Types Public With Macro (#1082)"

Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj, Microsoft.Azure.Cosmos/src/Query/Core/Metrics/TextTable.cs
=> Master build related fixes

Microsoft.Azure.Cosmos/src/CosmosClient.cs
adding comment about default appsettings impact
=> Adding comment about default appsettings impact

Microsoft.Azure.Cosmos/src/Json/JsonNavigator.JsonTextNavigator.cs, Microsoft.Azure.Cosmos/src/Query/Core/ExecutionContext/OrderBy/CosmosOrderByItemQueryExecutionContext.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/ContinuationTokens/OrderByContinuationTokenTests.cs
Fix remaining bugs to get order by working with continuation tokens for extended types
- [ x] Bug fix (non-breaking change which fixes an issue)
=> Fix Orderby Continuation'

Microsoft.Azure.Cosmos/src/Batch/BatchAsyncContainerExecutor.cs, Microsoft.Azure.Cosmos/src/Batch/BatchExecUtils.cs, Microsoft.Azure.Cosmos/src/Batch/ItemBatchOperation.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchUnitTests.cs
Allow the ability to send PK and EPK together in batch
- [ x] New feature (non-breaking change which adds functionality)
None
=> Add option to send PK to the backend with EPK

Microsoft.Azure.Cosmos.Samples/Usage/Cosmos.Samples.Usage.sln, Microsoft.Azure.Cosmos.Samples/Usage/UserManagement/Program.cs, Microsoft.Azure.Cosmos.Samples/Usage/UserManagement/UserManagement.csproj, Microsoft.Azure.Cosmos.Samples/Usage/UserManagement/UserManagementProgram.cs
Adding user and permission samples
closes #1142
=> Adding user and permission samples

Microsoft.Azure.Cosmos/Directory.Build.props, changelog.md
Updating the build for 3.6.0 release
=> 3.6.0 release update

Microsoft.Azure.Cosmos/contracts/API_3.6.0.txt
New items in the contract:
```
public sealed class BoundingBoxProperties
{
public BoundingBoxProperties();
public double Xmax { get; set; }
public double Xmin { get; set; }
public double Ymax { get; set; }
public double Ymin { get; set; }
}
public class ContainerProperties
{
public ContainerProperties();
public ContainerProperties(string id, string partitionKeyPath);
public ConflictResolutionPolicy ConflictResolutionPolicy { get; set; }
public Nullable<int> DefaultTimeToLive { get; set; }
public string ETag { get; }
// Only new property
public GeospatialConfig GeospatialConfig { get; set; }
public string Id { get; set; }
public IndexingPolicy IndexingPolicy { get; set; }
public Nullable<DateTime> LastModified { get; }
public Nullable<PartitionKeyDefinitionVersion> …
```
=> Adding 3.6.0 contract

README.md
Two variables with name 'response' were declared in the csharp example.
In the csharp example, two variables with the name 'response' are declared.
@billpratt
=> Fixed csharp example

Microsoft.Azure.Cosmos/src/Query/Core/ComparableTask/ComparableTaskScheduler.cs
Observe Exceptions in Comparable Task Scheduler
=> Observe Exceptions in Comparable Task Scheduler

Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
Allow passing in sessioncontainer to ClientOptions
=> Session container for SQL

changelog.md
Updating Change Log to reflect 3.7.0-preview release
=> 3.7.0-preview release

templates/static-tools.yml
CredScan service is currently having issues. This PR disables the CredScan until the issue is resolved to unblock the CI pipeline.
=> Disable CredScan to unblock CI pipeline.

changelog.md
=> 3.7.0-preview2 Changelog

Microsoft.Azure.Cosmos/Directory.Build.props, Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosExceptionFactory.cs, Microsoft.Azure.Cosmos/src/Util/Extensions.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Mocks/MockDocumentClient.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Mocks/MockRequestHelper.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ExceptionlessTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/RequestEventHandlerTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/StoreReaderTest.cs
Bumping the direct version to take fixes and optimizations.
=> Direct bump to version 3.7.1 

Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.cs, Microsoft.Azure.Cosmos/src/Json/JsonReader.JsonTextReader.cs, Microsoft.Azure.Cosmos/src/Linq/BuiltinFunctions/ChangeFeedQuery.cs, Microsoft.Azure.Cosmos/src/Number64.cs, Microsoft.Azure.Cosmos/src/Query/Core/ExecutionComponent/Aggregate/AggregateDocumentQueryExecutionComponent.cs, Microsoft.Azure.Cosmos/src/Query/Core/ExecutionComponent/Aggregate/Aggregators/AggregateItem.cs, Microsoft.Azure.Cosmos/src/Query/Core/ExecutionContext/OrderBy/OrderByQueryResult.cs, Microsoft.Azure.Cosmos/src/Query/Core/Metrics/TextTable.cs, Microsoft.Azure.Cosmos/src/Query/Core/QueryClient/ContainerQueryProperties.cs, Microsoft.Azure.Cosmos/src/Query/Core/QueryClient/QueryResponseCore.cs, Microsoft.Azure.Cosmos/src/Query/Core/UInt128.cs, Microsoft.Azure.Cosmos/src/Query/v2Query/DocumentQueryExecutionContextBase.cs, Microsoft.Azure.Cosmos/src/Routing/PartitionRoutingHelper.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/BaselineTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CustomSerializationTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DynamicQueryable.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/GatewayTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/OfferTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/AggregateQueryTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/BaselineTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ExceptionlessTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonExecutionTimes.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonNewtonsoftNavigator.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/TestHandler.cs
Made structs in the code base readonly. There really isn't a reason for a struct to not be readonly, since they should immutable to begin with.
=> Made Structs Readonly

Microsoft.Azure.Cosmos/contracts/API_3.7.0.txt
Adding 3.7.0 contract changes.
=> Adding 3.7.0 contract changes

changelog.md
=> Update changlog with 3.7.0 release

Microsoft.Azure.Cosmos/Directory.Build.props, changelog.md
Preparing for 3.7.1-preview release
=> 3.7.1-preview release notes

CODEOWNERS
Updating code ownership to add all .NET crew to as owners.
=> Update code ownership

CODEOWNERS
Moving kirillg up with the rest of the .NET team to avoid blocking on just sign-off.
=> Updating codeownership

PULL_REQUEST_TEMPLATE.md
Fixed PR template title examples
=> PR template: Fix examples of valid PR titles

.github/workflows/prlint.yml, PULL_REQUEST_TEMPLATE.md, azure-pipelines-v4.yml, azure-pipelines.yml
Porting https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1322 to V4
=> [vNext] PR Requirements: Add PR title requirements for changelog generation

Microsoft.Azure.Cosmos/contracts/API_3.8.0.txt, changelog.md
Adding the release notes for 3.8.0 and base contract.
Differences with 3.7.0:
=> Internal: Add 3.8.0 release notes

Microsoft.Azure.Cosmos/Directory.Build.props
Updates base build files to align with 3.8.0 release.
=> [Internal] API Version: Fix version for 3.8.0 release

Microsoft.Azure.Cosmos/Directory.Build.props
Correcting version on base file.
=> [Internal] API Version: Fix version number for release

Microsoft.Azure.Cosmos/src/Resource/Settings/UniqueKey.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContractEnforcement.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/UniqueKeyDefinitionTests.cs
Enable Uniquekey extensibility through unsealing (future proofing)
=> UniqueKey: Add Uniquekey extensibility through unsealing

README.md
Fixing the example to match the class renames.
Closes #1361
=> [Internal] Documentation: (Fix) README example

Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs, Microsoft.Azure.Cosmos/src/Resource/Offer/CosmosOffers.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosThroughputTests.cs
1. Added missing and adding Container.ReplaceThroughputPropertiesIfExistsAsync 
2. Fixed ReplaceThroughputPropertiesIfExists bug that caused a cosmos exception if the offer is not found.
3. Added additional tests
=> [Internal] Autoscale: Add Container.ReplaceThroughputPropertiesIfExistsAsync 

Microsoft.Azure.Cosmos/Directory.Build.props
=> Preview Version: Add SDK preview version

Microsoft.Azure.Cosmos/src/CosmosClient.cs, Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs, Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs, Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInlineCore.cs, Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs, Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs, Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseInlineCore.cs, Microsoft.Azure.Cosmos/src/Resource/Settings/ThroughputProperties.cs
Adding autoscale API to public preview release. 
NOTE: Migration scenarios are not supported.
=> Autoscale Preview: Add to public preview release

Microsoft.Azure.Cosmos/Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.8.0-preview.txt, Microsoft.Azure.Cosmos/contracts/API_3.8.1-preview.txt, Microsoft.Azure.Cosmos/contracts/API_3.9.0-preview.txt, Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs, Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs, Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInlineCore.cs, Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs, Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs, Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseInlineCore.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosThroughputTests.cs, changelog.md
Bumping the preview version to 3.9.0-preview
Updating autoscale to api and bumping the preview release.
closes #1330, #1365
=> Autoscale: Add preview release 3.9.0

azure-pipelines-encryption.yml
This PR adds Azure Pipeline support for releasing `Microsoft.Azure.Cosmos.Encryption`.
=> [Internal] Pipeline: Add Microsoft.Azure.Cosmos.Encryption release pipeline

Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs, azure-pipelines.yml, templates/build-preview.yml
This adds a build with the preview flag as part of the checks to ensure that preview build is always valid.
=> [Internal] Preview Build: Add preview build as part of gates

.github/workflows/prlint.yml
=> [Internal] Pull Request: Fix the pull request title validation

Microsoft.Azure.Cosmos/Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.9.1-preview.txt
Bump the preview API version to 3.9.1 and add 3.9.1 preview contract
=> 3.9.1-Preview: Add preview version 3.9.1

Microsoft.Azure.Cosmos/contracts/API_3.9.0-preview3.txt
Adding 3.9.0-preview3 API surface:
=> [Internal] Contract: Add 3.9.0-preview3 contract

changelog.md
Adding the items for 3.9.0-preview3.
=> [Internal] Changelog: Add 3.9.0 preview3 notes

Microsoft.Azure.Cosmos.Encryption/src/EncryptionContainer.cs, Microsoft.Azure.Cosmos.Encryption/src/EncryptionContainerExtensions.cs, Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/EncryptionTests.cs, Microsoft.Azure.Cosmos/Directory.Build.props
If EncryptionOptions is null, no need for encryption.
=> Client Encryption : Fix to not encrypt if EncryptionOptions is null

Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
RateLimitedRetries: fix code documentation refresh with details
=> RateLimitedRetries: Fix code documentation refresh with details

CODEOWNERS
Add owners for public contract changes.
=> Codowners: Add owner for public contract

changelog.md
Update changelog for 3.9.0 changes.
=> Changelog: Add 3.9.0 changes

Microsoft.Azure.Cosmos/Directory.Build.props, changelog.md
Bumping the preview version to do a hotfix release for the diagnostic [bug](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1539).
=> Version: Add 3.9.1 and 3.9.1-preview version

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/EnvironmentInformationTests.cs
This PR replaces Parallel.For since it looks like sometimes it might stop and not complete the list of iterations.
=> [Internal] Tests: Fix EnvironmentTest to use Tasks instead of Parallel

changelog.md
Add more context to the changelog about the regression.
=> Changelog: Add more context

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Benchmarks/MockedItemBenchmark.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Benchmarks/MockedItemOfTBenchmark.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Benchmarks/MockedItemStreamBenchmark.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Program.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/README.md
[Internal] PerfBenchmark: Add statistics and code cleanup
=> [Internal] PerfBenchmark: Add statistics and code cleanup

Microsoft.Azure.Cosmos.Samples/Usage/ItemManagement/Program.cs, Microsoft.Azure.Cosmos/src/RequestOptions/ItemRequestOptions.cs
1. Fixed the documentation for EnableContentResponseOnWrite
2. Added sample on how to use EnableContentResponseOnWrite
3. Added read all items samples
Put closes #1560, #1559
=> EnableContentResponseOnWrite documentation: Fix documentation and add samples

Microsoft.Azure.Cosmos/src/Diagnostics/CosmosClientSideRequestStatistics.cs, Microsoft.Azure.Cosmos/src/Handler/RetryHandler.cs, Microsoft.Azure.Cosmos/src/Query/Core/ExecutionContext/CatchAllCosmosQueryExecutionContext.cs, Microsoft.Azure.Cosmos/src/Resource/FeedIterators/FeedIteratorCore.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/NegativeQueryTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/DiagnosticValidators.cs
Query Response should not throw NullRef on CollectionNotFound or server errors.
=> [Internal] Diagnostics: Fix Minor Diagnostics and Query bugs

Microsoft.Azure.Cosmos.Encryption/src/EncryptionContainer.cs, Microsoft.Azure.Cosmos.Encryption/src/EncryptionFeedIterator.cs, Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs, Microsoft.Azure.Cosmos.Encryption/src/EncryptionTransactionalBatch.cs, Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj, Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/EncryptionTests.cs, Microsoft.Azure.Cosmos/Directory.Build.props
Ensure user can exercise encryption / decryption functionality using transactional batch requests.
=> Client Encryption : Add encryption support for transactional batch requests

README.md
Add descriptive scenarios for SDK usage.
=> [vNext] README: Add descriptive scenarios

Microsoft.Azure.Cosmos/azuredata/Resource/Container/CosmosContainer.cs, Microsoft.Azure.Cosmos/azuredata/Resource/Database/CosmosDatabase.cs
This PR fixes broken samples and makes sure that sample serialization is used with System.Text.Json and not Newtonsoft.Json
Closes #1590
Closes #1593
Closes #1591
=> [vNext] Documentation: Fix code samples 

README.md
=> [Internal] Documentation: Fix version on README

Microsoft.Azure.Cosmos/Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.10.0.txt, changelog.md
This PR bumps the SDK version to 3.10.0, updates the contract changes, and the changelog.
=> 3.10.0: Add changelog and new contract

TroubleshootingGuides/Exceptions.md
Fix the exception formatting to properly show the sub list.
=> Exception documentation: Fix formatting

Microsoft.Azure.Cosmos/Directory.Build.props, Microsoft.Azure.Cosmos/src/Handler/TransportHandler.cs, changelog.md
This reverts an accidental change that cause the transport handler to print the stack trace.
=> 3.10.1: Fix stack trace bug

Microsoft.Azure.Cosmos.Samples/Usage/ContainerManagement/Program.cs, Microsoft.Azure.Cosmos.Samples/Usage/DatabaseManagement/Program.cs, Microsoft.Azure.Cosmos.Samples/Usage/Handlers/Program.cs, Microsoft.Azure.Cosmos.Samples/Usage/IndexManagement/Program.cs, Microsoft.Azure.Cosmos.Samples/Usage/ItemManagement/Program.cs, Microsoft.Azure.Cosmos.Samples/Usage/NonPartitionContainerMigration/Program.cs, Microsoft.Azure.Cosmos.Samples/Usage/Queries/Program.cs, Microsoft.Azure.Cosmos.Samples/Usage/ServerSideScripts/Program.cs, Microsoft.Azure.Cosmos.Samples/Usage/UserManagement/UserManagementProgram.cs, Microsoft.Azure.Cosmos.Samples/Usage/appSettings.json, Microsoft.Azure.Cosmos/src/CosmosClient.cs, Microsoft.Azure.Cosmos/src/Handler/TransportHandler.cs, Microsoft.Azure.Cosmos/src/Linq/CosmosLinqExtensions.cs, Microsoft.Azure.Cosmos/src/Resource/Conflict/Conflicts.cs, Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs, Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs, Microsoft.Azure.Cosmos/src/Resource/FeedIterators/FeedIterator.cs, Microsoft.Azure.Cosmos/src/Resource/FeedIterators/FeedIterator{T}.cs, Microsoft.Azure.Cosmos/src/Resource/Permission/Permission.cs, Microsoft.Azure.Cosmos/src/Resource/Response.cs, Microsoft.Azure.Cosmos/src/Resource/Scripts/Scripts.cs, Microsoft.Azure.Cosmos/src/Resource/Settings/UserDefinedFunctionProperties.cs, Microsoft.Azure.Cosmos/src/Resource/User/User.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosBasicQueryTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseTests.cs, README.md
1. Add using statement to all FeedIterators in examples part of the comments
1. Add using statement to all FeedIterators in the samples
1. Add exception url to all async methods
1. Add additional examples to the database and container query stream iterator comments, and test to validate the new examples
1. Add more info the response.StatusCode to clarify it's usage.
=> Documentation & Samples: Add IDisposable to all examples & other improvements

README.md
Optimistic concurrency sample should show the need to retry the same modification.
=> [Internal] README: Fix optimistic concurrency sample

Microsoft.Azure.Cosmos/src/Query/Core/Metrics/QueryMetrics.cs
=> Internal QueryMetrics : Fix Access Modier

Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticsContextCore.cs
Fix build break caused by PR #1622 
=> Build: Fix build break caused by PR #1622

.github/workflows/prlint.yml, Microsoft.Azure.Cosmos/src/Routing/GlobalAddressResolver.cs, PULL_REQUEST_TEMPLATE.md
Updating the PR linter based on feedback. Cleaned up PR template to avoid the extra bloat.
=> [Internal] PR Lint: Fixes to use new title regex

.github/workflows/prlint.yml
PR to fix PR Lint which is currently returning: Unexpected input(s) 'repo-token', valid inputs are ['entryPoint', 'args', 'title-regex', 'on-failed-regex-comment']
=> [Internal] PR Lint: Fixes the yaml file

Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/Program.cs, Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/run.sh
- RunTime changed to 24Hours format
- Run script updates
> Limited to create, read only
> Run workload only once
> Operation count raised to 2M
=> [Internal] Benchmark: Fixes few misc fixes

CODEOWNERS
Add the same codowners for preview as for the public contract so they are treated as the same.
=> Codeowners: Fixes missing ownership

changelog.md
=> Changelog: Fixes heading format

changelog.md
=> Updating retirement date details

Microsoft.Azure.Cosmos/src/DocumentClient.cs
Fix PortReuseMode and other TCP setting in connection policy to be honored by DocumentClient
=> Transport: Fixes use of PortReuseMode and other Direct configuration settings

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.12.0.txt, changelog.md
This PR bumps the SDK version to 3.12.0. This adds the contract file and updates the changelog to the new version.
=> SDK : Adds 3.12.0 version and updates changelog

Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
Fixing a bad debug check that causes tests to fail when in debug mode.
=> [Internal] Tests: Fixes bad debug assert causing test failures.

CODEOWNERS
This adds a team so any Azure Cosmos DB LT can sign-off on public contracts. All public contract changes are still required to go through an API review with the SDK team. 
=> Codeowners: Adds new owners

Microsoft.Azure.Cosmos.Samples/Usage/Shared/Shared.csproj
This was a bug introduced by https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1731. The netstandard version should not have been bumped. It was done accidently assuming it was a net core app.
=> Samples: Fixes shared project build

SdkDesignGuidelines.md
Adding SDK guidelines to document all of the tribal knowledge for users contributing to the SDK.
=> Documentation: Adds SDK guidelines

Directory.Build.props, Microsoft.Azure.Cosmos.Encryption/changelog.md, Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs
Fix encryption serializer settings to make it more pass-through.
=> Encryption: Fixes serializer settings to make it more pass-through

Directory.Build.props
3.13.2 adds recent performance improvements from master.
=> Direct version: Adds version 3.13.2

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/QueryPlanBaselineTests.SystemFunctions.xml, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPlanBaselineTests.cs
Adds the following system functions to the service interop baseline:
* GetCurrentTicks
* DateTimeAdd
* DateTimeDiff
* DateTimeFromParts
* DateTimePart
* DateTimeToTicks
* DateTimeToTimestamp
* TicksToDateTime
* TimestampToDateTime
=> SystemFunctions : Adds DateTime System Functions

Microsoft.Azure.Cosmos/src/Routing/CollectionCache.cs, Microsoft.Azure.Cosmos/src/Routing/PartitionRoutingHelper.cs, Microsoft.Azure.Cosmos/src/SessionContainer.cs
Porting the SessionContainer optimizations from master. The is reduces lock content in the AddSession method by doing the  inner dictionary AddOrUpdate logic outside the GetOrAdd.  
Updated all version checks to use the new optimized `HttpConstants.VersionDates`
=> Performance: Adds SessionContainer optimizations and style fixes

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/GatewayTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryTests.cs, azure-pipelines-official.yml
Porting fixes for release pipeline.
Cherry picks: #1777 , #1791 
=> 3.11.1-Preview: Fixes release and emulator tests

changelog.md
This adds changelog notes for the 3.11.1-preview release
=> 3.11.1-preview: Adds changelog notes

Microsoft.Azure.Cosmos.Encryption/tests/Microsoft.Azure.Cosmos.Encryption.Tests/Contracts/DotNetSDKEncryptionAPI.json, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/ContractEnforcement.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
This adds method info like IsVirtual to the public contract files. This will prevent accidental breaking changes such as removing a virtual from a method.
=> [Internal] Contract validation: Adds method info to the contract

.github/workflows/prlint.yml
PR lint action is currently failing from a docker failure. This is fixed in the latest version.
=> Internal PR Lint: Fixes failure by bumping the version

Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs, Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/Parallel/ParallelCrossPartitionQueryPipelineStage.cs, Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/NameCacheStaleRetryQueryPipelineStage.cs
Signed-off-by: Floran Narenji <flnarenj@microsoft.com>
This change fixes some CancellationToken propagation following recent query changes.
=> Internal Query: Adds Fix for CancellationToken propagation

NuGet.config
Most packages come from nuget.org so it should be the first on the list.
=> Internal Nuget.config: Adds nuget.org as the primary

Directory.Build.props, changelog.md
This bumps the preview version 3.15.1. 
=> 3.15.1-preview: Adds hot fix version for Azure Active Directory changes

Microsoft.Azure.Cosmos/src/Pagination/NetworkAttachedDocumentContainer.cs, Microsoft.Azure.Cosmos/src/ReadFeed/Pagination/CrossPartitionReadFeedAsyncEnumerator.cs, Microsoft.Azure.Cosmos/src/ReadFeed/Pagination/ReadFeedPage.cs, Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs, Microsoft.Azure.Cosmos/src/Resource/FeedIterators/ReadFeedIteratorCore.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/FlakyDocumentContainer.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/InMemoryContainer.cs
Diagnostics can not be reused over multiple read next async calls.
=> Internal Diagnostics: Fixes ReadFeedDiagnostics.

Directory.Build.props, Microsoft.Azure.Cosmos.Encryption/changelog.md
Bump up the Encryption preview version to help release a new package.
=> Client Encryption : Adds upgrade to Encryption package to release a new version

Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj
Bump up the SDK version to 3.15.2-preview for Encryption package.
=> Client Encryption : Adds upgrade to SDK version to 3.15.2-preview for Encryption package

Microsoft.Azure.Cosmos/src/Json/JsonReader.JsonBinaryReader.cs
One missing check from a previous PR to get more helpful error message in the case we encounter malformed TypedJSON.
=> Internal Mongo: Adds scope bound check to TypedJSON helper

Microsoft.Azure.Cosmos/src/Patch/PatchConstants.cs
Minor update at backend
a minor update at backend is done that needs a update on SDK side.
Basically inc for increment is now changed to incr
=> [Internal] Patch: Fixes JSON Patch Syntax

Microsoft.Azure.Cosmos/src/Json/IJsonReader.cs, Microsoft.Azure.Cosmos/src/Json/ITypedJsonReader.cs, Microsoft.Azure.Cosmos/src/Json/Interop/NewtonsoftToCosmosDBReader.cs, Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.Strings.cs, Microsoft.Azure.Cosmos/src/Json/JsonReader.JsonBinaryReader.cs, Microsoft.Azure.Cosmos/src/Json/JsonReader.JsonTextReader.cs, Microsoft.Azure.Cosmos/src/Json/JsonReader.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonReaderTests.cs
We can get the buffered UTF-8 string - this gets the unbuffered UTF-8 string.
=> Serialization: Adds a way to get UTF-8 string that isn't buffered.

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.15.1.txt, changelog.md
Adding change log and contract for 3.15.1
No public API changes.
=> [Internal] Release: Adds 3.15.1 change log

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosHttpClientCoreTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Microsoft.Azure.Cosmos.Tests.csproj
A dependency was added to a test project is causing version conflicts in the compute sync. This removes the dependency since it is no needed.
=> Internal Tests: Fixes the compute build by removing unnecessary test dependency

Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/Fx/CosmosDiagnosticsLogger.cs
There was a bug in the diagnostics logging causing it to record the diagnostics.
=> Benchmark: Fixes a bug causing the diagnostics to not get logged

Directory.Build.props, Microsoft.Azure.Cosmos.Encryption/changelog.md
Updates the preview release version and the change log for Nuget package release.
=> Client Side Encryption : Adds version 1.0.0-preview8 and update the change log

Microsoft.Azure.Cosmos/src/Resource/Settings/ChangeFeedPolicy.cs
=> ChangeFeedPolicy: Fixes comment's sample

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.16.0.txt, Microsoft.Azure.Cosmos/src/Resource/Settings/ChangeFeedPolicy.cs, changelog.md
This bumps the SDK version to 3.16.0, and updates the changelog. No new public API changes.
=> Version 3.16.0: Adds new SDK version and updates changelog

changelog.md
Fixes the release date to show the correct year in the changelog.
To automatically close an issue: closes #2119
=> Changelog: Fixes release date

Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedCrossFeedRangeState.cs, Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedPage.cs, Microsoft.Azure.Cosmos/src/ChangeFeed/Pagination/ChangeFeedState.cs, Microsoft.Azure.Cosmos/src/ChangeFeed/Pagination/ChangeFeedStateBeginning.cs, Microsoft.Azure.Cosmos/src/ChangeFeed/Pagination/ChangeFeedStateContinuation.cs, Microsoft.Azure.Cosmos/src/ChangeFeed/Pagination/ChangeFeedStateNow.cs, Microsoft.Azure.Cosmos/src/ChangeFeed/Pagination/ChangeFeedStateTime.cs, Microsoft.Azure.Cosmos/src/ChangeFeed/Pagination/IChangeFeedStateTransformer{TResult}.cs, Microsoft.Azure.Cosmos/src/ChangeFeed/Pagination/IChangeFeedStateVisitor{TInput,TOutput}.cs, Microsoft.Azure.Cosmos/src/ChangeFeed/Pagination/IChangeFeedStateVisitor{TInput}.cs, Microsoft.Azure.Cosmos/src/FeedRange/FeedRange.cs, Microsoft.Azure.Cosmos/src/FeedRange/FeedRanges/FeedRangeEpk.cs, Microsoft.Azure.Cosmos/src/FeedRange/FeedRanges/FeedRangeInternal.cs, Microsoft.Azure.Cosmos/src/FeedRange/FeedRanges/FeedRangePartitionKey.cs, Microsoft.Azure.Cosmos/src/FeedRange/FeedRanges/FeedRangePartitionKeyRange.cs, Microsoft.Azure.Cosmos/src/Pagination/FeedRangeState{TState}.cs, Microsoft.Azure.Cosmos/src/Pagination/State.cs, Microsoft.Azure.Cosmos/src/ReadFeed/Pagination/ReadFeedState.cs, Microsoft.Azure.Cosmos/src/ReadFeed/ReadFeedCrossFeedRangeState.cs, Microsoft.Azure.Cosmos/src/ReadFeed/ReadFeedPage.cs, Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/DCountQueryPipelineStageTests.cs
Adds Internal Macro for Compute Consumption
=> Internal CrossFeedRangeState: Adds Internal Macro for Compute Consumption. 

Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Microsoft.Azure.Cosmos.Performance.Tests.csproj, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Microsoft.Azure.Cosmos.Tests.csproj, NuGet.config
Removing the myget dependency on hybrid row nuget and consuming it via nuget.org.
=> MyGet: Refactors HybridRow dependency to use Nuget.org

Microsoft.Azure.Cosmos/src/Resource/Conflict/Conflicts.cs, Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs, Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs, Microsoft.Azure.Cosmos/src/Resource/Scripts/Scripts.cs
Fixing several documentation issues in our samples.
Closes #2181
Closes #2182
Closes #2183
=> Documentation: Fixes several documentation errors

changelog.md
The PR did not properly link or close the issue causing it to be missed when generating the changelog. Adding the missing information.
=> Changelog: Adds fix for MalformedContinuationTokenException 

Directory.Build.props, Microsoft.Azure.Cosmos.Encryption/changelog.md
Updates the encryption preview release version and the change log for Nuget package release.
=> Client Side Encryption : Adds version 1.0.0-previewV10 and updates the change log.

Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/README.md
This adds information on how to setup the environment and examples of how to use PowerShell to run the project.
=> Benchmark: Adds setup instructions to readme

Microsoft.Azure.Cosmos/src/Resource/FeedIterators/FeedIteratorCore.cs, Microsoft.Azure.Cosmos/src/Serializer/CosmosElementSerializer.cs, Microsoft.Azure.Cosmos/src/Tracing/TraceComponent.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ChangeFeedAsync.xml, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.QueryAsync.xml, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ReadFeedAsync.xml
Adds missing POCO deserialization Trace. 
Resolves: https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2224
=> Diagnostics: Fixes missing POCO deserialization Trace.

Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceTextWriter.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/TraceWriterBaselineTests.TraceData.xml, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Tracing/TraceWriterBaselineTests.cs
Fixes the culture info of ITrace text strings.
Resolves: https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2223
=> Preview ITrace: Fixes Culture Info

Microsoft.Azure.Cosmos/src/Resource/Settings/IndexingPolicy.cs
Adds internal annotation support to indexing policy to allow storage of metadata.
=> [Internal] Indexing: Adds annotation to indexing policy

changelog.md
It was recently discovered that a previous change fixed an issues that would prevent the SDK from failing over. This PR is updating the changelog to include the additional information.
=> Changelog: Adds a note about failover logic fix

Directory.Build.props, Microsoft.Azure.Cosmos.Encryption/changelog.md, Microsoft.Azure.Cosmos.Encryption/src/Custom/EncryptionTransactionalBatch.cs, Microsoft.Azure.Cosmos.Encryption/src/EncryptionTransactionalBatch.cs, Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/LegacyEncryptionTests.cs, Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/MdeCustomEncryptionTests.cs, Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/MdeEncryptionTests.cs
1) Fix the response for transactional batch in case of non-success status code
2) Updates the Encryption preview release version and the change log.
=> Client Encryption : Fixes the response for transactional batch in case of non-success status code

Microsoft.Azure.Cosmos/src/Resource/Settings/IndexingPolicy.cs
Fixes null handling of Annotation in Indexing Policy
To automatically close an issue: closes #2305
=> [Internal] Indexing Policy: Fixes upgrade scenario to ignore Annotation property if null

Directory.Build.props
=> [Internal] 3.17.1 release: Fixes version

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.17.1.txt, changelog.md
Add changelog notes for 3.17.1 release
=> Changelog: Adds 3.17.1 notes

Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
Fixes Code formatting in CosmosClientOptions
To automatically close an issue: closes #2294
=> Documentation: Fixes Code formatting in CosmosClientOptions

Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
Fix typo in Documentation of GetItemLinqQueryable
To automatically close an issue: closes #2296
=> Documentation: Fixes typo in Documentation of GetItemLinqQueryable

Microsoft.Azure.Cosmos.Samples/Usage/ChangeFeed/Program.cs
Adds a sample for the new estimator API usage to onboard documentation.
=> Samples: Adds change feed estimator detailed sample

.github/workflows/prlint.yml
This adds support for removes tags in the PR title.
=> PR Bot: Adds support for removes

Microsoft.Azure.Cosmos.Encryption/src/Custom/EncryptionContainer.cs, Microsoft.Azure.Cosmos.Encryption/src/EncryptionContainer.cs, Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/LegacyEncryptionTests.cs, Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/MdeCustomEncryptionTests.cs, Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/MdeEncryptionTests.cs
Adds decryption support for ChangeFeed Processor.
#1484
=> Client Encryption : Adds decryption support for ChangeFeed Processor.

Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs, Microsoft.Azure.Cosmos/src/Resource/Settings/ContainerProperties.cs
=> Documentation: Fixes examples in container operations

Microsoft.Azure.Cosmos.Samples/Usage/BulkExecutorMigration/Program.cs
=> Samples: Fixes typo in BulkExecutorMigration program file

changelog.md
This PR fixes the dates in the changelog and adds missing changes.
=> Changelog : Adds missing changes and fixes the dates 

Microsoft.Azure.Cosmos/src/Patch/PatchOperation.cs, Microsoft.Azure.Cosmos/src/Patch/PatchOperationCore{T}.cs, Microsoft.Azure.Cosmos/src/Patch/PatchOperationsJsonConverter.cs, Microsoft.Azure.Cosmos/src/Patch/PatchOperation{T}.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosReadManyItemsTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Contracts/BenchmarkResults.json, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Contracts/PerformanceValidation.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosSerializerCoreTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PatchOperationTests.cs, azure-pipelines-functional.yml, azure-pipelines-nightly.yml, azure-pipelines.yml, changelog.md
Porting test fixes and features to the 3.19.0-preview release
=> 3.19.0-preview: Fixes to 3.19.0-preview branch

changelog.md
Adds the new PR and fixes the date.
=> 3.19.0-Preview: Adds changelog updates

changelog.md
The following PR was missed because it was merged after the initial changelog creation. This adds the missing change and all other changes were reviewed to verify no other PRs are missing.
=> Changelog: Adds PR 2331

Microsoft.Azure.Cosmos.Encryption/src/Custom/EncryptionContainer.cs, Microsoft.Azure.Cosmos.Encryption/src/Custom/EncryptionFeedIterator.cs, Microsoft.Azure.Cosmos.Encryption/src/Custom/EncryptionProcessor.cs, Microsoft.Azure.Cosmos.Encryption/src/EncryptionContainer.cs, Microsoft.Azure.Cosmos.Encryption/src/EncryptionFeedIterator.cs, Microsoft.Azure.Cosmos.Encryption/src/EncryptionProcessor.cs, Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/MdeCustomEncryptionTests.cs, Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/MdeEncryptionTests.cs
Adds the implementation for new ChangeFeed APIs - with checkpoint support and stream handling.
=> Client Encryption : Adds the implementation for new ChangeFeed APIs

Microsoft.Azure.Cosmos.Samples/Usage/Encryption/Encryption.csproj
Updates the Encryption Package used in the sample code.
=> Client Encryption : Adds Encryption Package 1.0.0-previewV15 to samples

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.19.0.txt, Microsoft.Azure.Cosmos/src/CosmosClient.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json, changelog.md
This PR is bumping the SDK version to 3.19.0, updating the changelog, and the contract files. 
Changes from 3.18.0 to 3.19.0
=> 3.19.0: Adds new release, changelog, and contract updates

Microsoft.Azure.Cosmos.Samples/Usage/Cosmos.Samples.Usage.sln, Microsoft.Azure.Cosmos.Samples/Usage/SystemTextJson/CosmosSystemTextJsonSerializer.cs, Microsoft.Azure.Cosmos.Samples/Usage/SystemTextJson/Program.cs, Microsoft.Azure.Cosmos.Samples/Usage/SystemTextJson/SystemTextJson.csproj
This PR adds a sample project that shows how users can leverage Azure.Core and System.Text.Json to replace Newtonsoft.Json as the serialization technology on the V3 SDK.
=> Samples: Adds System.Text.Json sample

Microsoft.Azure.Cosmos/src/Json/JsonWriter.JsonBinaryWriter.cs, Microsoft.Azure.Cosmos/src/Json/JsonWriter.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonWriterTests.cs
Initial draft of change to add a flag for enabling/disabling string encoding in JsonBinaryWriter
=> [Internal] Query: Adds flag for enabling string encoding in JsonBinaryWriter and default to true

Microsoft.Azure.Cosmos/contracts/API_3.18.1-preview.txt, changelog.md
=> [Internal] 3.18.1: Adds release notes and contract file

Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/README.md
Updating Read Me with linux VM set up and updated benchmark run command.
=> Benchmark: Fixes Read Me with Linux VM set up instructions

Microsoft.Azure.Cosmos.Samples/Usage/PowerShellRestApi/PowerShellScripts/MigrateToAnalyticalStore.ps1, changelog.md
Changes include setting the analytical storage capability via Az Powershell, making the script idempotent, and reducing required parameters.
=> MigrateToAnalyticalStore: Adds Az powershell to get account info

Microsoft.Azure.Cosmos.Encryption/changelog.md
Change log entry with upcoming release changes
=> [Internal] Client Encryption: Adds changelog for V16 release

Microsoft.Azure.Cosmos.Samples/Usage/SystemTextJson/CosmosSystemTextJsonSerializer.cs
=> Samples: Fixes InvalidOperationException: Json Serializer left an open stream.

changelog.md
Fixing syntax to resolve docs build HTML suggestion
=> Changelog: Fixes quotes for PatchOperation

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosAuthorizationTests.cs
Fix TestTokenCredentialFailedToRefreshAsync
Fix ClientTelemetryTests race conditions
Fix HttpClientConnectionLimitTest and add more logs
Add Upsert tests to validate session token exists.
To automatically close an issue: closes #2725
=> [INTERNAL] Tests: Fixes transient test failures and add upsert tests

Microsoft.Azure.Cosmos/src/Resource/ClientEncryptionKey/ClientEncryptionKeyProperties.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
Updates JSON property name of EncryptionAlgorithm to match backend.
=> Client Encryption: Fixes JSON property name of ClientEncryptionKeyProperties to match backend

Microsoft.Azure.Cosmos/src/Resource/Settings/DedicatedGatewayRequestOptions.cs
=> Documentation: Fixes MaxIntegratedCacheStaleness remarks

Directory.Build.props, Microsoft.Azure.Cosmos.Encryption/changelog.md, Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj
1. Integrates with latest version (3.22.0-preview) of SDK.
2. Adds changelog and bumps version
=> Client Encryption: Adds changelog and bumps version, and also integrates with 3.22.0-preview SDK version

templates/static-tools.yml
PR enables the binskim scan for the repository
=> BinSkim: Adds binskim scan

Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs, Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/HandlerTests.cs
Enabling Client telemetry feature in GA package, This feature can be enable or disable as mentioned here https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2385
=> Client Telemetry: Removes Preview Tag to GA this feature

README.md
=> README: Adds warning note

Microsoft.Azure.Cosmos/src/Batch/TransactionalBatch.cs, Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchInternal.cs, Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchPatchItemRequestOptions.cs, Microsoft.Azure.Cosmos/src/Patch/PatchOperation.cs, Microsoft.Azure.Cosmos/src/Patch/PatchOperationType.cs, Microsoft.Azure.Cosmos/src/RequestOptions/PatchItemRequestOptions.cs, Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs, Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInternal.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
This PR Includes the changes to remove Preview tags form patch operation related api's and classes.
- [Patch] New feature (non-breaking change which adds functionality)
=> Patch: Adds Patch to GA SDK

Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/v3/QueryStreamCrossPkWithPaginationV3BenchmarkOperation.cs, Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/v3/QueryStreamSinglePkWithPaginationV3BenchmarkOperation.cs, Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/v3/QueryTCrossPkWithPaginationV3BenchmarkOperation.cs, Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/v3/QueryTSinglePkWithPaginationV3BenchmarkOperation.cs
Added below query scenarios:
1. QueryStreamCrossPkWithPaginationV3BenchmarkOperation.cs 
2. QueryStreamSinglePkWithPaginationV3BenchmarkOperation.cs  
3. QueryTCrossPkWithPaginationV3BenchmarkOperation.cs 
4. QueryTSinglePkWithPaginationV3BenchmarkOperation.cs 
It covers non-aggregation queries with pagination enabled.
- [] Add test cases
=> Benchmark: Adds unordered query scenarios

Microsoft.Azure.Cosmos.Samples/Usage/ChangeFeed/Program.cs
Adding sample code that we can consume on documentation to showcase how to wire and add the new Notification APIs
=> Samples: Adds Notification API samples for Change Feed Processor

Microsoft.Azure.Cosmos.Encryption/src/EncryptionCosmosDiagnostics.cs, Microsoft.Azure.Cosmos.Encryption/src/EncryptionDiagnosticsContext.cs, Microsoft.Azure.Cosmos.Encryption/src/EncryptionTransactionalBatch.cs, Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/MdeEncryptionTests.cs
1. Implements / overrides GetClientElapsedTime method for EncryptionCosmosDiagnostics
2. Also add encryption related diagnostics information for TransactionalBatch
=> Client Encryption: Adds GetClientElapsedTime method for EncryptionCosmosDiagnostics

Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryOptions.cs
Optimized Memory Allocation while creating or assigning histogram. Made it same as Java.
Metrics | Old   | New | Improved
-- | -- | -- | --
CPU | 2,000 KB | 63 KB | -96.85%
Request Latency | 20,000 KB | 2996 KB | -85%
Request Charge | 8,000 KB | 70 KB | -99.1%
Memory | 48,000 KB | 110 KB |  -99.8%
Number requests 2881
- [] Bug fix (non-breaking change which fixes an issue) i.e 12.5%
To automatically close an issue: closes #2881
=> Client Telemetry: Adds memory optimization by reducing Histogram significant digits

Microsoft.Azure.Cosmos/src/Resource/Settings/DatabaseProperties.cs
Fixes database type in the documentations comments
To automatically close an issue: closes #2594
=> Documentation: Fixes Database type

Microsoft.Azure.Cosmos/src/RequestOptions/ItemRequestOptions.cs
Fixes error in trigger documentation.
To automatically close an issue: closes #2591
=> Documentation: Fixes ItemRequestOptions to use items instead of document for Triggers

Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
Closes https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2559
in the example the parameter is passed in as "tests", it should be "test". 
Change in object from tests to test.
=> Documentation: Fixes Typo in query documents

Microsoft.Azure.Cosmos/src/Handler/ResponseMessage.cs, Microsoft.Azure.Cosmos/src/Query/v3Query/QueryResponse.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/PopulateIndexMetricsTest.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
This is a feature request from customers to make the Index Metrics field available to access from the stream API.
To automatically close an issue: closes #2855
=> Query: Adds Index Metrics to Stream API

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OfflineEngineTests/BuiltinFunctionEvaluatorTests.cs
Created issue to explain and track the issue: #3005 
=> Query test: Adds Ignore for ToUpper which is failing gates

Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
Updated ReadManyItemsStreamAsync example code snippet with proper working code to fix [3033](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3033)
=> Documentation: Fixes ReadManyItemsStreamAsync example

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.25.0-preview.txt, Microsoft.Azure.Cosmos/contracts/API_3.25.0.txt, changelog.md
No public API changes in this release
=> 3.25.0: Adds changelog and bumps SDK version

Microsoft.Azure.Cosmos/src/CosmosClient.cs
(AzureCXP) fix for the client.CreateDatabaseAsync fixes https://github.com/Azure/azure-sdk-for-net#27135
Fixes Azure/azure-sdk-for-net#27135
=> Documentation: Fixes example on CreateDatabaseAsync

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.26.0-preview.txt, changelog.md
Doing a 3.26.0-preview release to unblock a new encryption SDK release.
=> 3.26.0-preview: Adds changelog and contract file

Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedProcessorBuilder.cs
Improves xml docs for the instance name to clarify meaning.
Closes https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3067
=> Documentation: Refactors WithInstanceName documentation

changelog.md
=> Change log: Adds merge callout

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.26.0.txt, changelog.md
Bumps the SDK version to 3.26.0.
=> 3.26.0: Adds changelog and contract files

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.26.1.txt, changelog.md
A hotfix release to unblock a customer that has a large container and it getting throttle by partition key range calls.
=> 3.26.1: Adds changelog and contract files

Microsoft.Azure.Cosmos/src/CosmosClient.cs, Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnostics.cs, Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
Closes #3084
Closes #3085
Closes #3091
=> Documentation: Adds remarks for different APIs

Microsoft.Azure.Cosmos/src/CosmosClient.cs
The example in the docs given is for the secret and not the cosmosDB connectionstring. This PR has the fix for the sample CosmosDB connectionstring
=> Documentation: Fixes connectionstring example

Directory.Build.props, Microsoft.Azure.Cosmos.Encryption.Custom/changelog.md, Microsoft.Azure.Cosmos.Encryption.Custom/src/EncryptionContainer.cs, Microsoft.Azure.Cosmos.Encryption.Custom/src/Microsoft.Azure.Cosmos.Encryption.Custom.csproj
Release Encryption.Custom package over latest preview SDK.
=> ClientEncryption: Adds 3.26.0-preview SDK dependency for Encryption.Custom

Microsoft.Azure.Cosmos.Encryption/changelog.md
Adds changelog entry for Cosmos.Encryption 1.0.0 that was missed earlier.
=> ClientEncryption: Adds changelog entry for Cosmos.Encryption 1.0.0

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Updates the expected error message because the recent emulator change includes an added link to the error message
To automatically close an issue: closes #3183
=> [INTERNAL] ItemRequestOptionAccessConditionTest: Fixes expected error message for new emulator version

Microsoft.Azure.Cosmos/src/OSS/Azure.Core/AppContextSwitchHelper.cs, Microsoft.Azure.Cosmos/src/OSS/Azure.Core/DiagnosticScope.cs, Microsoft.Azure.Cosmos/src/OSS/Azure.Core/DiagnosticScopeFactory.cs
Copied Diagnostic Scope files from Azure Core to get the support of `DiagnosticScope `which will be helpful to create activity.
=> [Preview] AI Integration: Adds Azure Core file in SDK to support diagnostics Scope

Directory.Build.props
Adds version 3.28.1 which targets the EN20220301 branch.
This adds the new optimize request headers, but the header change will be done in a follow up PR. This just so the perf runner can verify nothing changed with just the new direct version.
=> Direct: Adds versions 3.28.1

Directory.Build.props
Upgrades C# lang version to 10.0 to gain additional performance improvements.
closes #3205
=> [Internal] LangVersion: Adds C# Lang Version 10

.github/workflows/prlint.yml
Upgrade PR lint version to fix issue where it is not dismissing request changes in the reviews which is blocking PRs. 
https://github.com/MorrisonCole/pr-lint-action
=> PRLINT: Adds latest 1.6.1 version

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.27.2-preview.txt, Microsoft.Azure.Cosmos/contracts/API_3.27.2.txt, Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj, changelog.md
Bumps SDK version to 3.27.2. No public API changes are made. 
=> 3.27.2: Adds new SDK versions and contract files

changelog.md
updates incorrect links in the 3.27.2 release notes
=> 3.27.2: Fixes PR Links in Release Notes

Microsoft.Azure.Cosmos.Samples/Usage/SystemTextJson/Program.cs
Add a warning and a link to the issue tracking the problem to help customers avoid hitting the problem.
=> Samples: Adds warning about System.Text.Json and LINQ

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.28.0-preview.txt, Microsoft.Azure.Cosmos/contracts/API_3.28.0.txt, changelog.md
=> 3.28.0: Adds new SDK version and contract files

Microsoft.Azure.Cosmos.Samples/Usage/BulkExecutorMigration/BulkExecutorMigration.csproj, Microsoft.Azure.Cosmos.Samples/Usage/BulkSupport/BulkSupport.csproj, Microsoft.Azure.Cosmos.Samples/Usage/Cosmos.Samples.Usage.sln, Microsoft.Azure.Cosmos.Samples/Usage/CustomSerialization/CustomSerialization.csproj, Microsoft.Azure.Cosmos.Samples/Usage/Encryption/Encryption.csproj, Microsoft.Azure.Cosmos.Samples/Usage/Geospatial/Geospatial.csproj, Microsoft.Azure.Cosmos.Samples/Usage/Handlers/HandlerSample.csproj, Microsoft.Azure.Cosmos.Samples/Usage/HttpClientFactory/HttpClientFactory.csproj, Microsoft.Azure.Cosmos.Samples/Usage/ItemManagement/ItemManagement.csproj, Microsoft.Azure.Cosmos.Samples/Usage/NonPartitionContainerMigration/NonPartitionContainerMigration.csproj, Microsoft.Azure.Cosmos.Samples/Usage/Queries/Queries.csproj, Microsoft.Azure.Cosmos.Samples/Usage/ReEncryption/ReEncryption.csproj, Microsoft.Azure.Cosmos.Samples/Usage/Shared/Shared.csproj, Microsoft.Azure.Cosmos.Samples/Usage/TransactionalBatch/TransactionalBatch.csproj
All the dependabot PRs are broken because they change the Shared CSPROJ individually (https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3303)
=> [Internal] Dependencies: Fixes Newtonsoft.Json dependency on samples project

Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/BenchmarkConfig.cs, Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/run.sh
Enabling Open Telemetry for one of the test to keep track of the impact of this feature on a particular operation.
It will help us to keep an eye on performance impact of this particular feature.
=> [Internal] AI Integration: Adds Open telemetry in Benchmark tests

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.30.1-preview.txt, Microsoft.Azure.Cosmos/contracts/API_3.30.1.txt, changelog.md
This bumps the SDK version from `3.30.0` to `3.30.1`. No changes in the GA public and preview contract/s.
=> 3.30.1: Adds new SDK versions and contract files

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.30.1-preview.txt, Microsoft.Azure.Cosmos/contracts/API_3.30.1.txt, Microsoft.Azure.Cosmos/src/Routing/PartitionKeyRangeCache.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyRangeCacheTest.cs, changelog.md
**PartitionKeyRangeCache**: Fixes duplicate trace key generation
=> [Hotfix] PartitionKeyRangeCache: Fixes duplicate trace key generation

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.30.1-preview.txt, Microsoft.Azure.Cosmos/contracts/API_3.30.1.txt, Microsoft.Azure.Cosmos/src/Routing/PartitionKeyRangeCache.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyRangeCacheTest.cs, changelog.md
**PartitionKeyRangeCache:** Fixes duplicate trace key generation
=> [Hotfix-Preview] PartitionKeyRangeCache: Fixes duplicate trace key generation

Microsoft.Azure.Cosmos/src/OSS/cgmanifest.json
This pull request adds the JSON schema for `cgmanifest.json`.
A JSON schema helps you to ensure that your `cgmanifest.json` file is valid.
JSON schema validation is a build-in feature in most modern IDEs like Visual Studio and Visual Studio Code.
Most modern IDEs also provide code-completion for JSON schemas.
Most modern IDEs like Visual Studio and Visual Studio Code have a built-in feature to validate JSON files.
You can also use [this small script](https://github.com/JamieMagee/verify-cgmanifest) to validate your `cgmanifest.json` file.
Component Detection is able to read camel case and pascal case properties.
However, the JSON schema doesn't have a case-insensitive mode.
We therefore suggest camel case as it's the most common format for JSON.
To deserialize the `cgmanifest.json` file, …
=> [Internal] OSS: Adds `$schema` to `cgmanifest.json`

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.31.0-preview.txt, Microsoft.Azure.Cosmos/contracts/API_3.31.0.txt, changelog.md
This bumps the SDK version from 3.29.0 to 3.30.0. Please see the below changes in the GA public contract.
=> 3.31.0: Adds new SDK versions and contract files

Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ClientRetryPolicyTests.cs
Small change to a comment regarding handling of 503 errors in the `ClientRetryPolicy`.
=> ClientRetryPolicy: Refactors comment to reflect actual behavior

README.md
Closes https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3492
=> [Internal] README: Fixes code example

changelog.md
Update the minimum recommended version for the SDK.
=> [Internal] Changelog: Fixes recommended version to 3.31.0

Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
=> [Internal]Client Telemetry: Refactors code to remove unused variable

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.31.1-preview.txt, Microsoft.Azure.Cosmos/contracts/API_3.31.1.txt, changelog.md
This bumps the SDK version from `3.31.0` to `3.31.1`. No changes in the GA public and preview contract/s.
=> 3.31.1: Adds new SDK versions and contract files

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.31.1-preview.txt, Microsoft.Azure.Cosmos/contracts/API_3.31.1.txt, changelog.md
**Connection:** Fixes health check to identify broken connections earlier
=> [Hotfix-Preview] Connection: Fixes health check to identify broken connections earlier

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.31.1-preview.txt, Microsoft.Azure.Cosmos/contracts/API_3.31.1.txt, changelog.md
**Connection:** Fixes health check to identify broken connections earlier
=> [Hotfix] Connection: Fixes health check to identify broken connections earlier

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.31.2.txt, Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/OrderBy/OrderByCrossPartitionQueryPipelineStage.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/OrderByCrossPartitionQueryPipelineStageTests.cs, changelog.md
Hotfix release for [#3525](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3525) Query: Fixes performance regression on target partition on some ORDER BY queries with continuation
=> Release: Adds  hotfix release 3.31.2

Microsoft.Azure.Cosmos/src/DirectAddressResolutionFlow.dgml
[Internal]: AddressCaches HLD design
=> [Internal] AddressCaches: Adds HLD design

Microsoft.Azure.Cosmos.Samples/Usage/NuGet.config, NuGet.config
[Internal] nugetconfig: fixes Removing specific overrides
Removing explicit nugetconfig file, casing component governance alerts in master submodule
=> [Internal] nugetconfig: Removes specific overrides

Microsoft.Azure.Cosmos/src/Regions.cs
The abbreviation for Early Updates Access Program (EUAP) is not expanded in the description for those regions. This PR updates the description accordingly.
resolves Azure/azure-sdk-for-net#32456
=> Documentation: Fixes EUAP in Comments

Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceJsonWriter.cs, Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceTextWriter.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/TraceWriterBaselineTests.ScenariosAsync.xml, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/TraceWriterBaselineTests.Serialization.xml, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/TraceWriterBaselineTests.TraceData.xml
NOTE: This change will impact existing log parsing logic if-any.
=> Trace: Fixes Tracing/diagnostics hour-times to 24Hours

Microsoft.Azure.Cosmos/contracts/API_3.31.2-preview.txt
Adds the API contracts for 3.31.2-preview. The changelog and directory props are already present in master.
=> Release: Adds API contracts for 3.31.2-preview

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.31.2-preview.txt, Microsoft.Azure.Cosmos/contracts/API_3.31.2.txt, Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/OrderBy/OrderByCrossPartitionQueryPipelineStage.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/OrderByCrossPartitionQueryPipelineStageTests.cs, changelog.md
Hotfix release for [#3525](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3525) Query: Fixes performance regression on target partition on some ORDER BY queries with continuation
=> Release: Adds hotfix release 3.31.2-preview

Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/BenchmarkConfig.cs, Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/run.sh
Adding Distributed Tracing as an option in Benchmark tests. So that we can add some test with it enabled
=> [Internal] Performance Testing: Adds Distributed Tracing option in benchmarks

.github/fabricbot.json
Add Fabric Bot configuration to automatically tag issues
=> [Internal] Actions: Adds Fabric bot automation to tag issues

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.32.1-preview.txt, Microsoft.Azure.Cosmos/contracts/API_3.32.1.txt, changelog.md
Not public API changes:
Release is intended for:
https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3732
=> Release: Adds SDK version and changelog for 3.32.1

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.32.1-preview.txt, Microsoft.Azure.Cosmos/contracts/API_3.32.1.txt, Microsoft.Azure.Cosmos/src/ReadManyQueryHelper.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosReadManyItemsTests.cs, changelog.md
Cherry pick of commits into release branch
=> Release: Adds commits for 3.32.1-preview hotfix release

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.32.1-preview.txt, Microsoft.Azure.Cosmos/contracts/API_3.32.1.txt, Microsoft.Azure.Cosmos/src/ReadManyQueryHelper.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosReadManyItemsTests.cs, changelog.md
Cherry pick of commits into release branch
=> Release: Adds commits for 3.32.1 hotfix release

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.32.2-preview.txt, Microsoft.Azure.Cosmos/contracts/API_3.32.2.txt, changelog.md
Release is intended for:
https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3749
https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3713
=> Release: Adds SDK version and change log for 3.32.2

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.32.3-preview.txt, Microsoft.Azure.Cosmos/contracts/API_3.32.3.txt, changelog.md
Cherry-picks for 3.32.3 release
=> Release: Adds commits for 3.32.3 hotfix release

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.32.3-preview.txt, Microsoft.Azure.Cosmos/contracts/API_3.32.3.txt, changelog.md
Cherry-picks for 3.32.3-preview release
=> Release: Adds commits for 3.32.3-preview hotfix release

Microsoft.Azure.Cosmos.Encryption.Custom/src/Microsoft.Azure.Cosmos.Encryption.Custom.csproj, Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj, Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj, README.md, changelog.md
Update README, changelog and csproj to have correct API name.
=> [Internal] Documentation: Fixes API name to NoSQL

Microsoft.Azure.Cosmos.Samples/Usage/ApplicationInsights/ApplicationInsights.csproj, Microsoft.Azure.Cosmos.Samples/Usage/ApplicationInsights/Program.cs, Microsoft.Azure.Cosmos.Samples/Usage/OpenTelemetry/OpenTelemetry.csproj, Microsoft.Azure.Cosmos.Samples/Usage/OpenTelemetry/Program.cs
Updates SDK version and section tags for the OpenTelemetry and Application Insights samples.
=> [Internal] Samples: Fixes OpenTelemetry and Application Insights samples

Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/ARMTemplate/README.md
URL typo.
Fixes URL Typo in Deploy To Azure Button
=> [Internal] Benchmarking: Fixes URL Typo in Deploy To Azure Button

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.35.0-preview.txt, Microsoft.Azure.Cosmos/contracts/API_3.35.0.txt, changelog.md
This bumps the SDK version 3.35.0
Public contract change: 
Preview contract change:
=> SDK 3.35.0 : Adds version bump and changelog

Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/AzureVmBenchmark/azuredeploy.json, Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/BenchmarkConfig.cs
Dashboard with 2 charts for metrics.
=> Benchmark metrics - Dashboard with 2 charts

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.35.1-preview.txt, Microsoft.Azure.Cosmos/contracts/API_3.35.1.txt, changelog.md
This bumps the SDK version 3.35.1
No public API changes
=> SDK 3.35.1 : Adds version bump and changelog

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.35.1-preview.txt, Microsoft.Azure.Cosmos/contracts/API_3.35.1.txt, Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs, Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicy.cs, Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyControlPlaneRead.cs, Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyControlPlaneRetriableHotPath.cs, Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyDefault.cs, Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyNoRetry.cs, changelog.md
=> Release: Adds commits for 3.35.1 hotfix release

Directory.Build.props, Microsoft.Azure.Cosmos.Encryption.Custom/changelog.md, Microsoft.Azure.Cosmos.Encryption.Custom/src/Microsoft.Azure.Cosmos.Encryption.Custom.csproj
Update is to change package reference Microsoft.Azure.Cosmos to version 3.35.1-preview.
=> Client Encryption: Adds package reference Microsoft.Azure.Cosmos version 3.35.1-preview

changelog.md
This PR adds a missing item in the release note for cosmos SDK v `3.35.2`.
=> [Internal] Release Notes: Adds the Missing Items in the Release Notes for SDK Release `3.35.2`

changelog.md
This is a recommendation for customers if they would like to use the Optimistic Direct Execution feature. 
=> Query: Refactors changelog.md with Optimistic Direct Execution recommendation

Microsoft.Azure.Cosmos/src/Util/ConfigurationManager.cs
This PR disables the "Advanced Replica Selection" feature in preview package.
| Cosmos SDK Type | Replica Validation Enabled By Default? | Enable Replica Validation On Demand                | Disable Replica Validation On Demand                |
|-----------------|----------------------------------------|----------------------------------------------------|-----------------------------------------------------|
| Preview         | False                                   | `AZURE_COSMOS_REPLICA_VALIDATION_ENABLED` = `True` | `AZURE_COSMOS_REPLICA_VALIDATION_ENABLED` = `False` |
| GA              | False                                  | `AZURE_COSMOS_REPLICA_VALIDATION_ENABLED` = `True` | `AZURE_COSMOS_REPLICA_VALIDATION_ENABLED` = `False` |
To …
=> [Internal] Upgrade Resiliency: Refactors Code to Disable Replica Validation Feature in Preview

Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/AzureVmBenchmark/scripts/custom-script.sh
This PR fixes benchmark run command using `OSSProjectRef` parameter.
=> [Internal] Benchmark tool: Fixes benchmark run command using OSSProjectRef parameter

Microsoft.Azure.Cosmos/src/Query/Core/CoordinatorDistributionPlan/ClientQL/ClientQLArrayCreateScalarExpression.cs, Microsoft.Azure.Cosmos/src/Query/Core/CoordinatorDistributionPlan/ClientQL/ClientQLArrayLiteral.cs, Microsoft.Azure.Cosmos/src/Query/Core/CoordinatorDistributionPlan/ClientQL/ClientQLDistinctEnumerableExpression.cs, Microsoft.Azure.Cosmos/src/Query/Core/CoordinatorDistributionPlan/ClientQL/ClientQLFunctionIdentifier.cs, Microsoft.Azure.Cosmos/src/Query/Core/CoordinatorDistributionPlan/ClientQL/ClientQLGroupByEnumerableExpression.cs, Microsoft.Azure.Cosmos/src/Query/Core/CoordinatorDistributionPlan/ClientQL/ClientQLObjectLiteral.cs, Microsoft.Azure.Cosmos/src/Query/Core/CoordinatorDistributionPlan/ClientQL/ClientQLOrderByEnumerableExpression.cs, Microsoft.Azure.Cosmos/src/Query/Core/CoordinatorDistributionPlan/ClientQL/ClientQLSystemFunctionCallScalarExpression.cs, Microsoft.Azure.Cosmos/src/Query/Core/CoordinatorDistributionPlan/ClientQL/ClientQLTupleAggregate.cs, Microsoft.Azure.Cosmos/src/Query/Core/CoordinatorDistributionPlan/ClientQL/ClientQLTupleCreateScalarExpression.cs, Microsoft.Azure.Cosmos/src/Query/Core/CoordinatorDistributionPlan/ClientQL/ClientQLTupleType.cs, Microsoft.Azure.Cosmos/src/Query/Core/CoordinatorDistributionPlan/ClientQL/ClientQLUserDefinedFunctionCallScalarExpression.cs, Microsoft.Azure.Cosmos/src/Query/Core/CoordinatorDistributionPlan/CoordinatorDistributionPlanDeserializer.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/CoordinatorDistributionPlanBaselineTests.TestCoordinatorDistributionPlanDeserialization.xml, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/CoordinatorDistributionPlanBaselineTests.cs
I have this PR to address our approach to error handling during the deserialization process. It's essential for us to establish a consensus on how we should manage errors in this context. We have a couple of options:
Throw Errors: One approach is to throw exceptions whenever an error occurs during deserialization. This can help ensure that issues are immediately brought to our attention and force explicit handling of exceptional cases. 
Return and Propagate Errors: Alternatively, we can choose to return error information rather than throwing exceptions. This way, errors can be handled more gracefully through return values, and error details can be propagated up the call stack. 
- [] New …
=> Function Formatting for ClientQL Deserializing

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs
There were a few typos and minor mistakes I forgot to update in this test. 
=> [Internal] Query: Fixes minor issues with TestQueryValidityCheckWithODEAsync

Directory.Build.props, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientCreateAndInitializeTest.cs
Bumps up the `Cosmos.Direct` package version to `3.31.5`
=> [Internal] Direct Package: Adds version bump

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryReleaseTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryTestsBase.cs, azure-pipelines-official.yml
Cherry-pick https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4132
=> Release 3.36.0: Fixes Client Telemetry Integration test

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryReleaseTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryTestsBase.cs, azure-pipelines-official.yml
cherry-pick https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4132
=> Release 3.36.0: Fixes Client Telemetry Integration test (#4133)

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Fixes flaky `QuerySinglePartitionItemStreamTest` in `CosmosItemTests`.
=> [Internal] Query: Fixes flaky test

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientConfigurationDiagnosticTest.cs, azure-pipelines-official.yml
=> Release 3.36.0: Fixes client config test and preview pipeline (#4149) 

changelog.md
1. Fixes typo on Preview package name
2. updated release dates from 17 oct to 24 oct.
=> Documentation: Fixes changelog typo and date

Microsoft.Azure.Cosmos.Samples/Usage/SystemTextJson/Program.cs
Updates sample code to highlight that System.Text.Json attributes are not currently honored by LINQ.
closes #4168
=> Query: Fixes documentation to reflect state of System.Text.Json serializer

Microsoft.Azure.Cosmos.Samples/Usage/ApplicationInsights/Program.cs, Microsoft.Azure.Cosmos.Samples/Usage/CustomDiagnosticAndEventListener/Program.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientCreateAndInitializeTest.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Benchmarks/StopwatchAllocationsBenchmark.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DirectContractTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosConflictTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosHttpClientCoreTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ServicePointAccessorTests.cs
[Internal] CodeAnalsis: Fixing all warning in source/test/usage projects
=> [Internal] Code Analysis: Fixes all warning in source/test/usage projects

Microsoft.Azure.Cosmos.Samples/Usage/ApplicationInsights/ApplicationInsights.csproj, Microsoft.Azure.Cosmos.Samples/Usage/ApplicationInsights/Program.cs, Microsoft.Azure.Cosmos.Samples/Usage/OpenTelemetry/OpenTelemetry.csproj, Microsoft.Azure.Cosmos.Samples/Usage/OpenTelemetry/Program.cs
As part of this PR, update Samples with latest SDK i.e. 3.37.0 and updated AppInsights SDK and Azure Monitor library to latest stable version.
Added few more activity span to make results more meaningful on AppInsights UI
=> Distributed Tracing: Refactors Samples to use latest cosmosdb SDK

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.37.1-preview.txt, Microsoft.Azure.Cosmos/contracts/API_3.37.1.txt, Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs, changelog.md
Cherry-picks #4226 and #4231 for 3.37.1 release.
=> 3.37.1-preview: Adds cherry-picks for 3.37.1-preview release

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.38.0.txt, Microsoft.Azure.Cosmos/contracts/API_3.39.0-preview.0.txt, changelog.md
This bumps the SDK GA version from `3.37.1` to `3.38.0` and preview version from `3.37.1-preview` to `3.39.0-preview.0`. Please see the below changes in the GA public contract.
_[Note: To understand about the GA and preview versions styles, please take a look at our [versioning guidelines and principles](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/docs/versioning.md)]_
=> 3.38.0: Adds new SDK versions and contract files

Directory.Build.props, changelog.md
This PR cherry-picks the [`3.38.1` version bump PR](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4305)  and resolves the conflict by manual intervention, by downgrading the `Cosmos.Direct` package version.
=> [Hotfix] 3.39.0-preview.1: Fixes Change Log and Bumps Up Release Versions

Microsoft.Azure.Cosmos/src/Serializer/CosmosLinqSerializer.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Makes CosmosLinqSerializer available in public release.
=> Query: Adds Support for LINQ Custom Serializer in Public Release

docs/ReplicaValidationDesign.md
Fix spelling
Fix spelling of 'Background'
=> Documentation: Fixes spelling in ReplicaValidationDesign

changelog.md
Adds information about the known issues with hierarchical partition keys describes in #4326 
=> [Internal] Known Issues: Adds HPK know issue to changelog.md

Microsoft.Azure.Cosmos/src/Resource/Settings/DedicatedGatewayRequestOptions.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
=> integrated cache: Adds BypassIntegratedCache for public release

Directory.Build.props, Microsoft.Azure.Cosmos/src/Regions.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Upgrades Direct package version to 3.33.1
Changes in 3.33.1
* Added `USSec West Central` region
=> [Internal] Regions: Adds new USSec Region

azure-pipelines-official.yml
Adds Environment Variable to release pipeline yml file.
=> [Internal] Pipelines: Adds MultiRegion Test support for release pipeline

azure-pipelines-official.yml
=> 3.39.0: Adds Cherry Pick Azure Pipeline Yml

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/README.md
Updates README for performance test project to make things more clear.
=> [Internal] Benchmarking: Refactors README in Performance tests project

Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryRecorderFactory.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientConfigurationDiagnosticTest.cs
ref. https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4406
=> [Internal] Distributed Tracing: Fixes Client Config Test (#4406)

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestGroupByMultiValueTranslation.xml, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqGeneralBaselineTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj
This PR adds test for multi-value LINQ Group By translation. 
=> [Internal] Query: Adds tests for LINQ GROUP BY Multi-value translations

Directory.Build.props, changelog.md
=> SDK 3.39.1/3.40.0-preview.1: Adds version bump and changelog.

changelog.md
Included known issue in the list for cx awareness.
=> [Internal] ReleaseNotes : Adds known issue to list

Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
Closes https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4463
=> Documentation: Fixes recommended OpenTcpConnetionTimeout value

Microsoft.Azure.Cosmos.Samples/Tools/FaultInjection/src/implementataion/FaultInjectionServerErrorRule.cs
Fixes bug with ApplyPercentage where values of the apply percentage are inverted. So, a value of 
1 would be 0%, .4 60%, etc. This would ensure that the value's matched the behavior. 
=> [Internal] FaultInjection: Fixes bug with ApplicationPercentage

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.40.0.txt, Microsoft.Azure.Cosmos/contracts/API_3.41.0-preview.0.txt, changelog.md
This bumps the SDK GA version from `3.39.2` to `3.40.0` and preview version from `3.40.0-preview.2` to `3.41.0-preview.0`. Please see the below changes in the GA public contract.
_[Note: To understand about the GA and preview versions styles, please take a look at our [versioning guidelines and principles](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/docs/versioning.md)]_
=> 3.40.0: Adds new SDK versions and contract files

templates/nuget-pack.yml
[Internal] Release: Fixing package publishing
=> [Internal] Release: Fixes package publishing 

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.40.1.txt, Microsoft.Azure.Cosmos/contracts/API_3.41.0-preview.1.txt, Microsoft.Azure.Cosmos/contracts/API_3.41.1-preview.1.txt, changelog.md
This bumps the SDK GA version from 3.40.0 to 3.40.1 and preview version from 3.41.0-preview.0 to 3.41.0-preview.1. Since this is a hotfix release, there is no change in public contracts.
=> 3.40.1: Adds new SDK versions and contract files

Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPartitionProvider.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/QueryPlanBaselineTests.VectorSearch.xml, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPlanBaselineTests.cs
Fixes call to ServiceInterop in case of DISP_E_BUFFERTOOSMALL to account for vector embedding policy, and adds test cases to cover this path
=> Query: Fixes call to ServiceInterop in case of DISP_E_BUFFERTOOSMALL to account for vector embedding policy

Microsoft.Azure.Cosmos.Samples/Tools/FaultInjection/src/implementataion/ChaosInterceptor.cs
With the release of the latest version of the direct package the IChaosIntercepor interface was updated and changes need to be reflected in the FaultInjection Library. Implementation of methods will come in a separate PR when Gateway mode is implemented. 
=> FaultInjection: Refactors interface for Gateway Mode

Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryFeature.cs
This change adds a new QueryFeature flag for the MakeList and MakeSet aggregates.
=> Query: Adds a new QueryFeature flag for MakeList and MakeSet

Microsoft.Azure.Cosmos.Samples/Tools/FaultInjection/src/FaultInjection.csproj, Microsoft.Azure.Cosmos.Samples/Tools/FaultInjection/tests/FaultInjectionTests.csproj, Microsoft.Azure.Cosmos/src/RMResources.Designer.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj
Fixes msdata/direct branch so it merges. Removes direct package references so it uses local files. 
=> [Internal] msdata/direct: Fixes msdata/direct branch so it merges

Microsoft.Azure.Cosmos.Samples/Usage/CFPullModelAllVersionsAndDeletesMode/CFPullModelAllVersionsAndDeletesMode.csproj, Microsoft.Azure.Cosmos.Samples/Usage/CFPullModelAllVersionsAndDeletesMode/Program.cs, Microsoft.Azure.Cosmos.Samples/Usage/ChangeFeedAllVersionsAndDeletes/ChangeFeedAllVersionsAndDeletes.csproj, Microsoft.Azure.Cosmos.Samples/Usage/ChangeFeedAllVersionsAndDeletes/Program.cs, Microsoft.Azure.Cosmos.Samples/Usage/Cosmos.Samples.Usage.sln
Adds sample for change feed processor using All Versions and Deletes mode.
Updates change feed pull sample for All Versions and Deletes mode to use built in `ChangeFeedItem` type.
=> [Internal] Samples: Adds CFP sample for all versions and deletes mode

changelog.md
Updates release notes to include fix for HPK issue.
=> ReleaseNotes : Fixes Release notes for v 3.42.0

Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryFeature.cs
Adds a new query feature that will be sent to the gateways to indicate support for Hybrid Search
=> [Internal] Query: Adds new query feature for hybrid search

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosAvailabilityStrategyTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosMultiRegionDiagnosticsTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/MultiRegionSetupHelpers.cs
Test improvements to decrease test time for hedging. Includes having a set database that is to be reused test to test, and disposing clients properly + stopping the change feed. 
=> [Internal] Hedging: Refactors Tests 

Microsoft.Azure.Cosmos/FaultInjection/tests/FaultInjectionTests.csproj
Fixes test project file so it compiles. 
=> [Internal] FaultInjection: Fixes Test Project File

CODEOWNERS
[INTERNAL] CodeOwners: Adds Kevin and removing Kirill from code owners
=> [INTERNAL] CodeOwners: Adds Kevin and removing Kirill from code owners

changelog.md
[INTERNAL] Changelog: Add note about Newtonsoft.Json (10.0.3) security vulnerability and upgrade to latest patched version
Ref: #4674
=> [INTERNAL] Changelog: Adds note about Newtonsoft.Json (10.0.3) security vulnerability and upgrade to latest patched version

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.43.1.txt, Microsoft.Azure.Cosmos/contracts/API_3.44.0-preview.1.txt, Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs, Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs, Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs, Microsoft.Azure.Cosmos/src/Routing/IGlobalEndpointManager.cs, Microsoft.Azure.Cosmos/src/Routing/LocationCache.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ClientRetryPolicyTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json, changelog.md
Cherry-picks changes specified in changelog to release branch
=> 3.43.1: Adds cherry-picks to hotfix release branch

templates/build-test.yml
[INTENRAL] CodeCoverage: Fixes Upgrading code coverage task
Build warning
=> [INTENRAL] CodeCoverage: Fixes Upgrading code coverage task

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryTests.cs
[INTERNAL] CI : Fixes Quarantine StreamOperationsTestDirectModeAsync
=> [INTERNAL] CI : Fixes Quarantine StreamOperationsTestDirectModeAsync

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryReleaseTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/EndToEndTraceWriterBaselineTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosAuthorizationTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosBadReplicaTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosHttpClientCoreTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GlobalEndpointManagerTest.cs, azure-pipelines.yml, templates/build-preview.yml, templates/build-test.yml
[INTERNAL] CI: Moving flaky tests into separate groups
=> [INTERNAL] CI: Fixes Moving flaky tests into separate groups

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/PartitionKeyRangeCacheTests.cs
Removing dependency on `Task.Delay() `
To automatically close an issue: closes #4732
=> [Internal] Flaky Test: Fixes PartitionKeyRangeCacheTests 

Microsoft.Azure.Cosmos.Samples/Usage/ApplicationInsights/ApplicationInsights.csproj, Microsoft.Azure.Cosmos.Samples/Usage/AzureFunctions/AzureFunctions.csproj, Microsoft.Azure.Cosmos.Samples/Usage/BulkExecutorMigration/BulkExecutorMigration.csproj, Microsoft.Azure.Cosmos.Samples/Usage/BulkSupport/BulkSupport.csproj, Microsoft.Azure.Cosmos.Samples/Usage/CFPullModelAllVersionsAndDeletesMode/CFPullModelAllVersionsAndDeletesMode.csproj, Microsoft.Azure.Cosmos.Samples/Usage/CFPullModelLatestVersionMode/CFPullModelLatestVersionMode.csproj, Microsoft.Azure.Cosmos.Samples/Usage/ChangeFeed/ChangeFeed.csproj, Microsoft.Azure.Cosmos.Samples/Usage/ChangeFeedAllVersionsAndDeletes/ChangeFeedAllVersionsAndDeletes.csproj, Microsoft.Azure.Cosmos.Samples/Usage/ContainerManagement/ContainerManagement.csproj, Microsoft.Azure.Cosmos.Samples/Usage/CustomDiagnosticAndEventListener/CustomDiagnosticAndEventListener.csproj, Microsoft.Azure.Cosmos.Samples/Usage/CustomSerialization/CustomSerialization.csproj, Microsoft.Azure.Cosmos.Samples/Usage/DatabaseManagement/DatabaseManagement.csproj, Microsoft.Azure.Cosmos.Samples/Usage/Encryption/Encryption.csproj, Microsoft.Azure.Cosmos.Samples/Usage/Geospatial/Geospatial.csproj, Microsoft.Azure.Cosmos.Samples/Usage/Handlers/HandlerSample.csproj, Microsoft.Azure.Cosmos.Samples/Usage/HttpClientFactory/HttpClientFactory.csproj, Microsoft.Azure.Cosmos.Samples/Usage/IndexManagement/IndexManagement.csproj, Microsoft.Azure.Cosmos.Samples/Usage/ItemManagement/ItemManagement.csproj, Microsoft.Azure.Cosmos.Samples/Usage/NonPartitionContainerMigration/NonPartitionContainerMigration.csproj, Microsoft.Azure.Cosmos.Samples/Usage/OpenTelemetry/OpenTelemetry.csproj, Microsoft.Azure.Cosmos.Samples/Usage/Queries/Queries.csproj, Microsoft.Azure.Cosmos.Samples/Usage/ReEncryption/ReEncryption.csproj, Microsoft.Azure.Cosmos.Samples/Usage/ServerSideScripts/ServerSideScripts.csproj, Microsoft.Azure.Cosmos.Samples/Usage/SystemTextJson/SystemTextJson.csproj, Microsoft.Azure.Cosmos.Samples/Usage/TransactionalBatch/TransactionalBatch.csproj, Microsoft.Azure.Cosmos.Samples/Usage/UserManagement/UserManagement.csproj
[INTERNAL]STJ: Upgrade STJ to 8.0.5 as per dependa bot
=> [INTERNAL]STJ: Fixes STJ to 8.0.5 as per dependa bot

templates/build-preview.yml, templates/build-test.yml
[INTERNAL] CI: Fixes timeout for tasks to 60M
=> [INTERNAL] CI: Fixes timeout for tasks to 60M

templates/static-tools.yml
This reverts commit 8e718b1a24350fa38c1dd9060fef8566c285398f.
=> [INTERNAL] CI: Fixes Revert disabling Binskim as nuget repo failing 

changelog.md
=> Changelog: Adds 4725 and 4762 to 3.44.0 change log entry

Microsoft.Azure.Cosmos.Encryption.Custom/tests/EmulatorTests/Microsoft.Azure.Cosmos.Encryption.Custom.EmulatorTests.csproj, Microsoft.Azure.Cosmos.Encryption.Custom/tests/Microsoft.Azure.Cosmos.Encryption.Custom.Tests/Microsoft.Azure.Cosmos.Encryption.Custom.Tests.csproj, Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/Microsoft.Azure.Cosmos.Encryption.EmulatorTests.csproj, Microsoft.Azure.Cosmos.Encryption/tests/Microsoft.Azure.Cosmos.Encryption.Tests/Microsoft.Azure.Cosmos.Encryption.Tests.csproj, Microsoft.Azure.Cosmos.sln, Microsoft.Azure.Cosmos/FaultInjection/src/FaultInjection.csproj, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Microsoft.Azure.Cosmos.Tests.csproj
[INTERNAL] FaultInjection: Fixes Newtonsoft and SystemTextJson to use latest versions
=> [INTERNAL] FaultInjection: Fixes Newtonsoft and SystemTextJson to use latest versions

Microsoft.Azure.Cosmos/contracts/API_3.44.1.txt, Microsoft.Azure.Cosmos/contracts/API_3.45.0-preview.1.txt, changelog.md
No contract changes.
changelog changes
=> 3.44.1 and 3.45.0.preview.1: Adds contract and changelog update

Directory.Build.props
…
Bumped up to 3.44.1 and 3.45.preview.1
=> 3.44.1: Refactors SDK version to 3.44.1 and preview version to 3.45.preview.1 (#4800)

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.45.0.txt, Microsoft.Azure.Cosmos/contracts/API_3.46.0-preview.0.txt, changelog.md
This bumps the SDK GA version from `3.44.1` to `3.45.0` and preview version from `3.45.0-preview.1` to `3.46.0-preview.0`. Please take a look at the changes in the public GA and preview contract/s.
**GA Contract Changes:**
**Preview Contract Changes:**
=> 3.45.0: Adds new SDK versions and contract files

Microsoft.Azure.Cosmos/src/Resource/FeedIterators/FeedIteratorCore.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.QueryAsync.xml
Ref. https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4851 for detailed explanation
- 
To automatically close an issue: closes #4851
=> Open telemetry: Fixes Populating Query text for non-stream Iterator

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.45.2.txt, Microsoft.Azure.Cosmos/contracts/API_3.46.0-preview.2.txt, changelog.md
This bumps the SDK GA version from `3.45.1` to `3.45.2` and preview version from `3.46.0-preview.1` to `3.46.0-preview.2`. No changes in the public GA and preview contract/s. 
=> 3.45.2: Adds new SDK versions and contract files

Directory.Build.props, Microsoft.Azure.Cosmos.sln, Microsoft.Azure.Cosmos/contracts/API_3.46.0.txt, Microsoft.Azure.Cosmos/contracts/API_3.47.0-preview.txt, changelog.md
This bumps the SDK GA version from 3.45.2 to 3.46.0 and preview version from 3.46.0-preview.2 to 3.47.0-preview.0. No changes in the public GA contract and preview contract. The images are given below:
=> 3.46.0: Adds new SDK versions and contract files

templates/emulator-setup.yml
[INTERNAL] CI: Fixes reverts to public emulator from internal emulator
=> [INTERNAL] CI: Fixes reverts to public emulator from internal emulator

templates/build-test.yml
Fixes the pipeline template to set the environment variable with the account connection string correctly. 
=> [Internal] Pipelines: Fixes setting connection string environment variable

Microsoft.Azure.Cosmos/FaultInjection/src/implementation/FaultInjectionRuleProcessor.cs, Microsoft.Azure.Cosmos/FaultInjection/tests/FaultInjectionDirectModeTests.cs, Microsoft.Azure.Cosmos/FaultInjection/tests/FaultInjectionGatewayModeTests.cs, Microsoft.Azure.Cosmos/FaultInjection/tests/Utils/TestCommon.cs
Refactors tests for clarity. No behavior change.
=> [Internal] FaultInjection: Refactors FaultInjection Tests

Directory.Build.props, Microsoft.Azure.Cosmos/FaultInjection/src/FaultInjection.csproj, azure-pipelines-faultinjection.yml, templates/build-fault-injection-test.yml, templates/fault-injection-nuget-pack.yml
Adds YML files needed for fault injection release.
These files might need to be revisited in a separate PR, as there is no way to test the new pipeline without these files being in master first. 
=> [Internal] Pipelines: Adds FI pipeline YMLs

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.46.1.txt, Microsoft.Azure.Cosmos/contracts/API_3.47.0-preview.1.txt, changelog.md
This bumps the SDK GA version from `3.46.0` to `3.46.1` and preview version from `3.47.0-preview.0` to `3.47.0-preview.1`. No changes in the public GA and preview contract/s. 
=> 3.46.1: Adds new SDK versions and contract files

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.46.1.txt, Microsoft.Azure.Cosmos/contracts/API_3.47.0-preview.1.txt, Microsoft.Azure.Cosmos/src/Regions.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json, changelog.md
- Upgrade Resiliency: Fixes Code to Clean-up Unhealthy Connection Object
- Region Availability: Adding SDK changes for Upcoming Regions.
=> [Hotfix] Upgrade Resiliency: Fixes Code to Clean-up Unhealthy Connection Object

Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs, Microsoft.Azure.Cosmos/src/DocumentClient.cs, Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs, Microsoft.Azure.Cosmos/src/Routing/AvailabilityStrategy/AvailabilityStrategy.cs, Microsoft.Azure.Cosmos/src/Routing/AvailabilityStrategy/CrossRegionHedgingAvailabilityStrategy.cs, Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs, Microsoft.Azure.Cosmos/src/Routing/IGlobalEndpointManager.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosAvailabilityStrategyTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/AvailabilityStrategyUnitTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
This reverts commit ee83a589e9bd09180b83a271d9b8aefab646db76.
The commit was breaking the release branch, so this PR reverts the commit to fix the issue. The commit would have needed additional commits to work, will postpone that commit until the next release. 
=> Releases: Fixes release branch by reverting previous commit.

Directory.Build.props
Updates the direct version to 3.37.7
=> [Internal] ThroughputBucketing: Adds direct version bump

Microsoft.Azure.Cosmos.Encryption.Custom/tests/Microsoft.Azure.Cosmos.Encryption.Custom.Tests/Contracts/DotNetSDKEncryptionCustomAPI.json, Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs, Microsoft.Azure.Cosmos/src/Routing/AvailabilityStrategy/AvailabilityStrategy.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Changes Hedging APIs to public for GA
=> Hedging: Adds Hedging for Read Requests to GA

azure-pipelines-official.yml
Sets multimaster account connection string for release pipeline run. 
=> [Internal] Pipelines: Fixes pipeline release run

azure-pipelines-official.yml
Sets multimaster account connection string for release pipeline run. 
=> [Internal] Pipelines: Fixes pipeline release run (#5002) into release branch

azure-pipelines.yml
As we have been experiencing issues with our release pipelines, we are currently going to run all tests run in those pipelines in every PR to catch potential errors and cut down on the number of flakey tests.  For publicly submitted PRs, please create an issue with any flaky tests with the label `flaky tests`.  
=> [Internal] Pipelines: Adds all tests that are ran during release pipelines to PR runs

Directory.Build.props, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTests.cs
Direct package upgrade to 3.37.10
Also contains an emulator test to verify connection management during aggressive timeouts.
Brings in the fix from Direct package:
https://msdata.visualstudio.com/CosmosDB/_git/CosmosDB/pullrequest/1574317?_a=files
To automatically close an issue: …
=> Direct code: Adds a direct package that contains a fix for Faster detection of broken transport connections.

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.47.1.txt, Microsoft.Azure.Cosmos/contracts/API_3.48.0-preview.1.txt, changelog.md
- Build.props change
NO CONTRACT CHANGES
=> 3.47.1: Adds build props for sdk-hotfix-release-3.47.1

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.47.2.txt, Microsoft.Azure.Cosmos/contracts/API_3.48.0-preview.2.txt, changelog.md
This bumps the SDK GA version from `3.47.1` to `3.47.2` and preview version from `3.48.0-preview.1` to `3.48.0-preview.2`. No changes in the public GA and preview contract/s. 
=> 3.47.2: Adds new SDK versions and contract files

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.47.2.txt, Microsoft.Azure.Cosmos/contracts/API_3.48.0-preview.2.txt, Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchOperationResult.cs, Microsoft.Azure.Cosmos/src/Json/Interop/CosmosDBToNewtonsoftReader.cs, Microsoft.Azure.Cosmos/src/Json/Interop/CosmosDBToNewtonsoftWriter.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemIntegrationTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchSchemaTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchUnitTests.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/NewtonsoftInteropTests.cs, changelog.md
This PR cherry-picks the following commits:
- https://github.com/Azure/azure-cosmos-dotnet-v3/pull/5030
=> [Hotfix] Binary Encoding: Fixes Serialization Gaps on Newtonsoft Reader/Writer for Transactional Batch

Microsoft.Azure.Cosmos/src/DocumentClient.cs, Microsoft.Azure.Cosmos/src/Util/ConfigurationManager.cs
Option to enable Channel level multiplexing
=> [INTERNAL] Channel: Adds Option to enable Channel level multiplexing

Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Adds the CosmosClientBuilder.WithAvailabilityStrategy method into GA.
To automatically close an issue: closes #5053
=> AvailabilityStrategy: Adds WithAvailabilityStrategy method to public GA

Microsoft.Azure.Cosmos/src/Handler/TransportHandler.cs
Fixes a race conditions where StoreProxy returned can be null when the client is getting disposed at the same time.
NOTE: Testing this is not easy due to this ebing a race condition. I evaluated using the ExceptionLess tests (which is using MockTransportHandler) - but it was not sutainable - because the race condition to hit the NullRef is tiny. Given that throwing ObjectDisposedException happens in other places regularly in this code path I think it is acceptable to not add a unit tests trying to provoke this edge condition.
To …
=> [Internal]: Fixes NullRef in TransportHandler when client is concurrently disposed.

changelog.md
Fixes changelog to have the correct version.
=> [Interna]] Changelog: Fixes Changelog

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.48.1.txt, Microsoft.Azure.Cosmos/contracts/API_3.49.0.preview.1.txt, changelog.md
Hotfix will include crucial bugfix: https://github.com/Azure/azure-cosmos-dotnet-v3/pull/5108
=> [Internal] 3.48.1: Refactors changelog + version for 3.48.1 hotfix

Microsoft.Azure.Cosmos/src/Resource/Settings/ContainerProperties.cs
HPK: Fixes code documentation to reference PartitionKeyPaths for HPK scenarios
=> HPK : Fixes code documentation to reference PartitionKeyPaths for HPK scenarios

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.49.1.txt, Microsoft.Azure.Cosmos/contracts/API_3.50.0-preview.1.txt, changelog.md
This change is a cherry-pick of #5176:
Version bump: Adds changelog, and contracts for version 3.49.1 release
=> Version bump: Adds changelog, and contracts for version 3.49.1 release (Cherry-Pick)

Microsoft.Azure.Cosmos.Samples/Usage/Hedging/ReadRequestDiagnosticsExample.json, Microsoft.Azure.Cosmos/src/Routing/AvailabilityStrategy/AvailabilityStrategy.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json, docs/Cross Region Request Hedging.md
This pull request GAs hedging for write requests. It also updates hedging documentation and adds a full diagnostics example. 
=> Hedging: Adds Hedging for Write requests GA

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.50.0.txt, Microsoft.Azure.Cosmos/contracts/API_3.51.0-preview.0.txt, changelog.md
Updates SDK to version 3.50.0
GA Contracts: 
Preview Contracts: 
=> 3.50.0: Adds version bump and changelog

Microsoft.Azure.Cosmos/src/Query/Core/QueryAdvisor/QueryAdviceRuleDocumentation.xml, Microsoft.Azure.Cosmos/src/Query/Core/QueryAdvisor/RuleDirectory.cs
This PR updates the query advice rule documentation to reflect the latest wording for Query Advisor capability.
=> [Internal] Query: Fixes QueryAdviceRuleDocumentation

changelog.md
Changelog displays wrong version
=> [Internal] Changelog: Fixes Changelog

Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.Strings.cs, Microsoft.Azure.Cosmos/src/Json/JsonStringDictionary.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonReaderTests.cs
Porting a fix for encoding for multi-byte user defined strings.
=> [Internal] Binary Encoding: Fixes encoding for multi-byte user defined strings

azure-pipelines.yml
This PR allows automatic triggering of pipelines for the msdata/direct branch
=> [Internal] Msdata: Adds pipeline runs to msdata/direct branch

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.52.0.txt, Microsoft.Azure.Cosmos/contracts/API_3.53.0-preview.0.txt, changelog.md
This bumps the SDK GA version from `3.51.0` to `3.52.0` and preview version from `3.52.0-preview.0 ` to `3.53.0-preview.0.` Please see the below changes in the public GA and preview contract/s.
GA Contract Changes:
Preview Contract Changes:
=> 3.52.0: Adds new SDK versions and contract files

Microsoft.Azure.Cosmos.Encryption.Custom/src/Microsoft.Azure.Cosmos.Encryption.Custom.csproj, Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj, Microsoft.Azure.Cosmos/FaultInjection/src/FaultInjection.csproj, Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
Sets the license expression on the nuget package 
Closes #5187
=> set license expression #5187

Microsoft.Azure.Cosmos/src/Query/Core/QueryClient/CosmosDistributedQueryClient.cs, Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs, Microsoft.Azure.Cosmos/src/Resource/CosmosResponseFactoryCore.cs, Microsoft.Azure.Cosmos/src/Tracing/TraceData/TraceDatumKeys.cs, Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryPerfTest/MetricsAccumulator.cs
Adds a new class for trace datum keys so that trace parsing in query benchmarks stays up to date.
=> [Internal] Query: Adds Constants for Trace Datum Keys

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.53.0.txt, Microsoft.Azure.Cosmos/contracts/API_3.54.0-preview.0.txt, changelog.md
GA Contract changes: 
Preview changes: 
=> 3.53.0: Adds new SDK version and contract files

azure-pipelines-msdata-aot.yml
=> [Internal]msdata/aot: Adds Base pipes for aot changes to msdata/aot

azure-pipelines-msdata-aot.yml
=> [Internal] AOT: Adds Base Pipeline for AOT Package Generation

Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
This PR skips non project reference dependencies from `Microsoft.Azure.Cosmos.csproj` file.
=> [Internal] AOT: Adds Code to Skip Non Project Reference Dependency from Csproj

Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
Fix Manifest in Build Pipeline 
=> [Internal] AOT: Adds Code to Fix Manifest in Build Pipeline Part 1

Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj, azure-pipelines-msdata-aot.yml
Fixes Build Configuration in Pipeline Yaml.
=> [Internal] AOT: Adds Code to Fix Build Configuration in Pipeline Yaml

Directory.Build.props, Microsoft.Azure.Cosmos/contracts/API_3.53.1.txt, Microsoft.Azure.Cosmos/contracts/API_3.54.0-preview.1.txt, changelog.md
This bumps the SDK GA version from 3.53.0 to 3.53.1 and preview version from 3.54.0-preview.0 to 3.54.0-preview.1 It is a patch upgrade to the previous release.
There are no contract changes
=> 3.53.1: Adds hotfix release 3.53.1

Directory.Build.props
- Contains changes for Add annotations and suppressions for safe EventSource usage (#5389)
- 
=> [Internal] AOT: Adds 0.1.2-preview.1 release

Microsoft.Azure.Cosmos/src/DocumentClientEventSource.cs
The DocumentClientEventSource type has a helper method that needs RUC, but there's no way to include that method directly in the type since the base type (EventSource) has DynamicallyAccessedMembers.NonPublicMethods applied. This change hides the helpers inside a private nested class.
=> [Internal] AOT: Refactors Code to Hide RUC members from `DAM.NonPublicMethods`

Microsoft.Azure.Cosmos/src/DocumentClientEventSource.cs
Add suppression instead of trying to hide the method. This should be safe since EventSource will ignore `NonEvent` methods.
=> [Internal] AOT: Adds Code to Suppress DAM warning

Directory.Build.props
Contains changes for Add annotations and suppressions for safe `EventSource` usage.
=> [Internal] AOT: Adds 0.1.2-preview.2 Release
