Azure/azure-cosmos-dotnet-v3

Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItems.cs

The description for the `maxConcurrency` parameter was talking about the `PartitionKey`, probably leftovers from a previous method signature.
This PR fixes that.

Fixed the maxConcurrency parameter summary

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs

This test verifies that if the EPK option is set that only a single partition key range is selected.

Add test to verify that EPK option is honored in query pipeline.

---

Microsoft.Azure.Cosmos/src/AssemblyInfo.cs
Microsoft.Azure.Cosmos/src/Handler/CosmosRequestMessage.cs
Microsoft.Azure.Cosmos/src/Handler/RouterHandler.cs
Microsoft.Azure.Cosmos/src/Headers/CosmosRequestMessageHeaders.cs
Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
Microsoft.Azure.Cosmos/src/Query/StandByFeedContinuationToken.cs
Microsoft.Azure.Cosmos/src/RequestOptions/CosmosChangeFeedRequestOptions.cs
Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItemsCore.cs
Microsoft.Azure.Cosmos/src/Resource/QueryResponses/CosmosChangeFeedResultSetIteratorCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemChangeFeedTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosResponseMessageTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/StandByFeedContinuationTokenTests.cs

Merge master into release (CF Pull internal API)

Merge master into release (CF Pull internal API)

---

Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimatorCore.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedManagement/PartitionControllerCore.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedManagement/PartitionLoadBalancerCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/BaseChangeFeedClientHelper.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/DynamicTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/EstimatorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/SmokeTests.cs

This PR adds Emulator tests covering different scenarios both for Change Feed Processor and Change Feed Estimator.
All tests have a defined Category in case we want to turn the on/off.
Additionally, some changes were made so it is now possible to Start, Stop and then Start again a Processor and Estimator. Originally they were left in a non Start-able state after a Stop.

Adding Change Feed Processor and Estimator emulator tests

---

Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimatorCore.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedProcessorBuilder.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedProcessorCore.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLease.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseUpdaterCosmos.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Utils/CosmosContainerExtensions.cs
Microsoft.Azure.Cosmos/src/Resource/CosmosIdentifier.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/BootstrapperTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/ChangeFeedEstimatorCoreTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/ChangeFeedProcessorBuilderTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/ChangeFeedProcessorCoreTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentServiceLeaseContainerCosmosTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentServiceLeaseContainerInMemoryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentServiceLeaseTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentServiceLeaseUpdaterCosmosTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentServiceLeaseUpdaterInMemoryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/EqualPartitionsBalancingStrategyTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/Exceptions/LeaseLostExceptionTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/Exceptions/ObserverExceptionTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/HealthinessMonitorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/ObserverExceptionWrappingChangeFeedObserverDecoratorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/PartitionControllerSplitTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/PartitionControllerTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/PartitionLoadBalancerTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/PartitionSupervisorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/RemainingWorkEstimatorTests.cs

This PR adds 100+ unit tests covering the Change Feed Processor / Estimator. Some where ported from the current CFP SDK repo and refactored for our new class distribution, others are entirely new based on our new Builder.
Some fixes to current files:
* `DocumentServiceLease` should've been `Serializable`
* Added `internal` constructor to `ChangeFeedEstimatorCore` for mocking purposes
* Added `internal` `WithMonitoredContainerRid` builder extension to be able to specify the ContainerRid for the leases so the Builder does not have to do a `GetRID` call (which would fail in a mocked scenario).
* `DocumentServiceLeaseUpdaterCosmos` was incorrectly detecting `NotFound` status through exceptions
* `CosmosIdentifier` got some attributes marked as `virtual` although this will be refactored once …

Adding Change Feed Processor Unit Tests

---

Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainerCore.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosContainerSettings.cs

Contianer is caching the None mapping which in-case of container re-create might get stale. 
None values always derived from CosmosContainerSettings. It resutls in one extra call to local cache most of the time.

Making Container.NonePartitionKeyValue stateless

---

Microsoft.Azure.Cosmos/src/CosmosClient.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContractTests.cs

Moving API version initialization to static CTOR.
And related unit-test

Moving API version initialization to static CTOR

---

Microsoft.Azure.Cosmos/src/Query/CosmosPipelinedItemQueryExecutionContext.cs
Microsoft.Azure.Cosmos/src/RequestOptions/CosmosQueryRequestOptions.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs

Testing  query Offset-Limit from V3 SDK.
Added EnableCrossPartitionSkipTake as internal and added exception handling for it  in 
CosmosPipelinedItemQueryExecutionContext.cs , this will go  once we are ready with this feature for customer.

Query Offset/Limit testing from V3 SDK

---

Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosAccountSettings.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SettingsContractTests.cs

Due to the lack of JsonProperty, the SDK was not being able to detect Multi Master accounts correctly.

EnableMultipleWriteLocations serialization bug

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs

Distinct and MultiOrder code is already exist in V3 SDK , along with needed test cases.
Verified all the changes need to support these two features. Just sending one change PR which
will make sure we are testing MultiOrder  with the latest api version.

Testing MultiOrder with latest version

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs

The current function creates the container and inserts one item.
Refactored to two separate functions to allow creation of multiple items in the container. This is needed for future tests.

Refactor CreateNonPartitionContainerItem to allow creation of more items in the container.

---

Microsoft.Azure.Cosmos/src/Query/CosmosOrderByItemQueryExecutionContext.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs

This PR escapes non ascii characters in query continuation tokens.
For cross partition queries with ORDER BY we generate a continuation token that serializes the state of the query. That state includes the order by item. The problem happens when a user tries to resume that query from the continuation token and we put that continuation token in an HTTP header. The gateway rejects the header and we get back some HTML file explaining that the request was invalid. The problem is when we try to parse that HTML page as JSON we get a serialization exception and the user sees: "Unexpected character encountered while parsing value: (value is lt). Path '', line 0, position 0.". Which is basically saying that the "<" character in "<HTML>" is not valid JSON.
The solution was to escape all non ascii …

Escaping non ascii characters in query continuation tokens

---

Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedProcessorBuilder.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedProcessing/AutoCheckpointer.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedProcessing/ChangeFeedObserver.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedProcessing/ChangeFeedObserverBase.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedProcessing/ChangeFeedObserverFactoryCore.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedProcessing/ObserverExceptionWrappingChangeFeedObserverDecorator.cs
Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItems.cs
Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItemsCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/DynamicTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/EstimatorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/SmokeTests.cs

`IReadOnlyList` contains an additional index property that `IReadOnlyCollection` does not. The changes are meant to be read in order (use the Enumerator), so moving to `IReadOnlyCollection` enforces this contract.
This PR fixes #172

Moving IReadOnlyList to IReadOnlyCollection

---

Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItems.cs
Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItemsCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/EstimatorTests.cs

Renaming `CreateChangeFeedProcessorBuilder` to `CreateChangeFeedEstimatorBuilder` for estimation purposes.

Change Feed Estimator public API

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryTests.cs

Test is flaky and also not a client test

Ignoring TestLazyIndexAllTerms

---

Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.cs

Added new system strings.
Tests already exist in:
`JsonWriterTests.cs` and `JsonReaderTests.cs`
SystemStringTest
It uses reflection so it automatically picks up the full set of strings:
```c#
[TestMethod]
[Owner("brchon")]
public void SystemStringTest()
{
Type jsonBinaryEncodingType = typeof(JsonBinaryEncoding);
FieldInfo systemStringsFieldInfo = jsonBinaryEncodingType.GetField("SystemStrings", BindingFlags.NonPublic | BindingFlags.Static);
string[] systemStrings = (string[])systemStringsFieldInfo.GetValue(null);
Assert.IsNotNull(systemStrings, "Failed to get system strings using reflection");
int systemStringId = 0;
foreach (string systemString in systemStrings)
{
string expectedString = "\"" + systemString + "\"";
byte[] binaryOutput =
{
BinaryFormat, …
```

Adding new system strings

---

Microsoft.Azure.Cosmos/src/Resource/Conflict/CosmosContainer.Conflict.cs
Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainers.cs
Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabases.cs
Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItems.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosUserDefinedFunctionSettings.cs
Microsoft.Azure.Cosmos/src/Resource/StoredProcedure/CosmosStoredProcedures.cs
Microsoft.Azure.Cosmos/src/Resource/Trigger/CosmosTriggers.cs
Microsoft.Azure.Cosmos/src/Resource/UserDefinedFunction/CosmosUserDefinedFunctions.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemChangeFeedTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CustomSerializationTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/UserDefinedFunctionsTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ResultSetIteratorTests.cs

It will rename CosmosResultSetIterator  to CosmosFeedIterator  in documentation and its sample examples.
Also  changing the object name from setIterator to feedIterator for consistency

Replacing CosmosResultSetIterator to CosmosFeedIterator in Documentation.

---

Microsoft.Azure.Cosmos/src/CosmosClient.cs
Microsoft.Azure.Cosmos/src/Handler/ClientPipelineBuilder.cs
Microsoft.Azure.Cosmos/src/Handler/CosmosRequestMessage.cs
Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainerCore.cs
Microsoft.Azure.Cosmos/src/Resource/CosmosClientContext.cs
Microsoft.Azure.Cosmos/src/Resource/CosmosClientContextCore.cs
Microsoft.Azure.Cosmos/src/Routing/ClientCollectionCache.cs
Microsoft.Azure.Cosmos/src/Routing/CollectionCache.cs
Microsoft.Azure.Cosmos/src/Util/ExecUtils.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TransportWrapperTests.cs

CreateItemStreamAsync targeting a NP collection with NonePartitionKeyValue should not throw exception. Expected to return status code. 
Currently for partitioned collection its returning 404 and will return the same. 
For GA we should make it 424 (Dependency failure) instead for dis-disambiguate it. 
- ExecUtils moved to the path of deprecation. Related changes moved to RequestInvokerHandler
- RequestInvokerHandler made primary entry contract for client
- Fixed a bug introduced with FI from master, where cached ContainerSettings are not used. 
closes #233

Exception-less Streaming API for non-existing NP container scenarios

---

Microsoft.Azure.Cosmos.Samples/CodeSamples/ContainerManagement/Program.cs
Microsoft.Azure.Cosmos.Samples/CodeSamples/DatabaseManagement/Program.cs
Microsoft.Azure.Cosmos.Samples/CodeSamples/Handlers/Program.cs
Microsoft.Azure.Cosmos.Samples/CodeSamples/ItemManagement/Program.cs
Microsoft.Azure.Cosmos.Samples/CodeSamples/Queries/Program.cs
Microsoft.Azure.Cosmos.Samples/CodeSamples/ServerSideScripts/Program.cs

Fixing samples build break

---

Microsoft.Azure.Cosmos/src/Query/CosmosQueryExecutionContextFactory.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs

Fix for query failing with CosmosContainerSettings.NonePartitionKeyValue on non partitioned container.
Issue fix involve two points
1. We need to check CosmosContainerSettings.NonePartitionKeyValue whenever fetching PartitionKeyInternal
2. Remove setting PartitionKey.FromInternalKey(containerSettings.GetNoneValue()) in code as partition key in case of NonePartitionKeyValue , because we are now checking condition 
else if (Object.ReferenceEquals(partitionKey, CosmosContainerSettings.NonePartitionKeyValue)) in 
RequestInvokerHandler , which makes it false if we didn't leave it as CosmosContainerSettings.NonePartitionKeyValue
-  Bug fix (non-breaking change which fixes an issue)
#241

Query issue fix for none partitioned collection

---

Microsoft.Azure.Cosmos/src/CosmosClient.cs
Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
Microsoft.Azure.Cosmos/src/Query/CosmosQueryContext.cs
Microsoft.Azure.Cosmos/src/Query/CosmosQueryExecutionContextFactory.cs
Microsoft.Azure.Cosmos/src/Resource/QueryResponses/CosmosResultSetIteratorCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.AggregateMixedTypes_baseline.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.OnePartition.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTestsNp.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DirectContractTests.cs

Query related fixes for 3.0.0.11-preview release

---

Microsoft.Azure.Cosmos/src/Resource/CosmosException.cs
Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItemsCore.cs
Microsoft.Azure.Cosmos/src/Resource/QueryResponses/CosmosQueryResponse.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosNotFoundTests.cs

The query pipeline was updated to use the v3 pipeline which throws cosmos exceptions instead of document client exceptions. The try catch for the query logic is now updated to handle the new exception type.
closes #256

Not found fix for release branch

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/DynamicTests.cs

Current emulator in CI has socket issues due to a reported bug. This issues make some of our tests fails, particularly `TestReducePageSizeScenario`. This PR disables such test until 
- [X ] Bug fix (non-breaking change which fixes an issue)
#289 is tracking the re-enablement of this test once the Emulator fix is done.

TestReducePageSizeScenario failing on CI

---

Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainers.cs
Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainersCore.cs
Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabases.cs
Microsoft.Azure.Cosmos/src/Resource/Database/CosmosDatabasesCore.cs
Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItems.cs
Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItemsCore.cs
Microsoft.Azure.Cosmos/src/Resource/StoredProcedure/CosmosStoredProcedures.cs
Microsoft.Azure.Cosmos/src/Resource/StoredProcedure/CosmosStoredProceduresCore.cs
Microsoft.Azure.Cosmos/src/Resource/Trigger/CosmosTriggers.cs
Microsoft.Azure.Cosmos/src/Resource/UserDefinedFunction/CosmosUserDefinedFunctions.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosReadFeedTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.OnePartition.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTestsNp.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/NameRoutingTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/StoredProcedureTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TriggersTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/UserDefinedFunctionsTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TestCommon.cs

Based on feed back rename all iterators to be plural.
Get{Resource}Iterator -> Get{Resource}sIterator 
closes #270

Rename all iterators to be plural

---

Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosContainerSettings.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosContainerSettingsTests.cs

The UnixDateTimeConverter throws if the value is null. Last Modified is a null-able date which causes an exception for compute scenarios. Adding a JSON ignore tag to prevent serializing the null value.

CosmosContainerSettings.LastModified is now ignored if null

---

Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosContainerSettings.cs

CreateWithResourceId marked as pure internal
closes #260

CreateWithResourceId marked as pure internal

---

Microsoft.Azure.Cosmos/src/Resource/CosmosException.cs
Microsoft.Azure.Cosmos/src/Routing/NonRetriableInvalidPartitionExceptionRetryPolicy.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosNotFoundTests.cs

This fixes a bug which causes a 410 exception to be returned to users. The retry policy was updated to handle CosmosException type instead of DocumentClientExceptions.

Release branch name cache fix

---

Microsoft.Azure.Cosmos/src/Headers/CosmosResponseMessageHeaders.cs
Microsoft.Azure.Cosmos/src/Resource/Item/ItemResponse.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosResponseMessageHeadersTests.cs

This PR creates a promoted property in the `CosmosResponseMessageHeaders` to access the Session Token easily, both in Stream and Typed operations.
As an example, to obtain the Session Token, both in Typed and Stream operations, the user can do:
ItemResponse<MyClass> responseAstype = await container.CreateItemAsync<MyClass>(partitionKey: myPK, item: myItem);
string sessionToken = responseAstype.Headers.Session;
CosmosResponseMessage readResponse = await container.ReadItemAsStreamAsync(myPK, myItem.id, new ItemRequestOptions() { SessionToken = sessionToken });
string sessionTokenFromStreamOperation = readResponse.Headers.Session;
- [X ] New feature (non-breaking change which adds functionality)
This PR closes #269

Session Token as promoted property in Headers

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosJsonSerializerTests.cs

This PR adds a test to assert the default serialization behavior (`NullValueHandling = NullValueHandling.Ignore`) and make sure we don't regress it in any future change.
This PR closes #350

Adding test to cover default serialization behavior

---

Microsoft.Azure.Cosmos.Samples/CodeSamples/AzureFunctions/Startup.cs

Current Azure Functions sample ran locally, but when deployed to Azure, it was missing the Environment aware extension to read the configuration.
This PR closes #374

Azure Functions sample fix

---

Microsoft.Azure.Cosmos/src/Resource/CosmosResponseFactory.cs
Microsoft.Azure.Cosmos/src/Scripts/CosmosScripts.cs
Microsoft.Azure.Cosmos/src/Scripts/CosmosScriptsCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/GatewayTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/NameRoutingTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/StoredProcedureTests.cs

This PR adds the possibility of executing a Stored Procedure and receive the response as a Stream instead of a particular Type and to send a Stream as the payload directly.
The signature of the method in the `CosmosScripts` group is:
`public Task<CosmosResponseMessage> ExecuteStoredProcedureStreamAsync(Stream)`
This PR closes #362
This PR closes #201

ExecuteStoredProcedure with Streams support

---

Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainer.cs
Microsoft.Azure.Cosmos/src/Resource/Container/CosmosContainerCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosConflictTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ResultSetIteratorTests.cs

Following #333, the Container -> Conflicts property is converted to Container -> GetConflicts() following the pattern of GetContainer().
This PR closes #333

GetConflicts instead of property

---

Microsoft.Azure.Cosmos/src/DocumentClient.cs

GetEntryAssembly is null in case of .net2.0, which is causing failures in test code which uses reflections.
Fixing code to not run when GetEntryAssembly is null.

Fixing issue with getentryassembly being null in case of .net2.0 in release branch

---

Microsoft.Azure.Cosmos/src/DocumentClient.cs

Cherry-pick: Fixing issue with getentryassembly being null in case of .net2.0 (#367)
Release commit: 698fb0dca217ab92cfc56b33297fdba8fe238265

Cherry-pick: Fixing issue with getentryassembly being null in case of .net2.0 (#367)

---

Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedProcessorBuilder.cs
Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItems.cs
Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItemsCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/DynamicTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/EstimatorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/SmokeTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/ChangeFeedProcessorBuilderTests.cs

This PR addresses 2 renames:
* workflowName -> processorName
* WithCosmosLeaseContainer -> WithLeaseContainer 
This PR closes #387

Rename workflowName and WithCosmosLeaseContainer 

---

Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosConflictSettings.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosContainerSettings.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosDatabaseSettings.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosStoredProcedureSettings.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosVirtualUnitTest.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SettingsContractTests.cs

Updating the data contract to match the SDK .NET standards. This removes virtual from all the properties which will block the ability to mock the contracts.
Put closes #344

Removed virtual from data contracts

---

Microsoft.Azure.Cosmos/src/Handler/ClientPipelineBuilder.cs
Microsoft.Azure.Cosmos/src/Handler/CosmosRequestMessage.cs
Microsoft.Azure.Cosmos/src/Handler/NamedCacheRetryHandler.cs
Microsoft.Azure.Cosmos/src/Handler/PartitionKeyRangeHandler.cs
Microsoft.Azure.Cosmos/src/Handler/RetryHandler.cs
Microsoft.Azure.Cosmos/src/Query/CosmosGatewayQueryExecutionContext.cs
Microsoft.Azure.Cosmos/src/Query/DefaultDocumentQueryExecutionContext.cs
Microsoft.Azure.Cosmos/src/Routing/InvalidPartitionExceptionRetryPolicy.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/MockDocumentClient.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyRangeHandlerTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/RetryHandlerTests.cs

This fixes the issue where the collection recreate causes a 410 exception to be returned to users.
InvalidPartitionExceptionRetryPolicy refreshes the name collection cache, but no the RID based Collection Cache. The PartitionKeyRangeHandler does a collection cache lookup based on rid which always gets the stale value. Updated PartitionKeyRangeHandler to use name cache lookup to match the other retry policies.

Read feed correctly handle 410 gone.

---

Microsoft.Azure.Cosmos/src/FeedResponseBinder.cs
Microsoft.Azure.Cosmos/src/Linq/DocumentQuery.cs
Microsoft.Azure.Cosmos/src/Resource/Item/CosmosItemsCore.cs
Microsoft.Azure.Cosmos/src/Resource/QueryResponses/CosmosQueryResponse.cs
Microsoft.Azure.Cosmos/src/Resource/QueryResponses/CosmosResultSetIteratorCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs

Stream query are not accessing the internal continuation token. This is causing the query API to always throw as the iterator tries to access the value. It now correctly access the continuation token and added tests.

Fix query continuation token throw

---

Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.cs
Microsoft.Azure.Cosmos/src/Json/JsonNavigator.JsonBinaryNavigator.cs
Microsoft.Azure.Cosmos/src/Json/JsonNavigator.JsonTextNavigator.cs
Microsoft.Azure.Cosmos/src/Json/JsonNavigator.cs
Microsoft.Azure.Cosmos/src/Json/JsonReader.JsonBinaryReader.cs
Microsoft.Azure.Cosmos/src/Json/JsonReader.cs
Microsoft.Azure.Cosmos/src/Json/JsonStringDictionary.cs
Microsoft.Azure.Cosmos/src/Json/JsonWriter.JsonBinaryWriter.cs
Microsoft.Azure.Cosmos/src/Json/JsonWriter.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonNavigatorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonReaderTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonStringDictionaryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonTestUtils.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonWriterTests.cs

The PR adds user string encoding for binary encoding. For field names in documents can be converted to a single byte to save on storage. The PR is mainly a port of the native implementation:
https://msdata.visualstudio.com/_git/CosmosDB/commit/09b4b84c7424ef9a86936248c462e76fcaebbaf8?path=%2FProduct%2FBackend%2Fnative%2FTest%2Fcommon%2Fserialization%2FJsonWriterTest.cpp&gridItemType=2&mpath=%2FProduct%2FBackend%2Fnative%2FTest%2Fcommon%2Fserialization%2FJsonWriterTest.cpp&opath=%2FProduct%2FBackend%2Fnative%2FTest%2Fcommon%2Fserialization%2FJsonWriterTest.cpp&mversion=GC09b4b84c7424ef9a86936248c462e76fcaebbaf8&oversion=GC49c76647064e9ecaeb3c28be959f1ed818010bc6&_a=compare
Once the handshake protocol is finalized we can leverage this in production.

user string encoding for binary encoding

---

Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseUpdaterCosmos.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Utils/CosmosContainerExtensions.cs
Microsoft.Azure.Cosmos/src/RequestOptions/RequestOptions.cs
Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosJsonSerializerTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosNotFoundTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosReadFeedTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CustomSerializationTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Fluent/CosmosContainerSettingsFluentTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/NameRoutingTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TransportWrapperTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Benchmarks/DocumentBenchmark.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentServiceLeaseUpdaterCosmosTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/HandlerTests.cs

Changing item operations parameter order to:
CreateItemAsync        (Item, PK = null, Options = null)
UpsertItemAsync        (Item, PK = null, Options = null)
ReplaceItemAsync    (Item, Id, PK = null, options = null)
CreateItemStreamAsync    (Stream, PK, Options = null)
UpsertItemStreamAsync    (Stream, PK, Options = null)
ReplaceItemStreamAsync    (Stream, Id, PK, options = null)
ReadItemAsync        (Id, PK, Options)
DeleteItemAsync        (Id, Pk)
Closes #428

Parameter order in item operations

---

Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimatorCore.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedProcessing/ChangeFeedEstimatorDispatcher.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedProcessing/ChangeFeedObserverBase.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedProcessing/ChangeFeedObserverFactoryCore.cs
Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/DynamicTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/EstimatorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/SmokeTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/ChangeFeedEstimatorCoreTests.cs

Based on feedback, we are renaming the builder methods for Change Feed processor and estimator and replacing `Func` with explicit delegates to avoid parameter confusion:
public delegate Task ChangesHandler<T>(
IReadOnlyCollection<T> changes, 
CancellationToken cancellationToken);
public delegate Task ChangesEstimationHandler(
long estimatedPendingChanges, 
CancellationToken cancellationToken);
public abstract ChangeFeedProcessorBuilder DefineChangeFeedProcessor<T>(
string processorName,
ChangesHandler<T> onChangesHandler);
public abstract ChangeFeedProcessorBuilder DefineChangeFeedEstimator(
string processorName,
ChangesEstimationHandler estimationHandler,
TimeSpan? estimationPeriod = null);
Closes #432

Change Feed Processor public API name changes

---

Microsoft.Azure.Cosmos/src/Fluent/Settings/ConflictResolutionDefinition.cs
Microsoft.Azure.Cosmos/src/Fluent/Settings/ContainerBuilder.cs
Microsoft.Azure.Cosmos/src/Fluent/Settings/UniqueKeyDefinition.cs
Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs
Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/DynamicTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/EstimatorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/SmokeTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/CompositeIndexDefinitionTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/ConflictResolutionDefinitionTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/ContainerDefinitionForCreateTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/IndexingPolicyDefinitionTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/PathsDefinitionTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/SpatialIndexDefinitionTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/UniqueKeyDefinitionTests.cs

To align with user intent and make the Builder discoverable, the methods in the Container to access the Change Feed Builders are changed to:
* `GetChangeFeedProcessorBuilder`
* `GetChangeFeedEstimatorBuilder`
For Container, changing `DefineContainer` to `GetContainerBuilder` and `CreateContainerDefinition` to `ContainerBuilder`.
Closes #448

Builders Get contract

---

Microsoft.Azure.Cosmos/src/Spatial/BoundingBox.cs
Microsoft.Azure.Cosmos/src/Spatial/Crs.cs
Microsoft.Azure.Cosmos/src/Spatial/Geometry.cs
Microsoft.Azure.Cosmos/src/Spatial/GeometryCollection.cs
Microsoft.Azure.Cosmos/src/Spatial/GeometryParams.cs
Microsoft.Azure.Cosmos/src/Spatial/GeometryValidationResult.cs
Microsoft.Azure.Cosmos/src/Spatial/LineString.cs
Microsoft.Azure.Cosmos/src/Spatial/LineStringCoordinates.cs
Microsoft.Azure.Cosmos/src/Spatial/LinearRing.cs
Microsoft.Azure.Cosmos/src/Spatial/LinkedCrs.cs
Microsoft.Azure.Cosmos/src/Spatial/MultiLineString.cs
Microsoft.Azure.Cosmos/src/Spatial/MultiPoint.cs
Microsoft.Azure.Cosmos/src/Spatial/MultiPolygon.cs
Microsoft.Azure.Cosmos/src/Spatial/NamedCrs.cs
Microsoft.Azure.Cosmos/src/Spatial/Point.cs
Microsoft.Azure.Cosmos/src/Spatial/Polygon.cs
Microsoft.Azure.Cosmos/src/Spatial/PolygonCoordinates.cs
Microsoft.Azure.Cosmos/src/Spatial/Position.cs
Microsoft.Azure.Cosmos/src/Spatial/UnspecifiedCrs.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SpatialTests.cs

This PR adds `[DataContract]` to Spatial classes and unit tests to verify serialization.
Closes #16

Spatial classes with DataContract

---

Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQuery.cs
Microsoft.Azure.Cosmos/src/Resource/CosmosExtensions.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs

This will add the extension method ToFeedIterator () on IQueryable which will give user the ability
to create LINQ query and execute it asynchronously via FeedIterator.
It will close #https://github.com/Azure/azure-cosmos-dotnet-v3/issues/460

Adding ToFeedIterator to LINQ

---

Microsoft.Azure.Cosmos/src/Handler/TransportHandler.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
Microsoft.Azure.Cosmos/src/Resource/CosmosException.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosItemUnitTests.cs

Making the CosmosException headers public, and adding retry after. This is needed for different retry scenarios.

CosmosException response headers are public and adding retry after

---

Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/SinglePartitionRequestOptionsFactory.cs
Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
Microsoft.Azure.Cosmos/src/PartitionKey.cs
Microsoft.Azure.Cosmos/src/Query/CosmosQueryExecutionContextFactory.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/ContainerProperties.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentServiceLeaseUpdaterInMemoryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosItemUnitTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyTests.cs

Partition Key currently takes an object as a parameter for the constructor. This is very confusing to users since only a few primitives are supported.
closes #354, fixes #471

Adding specific constructors to PartitionKey

---

Microsoft.Azure.Cosmos/src/CosmosClient.cs
Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs

During CosmosClient constructor, we are doing a locking call to obtain the account consistency. Account consistency is only ever checked if the user overwrites the Consistency at the request level, so this lock was penalizing all clients for a check that only is done in a subset of scenarios.
Closes #475

Make CosmosClient creation non-blocking

---

Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedProcessorCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/DynamicTests.cs

Current CFP V2 supports Lease container to be fixed. If a user on V2 migrates to V3, we need to also support the possibility of fixed lease containers. The code was meant to support it but since migrated Fixed containers now have a system PK, it was not behaving as it should.
Closes #491

Change Feed Processor supporting fixed lease containers

---

Microsoft.Azure.Cosmos/src/Resource/QueryResponses/QueryResponse.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs

There was a previous assumption that all exceptions from Cosmos DB contained an error message. This is not true for the throttle exception(429 ToManyRequests). I removed the unnecessary null check and added tests.
Put closes #518

Fixed query handling 429s by removing unnecessary null check.

---

Microsoft.Azure.Cosmos/src/Resource/Conflict/Conflicts.cs
Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs
Microsoft.Azure.Cosmos/src/Resource/Scripts/Scripts.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/UserDefinedFunctionProperties.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosNotFoundTests.cs

This PR will remain the stream APIs for container
From  - ReadStreamAsync,DeleteStreamAsync,ReplaceStreamAsync 
To  - ReadContainerStreamAsync,DeleteConatinerStreamAsync,ReplaceContainerStreamAsync 
Also it will fix the gap between actual APIs and example implementation in documentation on all the resources through out the code and add missing examples.

Renaming container stream api and improving documentation example throughout code

---

Microsoft.Azure.Cosmos/src/Query/ParallelQuery/DocumentProducer.cs
Microsoft.Azure.Cosmos/src/Query/ParallelQuery/ItemProducer.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/ItemProducerTreeUnitTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/MockItemProducerFactory.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/MockQueryFactory.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/MockResponseForSinglePartition.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPipelineMockTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryResponseMessageFactory.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/ToDoItem.cs

Fixes bug that causes item producer tree to lose continuation token on split. Added more mocks tests to include continuation token.

Porting Fix query split bug loses continuation token (#531) to releases\3.0.0

---

Microsoft.Azure.Cosmos/src/Resource/CosmosException.cs

Fix mis-typed message in CosmosException.ToString() 
closes #547

Fix mis-typed message in CosmosException.ToString() 

---

Microsoft.Azure.Cosmos/src/Linq/CosmosLinqExtensions.cs
Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQuery.cs
Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQueryProvider.cs
Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
changelog.md

Continuation token will work in both the execution flow
1. Asynchronous execution via FeedIterator with extension method ToFeedIterator().
```C#
IOrderedQueryable<T> linqQueryable = this.Container.GetItemLinqQueryable<T>(
continuationToken: continuationToken,
requestOptions: queryRequestOptions);
IQueryable<T> queriable = linqQueryable.Where(item => (item.intField < 100));
FeedIterator<T> feedIterator = queriable.ToFeedIterator();
```
2. Synchronous blocking LINQ execution.
```c#
IOrderedQueryable<T> linqQueryable = this.Container.GetItemLinqQueryable<T>(
allowSynchronousQueryExecution: true,
continuationToken: continuationToken,
requestOptions: queryRequestOptions);
List<T> list = linqQueryable.Where(item => (item.intField < 100)).ToList();
```
closes #537

Adding continuation token support for LINQ

---

Microsoft.Azure.Cosmos/src/Json/JsonReader.JsonTextReader.cs
Microsoft.Azure.Cosmos/src/Json/JsonTextUtil.cs
Microsoft.Azure.Cosmos/src/Json/JsonWriter.JsonTextWriter.cs
Microsoft.Azure.Cosmos/src/Json/NewtonsoftInterop/JsonNewtonsoftReader.cs
Microsoft.Azure.Cosmos/src/Json/NewtonsoftInterop/JsonNewtonsoftWriter.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonNavigatorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonReaderTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonTokenInfo.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonWriterTests.cs
changelog.md

The query pipeline was using the local culture settings to parse the JSON.  Cosmos stores the JSON as invariant culture. This would cause query parsing to fail and prevent the user from getting the results. The JSON navigator, reader, and writer are updated to always use invariant culture for parsing now.
Put closes #542

Query correctly handles different language cultures

---

Microsoft.Azure.Cosmos/src/CosmosClient.cs
Microsoft.Azure.Cosmos/src/Handler/AbstractRetryHandler.cs
Microsoft.Azure.Cosmos/src/Handler/PartitionKeyRangeHandler.cs
Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
Microsoft.Azure.Cosmos/src/Handler/TransportHandler.cs
Microsoft.Azure.Cosmos/src/Query/CosmosQueryExecutionContextFactory.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
Microsoft.Azure.Cosmos/src/Resource/CosmosException.cs
Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
Microsoft.Azure.Cosmos/src/Resource/Offer/CosmosOffers.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Fluent/ContainerSettingsTests.cs

This PR will move the offer operations to use new V3 pipeline for point to point and query from older documentClient.
Also it will move the read and replace throughput api code from database and container core class to common place at CosmosOffer class.
Closes #450

Moving offer operations to new V3 pipeline

---

Microsoft.Azure.Cosmos/src/Query/QueryPartitionProvider.cs
changelog.md

If the incorrect service interop version is loaded it can cause unexpected exceptions which then has no serializedQueryExecutionInfo. This causes the user to get an error with no message information.  If there is no message is now gives a warning to verify the version and gives the original exception content. 
#573 will prevent this issue in the future.
#566 fixes the empty error message, but not the root problem

Fixed empty error message if query parsing fails from unexpected exception.

---

Microsoft.Azure.Cosmos/src/Fluent/Settings/ContainerBuilder.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
changelog.md

Adding CreateIfNotExistsAsync to container builder
Put closes #591

Adding CreateIfNotExistsAsync to container builder

---

Microsoft.Azure.Cosmos.Samples/CodeSamples/Queries/Program.cs

Very minor change in the samples. There is an Assert that can never fail because the count is never incremented.

Missing count increment in Sample preventing Assert from ever failing

---

Microsoft.Azure.Cosmos/src/Handler/ResponseMessage.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosBasicQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemChangeFeedTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosReadFeedTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
changelog.md

Users are finding it difficult to find the continuation token. In the typed responses continuation token is directly on FeedResponse<T>, and ResponseMessage it is hidden under ResponseMessage.Headers. To make it more discoverable for users a reference will be add directly on ResponseMessage.

Adding continuation token property to response message

---

Microsoft.Azure.Cosmos/src/Linq/CosmosLinqExtensions.cs
Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQuery.cs
Microsoft.Azure.Cosmos/src/Resource/QueryResponses/QueryDefinition.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryDefinitionUnitTests.cs
changelog.md

This PR will add ToQueryDefinition() method on IQueryable<T>.
User can generate QueryDefinition() from LINQ and used it in stream api GetItemQueryStreamIterator.
closes #578

Adding ToQueryDefinition method on an IQueryable

---

Microsoft.Azure.Cosmos/src/Handler/RequestMessage.cs
Microsoft.Azure.Cosmos/src/Handler/RouterHandler.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosBasicQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ResponseMessageTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ResultSetIteratorTests.cs
changelog.md

Read feed with partition key has bug that causes it to go down the wrong pipeline which adds additional values which are not compatible with partition key. I updated the logic and added tests.
Put closes #610

Fixed a bug with read feed with partition key.

---

Microsoft.Azure.Cosmos/src/CosmosIndexJsonConverter.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/Index.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/SpatialPath.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/DynamicTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Fluent/ContainerSettingsTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/NonPartitionedContainerHelper.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TestCommon.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SettingsContractTests.cs
changelog.md

The indexing policy's include path index object was using a converter from the Direct dependency which was using the Document namespace object instead of the v3 Cosmos namespace types. This caused the conversion to fail and return random results. Ported the converter to github repo and updated it to use the v3 types.
Fixed Spatial indexes serialization. There was bug that caused it to get serialized with an extra property which the backend did not understand which caused a bad request. 

Fixed SpatialPath serialization and compatibility with older index versions

---

Microsoft.Azure.Cosmos.sln
Microsoft.Azure.Cosmos/.editorconfig

.editorconfig repo override
This repo override ensures consistency of conventions.
In VS non-adherence will show up as error list. 
msuild doesn't yet consider .editorconfig into build process. When this gap is addressed we can even apply at build time.
Please upgrade VS to 2019 latest version.
[https://github.com/dotnet/roslyn/issues/33558](https://github.com/dotnet/roslyn/issues/33558)

.editorconfig repo override

---

Microsoft.Azure.Cosmos/src/Resource/Settings/ContainerProperties.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SettingsContractTests.cs

To maintain compatibility with previous versions, a null PartitionKey should be omitted from the serialized payload.

Container serialization include PartitionKeyDefinition only if not null

---

Microsoft.Azure.Cosmos/src/Resource/QueryResponses/ChangeFeedResultSetIteratorCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeedResultSetIteratorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/MockDocumentClient.cs

The StandByFeedIterator, when reading through multiple tokens, if the first token returns a 304 (NotModified), it will shift the Continuation Token for the next request to go to the second token, but returns the 304 to the caller.
This PR changes the behavior to continue across all tokens until either:
* One returns an OK, in which case, it will return an OK with the results and the updated Continuation Token
* All tokens return NotModified, in which case, it will return a NotModified with an updated Continuation Token
In the scenario where the container has only one partition key range (one token), and the Iterator gets a 304, it will return it as-is, since there is no other tokens to read.
The PR includes unit tests for all described scenarios.
Closes #647

StandByFeedIterator to continue on NotModified

---

Microsoft.Azure.Cosmos/src/Query/StandByFeedContinuationToken.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemChangeFeedTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeedResultSetIteratorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/StandByFeedContinuationTokenTests.cs

Currently, the StandByFeedIterator is a single consumer pull model. This PR adds a new API called `GetChangeFeedTokensAsync`.
```c#
`Task<IEnumerable<string>> GetChangeFeedTokensAsync(CancellationToken cancellationToken = default(CancellationToken))`
```
The goal of this API is to provide a set of Tokens that can be used as initial state on any StandByFeedIterator to limit the scope of the sequential read to a subset of partitions.
This way, the tokens can be distributed on parallel compute units and each compute unit can read in parallel changes only for the scope of the initial token.
For example:
```c#
IEnumerable<string> tokens = await container.GetChangeFeedTokensAsync();
// In machine 1
FeedIterator iteratorForToken =
container.GetStandByFeedIterator(continuationToken: tokens[0], …
```

Scaled out StandByFeedIterator

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/LocationCacheTests.cs

GetCosmosSerializerWithWrapperOrDefaultWithOptionsTest had a test with newline characters hard coded as Windows. This caused the comparison to fail for Unix systems. Test is updated to use Enivornment.NewLine to ensure the new line characters are correct.
ValidateAsync doubled the wait time to match internal repo version
TestOpenAsyncFailFast: Updated to match internal repo version that uses call back rather than timeout to validate.
Put closes #712, #711 , #710

Fixed flaky tests: ValidateAsync, TestOpenAsyncFailFast, GetCosmosSerializerWithWrapperOrDefaultWithOptionsTest

---

Microsoft.Azure.Cosmos/src/Resource/Settings/AccountProperties.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosAccountServiceConfiguration.cs

Fixes a typo on a couple of internal properties of the `AccountProperties` class. There is no breaking change since they are internal.

Fixed a typo with the account properties

---

Microsoft.Azure.Cosmos/src/Query/CosmosQueryExecutionContextFactory.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosNotFoundTests.cs
changelog.md

Fixed query iterator HasMoreResults to return false if the container is not found.

Query iterator HasMoreResults now returns false if an exception is hit

---

Microsoft.Azure.Cosmos/src/Batch/ServerBatchRequest.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/PartitionKeyRangeServerBatchRequestTests.cs

As part of the work for https://github.com/Azure/azure-cosmos-dotnet-v3/issues/584, this PR adds new tests to cover possible batch request overflow due to materialization.

Adding tests to cover Batch request overflow

---

Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
Microsoft.Azure.Cosmos/src/EnvironmentInformation.cs
Microsoft.Azure.Cosmos/src/UserAgentContainer.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/HeadersValidationTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
changelog.md

This PR applies a refactor on the UserAgentContainer, creating a child class `Cosmos.UserAgentContainer` that has a different base user agent. The new base user agent uses `EnvironmentInformation` and generates a format of:
`{OS}/{Process Architecture} {SDK Version}/{Direct pkg Version}-{Framework} {ClientId} {UserSuffix}`
For example:
`Microsoft Windows 10.0.18362 /X64 3.1.1/3.1.4-.NET Core 4.6.27617.04 03445 mycustomsuffix`
The information is read from the RuntimeEnvironment NET Standard 2.0 https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeenvironment?view=netstandard-2.0
Closes #697

Fix for longer UserAgent suffix

---

Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQuery.cs
Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQueryProvider.cs
Microsoft.Azure.Cosmos/src/Linq/DocumentQueryEvaluator.cs
Microsoft.Azure.Cosmos/src/Linq/ExpressionToSQL.cs
Microsoft.Azure.Cosmos/src/Linq/SQLTranslator.cs
Microsoft.Azure.Cosmos/src/Linq/TranslationContext.cs
Microsoft.Azure.Cosmos/src/Linq/TypeSystem.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
Microsoft.Azure.Cosmos/src/Serializer/CosmosSerializationOptions.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemLinqTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/ToDoActivity.cs
changelog.md

This PR will help fixing issue where LINQ query generation was not entertaining the camel case option passed as serialization option during client creation.
So the item created with the camel case serialization where not able to retrieved from LINQ query.
#570
**Note** : User need to explicitly set CosmosSerializationOptions on clientOption( .WithSerializerOptions()). having PropertyNamingPolicy = CosmosPropertyNamingPolicy.CamelCase.
WithCustomSerializer() method wont work in this case.

Adding camel case serialization on LINQ query generation

---

Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
Microsoft.Azure.Cosmos/src/Query/Aggregation/SingleGroupAggregator.cs
Microsoft.Azure.Cosmos/src/Query/CosmosQueryExecutionContextFactory.cs
Microsoft.Azure.Cosmos/src/Query/DocumentQueryExecutionContextFactory.cs
Microsoft.Azure.Cosmos/src/Query/ExecutionComponent/AggregateDocumentQueryExecutionComponent.cs
Microsoft.Azure.Cosmos/src/Query/ExecutionComponent/GroupByDocumentQueryExecutionComponent.cs
Microsoft.Azure.Cosmos/src/Query/PipelinedDocumentQueryExecutionContext.cs
Microsoft.Azure.Cosmos/src/Query/QueryFeature.cs
Microsoft.Azure.Cosmos/src/Query/QueryInfo.cs
Microsoft.Azure.Cosmos/src/Query/QueryPlanHandler.cs
Microsoft.Azure.Cosmos/src/Query/QueryPlanRetriever.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqAggregateFunctionBaselineTests.TestAny.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqAggregateFunctionsBaselineTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/QueryPartitionProviderTest.Aggregates.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/QueryPartitionProviderTest.Negative.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/QueryPartitionProviderTest.NonValueAggregate.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncStreamerTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ComparableTaskSchedulerTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosQueryUnitTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/ContainerDefinitionForCreateTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Microsoft.Azure.Cosmos.Tests.csproj

This PR adds cross partition support for non value aggregates.
Before we enforced that a user had to write their cross partition aggregate queries like so:
```
SELECT VALUE MIN(c.age)
FROM c
```
now we are supporting non value aggregates like so:
```
SELECT MIN(c.age)
FROM c
SELECT MIN(c.age) as min_age
FROM c
```
And also multiple aggregates:
```
SELECT MIN(c.age) as min_age, MAX(c.age) as max_age
FROM c
```
This bridges the set of queries that single partition and cross partition can support.
We still do not support composite aggregates like:
```
SELECT (MIN(c.age) + MAX(c.age)) / 2 as mid_point_age
FROM c
```
Baseline tests have been added in QueryPartitionProviderTest.cs to verify the new features and existing features remained unchanged.
Cross partition GROUP BY and AGGREGATES now …

Cross Partition Non Value Aggregates

---

Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQuery.cs

When this exception is thrown, it refers to `GetItemsQueryIterator` but it should be `GetItemQueryIterator`:
```
Unhandled Exception: System.NotSupportedException: To execute LINQ query please set allowSynchronousQueryExecution true or use GetItemsQueryIterator to execute asynchronously
at Microsoft.Azure.Cosmos.Linq.CosmosLinqQuery`1.GetEnumerator()+MoveNext()
at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

Fix typo (perhaps due to API change) in exception message

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs

AutoIdGeneration unit-tests
- Ensure V3 doesn't auto generate Id's
- AutoId generation pattern (migration guidance)
- ReIndex progress test

AutoIdGeneration unit-tests

---

Microsoft.Azure.Cosmos/src/Routing/AsyncCache.cs
Microsoft.Azure.Cosmos/src/Routing/AsyncLazy.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/AsyncCacheTest.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SingleTaskScheduler.cs

Resolving an async deadlock caused by `AsyncCache` performing a blocking wait.
- Bug fix (non-breaking change which fixes an issue)
Closes #758 and probably #717

Fix for an async deadlock, reported in #758 (and probably #717)

---

Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
changelog.md

When dealing with Exception-less responses (Conflict, NotFound, Precondition failed, Throttling), the GatewayStoreModel was updating the session token when it shouldn't be.
This PR adds the fix plus tests for both Exceptions and Exception-less scenarios.

Session being updated incorrectly on Gateway mode

---

Microsoft.Azure.Cosmos/src/Linq/CosmosLinqExtensions.cs
Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQuery.cs
Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQueryProvider.cs
Microsoft.Azure.Cosmos/src/Query/CosmosDiagnosticsAggregate.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemLinqTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
changelog.md

…ccess to diagnostics.
Converted all aggregate linq queries like CountAsync to return a Response<T>. This will allow users to access the request charge and diagnostics information for the request.
Only the request charge and diagnostics is aggregated. All other fields on Response<T> such as activity id will be null since they can not be aggregated.
Response<T> does have an implicit conversion to type T so users can still do the following:
```
int intSum = await linqQueryable.Select(item => item.taskNum).SumAsync();
```
Or
```
Response<int> intSum = await linqQueryable.Select(item => item.taskNum).SumAsync();
string totalCharge = intSum.RequestCharge;
string diagnosticis = intSum.Diagnostics.ToString();
```

Converted all aggregate linq queries to return Response<T> 

---

Microsoft.Azure.Cosmos.Samples/Usage/ChangeFeed/ChangeFeed.csproj
Microsoft.Azure.Cosmos.Samples/Usage/ChangeFeed/Program.cs

Adding a sample to cover code migration from the Change Feed Processor library (SDK V2) to V3 SDK.

Adding Change Feed Processor code migration sample

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs

The PR [763](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/763) accidentally deleted several tests as part of the refactoring. Add the test back.

Adding AutoGenerateId tests back to CosmosItemTest

---

Microsoft.Azure.Cosmos/src/Linq/TypeSystem.cs
Microsoft.Azure.Cosmos/src/Serializer/CosmosSerializationOptions.cs
Microsoft.Azure.Cosmos/src/Serializer/CosmosSerializationUtil.cs

The query core logic works with the serializer. The serializer uses the CamelCaseNamingStrategy which is not support in Netwonsoft 6.0.8. The code has been refactored to make it an external util class to avoid the conflict when doing the v2 submodule.

Query Core serialization options

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/AsyncCacheTest.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Utils/Logger.cs

Increased the timeout to 1 minute and added info on how long it takes the factory to start to see if the factory is causing the timeouts.

Fixed flaky TestAsyncDeadlock

---

Microsoft.Azure.Cosmos/src/Routing/IRoutingMapProviderExtensions.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosBasicQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Routing/IRoutingMapProviderExtensionsTest.cs
changelog.md

There was a bug where the SDK could not handle collisions in the effective partition key. Normally this is pretty much impossible, since the epk is 128, but in HashV1 we only hash the first 100 bytes. This means any two strings with the same large prefix will collide. This collision caused an assertion error (the query ranges were not sorted and non-overlapping (because there was a perfect overlap)).
The client side solution was to push the invariant into the structure instead of the check. The client now puts all the ranges into a sorted set to avoid this issue. In future this work should be pushed to the backend.
Fix is ported from internal PR: https://msdata.visualstudio.com/DefaultCollection/CosmosDB/_git/CosmosDB/pullrequest/248585
closes …

Fixed a bug that caused sortedRanges exception

---

Microsoft.Azure.Cosmos.Samples/Usage/BulkSupport/Program.cs

Removed unused variable

---

Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs

Added documentation that the partition key value is immutable and can not be changed in a replace operation. I added a test and verified that the id value can be updated during a replace. 

Updating replace item documentation

---

Microsoft.Azure.Cosmos/src/Query/Core/ExecutionContext/CosmosQueryExecutionContextFactory.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs

There was a bug in the previous logic that was preventing the test from validating gateway mode. Also having a static variable caused conflicts since the test run async. Converted the test to use a local value to override, and added additional validation that the gateway is getting called when gateway mode is forced.

Fixed cross partition query force gateway plan tests

---

Microsoft.Azure.Cosmos/Directory.Build.props
Microsoft.Azure.Cosmos/src/UserAgentContainer.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/HeadersValidationTests.cs
changelog.md

Fixed a bug that caused the user agent overrides to not get applied. Refactored the Doucments.UserAgentContainer to allow the base user agent string to be overriden.

Fixed user agent string

---

Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
changelog.md

This value is used to denote the maximum timeout per network request, rather than the overall request. Cosmos SDK's availability resiliency is heavily reliant on failure detection and retries, both within a partition as well as between regions. However, this requires us to not wait indefinitely (which, honestly, 60 seconds is) for a response from the server, and timeout such network calls and let our retry logic kick in.
Hence.. this change decreases the timeout from 60s to 10s.

Reduce request timeout to 10s from 60s

---

Microsoft.Azure.Cosmos/src/Query/Core/ExecutionContext/PipelinedDocumentQueryExecutionContext.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs

GROUP BY queries were not honoring `MaxItemCount`. None of the tests caught it. I updated the tests to assert that max item count is honored. The bug was a simple fix. 
- [ x] Bug fix (non-breaking change which fixes an issue)

Max Item Count Fix

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/NonPartitionedContainerHelper.cs

The NonPartitionedContainerHelper was using a static date time variable. This will cause auth failures if the tests take to long. Updated it to always get the latest date time. 

Fixing 403 errors caused by NonPartitionedContainerHelper 

---

Microsoft.Azure.Cosmos/src/EnvironmentInformation.cs
Microsoft.Azure.Cosmos/src/UserAgentContainer.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/HeadersValidationTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/UserAgentTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/EnvironmentInformationTests.cs

The http headers only allow certain formats. The Mac OS creates a operating system string that causes the validation to fail. The / are converted | so it does not hit the same issue. 
Examples:
`cosmos-netstandard-sdk/3.3.0|3.3.0|60526|X64|Darwin 18.0.0 Darwin Kernel V|.NET Core 4.6.28008.01| UserApplicationName/1.0`
`cosmos-netstandard-sdk/3.3.0|3.3.0|28400|X64|Microsoft Windows 10.0.18362 |.NET Core 4.6.28008.01| UserApplicationName/1.0`
Put fixes #891

Fixed invalid user agent format exception for Mac OS.

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/DynamicTests.cs
azure-pipelines-official.yml

Removing ESRP signing and going to use the partner release pipeline to do signing and publishing package to nuget.org. The partner release pipeline step will be separate from this pipeline.

Fix azure-pipelines-official

---

Microsoft.Azure.Cosmos/src/Linq/ExpressionToSQL.cs
Microsoft.Azure.Cosmos/src/Linq/SQLTranslator.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemLinqTests.cs
changelog.md

Camel case with LINQ was not being tested because of a missing tag in the test. LINQ was not honoring camel case because the serialization settings did not get passed to the inner method. I removed all the default nulls to avoid the missing parameter in the future.
fixes #905

Fixed LINQ with camel case.

---

Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
Microsoft.Azure.Cosmos/src/Routing/LocationCache.cs

This PR has changes to fix configuration error when running batch CTL. It is a follow up to this PR: https://github.com/Azure/azure-cosmos-dotnet-v3/pull/388
Signed-off-by: Rakesh Kumar <rakkuma@microsoft.com>

Fixing issue with getentryassembly being null in case of .net2.0

---

Microsoft.Azure.Cosmos/src/Resource/QueryResponses/ChangeFeedResultSetIteratorCore.cs

The current StandByFeedIterator is checking for a scenario that no longer happens in the backend (a page size error reading the Change Feed), and this check implies a `Contains` evaluation on the failed response. We can safely remove this overhead.

Stand By Feed iterator cleanup

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryTests.cs

Add test category for query tests so test can be split to adhere to 30min max test duration.
Add properties needed to run emulator in cloud test.

Prerequisites for mono repo emulator tests

---

Microsoft.Azure.Cosmos/src/CosmosElements/CosmosElement.cs

A method was renamed in one PR but not in the other causing a build break.
Error    CS0117    'CosmosElement' does not contain a definition for 'Create'    Microsoft.Azure.Cosmos    C:\azure-cosmos-dotnet-v3\Microsoft.Azure.Cosmos\src\CosmosElements\CosmosElement.cs 
https://github.com/Azure/azure-cosmos-dotnet-v3/pull/875/files
https://github.com/Azure/azure-cosmos-dotnet-v3/pull/825/files

Fixing build break in master from bad merge 

---

Microsoft.Azure.Cosmos/src/Query/Core/ExecutionContext/CosmosCrossPartitionQueryExecutionContext.cs
Microsoft.Azure.Cosmos/src/Query/Core/ExecutionContext/CosmosOrderByItemQueryExecutionContext.cs
Microsoft.Azure.Cosmos/src/Query/Core/ExecutionContext/CosmosParallelItemQueryExecutionContext.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/MockPartitionResponse.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/MockQueryFactory.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPipelineMockTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryResponseMessageFactory.cs
changelog.md

This prevents an issue where a partial aggregate can be returned instead of error 429 in some cases.
- [ x ] Bug fix (non-breaking change which fixes an issue)

fix error with partial count returned

---

Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
Microsoft.Azure.Cosmos/src/PartitionKey.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosItemUnitTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyTests.cs

Added ability to TryParse a partition key. This feature is needed for compute gateway to parse the partition key from a header.

Cosmos.PartitionKey.TryParse

---

Microsoft.Azure.Cosmos/src/Query/Core/OrderByItem.cs
Microsoft.Azure.Cosmos/src/Query/Core/OrderByQuery/OrderByConsumeComparer.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
changelog.md

Allows for ordering by undefined fields. The fix was just to allow nulls to propagate through the sort code. 

ORDER BY Undefined

---

Microsoft.Azure.Cosmos/src/Batch/BatchAsyncBatcher.cs
Microsoft.Azure.Cosmos/src/Batch/BatchAsyncContainerExecutor.cs
Microsoft.Azure.Cosmos/src/Batch/BatchCore.cs
Microsoft.Azure.Cosmos/src/Batch/BatchExecUtils.cs
Microsoft.Azure.Cosmos/src/Batch/BatchExecutor.cs
Microsoft.Azure.Cosmos/src/Batch/ItemBatchOperation.cs
Microsoft.Azure.Cosmos/src/Batch/PartitionKeyRangeServerBatchRequest.cs
Microsoft.Azure.Cosmos/src/Batch/ServerBatchRequest.cs
Microsoft.Azure.Cosmos/src/Batch/SinglePartitionKeyServerBatchRequest.cs
Microsoft.Azure.Cosmos/src/ClientResources.Designer.cs
Microsoft.Azure.Cosmos/src/ClientResources.resx
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/BatchAsyncContainerExecutorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/BatchSinglePartitionKeyTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/CosmosItemBulkTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncBatcherTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncContainerExecutorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncStreamerTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchExecUtilsUnitTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchSchemaTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchUnitTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/PartitionKeyBatchResponseTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/PartitionKeyRangeBatchExecutionResultTests.cs
changelog.md

We had an optimization to not make Batch requests to the server if we think they are too large - removing this since making server requests allows for the natural error handling flow (similar to regular point operations where we don't check the max size of input on the client) among other benefits.

Don't fail on client for Batch API for large requests

---

Microsoft.Azure.Cosmos/src/Util/Extensions.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDiagnosticsTests.cs

Diagnostics were not set in the CosmosResponse for failed requests; set them.

Ensure diagnostics are set even for failed requests

---

Microsoft.Azure.Cosmos/src/Query/v3Query/FeedIterator.cs
Microsoft.Azure.Cosmos/src/Query/v3Query/FeedIteratorCore.cs
Microsoft.Azure.Cosmos/src/Query/v3Query/FeedIteratorOfT.cs
Microsoft.Azure.Cosmos/src/Query/v3Query/FeedResponse.cs
Microsoft.Azure.Cosmos/src/Query/v3Query/QueryIterator.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ContainerResponse.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ItemResponse.cs
Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseResponse.cs
Microsoft.Azure.Cosmos/src/Resource/Permission/PermissionResponse.cs
Microsoft.Azure.Cosmos/src/Resource/QueryResponses/ChangeFeedPartitionKeyResultSetIteratorCore.cs
Microsoft.Azure.Cosmos/src/Resource/QueryResponses/ChangeFeedResultSetIteratorCore.cs
Microsoft.Azure.Cosmos/src/Resource/Response.cs
Microsoft.Azure.Cosmos/src/Resource/Scripts/StoredProcedureExecuteResponse.cs
Microsoft.Azure.Cosmos/src/Resource/Scripts/StoredProcedureResponse.cs
Microsoft.Azure.Cosmos/src/Resource/Scripts/TriggerResponse.cs
Microsoft.Azure.Cosmos/src/Resource/Scripts/UserDefinedFunctionResponse.cs
Microsoft.Azure.Cosmos/src/Resource/Throughput/ThroughputResponse.cs
Microsoft.Azure.Cosmos/src/Resource/User/UserResponse.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/StoredProcedureTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TriggersTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/UserDefinedFunctionsTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosVirtualUnitTest.cs
changelog.md

Users can't mock an internal abstract method. Removing the internal abstract method to fix unit testing.
Fixes #977

Fix mocking for FeedIterator and Response classes

---

Microsoft.Azure.Cosmos/src/DocumentClient.cs
Microsoft.Azure.Cosmos/src/Query/v3Query/QueryIterator.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/MockDocumentClient.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/MockQueryNegativeTests.cs

Internal teams depend on the substatuscode to be populated. This fixes a bug where the substatuscode was not getting set on the conversion to the public type.
Test will be added in future iterations. 

Fixed substatuscode so it gets set on query response.

---

Microsoft.Azure.Cosmos/src/Diagnostics/PointOperationStatistics.cs
Microsoft.Azure.Cosmos/src/Query/v3Query/QueryIterator.cs
Microsoft.Azure.Cosmos/src/Util/Extensions.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDiagnosticsTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncBatcherTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncContainerExecutorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/ItemBatchOperationStatisticsTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/PartitionKeyBatchResponseTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/PartitionKeyRangeBatchExecutionResultTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosQueryUnitTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PointOperationStatisticsTest.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/ItemProducerTreeUnitTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryResponseMessageFactory.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/UsableSemaphoreWrapperTests.cs
changelog.md

Added the user requested session token and the response session token to diagnostics to help troubleshoot session token issues. Refactored naming to normalize it across methods.
Put closes #992

Include session token to diagnostics

---

Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj

Fixed project so that $(DefineConstants) are propagated correctly when '$(DelaySign)' == 'true'
I didn't open a specific issue.

Fixed project so that $(DefineConstants)are propagated correctly

---

Microsoft.Azure.Cosmos/src/GatewayStoreClient.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosGatewayTimeoutTests.cs
changelog.md

Added additional context to the request time out exception in gateway. It was discovered during testing that the HttpClient can throw a OperationCanceledException or TaskCancelledException 
during a request timeout. Added additional logic to handle both exceptions.

Gateway OperationCanceledException are now returned as request timeouts

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosGatewayTimeoutTests.cs

The gateway test passes locally, but seems to be flaky in the gates. Changing the test to always throw the timeout exception, and validate the message. This removes the dependency on the HttpClient to throw the timeout exception.

Fixed flaky gateway timeout test

---

Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
Microsoft.Azure.Cosmos/src/Resource/Throughput/ThroughputResponse.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Resource/Throughput/ThroughputResponseTests.cs

fix the value that is being retrieved when mapping ThoughputResponse.IsReplacePending
This PR is to fix the value that is being retrieved when mapping ThoughputResponse.IsReplacePending as it is currently incorrectly attempting to read `WFConstants.BackendHeaders.MinimumRUsForOffer`
Closes #1024

Fix ThroughputResponse.IsReplacePending

---

Microsoft.Azure.Cosmos/src/Query/Core/ExecutionComponent/GroupByDocumentQueryExecutionComponent.cs

We had an OOM due to the way we were draining from the grouping table. The initial list size if the user page size instead of the actual grouping table size. I start the list off as the min of the two sizes. 

GROUP BY OOM Fix

---

Microsoft.Azure.Cosmos/src/Resource/Settings/AccountProperties.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/ConflictProperties.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/ContainerProperties.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/DatabaseProperties.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/PermissionProperties.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/StoredProcedureProperties.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/ThroughputProperties.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/TriggerProperties.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/UserDefinedFunctionProperties.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/UserProperties.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseAccountSettingsTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosPermissionTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosUserTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Fluent/ContainerSettingsTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/StoredProcedureTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TriggersTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/UserDefinedFunctionsTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/SelflinkValidator.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ComparableTaskSchedulerTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SettingsContractTests.cs
changelog.md

Adding the self link to all the public resource properties. 

Selflink is added to all public resource properties.

---

Microsoft.Azure.Cosmos/src/Query/v3Query/QueryIterator.cs
Microsoft.Azure.Cosmos/src/Query/v3Query/QueryResponse.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ComparableTaskSchedulerTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosQueryUnitTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Scenarios/GremlinScenarioTests.cs
changelog.md

This fixes a bug where query stream iterator response message would return a stream on failure scenario. It now returns null for the content if the query failed.
closes #1034

Fixed query responses to return null Content if it is a failure.

---

Microsoft.Azure.Cosmos/src/Headers/CosmosMessageHeadersInternal.cs
Microsoft.Azure.Cosmos/src/Headers/Headers.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/HeadersTests.cs

The SDK has a soft contract with Compute to expose sub status code through a secret header. For some reason the SDK decided that the sub status code should be both stored as an enum and a string and that they could go out of sync. I change it so that we only store the enum and the string is just the .ToString of the enum.

Removed Duplicate Substatus Code

---

Microsoft.Azure.Cosmos/src/Resource/CosmosException.cs
changelog.md

Adds support for StackTrace and InnerException in CosmosException.
- [ x] New feature (non-breaking change which adds functionality)

CosmosException StackTrace and InnerException in ToString()

---

Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchOperationResult.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchOperationResultTests.cs
changelog.md

https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1048
Mocking constructors were missing from TransactionalBatchOperationResult.  Probably by accident.  This pull request adds them back in.
Other public classes in this project support mocking.  It's also consistent with guidance here: https://azure.github.io/azure-sdk/dotnet_introduction.html
closes #1048 

Add mocking constructors to TransactionalBatchOperationResult

---

Microsoft.Azure.Cosmos.Samples/Usage/Cosmos.Samples.Usage.sln
Microsoft.Azure.Cosmos.Samples/Usage/TransactionalBatch/Program.cs
Microsoft.Azure.Cosmos.Samples/Usage/TransactionalBatch/TransactionalBatch.csproj
Microsoft.Azure.Cosmos/src/Batch/TransactionalBatch.cs
Microsoft.Azure.Cosmos/src/CosmosClient.cs
Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
Microsoft.Azure.Cosmos/src/Fluent/Settings/ContainerBuilder.cs
Microsoft.Azure.Cosmos/src/Resource/Conflict/Conflicts.cs
Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs
Microsoft.Azure.Cosmos/src/Resource/Permission/Permission.cs
Microsoft.Azure.Cosmos/src/Resource/Scripts/Scripts.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/ContainerProperties.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/PermissionProperties.cs
Microsoft.Azure.Cosmos/src/Resource/User/User.cs
Microsoft.Azure.Cosmos/src/Serializer/CosmosSerializer.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs

Rename Batch in Samples to TransactionalBatch.
General doc fixes across SDK to fix non-displayed / stray links in generated documentation:
> see and seealso with href need text for display. 
> seealso should be top level (not within remarks etc.) and isn't inlined into the documentation but shows up as a separate section. 
> exception needs cref. 
> list needs a type attribute.
Sample and documentation update.

Batch sample project rename and other doc fixes

---

Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosHandlersTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/NameRoutingTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/CustomHandler.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/RequestHandlerHelper.cs
changelog.md

Fixed bug where if a user provided the wrong partition key value the request would be sent twice. The retry logic for the partition key extraction was always being used if it was a user provided partition key value or an extracted partition key value. The retry logic should only be used for SDK extracted partition key value in scenarios where the cache is stale.

CreateItem will only retry for auto-extracted partition key in-case of container re-creation

---

Microsoft.Azure.Cosmos/src/CosmosElements/CosmosArray.LazyCosmosArray.cs
Microsoft.Azure.Cosmos/src/CosmosElements/CosmosObject.LazyCosmosObject.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosElements/LazyCosmosElementTests.cs

Added a caching layer for nested lazy `CosmosElements` (`CosmosObject`, `CosmosArray`). 
* Has an array that starts off as the size of the list
* Each element is a `Lazy<CosmosElement>`
* `Count()` is now O(1) instead of O(n)
* Has a concrete dictionary to store key value pairs that the user asks for (so subsequent results can be served from the cache).
* `Count()` is backed by a `Lazy<int>`.
* I chose not to do anything special for `Keys`, `Values`, `IEnumerator<KeyValuePair>`, since those are all `IEnumerable` and it the expectation that the user caches the result using `.ToList()` if they are calling it multiple times.

Cache CosmosElements in Nested Lazy Types

---

Microsoft.Azure.Cosmos/src/GatewayStoreClient.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTests.cs
changelog.md

Diagnostics: For BadRequest with large headers this PR lists the header sizes.

Diagnostics: Including header size details for BadRequest with large headers

---

Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchResponse.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchUnitTests.cs
changelog.md

Ensure the TransactionalBatchResponse is formed even when the server returns some response with a body that isn't in the expected format.

Fix possible NullReferenceException on a TransactionalBatch code path

---

Microsoft.Azure.Cosmos/src/DocumentClient.cs
Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosQueryClientCoreTest.cs
changelog.md

CosmosQueryClientCore did not implement TryGetOverlappingRangesAsync, so when a query tries split proofing it runs into a NotImplementedException. We didn't have any integration tests (nor do we have any now), since the public emulator can't simulate a split.

Fix SplitException

---

Microsoft.Azure.Cosmos/src/Batch/BatchAsyncContainerExecutor.cs
Microsoft.Azure.Cosmos/src/Batch/BatchExecUtils.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/CosmosItemBulkTests.cs
changelog.md

When an item was sent through Bulk using the Type API and the object did not contain the PartitionKey, the process was failing with a Null Reference due to the BulkExecutor failing to correctly resolve the Partition.
The PK is extracted as PartitionKey.None but the Executor is unable to correctly detect it.
This PR fixes the issue, plus adds coverage for the scenario.
This PR closes #1088

Bulk API - Operations with no PK

---

Microsoft.Azure.Cosmos/src/Diagnostics/PointOperationStatistics.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosClientSideRequestStatistics.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDiagnosticsTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TransportWrapperTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PointOperationStatisticsTest.cs
changelog.md

Using JsonConverter from the object causes several classes to miss private properties that are only exposed via an AppendToBuilder method. This converted the diagnostics to use the AppendToBuilder to retrieve the additional information.
Example for success:
```
{
"ActivityId": "51ec34e7-559b-422f-984e-56105ec57e81",
"StatusCode": "201",
"SubStatusCode": "Unknown",
"RequestCharge": "11.62",
"ErrorMessage": "",
"Method": "POST",
"RequestUri": "dbs/771e57a9-9280-49a1-8f85-4c6715a2700d/colls/8adc660b-16ea-419f-ba05-1ad3bdc9968a",
"RequestSessionToken": "",
"ResponseSessionToken": "0:-1#41",
"ClientSideRequestStatistics": {
"RequestStartTimeUtc": "2019-12-06T21:46:46.5829811Z",
"RequestEndTimeUtc": "2019-12-06T21:46:46.9974853Z", …
```

Fixed missing store result info from diagnostics

---

Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
changelog.md

I've added support for SourceLink. Now consumer of this package should be able to easily debug through the cosmos sdk.
I've tested it only manually. I tried to be as close as possible to azure pipeline tasks by running `dotnet cli` locally with arguments from tasks but I will still suggest to test it once again with normal azure pipelines and see if it is working correctly.
#1069

Add sourcelink support

---

Microsoft.Azure.Cosmos/src/Serializer/CosmosSerializerCore.cs

The previous check only shows up in debug test runs but causes  normal test run to fail without reason. The new check always throws an exception with a message so it is clear why the test failed. Added additional types to skip to avoid breaking tests.

Fixed the serializer check. 

---

Microsoft.Azure.Cosmos/azuredata/Handler/ClientPipelineTransport.cs
Microsoft.Azure.Cosmos/azuredata/Handler/RequestInvokerHandler.cs
Microsoft.Azure.Cosmos/azuredata/Resource/ClientContextCore.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/HandlerTests.cs
changelog.md

Azure Core ClientOptions has a 3 max retry default that will make any failed request be retried after the SDK Retry policies already retried the expected amount of times.
The vNext flow leverages the Core Pipeline as follows:
1. The ClientContextCore creates the Request and sends it through the Core Pipeline
2. The Core Pipeline adds Pipeline policies (Logging, User Custom Retries, etc)
3. The Request gets sent through the SDK RequestInvoker
4. SDK internal retry policies are applied
5. Request is sent through Transport
If the request fails, retry policies are evaluated on 4 and if needed, the request is retried (like in a 429). If the request should not be retried or if retries were exhausted, the response goes up across the Core Pipeline (logging is leveraged) and eventually to the …

[vNext] Disable Core pipeline retries

---

Microsoft.Azure.Cosmos/azuredata/Serializer/CosmosTextJsonSerializer.cs

The System.Text.Json serializer was doing double dynamic casting, that is really not needed.

[vNext] Double dynamic casting

---

Microsoft.Azure.Cosmos/azuredata/Azure.Cosmos.csproj
changelog.md

Even though we don't have any public usage, internal classes still require the Newtonsoft.Json package to be available at runtime.

[vNext] Newtonsoft dependency

---

Microsoft.Azure.Cosmos/src/Resource/QueryResponses/ChangeFeedResultSetIteratorCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemChangeFeedTests.cs
changelog.md

Currently the StandByFeedIterator will only move to the next partition if the current one has no more changes.
In scenarios where all partitions are receiving constant changes, changes from other partitions might get delayed.
With this change, the StandByFeedIterator will move to the next range upon receiving a Change Feed response, so the next `ReadNextAsync` will read from the next range.
This PR closes #1117

StandByFeedIterator breath first

---

Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
Microsoft.Azure.Cosmos/src/Query/Core/Metrics/BackendMetrics.cs
Microsoft.Azure.Cosmos/src/Query/Core/Metrics/BackendMetricsParser.cs
Microsoft.Azure.Cosmos/src/Query/Core/Metrics/BackendMetricsTokenizer.cs
Microsoft.Azure.Cosmos/src/Query/Core/Metrics/ClientSideMetrics.cs
Microsoft.Azure.Cosmos/src/Query/Core/Metrics/FetchExecutionRange.cs
Microsoft.Azure.Cosmos/src/Query/Core/Metrics/FetchExecutionRangeAccumulator.cs
Microsoft.Azure.Cosmos/src/Query/Core/Metrics/IndexUtilizationData.cs
Microsoft.Azure.Cosmos/src/Query/Core/Metrics/IndexUtilizationInfo.cs
Microsoft.Azure.Cosmos/src/Query/Core/Metrics/PartitionedQueryMetrics.cs
Microsoft.Azure.Cosmos/src/Query/Core/Metrics/QueryMetrics.cs
Microsoft.Azure.Cosmos/src/Query/Core/Metrics/QueryMetricsDelimitedStringWriter.cs
Microsoft.Azure.Cosmos/src/Query/Core/Metrics/QueryMetricsTextWriter.cs
Microsoft.Azure.Cosmos/src/Query/Core/Metrics/QueryMetricsWriter.cs
Microsoft.Azure.Cosmos/src/Query/Core/Metrics/QueryPreparationTimes.cs
Microsoft.Azure.Cosmos/src/Query/Core/Metrics/RuntimeExecutionTimes.cs
Microsoft.Azure.Cosmos/src/Query/Core/Metrics/TextTable.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
azure-pipelines.yml
templates/build-internal.yml
templates/build-test.yml

There is a lot of conditional logic based on the internal flag. This adds a yaml file to build the solution with the internal flag set to prevent build breaks from getting merged in.
Refactored the display name to make it easier to read and prevent the values from getting truncated.

Add build for internal flag to catch build breaks

---

Microsoft.Azure.Cosmos/src/Query/Core/ExecutionContext/CosmosQueryExecutionContextFactory.cs
Microsoft.Azure.Cosmos/src/Query/Core/QueryClient/CosmosQueryClient.cs
Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPlanRetriever.cs
Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/PermissionProperties.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosPermissionTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
changelog.md

Fixed authorization issue when doing a query with resource token for a specific partition key when using the gateway query plan retriever.
Fixed a bug for permissions on a specific item. The resource link generation was using the permission id instead of the item id. So the permission was for the incorrect resource link. 
closes #1073

Fixed authorization with query using resource token for a specific partition key

---

Microsoft.Azure.Cosmos.Samples/Usage/ItemManagement/Program.cs

the original sample showed updating the value of AccountNumber (which is the partitionkey for this collection) on the retrieved item, and then doing an upsert
when i run this sample, it doesn't update the original item, it merely creates a new item, with a new partition key set but the old original item with the original partition key remains in the database. we effectively now have a duplicate document.
the observed behavior is as expected considering cosmosdb treats id + pk as unique for a document
therefore changing the pk value means cosmos db would never find the original item to update it, so it creates a new one.
if you run this sample, you end up with TWO SalesOrder3 items, 1 in the original partition, and another exactly the same but in a different partition
i believe the sample …

Updating UpsertItemAsync

---

Microsoft.Azure.Cosmos/src/Json/IJsonReader.cs
Microsoft.Azure.Cosmos/src/Json/Interop/CosmosDBToNewtonsoftReader.cs
Microsoft.Azure.Cosmos/src/Json/Interop/NewtonsoftToCosmosDBReader.cs
Microsoft.Azure.Cosmos/src/Json/Interop/NewtonsoftToCosmosDBWriter.cs
Microsoft.Azure.Cosmos/src/Json/JsonNavigator.JsonBinaryNavigator.cs
Microsoft.Azure.Cosmos/src/Json/JsonNavigator.JsonTextNavigator.cs
Microsoft.Azure.Cosmos/src/Json/JsonReader.JsonBinaryReader.cs
Microsoft.Azure.Cosmos/src/Json/JsonReader.JsonTextReader.cs
Microsoft.Azure.Cosmos/src/Json/JsonReader.cs
Microsoft.Azure.Cosmos/src/Json/JsonWriter.JsonTextWriter.cs
Microsoft.Azure.Cosmos/src/Json/JsonWriter.cs
Microsoft.Azure.Cosmos/src/RequestOptions/QueryRequestOptions.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosBasicQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonReaderTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonRoundtripTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonTestUtils.cs

This PR enables binary encoding with dictionary encoding to roundtrip. Currently if we try and read the payload of a dictionary encoded binary with a regular binary reader, which is the case for stream API where we can't pass around the dictionary, then the data is essentially corrupted.
The fix is to return false for `TryGetBufferedRawJson` on all the binary readers / navigators if they have a `JsonStringDictionary`. This forces the writer to get the actual string value. The saving grace is we now have TryGetBufferedUTF8StringValue. This should allow us to turn on dictionary encoding from the backend.
I updated the roundtrip tests with dictionary encoding to show that we are able to roundtrip dictionary encoding with regular binary writers and text writers.

Dictionary Encoding RoundTrip

---

README.md

The link to _GitHub samples_ in `README.md` resulted in a 404 Not Found response from GitHub. Moving one level up in the folder hierarchy of the source code links to what seems to be the intended folder on GitHub.
I also fixed the spelling of _GitHub_ in the link text.
- [ x] Bug fix (non-breaking change which fixes an issue)

Fix broken link to GitHub samples

---

Microsoft.Azure.Cosmos/src/Encryption/EncryptionProcessor.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/EncryptionTests.cs
changelog.md

Fix a bug in ClientEncryption decryption flow where the input stream would have been disposed by the base serializer and therefore couldn't be reused in case it can be returned as-is (i.e. when there is nothing to decrypt). This manifests when decryption has been invoked because the encryption key wrap provider is configured on the client, but a particular document being read wasn't encrypted.

Client encryption - Fix bug in read path without encrypted properties

---

Microsoft.Azure.Cosmos/azuredata/CosmosClient.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/DotNetSDKAPI.json
changelog.md

Aligning with the Azure Core SDK guidelines for client constructors (https://azure.github.io/azure-sdk/dotnet_introduction.html#dotnet-client-ctor), this PR explicitly adds a `CosmosClient` constructor that just takes `connectionString`, and one that takes `connectionString` and `options`.
```csharp
public CosmosClient(string connectionString);
public CosmosClient(
string connectionString,
CosmosClientOptions clientOptions);
```
Closes #1245

vNext - CosmosClient constructor

---

Microsoft.Azure.Cosmos/azuredata/CosmosClientOptions.cs
Microsoft.Azure.Cosmos/azuredata/Fluent/CosmosClientBuilder.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/DotNetSDKAPI.json
changelog.md

Following API review, this PR does two thing:
1. Rename `CosmosClientOptions.SerializerOptions` to `CosmosClientOptions.DefaultSerializerOptions` to better reflect the intent (customizing the default serializer)
2. Getting the `CosmosClientOptions.DefaultSerializerOptions` no longer returns `null` but the default instance with the default values of the `SerializerOptions`.
Closes #1246

vNext - DefaultSerializationOptions

---

Microsoft.Azure.Cosmos/azuredata/CosmosClient.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/DotNetSDKAPI.json
changelog.md

Based on API Review, the pipeline should be immutable after being created and exposing publicly the CosmosClientOptions would allow for changes to be made after.
Closes #1244

vNext - Remove CosmosClient.CosmosClientOptions

---

Microsoft.Azure.Cosmos/src/Json/JsonReader.JsonTextReader.cs
Microsoft.Azure.Cosmos/src/Query/Core/ExecutionComponent/Aggregate/Aggregators/SumAggregator.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/DistinctQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/QueryTestsBase.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonReaderTests.cs

For CosmosElementContinuationToken double.NaN serializes to a string in JSON, meaning that the type changes when we try to roundtrip it. The fix was to try and parse the double if the user gives a string continuation token. Binary doesn't have this issue.

Fix Double.NaN roundtrip bug for CosmosElementContinuationToken

---

Microsoft.Azure.Cosmos/src/Spatial/MultiPolygon.cs
Microsoft.Azure.Cosmos/src/Spatial/PolygonCoordinates.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
changelog.md

Changed MultiPolygon and PolygonCoordinates back to public as I believe they were inadvertently reverted to internal as described in #1235. Related issues include #70, #79, and #136 (and of course #1235). 
Closes #1235.

Make MultiPolygon and PolygonCoordinates classes public.

---

Microsoft.Azure.Cosmos/src/PartitionKey.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContractEnforcement.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyTests.cs
changelog.md

This PR adds methods and operators for basic comparison to the `PartitionKey` struct.
closes #1233

Partitionkey add methods for comparison

---

Microsoft.Azure.Cosmos/src/Query/Core/ExecutionContext/OrderBy/CosmosOrderByItemQueryExecutionContext.Resume.cs

For cross partition ORDER BY queries we rewrite the query to inject a filter. For example if we left off on partition N with the value `("A", 1)`, then the filters are:
`(> "A") OR (= "A" AND > 1), (> "A") OR (= "A" AND >= 1), (> "A") OR (= "A" AND >= 1)`
The problem is that this filter is not efficient for the backend, since it can not leverage a composite index if any of the prefix filters have an inequality.
The solution is to just filter on `WHERE true` for the partition that we left off on, since we already have a continuation token. Note that for a single partition query we always resume on the partition we left off on meaning this optimization will pay extra dividends there.
In parallel backend will work on pushing the generated filter to the index, since we still need it for the …

ORDER BY Resume Optimization

---

Microsoft.Azure.Cosmos/src/Handler/ResponseMessage.cs
Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosException.cs
Microsoft.Azure.Cosmos/src/Util/Extensions.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TransportWrapperTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosExceptionTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosQueryUnitTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
changelog.md

Updating the exception messages to provide a consistent story with all the information. This ensures that if a user only collects a Message or other property there will always be the information required to troubleshoot it.
1. ResponseMessage.Content will always be null for exception scenarios
2. ResponseMessage.ErrorMessage will contain the same thing as CosmosException.Message (no stack trace, no diagnostics)
1. CosmosException.Message, ResponseMessage.ErrorMessage contain the same value.
2. CosmosException.ToString() includes stacktrace, diagnostics, error message, and all relevant information.
3. CosmosException.ResponseBody is the raw response from the service or DCE.Message
```
{
"Errors": [
"One of the specified pre-condition is not met"
]
}
```
```
Response status code does not …
```

Updated exception messages

---

Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
changelog.md

The XML was not getting copied to the ref folder causing the XML documentation to not get loaded on projects. This ensures the file get's copied and the XML documentation works in Visual Studio.
closes: #1281 #1303

Fixed project's XML documentation

---

Microsoft.Azure.Cosmos.Samples/Usage/AzureFunctions/AzureFunctionsCosmosClient.cs
Microsoft.Azure.Cosmos.Samples/Usage/BulkExecutorMigration/BulkExecutorMigration.csproj
Microsoft.Azure.Cosmos.Samples/Usage/BulkExecutorMigration/Program.cs
Microsoft.Azure.Cosmos.Samples/Usage/BulkSupport/Program.cs
Microsoft.Azure.Cosmos.Samples/Usage/ChangeFeed/Program.cs
Microsoft.Azure.Cosmos.Samples/Usage/Cosmos.Samples.Usage.sln
Microsoft.Azure.Cosmos.Samples/Usage/CustomSerialization/Program.cs
Microsoft.Azure.Cosmos.Samples/Usage/Handlers/Program.cs
Microsoft.Azure.Cosmos.Samples/Usage/IndexManagement/Program.cs
Microsoft.Azure.Cosmos.Samples/Usage/ItemManagement/Program.cs
Microsoft.Azure.Cosmos.Samples/Usage/NonPartitionContainerMigration/Program.cs
Microsoft.Azure.Cosmos.Samples/Usage/TransactionalBatch/Program.cs

This PR adds a specialized Sample that shows how to migrate from using the Bulk Executor Library (V2) to V3 Bulk support by covering Bulk Import, Bulk Update, and Bulk Delete, and how to obtain the same metrics the Bulk Executor Library.
Bulk Executor Library has a response type of BulkImportResponse: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmosdb.bulkexecutor.bulkimport.bulkimportresponse?view=azure-dotnet
The proposed response type provides the same information:
```
public class BulkOperationResponse<T>
{
public TimeSpan TotalTimeTaken { get; set; }
public int SuccessfulDocuments { get; set; } = 0;
public double TotalRequestUnitsConsumed { get; set; } = 0;
public IReadOnlyList<(T, Exception)> Failures { get; set; }
}
```

Adding Bulk migration example

---

Microsoft.Azure.Cosmos/src/PartitionKey.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyTests.cs
changelog.md

`PartitionKey` is a struct. `default(struct)` initializes all referenced properties to their default values (ref https://docs.microsoft.com/dotnet/csharp/language-reference/language-specification/structs#class-and-struct-differences)
>The default value of a struct is the value produced by setting all value type fields to their default value and all reference type fields to null (Default values).
Due to this behavior, comparisons using `default(PartitionKey)` were causing NullRefs.
This PR handles the case of `default(PartitionKey)` by assigning it the `Null` value for comparison purposes.
Closes #1307

Compare case for default(PartitionKey)

---

Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
Microsoft.Azure.Cosmos/src/DocumentClient.cs
Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
Microsoft.Azure.Cosmos/src/Routing/GlobalAddressResolver.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
changelog.md

This PR adds a new Direct/TCP configuration to enable TCP end-of-connection detection for proactive address refresh.

TCP endpoint rediscovery

---

Microsoft.Azure.Cosmos/src/Encryption/EncryptionProcessor.cs
Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/EncryptionTests.cs
changelog.md

While we do not support filtering on encrypted properties etc., for queries where the full item would be returned, we want to decrypt the encrypted properties on the client before returning the query result.

Client Encryption - Decrypt the encrypted properties before returning query result

---

Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
Microsoft.Azure.Cosmos/src/Query/Core/ExecutionContext/PipelinedDocumentQueryExecutionContext.cs

This PR shows the alternative way to remove null in the codebase. We can bump the lang version to 8.0 and use the `#nullable enable` macro to opt into the nullable reference feature one file at a time. When the entire code base has this set we can flip the default and remove this macro.

Nullable Enable

---

Microsoft.Azure.Cosmos/src/Batch/BatchAsyncContainerExecutor.cs
Microsoft.Azure.Cosmos/src/Batch/BatchCore.cs
Microsoft.Azure.Cosmos/src/Batch/BatchExecutor.cs
Microsoft.Azure.Cosmos/src/Batch/ItemBatchOperation.cs
Microsoft.Azure.Cosmos/src/Batch/ServerBatchRequest.cs
Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchItemRequestOptions.cs
Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchResponse.cs
Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
Microsoft.Azure.Cosmos/src/Resource/CosmosClientContext.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/EncryptionTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncBatcherTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncOperationContextTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncStreamerTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchRequestPayloadReader.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchSchemaTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/PartitionKeyBatchResponseTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/PartitionKeyRangeBatchExecutionResultTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/PartitionKeyRangeServerBatchRequestTests.cs
changelog.md

Enable client encryption / decryption for transactional batch requests.
anujtoshniwal

Client Encryption: Add client encryption / decryption for transactional batch requests

---

Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDiagnosticsTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/DiagnosticValidators.cs

The code currently tells if it the query plan is from gateway or service interop. This fixes get query plan from gateway to include the diagnostics from that call. This allows to see if there are retries or other exceptions that might cause a delay in the get query plan call.

Query Diagnostics: Fix get query plan diagnostics

---

Microsoft.Azure.Cosmos/Directory.Build.props
Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj

This PR separates package versioning for Preview releases from Official/GA releases to avoid releases using the Preview version.
The effect of the different flags on builds are below:

[Internal] Build: Add Independent version for Preview

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqAggregateFunctionsBaselineTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqAttributeContractBaselineTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqGeneralBaselineTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqSQLTranslationBaselineTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqTranslationBaselineTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/QueryTestsBase.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/RetriableTestClassAttributeTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/RetriableTestClass.cs

To address transient test failures with the Emulator in our tests, this PR adds a new `[TestClass]` decorator that inherits from `VisualStudio.TestTools.UnitTesting.TestClass`.
[MSTestEx](https://github.com/pvlakshm/MSTestEx/blob/master/docs/AttributeEx/RetryAttribute.md) has a `[Retry]` attribute but it has an undesirable outcome, it retries the test but it still marks it as failed if some of the iterations failed.
This decorator will retry all `[TestMethods]` in a class and set the result to the last iteration (either success or failure).
**All existing Emulator tests will now be using the new retry behavior by default**. Some particular files had to be changed due to namespace collision with the original `TestClass`.
By default it retries once, but it can be customized through the …

[Internal] Tests: Add retriable TestClass decorator

---

Microsoft.Azure.Cosmos/src/Query/v3Query/QueryIterator.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/SanityQueryTests.cs

The error message for malformed continuation token was using the parsed version in the exception message instead of the user passed in value. This means if the parsing failed the continuation token text in the error message is null. 
Fixed existing test to correctly validate stream api calls and that correct message is being returned.

Query: Fix malformed continuation token error message.

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/UniqueIndexTests.cs

1. Updated UniqueIndexTests to use v3 CosmosClient. 
2. Updated the asserts to include the full exception message to see the reason for the failure. Currently it only has the enum comparison failure, and not the reason for the underlying 400 exception.
2. Switched status code to HttpStatusCode to avoid confusion around the assert failing.  Both Document.StatusCodes.BadRequest and Document.StatusCodes.StartingErrorCode have a value of 400.

[Internal] UniqueIndexTests: Fix to use CosmosClient instead of DocumentClient

---

Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs

ReplaceItemAsync allows updating the id value. Only the PartitionKeyValue is required to be the same.

ReplaceItemAsync documentation: Fix id comment to clarify the expected value

---

Microsoft.Azure.Cosmos/azuredata/Resource/Settings/IndexingPolicy.cs
Microsoft.Azure.Cosmos/azuredata/Resource/Settings/UniqueKeyPolicy.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/Enums/OperationKind.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/DotNetSDKAPI.json

This PR removes an `[Obsolete]` member in the `OperationKind` enum as part of the API Review and fixes some class documentation.

[vNext] Documentation: Fix Obsolete member and fix classes comments

---

Microsoft.Azure.Cosmos/src/Resource/Settings/IndexingPolicy.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/UniqueKeyPolicy.cs

This PR fixes old links and removes old examples coming from V2 SDK on UniqueKey and IndexingPolicy.
Mirror change from https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1367

[Internal] Documentation: Fix documentation example and links

---

Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs

This PR fixes a documentation bug that incorrectly states that it sets the minimum, when it is the maxmium.

[Internal] Documentation: Fix text on retry builder extension

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
changelog.md

Direct 3.9.0 brings MemoryStream with TryGetBuffer support on DocumentServiceResponse, which benefits any code path that uses TryGetBuffer on the response Content to avoid Array allocations, like the query CosmosElementSerializer (https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/CosmosElements/CosmosElementSerializer.cs#L84). It should yield a reduced memory allocation and reduced CPU (due to less GC work).

[Internal] Documentation: Add notes and test for memory optimization

---

Microsoft.Azure.Cosmos.Encryption/Directory.Build.props
Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj
Microsoft.Azure.Cosmos/Directory.Build.props

Make Encryption project depend on preview SDK.
Add nuget related attributes to Encryption.csproj

Client Encryption : Add nuget info to Encryption csproj and compile against preview SDK

---

Microsoft.Azure.Cosmos/Directory.Build.props
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TransportWrapperTests.cs
changelog.md

Bump direct version to the latest 3.9.0

[Internal] Direct Version: Add direct version 3.9.0

---

Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj

The current CSPROJ for `Microsoft.Azure.Cosmos.Encryption` is missing required attributes for Nuget publishing.

[Internal] Package: Add missing nuget required properties

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/CosmosElements/DeserializerBenchmark.cs

This PR fixes a build issue introduced in https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1368, for some reason the gated builds passed.

[Internal] Performance: Fix namespace reference

---

templates/build-test.yml

Our YAML for tests is using `dotnet run` on the Performance project, which makes no sense and it is only slowing down gated checks.
Running microbenchmarks on Azure DevOps machines will never yield reliable results.

[Internal] Build: Fix Performance project step

---

Microsoft.Azure.Cosmos.Samples/Usage/BulkExecutorMigration/Program.cs

Apprently azure-docs doesn't like tags named `<Operation>` and doesn't render correctly. Fixing tag name.
Found some wrong tags that were incorrectly closed twice too.

[Internal] Samples: Fix Bulk migration tag

---

Microsoft.Azure.Cosmos/src/PartitionKey.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/DotNetSDKAPI.json
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/PartitionKeyTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContractEnforcement.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyTests.cs
changelog.md

This PR ports https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1265 and https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1312 to support IEquatable<PartitionKey> as required per API review.

[vNext] PartitionKey: Add IEquatable support

---

Microsoft.Azure.Cosmos/src/Resource/Conflict/ConflictsInlineCore.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
Microsoft.Azure.Cosmos/src/Resource/Permission/PermissionCore.cs
Microsoft.Azure.Cosmos/src/Resource/Permission/PermissionInlineCore.cs
Microsoft.Azure.Cosmos/src/Resource/Scripts/ScriptsCore.cs
Microsoft.Azure.Cosmos/src/Resource/Scripts/ScriptsInlineCore.cs
Microsoft.Azure.Cosmos/src/Resource/User/UserCore.cs
Microsoft.Azure.Cosmos/src/Resource/User/UserInlineCore.cs

This is a continuation of PR https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1401 to fix all the remaining types.
The `UserResponse.Database` is returning `UserCore` instead of the correct `UserInlineCore`. To fix this issue the type was converted to inheritance instead of composition. 
Composition created a circle reference where UserInlineCore needed UserCore for the actual implementation, but UserCore needed the UserInlineCore for the response creation.
Current model
```C#
public abstract User
internal UserCore : User
internal UserInlineCore : User
```
New model
```C#
public abstract User
internal UserCore : User
internal UserInlineCore : UserCore 
```

Response type: Fix deadlock on scenarios with SynchronizationContext for remaining Response.ResourceType

---

Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInternal.cs
Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs
Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json

This PR adds a Database reference to the Container, and a CosmosClient reference to the database. This will allow users to only pass the Container around, and still get access to the parent CosmosClient. This prevents customer from needing to pass the Client, Database, and Container to all APIs.
`Container.Database`
`Database.Client`

Container: Add a database reference to the container

---

Microsoft.Azure.Cosmos/src/Resource/CosmosResponseFactoryCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosJsonSeriliazerUnitTests.cs

Preview response factory should not throw on not modified responses since it's an expected status code for changefeed. The QueryResponse and ReadFeedResponse already do the check in their factories to ensure status code so removed the unnecessary duplicate check.

ResponseFactory: Fix changefeed not modified should not throw

---

Microsoft.Azure.Cosmos/src/FeedRange/FeedRanges/FeedRangePartitionKeyRange.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/FeedToken/QueryFeedTokenTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/FeedRange/FeedRangeTests.cs

This PR changes the exception type when the FeedRange for a PartitionKeyRangeId does not exist. 
Changing this to CosmosException allows it to surface in naturally through the Query pipeline, otherwise it surfaces with a InternalServerError that contains the actual error as an internal exception.
This way, the exception will be a CosmosException and will be the actual exception being thrown from the GetEffectiveRanges call.

[Internal] FeedRange: Fix ExceptionType for PKRangeId

---

Microsoft.Azure.Cosmos/azuredata/Azure.Cosmos.csproj
Microsoft.Azure.Cosmos/azuredata/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseContainerCosmos.cs
Microsoft.Azure.Cosmos/azuredata/CosmosClient.cs
Microsoft.Azure.Cosmos/azuredata/Resource/Conflict/CosmosConflicts.cs
Microsoft.Azure.Cosmos/azuredata/Resource/Container/ContainerCore.Items.cs
Microsoft.Azure.Cosmos/azuredata/Resource/Container/CosmosContainer.cs
Microsoft.Azure.Cosmos/azuredata/Resource/Database/CosmosDatabase.cs
Microsoft.Azure.Cosmos/azuredata/Resource/Database/DatabaseCore.cs
Microsoft.Azure.Cosmos/azuredata/Resource/Scripts/CosmosScripts.cs
Microsoft.Azure.Cosmos/azuredata/Resource/Scripts/ScriptsCore.cs
Microsoft.Azure.Cosmos/azuredata/Resource/User/CosmosUser.cs
Microsoft.Azure.Cosmos/azuredata/Resource/User/UserCore.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/AsyncEnumerationTests.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/CosmosBasicQueryTests.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/CosmosDatabaseTests.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/CosmosItemChangeFeedTests.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/CosmosNotFoundTests.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/CosmosReadFeedTests.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/CrossPartitionQueryTests.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/SmokeTests.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/StoredProcedureTests.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/TriggersTests.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/UserDefinedFunctionsTests.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/Utils/QueryOracle.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/Utils/QueryOracleUtil.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/Utils/TestCommon.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/ChangeFeed/DocumentServiceLeaseContainerCosmosTests.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/DotNetSDKAPI.json

This PR addresses the Review feedback regarding iterator naming.
All existing `GetXXXXQueryIterator` are renamed to `GetXXXXQueryResultsAsync` to convey the async nature and async enumeration capabilities.
All existing `GetXXXXQueryStreamIterator` are renamed to `GetXXXXQueryStreamResultsAsync` to convey the async nature and async enumeration capabilities.
Documentation and examples were updated to reflect the changes and correct some incorrect texts.
The `Microsoft.VisualStudio.Threading.Analyzers` analyzer is updated to support `IAsyncEnumerable` (it does not yet detect correctly `AsyncPageable` so I had to introduce local suppression messages).

[vNext] Contract: Fix iterators to Async rename

---

Microsoft.Azure.Cosmos/src/Resource/Settings/ContainerProperties.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/DatabaseProperties.cs

This PR fixes some old broken examples from DatabaseProperties and also fixes the DefaultTimeToLive example (-1 is used to set the TTL on but items not expiring).

Documentation: Fix Database and ContainerProperties code comments

---

Microsoft.Azure.Cosmos/src/Batch/BatchAsyncContainerExecutor.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosHandlersTests.cs

This PR adds atomicity header for streamer API. Right now in backend we do assume the default request to be non atomic, so adding this won't have any issues.

[Internal] Bulk: Fix Explicit addition of atomicity header for Bulk 

---

Microsoft.Azure.Cosmos.Encryption/src/EncryptionContainer.cs
Microsoft.Azure.Cosmos.Encryption/src/EncryptionItemRequestOptions.cs
Microsoft.Azure.Cosmos.Encryption/src/EncryptionTransactionalBatchItemRequestOptions.cs
Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj
Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/EncryptionTests.cs
Microsoft.Azure.Cosmos/Directory.Build.props

Make Encryption project depend on latest released version of preview SDK and bump its version. 
Rename EncryptionOption to EncryptionOptions as the conflict with the base classes have been removed.
While breaking, Encryption is in private preview and the change is expected.

ClientEncryption: Fix dependency to latest SDK preview in Encryption package

---

Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
Microsoft.Azure.Cosmos/src/Query/v3Query/QueryResponse.cs
Microsoft.Azure.Cosmos/src/Query/v3Query/ReadFeedResponse.cs
Microsoft.Azure.Cosmos/src/Serializer/CosmosElementSerializer.cs
Microsoft.Azure.Cosmos/src/Serializer/CosmosSerializerCore.cs

Moved CosmosElementSerializer outside the CosmosElement namespace, since one uses the other and that's about it. They are independent pieces of code and ownership is separate.

[Internal] Serializer : Fix Moved CosmosElementSerializer outside the CosmosElement namespace.

---

Microsoft.Azure.Cosmos/src/FeedIteratorCore.cs
Microsoft.Azure.Cosmos/src/FeedRangeIteratorCore.cs
Microsoft.Azure.Cosmos/src/Serializer/CosmosElementSerializer.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs

#1398 made the underlying transport's stream have an accessible buffer, which benefited point operations and queries while reading through to create CosmosElements.
But there were other parts in the code that was taking this underlying stream and test it for required conversion (binary to text). This code was doing a memcopy into a new MemoryStream.
This new MemoryStream did not have the buffer accessible, so it was hurting the performance while deserializing the resulting MemoryStream to the user type.
This PR makes sure these new MemoryStreams have the buffer accessible and also adds a test to verify this does not regress.

Performance: Fix MemoryStream with un-accesible buffer

---

Microsoft.Azure.Cosmos/azuredata/Fluent/Settings/ContainerDefinition.cs
Microsoft.Azure.Cosmos/azuredata/Resource/Settings/CosmosContainerProperties.cs
Microsoft.Azure.Cosmos/azuredata/Serializer/Settings/TextJsonContainerPropertiesConverter.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/Fluent/ContainerSettingsTests.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/DotNetSDKAPI.json
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/Fluent/ContainerDefinitionForCreateTests.cs

This PR renames `CosmosContainerProperties.DefaultTimeToLive` to `CosmosContainerProperties.DefaultTimeToLiveInSeconds` and also `Fluent.ContainerDefinition.WithDefaultTimeToLive()` to `Fluent.ContainerDefinition.WithDefaultTimeToLiveInSeconds()`.
Closes #1494

[vNext] TimeToLive: Fix name of DefaultTimeToLive to DefaultTimeToLiveInSeconds

---

Microsoft.Azure.Cosmos/azuredata/CosmosClientOptions.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs

Azure Core Diagnostics can automatically log headers from the Responses. But it needs the SDK to individually indicate which headers (to avoid logging private information or information you wouldn't want unless [opted-in](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Diagnostics.md#logging-redacted-headers-and-query-parameters).
Following other SDKs, this PR adds relevant headers to the Diagnostics collection in the Core SDK type:
* https://github.com/Azure/azure-sdk-for-net/blob/6944bd8761b5d89e28d3e57f8261ae49971b7459/sdk/storage/Azure.Storage.Files.DataLake/src/DataLakeClientOptions.cs#L89
* https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/BlobClientOptions.cs#L99

[vNext] Monitoring: Add explicit headers

---

Microsoft.Azure.Cosmos/azuredata/CosmosClientOptions.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs

Azure Core Diagnostics has an ApplicationId property to add an application identifier to the collected logs. This maps to your ApplicationName property.
This PR makes it so if the user changes the `ApplicationName`, the `Diagnostics.ApplicationId` is also set to the same value.
Closes #1054

[vNext] Monitoring: Add Diagnostics.ApplicationId when ApplicationName is set

---

Microsoft.Azure.Cosmos/src/Routing/PartitionKeyRangeCache.cs
Microsoft.Azure.Cosmos/src/Routing/PartitionRoutingHelper.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyRangeHandlerTests.cs

ReadFeed with container cache misss will lead to NRE (from LINIQ). 
Fix: 
1. Return expected payload so-that callers can retry (force-refresh)
2. Avoid unnecessary array materializations (in simple paths, except reverse)
3. Info log turned to warning for observability

PartitionRoutingHelper: Fix ReadFeed ArgumentNullException due to container cache miss

---

Microsoft.Azure.Cosmos/src/EnvironmentInformation.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/UserAgentTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/EnvironmentInformationTests.cs

ClientId in the UserAgent string had a high cardinality of values. The point of it was to help identify scenarios where the user was creating multiple instances of the CosmosClient within the same process (not Singleton).
This PR changes the logic behind ClientId to have a zero based incremental value with a max bound instead of being based on the time.

[Internal] UserAgent: Fix ClientId generation

---

.editorconfig

My personal preferences - I don't care whether you change any of the value s- as long as tools enforce consistency I don't want to spend any time discussing preferences - I am aware that taste is hugely different here. I care that all the settings I modified have some enforcement in .editorconfig to recuce time we all waste discussion prettiness on CRs :-)

[Internal] Build infrastructure: Fix default .editorconfig 

---

Microsoft.Azure.Cosmos/src/Diagnostics/CosmosClientSideRequestStatistics.cs
Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosException.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDiagnosticsTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TransportWrapperTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TransportClientHelper.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosDiagnosticsUnitTests.cs

This fixes a bug in the diagnostics where a circle reference was created causing the diagnostics `ToString()` to grow exponentially. 
The `CosmosClientSideRequestStatistics` directly adds the content to the `CosmosDiagnostics`. Some of the `DocumentClientExceptions` include the `IClientSideRequestStatistics` in the message which would then call the `CosmosDiagnostic.ToString()`.  The `CosmosDiagnostic` records each `DocumentClientExceptions` and adds the message to it's records creating a circle reference.

Diagnostics: Fix ToString() to not grow exponentially with retries

---

changelog.md

Please see this page: https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sdk-dotnet-standard it has 2 titles. This PR is to remove the second title.
1. Changelog will be generated from PR titles.
2. PR titles will be formatted with the following layout.
1. Internal is optional and represents changes with no public facing changes such as test only changes
2. Category represents the area of the change like batch, changefeed, point operation, or query
3. Add or Fix identifies if a new feature is being added or if a bug is being fixed
4. Description is a user friendly explanation of the change
`[Internal] Category: (Add|Fix) Description`
`Diagnostics: Add GetElapsedClientLatency to CosmosDiagnostics`<br/>
`PartitionKey: Fix null reference when using default(PartitionKey)`<br/> …

Removing H1 to reuse this content in a H2 for docs

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ComparableTaskSchedulerTests.cs

Stabilized flaky test by making timer longer.

Internal ComparableTaskScheduler : Fix Flaky Test

---

Microsoft.Azure.Cosmos/azuredata/Resource/Settings/IndexingPolicy.cs
Microsoft.Azure.Cosmos/azuredata/Resource/Settings/SpatialPath.cs
Microsoft.Azure.Cosmos/azuredata/Serializer/Settings/TextJsonSpatialPathConverter.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/Enums/SpatialType.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.EmulatorTests/IndexingPolicyEqualityComparer.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/ContractTests.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/DotNetSDKAPI.json
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ContractTests.cs

This PR removes Azure.Cosmos.Spatial from the public surface and moves the remaining SpatialPath and SpatialType that are used on IndexingPolicy to the base namespace.

[vNext] Contract: Fix Move SpatialPath to base namespace

---

Microsoft.Azure.Cosmos/Directory.Build.props
Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticsSerializerVisitor.cs
Microsoft.Azure.Cosmos/src/Regions.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TransportWrapperTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosDiagnosticsUnitTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
changelog.md

Update the direct version to the latest

[Internal] Direct: Add version 3.10.0

---

Microsoft.Azure.Cosmos/src/Diagnostics/CosmosClientSideRequestStatistics.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDiagnosticsTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/DiagnosticValidators.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TransportClientHelper.cs

The firstStartRequestTimestamp was getting set to the CosmosClientSideRequestStatistics creation time, and not the actual first request start time. This would cause the EstimatedClientDelayFromAllCauses to show a small value when it should be 0 since there was no failures.
Bug introduced in https://github.com/Azure/azure-cosmos-dotnet-v3/pull/1570 which has not been released.

[Internal] Diagnostics: Fix bug causing flaky test

---

Microsoft.Azure.Cosmos/src/Query/Core/SqlParameter.cs
Microsoft.Azure.Cosmos/src/Query/v3Query/QueryDefinition.cs
Microsoft.Azure.Cosmos/src/Query/v3Query/QueryDefinitionEqualityComparer.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryDefinitionComparerUnitTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/QueryDefinitionUnitTests.cs

Equality comparer for internal use in compute. We need access to the QueryDefinition parameters to compare for their equality.

[Internal] Query: Add equality comparer for QueryDefinition

---

Microsoft.Azure.Cosmos/azuredata/Handler/RequestMessage.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/Diagnostics/DiagnosticsScopeTests.cs

`AzureEventSourceListener` console logger calls the `EnumerateHeaders` on the Request and Response on the Core pipeline.
Response had the method implemented, but Request did not.
This PR adds the correct implementation call on Request to avoid the exception on the logger.
Closes #1592

[vNext] Logging: Fix NotImplementedException while using ConsoleLogger

---

Microsoft.Azure.Cosmos.Encryption/src/EncryptionTransactionalBatch.cs
Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/EncryptionTests.cs

For a TransctionalBatch operation, if an empty PathsToEncrypt list is passed in as part of EncryptionOptions, the EncryptAsync method returned the input stream as is (as opposed to creating a new encrypted stream) which gets disposed, leading to ObjectDisposedException when trying to execute the batch. The fix is to ensure we do not dispose the input stream before executing TransactionalBatch.

Client Encryption : Fix to ensure input stream is not disposed before executing TransactionalBatch

---

Microsoft.Azure.Cosmos/src/Query/Core/ComparableTask/ComparableTaskScheduler.cs
Microsoft.Azure.Cosmos/src/Query/v3Query/QueryIterator.cs
Microsoft.Azure.Cosmos/src/Resource/FeedIterators/FeedIterator.cs
Microsoft.Azure.Cosmos/src/Resource/FeedIterators/FeedIteratorCore.cs
Microsoft.Azure.Cosmos/src/Resource/FeedIterators/FeedIteratorInlineCore.cs
Microsoft.Azure.Cosmos/src/Resource/FeedIterators/FeedIteratorInlineCore{T}.cs
Microsoft.Azure.Cosmos/src/Resource/FeedIterators/FeedIterator{T}.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosBasicQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosPermissionTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/NameRoutingTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/PartitioningQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/QueryTestsBase.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/SanityQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/SkipTakeQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/SmokeTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/UserDefinedFunctionsTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/DotNetSDKAPI.json

This PR adds IDisposable to the FeedIterators to fix a memory leak caused by the query logic buffering pages in the background. The FeedIterators have default implementation to avoid breaking any users that are extending the base abstract class.
**NOTE: BREAKING CHANGE**
Any users that have a static analysis tool checking for IDisposable will be broken when upgrade to this version.
Put closes #1607

Query: Fix memory leak by making FeedIterator IDisposable

---

Microsoft.Azure.Cosmos/src/Query/Core/ExecutionContext/ItemProducers/ItemProducer.cs
Microsoft.Azure.Cosmos/src/Query/Core/ExecutionContext/ItemProducers/ItemProducerTree.cs
Microsoft.Azure.Cosmos/src/Query/Core/ExecutionContext/OrderBy/CosmosOrderByItemQueryExecutionContext.Resume.cs
Microsoft.Azure.Cosmos/src/Query/Core/QueryClient/CosmosQueryExecutionInfo.cs
Microsoft.Azure.Cosmos/src/Query/Core/QueryClient/QueryResponseCore.cs
Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryContextCore.cs

Wires through QueryExeuctionInfo to determine when the Rids are reversed on order by resume keys. This is necessary, since comparing just the first column leads to a bug.

Query : Fix Multi- ORDER BY continuation token support with QueryExecutionInfo Response headers

---

Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
Microsoft.Azure.Cosmos/src/Query/Core/Parser/CstToAstVisitor.cs
Microsoft.Azure.Cosmos/src/Query/Core/Parser/ErrorListener.cs
Microsoft.Azure.Cosmos/src/Query/Core/Parser/IsqlListener.cs
Microsoft.Azure.Cosmos/src/Query/Core/Parser/IsqlVisitor.cs
Microsoft.Azure.Cosmos/src/Query/Core/Parser/LASets.cs
Microsoft.Azure.Cosmos/src/Query/Core/Parser/sqlBaseVisitor.cs
Microsoft.Azure.Cosmos/src/Query/Core/Parser/sqlLexer.cs
Microsoft.Azure.Cosmos/src/Query/Core/Parser/sqlParser.cs
Microsoft.Azure.Cosmos/src/SqlObjects/SqlQuery.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/SanityQueryTests.cs

Removing this dependency until we figure things out.

Internal Query : Fix Remove Antlr dependency for now 

---

Microsoft.Azure.Cosmos/src/Query/Core/ExecutionContext/OrderBy/CosmosOrderByItemQueryExecutionContext.Resume.cs

It's possible that execution info is null (maybe in the future we stop returning it).

Internal Query : Fix Made ExecutionInfo optional 

---

Microsoft.Azure.Cosmos/src/TimerWheel/TimerWheel.cs
Microsoft.Azure.Cosmos/src/TimerWheel/TimerWheelCore.cs
Microsoft.Azure.Cosmos/src/TimerWheel/TimerWheelTimer.cs
Microsoft.Azure.Cosmos/src/TimerWheel/TimerWheelTimerCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Benchmarks/TimerBenchmark.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/TimerWheel/Utils.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/TimerWheel/TimerWheelCoreTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/TimerWheel/TimerWheelTimerCoreTests.cs

This PR adds a [Simple Timer Wheel](https://blog.acolyer.org/2015/11/23/hashed-and-hierarchical-timing-wheels/) implementation that can be used to host and manage multiple tasks that have independent timeout intervals and reduce memory allocations versus using independent `System.Threading.Timer` instances.
Creation of the wheel requires the *resolution* of each wheel's bucket and the amount of *buckets*, which define which is the *MaxInterval*.
```csharp
TimerWheel wheel = TimerWheel.CreateTimerWheel(resolutionInMs: 50, buckets: 20);
```
Once a wheel is created, new timers can be requested by specifying the *timeout in milliseconds* for that particular timer. Then, a call to `StartTimerAsync` will return a `Task` that resolves once the timeout is up:
```csharp
TimerWheelTimer timer = …
```

[Internal] Performance: Add TimerWheel implementation

---

Microsoft.Azure.Cosmos/src/CosmosClient.cs
Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientTests.cs

Currently we check for `null` parameters on the `CosmosClient` and `CosmosClientBuilder` constructor. But if customers are reading the key (for example) from a configuration source (like KeyVault) where the value stored there is an empty string, this leads to a support case for a 401 - Not Authorized.
401 investigations are not easy, and from past experience, this is an easy fix that can rule out one of the most common scenarios.

CosmosClient: Add check for empty keys

---

TroubleshootingGuides/Exceptions.md

Link text “To many requests” should be “Too many requests”.

Documentation: Fix typo

---

Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/SynchronizationContextTests.cs

CosmosOperationCanceledException catch logic is moved up into the inline helper. This fixes an issue where some OperationCanceledException where not getting converted because some caches and other operations do not use the request invoker. 

CosmosOperationCanceledException: Fix handler to catch all operation cancelled exceptions

---

Microsoft.Azure.Cosmos/azuredata/CosmosClientOptions.cs
Microsoft.Azure.Cosmos/azuredata/Fluent/CosmosClientBuilder.cs
Microsoft.Azure.Cosmos/azuredata/Serializer/JsonEncodedStrings.cs
Microsoft.Azure.Cosmos/azuredata/Serializer/TextJsonCosmosClientOptionsConverter.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
Microsoft.Azure.Cosmos/tests/Azure.Cosmos/Azure.Cosmos.Tests/DotNetSDKAPI.json

Following API review feedback, this PR removes the `CosmosClientOptions.ApplicationName` property that competes with `ClientOptions.Diagnostics.ApplicationId`.
Since ApplicationName is a fairly common setting, it is promoted to the `CosmosClientOptions` constructor instead, as proposed during review:
`CosmosClientOptions options = new CosmosClientOptions(applicatioId: "MyApp");`
Internally it will set the Cosmos DB user-agent suffix and also the Azure.Core Diagnostics.ApplicationId.

[vNext] Contract: Add CosmosClientOptions constructor for ApplicationName

---

Microsoft.Azure.Cosmos/Directory.Build.props
Microsoft.Azure.Cosmos/src/Routing/AddressResolver.cs
Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
Microsoft.Azure.Cosmos/src/Routing/GlobalAddressResolver.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/RequestEventHandlerTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/StoreReaderTest.cs

This PR resolves a CPU consumption issue while using `CosmosClientOptions.EnableTcpConnectionEndpointRediscovery` that could cause higher CPU than intended.

Performance: Fix CPU consumption with EnableTcpConnectionEndpointRediscovery

---

CODEOWNERS

The order of the code owner files matters. This changes the order to ensure the proper owners are required.

[Internal] Codeowners: Fix order to ensure correct required reviewers

---

Microsoft.Azure.Cosmos/src/Routing/GlobalAddressResolver.cs

AddressResolver has a  GetorAdd is followed by a call to .Count which in a ConcurrentDictionary
will acquire all locks for all buckets. This is really expensive. Since the check
there is only to see if we've exceeded the count of endpoints, we can simply
avoid that check altogether if we are not adding any more endpoints.

[Internal] SDK: Fix Lock Contention on GlobalAddress Resolver

---

changelog.md

This fixes spelling and other grammar issues with the changelog.

Changelog: Fix spelling and update format

---

Directory.Build.props
Microsoft.Azure.Cosmos.Encryption/Directory.Build.props
Microsoft.Azure.Cosmos.Samples/Directory.Build.props
Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/CosmosBenchmark.csproj
Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/README.md
Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/run.sh
Microsoft.Azure.Cosmos.Samples/Tools/Directory.Build.props
Microsoft.Azure.Cosmos/Directory.Build.props

- Directory.Build.props moved upto the root for all of source availability
- No touch benchmark execution support (including targetting current branch), related README changes
- Linux bash script used internally for running tests

[Internal] Benchmark: Adds Few more benchmark related changes

---

Microsoft.Azure.Cosmos/src/GatewayStoreClient.cs
Microsoft.Azure.Cosmos/src/Handler/TransportHandler.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs

This fixes a bug where Trace.CorrelationManager.ActivityId was getting set to Guid.Empty instead of the response Activity Id. This causes any traces to have Guid.Empty instead of the correct value.

Gateway Trace: Fixes a bug where the ActivityId is being set to Guid.Empty

---

Microsoft.Azure.Cosmos/src/AuthorizationHelper.cs
Microsoft.Azure.Cosmos/src/DocumentClient.cs
Microsoft.Azure.Cosmos/src/Handler/TransportHandler.cs
Microsoft.Azure.Cosmos/src/IComputeHash.cs
Microsoft.Azure.Cosmos/src/ICosmosAuthorizationTokenProvider.cs
Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
Microsoft.Azure.Cosmos/src/SecureStringHMACSHA256Helper.cs
Microsoft.Azure.Cosmos/src/StringHMACSHA256Hash.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Benchmarks/MasterKeyAuthorizationBenchmark.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Benchmarks/MockedItemBenchmark.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Benchmarks/SdkBenchmarkConfiguration.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Mocks/MockDocumentClient.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Query/EndToEnd.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DirectContractTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Utils/MockDocumentClient.cs

Including exclusive auth performance micro benchmark.
Changes includes: 
1. Caching the HMACSHA256
2. Contract adjusted to avoid leaking bytes out
After the changes
RPS: 2-3% UP
Latency: 3-6% UP
GEN0: 30% DOWN
Allocations: 28% DOWN
|                    Method |     Mean |     Error |    StdDev |       Q3 |      P80 |      P85 |      P90 |      P95 |     P100 |      Op/s |  Gen 0 | Allocated |
|-------------------------- |---------:|----------:|----------:|---------:|---------:|---------:|---------:|---------:|---------:|----------:|-------:|----------:|
| CreateSignatureGeneration | 3.579 us | 0.0336 us | 0.0280 us | 3.603 us | 3.605 us | 3.612 us | 3.612 us | 3.614 us | 3.618 us | 279,387.0 | 0.0458 |     896 B |
|   ReadSignatureGeneration | 3.542 us | 0.0490 us | 0.0458 us | 3.576 us | …

Performance: Fixes Reduces AuthorizationHelper memory allocations

---

Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/Microsoft.Azure.Cosmos.Encryption.EmulatorTests.csproj
Microsoft.Azure.Cosmos.Encryption/tests/Microsoft.Azure.Cosmos.Encryption.Tests/Microsoft.Azure.Cosmos.Encryption.Tests.csproj
Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/CosmosBenchmark.csproj
Microsoft.Azure.Cosmos.Samples/Usage/Shared/Shared.csproj
Microsoft.Azure.Cosmos/src/Linq/BuiltinFunctions/StringBuiltinFunctions.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Microsoft.Azure.Cosmos.Performance.Tests.csproj
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Microsoft.Azure.Cosmos.Tests.csproj
changelog.md

This updates all the project to use .NET core 2.1 or 3.1 which are LTS version. The [.NET core lifecycle](https://dotnet.microsoft.com/platform/support/policy/dotnet-core) shows these will be supported until August 21, 2021.

[Internal] Projects: Fixes all project to use LTS .NET core versions

---

Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedManagement/PartitionControllerCore.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/SmokeTests.cs

Currently V3 Change Feed Processor is compatible with V2 Change Feed Processor by doing a forward migration of the schema to the schema used in V3.
**Lease schema for V2 CFP**
```
{
"id": "<lease-id>",
"PartitionId": "<partition-key-range-id>",
"Owner": "<some-owner>",
"ContinuationToken": "<some-continuation>",
}
```
**Lease schema for V3 CFP**
```
{
"id": "<lease-id>",
"LeaseToken": "<partition-key-range-id>",
"Owner": "<some-owner>",
"ContinuationToken": "<some-continuation>",
}
```
The V3 SDK performs the in-place migration by removing the `PartitionId` property and replacing it for the future-proof `LeaseToken` (for then leases can be created in a different granularity level from partitions).
The problem is that if the user wants to rollback (return to V2) for whatever reason (maybe …

Change Feed Processor: Adds backward compatibility of lease store

---

UpdateContracts.ps1

The PS1 command file used to update public contract was targeting `netcoreapp2.0` but our test projects were moved to `netcoreapp2.1`.

[Internal] Tests: Fixes contract update tool

---

templates/build-test.yml

Unit tests project runs on Release configuration, which makes any Debug.Assert calls moot for verification purposes.

[Internal] Tests: Fixes tests configuration

---

Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/CosmosBenchmark.csproj
Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
templates/build-test.yml

Performance: Adds includes compiler optimize option

Performance: Adds includes compiler optimize option

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Json/JsonRoundTripBenchmarks.cs

Commenting out file like the others to fix the Benchmark run exception.
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\azure-cosmos-dotnet-v3\Microsoft.Azure.Cosmos\tests\Microsoft.Azure.Cosmos.Performance.Tests\TestJsons\NutritionData.json'.

[Internal] Performance.Tests: Fixes perf benchmarks so that MockedItemBenchmark can run

---

Microsoft.Azure.Cosmos.Samples/Usage/BulkExecutorMigration/Program.cs
Microsoft.Azure.Cosmos.Samples/Usage/Cosmos.Samples.Usage.sln
Microsoft.Azure.Cosmos.Samples/Usage/HttpClientFactory/HttpClientFactory.csproj
Microsoft.Azure.Cosmos.Samples/Usage/HttpClientFactory/Program.cs

This PR adds a new Samples project focused on `CosmosClientOptions.HttpClientFactory` and its use cases:
* Disabling SSL validation for Emulator scenarios
* Leveraging NET Core IHttpClientFactory for ASP.NET and console applications
* Reusing HTTP connections when IHttpClientFactory is not available

[Internal] Samples: Adds HttpClientFactory usage samples

---

Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/ConsistencyLevel.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/ContainerProperties.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/HashIndex.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/IncludedPath.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/IndexKind.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/RangeIndex.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/SpatialIndex.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/ThroughputProperties.cs

We had old Azure articles URLs lingering on some of our public types and methods. Replaced them with the new format and correct urls.

[Internal] Documentation: Fixes old article Urls on public classes and APIs

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/GatewayTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryTests.cs

This PR is fixing the following tests that are broken from the new emulator. 
Cosmos DB master PR that made the change: https://msdata.visualstudio.com/DefaultCollection/CosmosDB/_git/CosmosDB/pullrequest/368488

[Internal] Tests: Fixes emulator test that are broken from new emulator

---

Microsoft.Azure.Cosmos/src/RequestOptions/RequestOptions.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json

This make the RequestOptions.Properties as part of the public SDK. 

RequestOptions.Properties: Adds new feature to public SDK

---

Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainer.cs
Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerCore.cs
Microsoft.Azure.Cosmos.Encryption/src/DataEncryptionKeyContainerInlineCore.cs
Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/EncryptionTests.cs
Microsoft.Azure.Cosmos.Encryption/tests/Microsoft.Azure.Cosmos.Encryption.Tests/Contracts/DotNetSDKEncryptionAPI.json

Add overload with QueryDefinition for GetDataEncryptionKeyQueryIterator() so user doesn't have to necessarily use plaintext query parameters. 

Client Encryption : Adds overload with QueryDefinition for GetDataEncryptionKeyQueryIterator

---

Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchResponse.cs
Microsoft.Azure.Cosmos/src/DocumentClient.cs
Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
Microsoft.Azure.Cosmos/src/Routing/GlobalAddressResolver.cs
Microsoft.Azure.Cosmos/src/SecureStringHMACSHA256Helper.cs
Microsoft.Azure.Cosmos/src/SessionContainer.cs

There are a few places where finalizers are used and most of them are actually not useful and just cause overhead.
But there is one class which currently doesn't have a finalizer, but must have one - `SecureStringHMACSHA256Helper` holds native resources.
- Bug fix (non-breaking change which fixes an issue)

Performance: Adds finalizer optimizations in a few places

---

Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs

Creation of the `CosmosHttpClient` tries to set the Proxy and MaxConnectionsPerServer properties on `HttpClientHandler`, but these are not supported on all platforms.
This fix conditionally attempts to set them and detects `PlatformNotSupportedException` and retries without these parameters.
Due to the nature of the issue, no mocking can be done to test it.
Testing was done with a real Blazor WASM application.
Closes #1860 
Closes #1862

Blazor: Fixes not supported HTTP features

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/ChangeFeedEstimatorCoreTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/ChangeFeedProcessorCoreTests.cs

Some unit tests were starting CFP processors and CF estimators, evaluating that initialization, but not stopping the instances. This didn't fail the test because the test was covering the initialization process, but it left Tasks running in the back that would fail with NullReferenceExceptions because the mocked instances were not mocking all methods, just mocking the methods on the test scope.

[Internal] Tests: Fixes CFP tests not stopping

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Mocks/MockDocumentClient.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Program.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/README.md
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/TimerWheel/TimerWheelCoreTests.cs

Recent auth changes always creates the compute function in the constructor now causing non-base64 string to throw an exception.

[Internal] MockItemBenchmarks: Fixes benchmarks to pass valid master key format

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/TimerWheel/TimerWheelCoreTests.cs

Recently, TimerWheel tests that were time sensitive have began to randomly fail. This could be related to CI machine resources. To reduce flakyness, this PR extends the expected times, from the correctness perspective, nothing is changing.
Also adding `using` clauses to dispose of timers after test executes.

[Internal] TimerWheel: Fixes tests to avoid flakyness

---

Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Utils/CosmosContainerExtensions.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentServiceLeaseStoreCosmosTests.cs

If during initialization, the lease collection is getting throttled (or has other issues, like, not existing), the error was not getting correctly handled and resulted in a null reference exception.
Closes #1883

Change Feed Processor: Fixes failures during initialization

---

Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs

Update lambda on `AddOrUpdate` on ConcurrentDictionary is not thread-safe, so there could be scenarios where a loop can be generated causing high CPU usage on the code path.

Performance: Fixes HashSet usage on Address refresh path

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/ChangeFeedEstimatorIteratorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/TimerWheel/TimerWheelCoreTests.cs

Time based verifications are susceptible to machine based issues. This PR eliminates the time checks while maintaining the verification of correctness over the timer actually firing.

[Internal] Tests: Fixes flaky verifications

---

Microsoft.Azure.Cosmos.Samples/Usage/ChangeFeed/Program.cs

When instance of old changefeed processor is configured, `ChangeFeedProcessorBuilder.WithProcessorOptions` method is called 2 times, and options are overridden and default values are used for `StartFromBeginning`/`LeasePrefix` properties. This PR removes duplication by merging setups.
To automatically close an issue: closes #1915

Samples: Fix ChangeFeed sample to have correct setup for old processor

---

Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimatorIterator.cs

The Estimator was using a Partitioner to issue concurrent estimations and construct the result pages, but the diagnostics were being added concurrently through a thread-unsafe method.
This PR removes the Partitioner (which really was not adding any benefit) and makes sure the diagnostics are added non-concurrently.
This PR also removes flakyness in tests at https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/ChangeFeedEstimatorIteratorTests.cs due to randomly not having the expected diagnostics.

[Internal] Change Feed: Fixes estimator diagnostics

---

Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimatorIterator.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/ChangeFeedEstimatorIteratorTests.cs

Estimator was using `Task.Run` to trigger parallel operations on the leases, which seems to be causing flakyness during test runs in some cases.
This refactor removes the `Task.Run` need and simplifies it. Also cleans up some code style complains from editorConfig.

[Internal] Change Feed Estimator: Fixes Task.Run

---

Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
Microsoft.Azure.Cosmos/src/Resource/Database/DatabaseCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs

This fixes a bug where the RequestOption.Properties was not being sent to all the calls in the CreateContainerIfNotExistsAsync method.
closes #1948

RequestOption.Properties: Fixes RequestOption.Properties for CreateContainerIfNotExistsAsync

---

Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientTests.cs

This fixes the following issues:
1. Previously WebProxy would get set even if an argument exception was thrown
2. Setting a null value caused an ArgumentException which is not necessary for null values.
3. WebProxy can now be set without being in gateway mode like HttpClientFactory. It's possible users want custom HttpClient settings even when in direct mode because control plane operation like Database and Container still go through HttpClient.
closes #1953

CosmosClientOptions and ClientBuilder: Fixes ArgumentException when setting null value on HttpClientFactory or WebProxy 

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosAuthorizationTests.cs

TestTokenCredentialBackgroundRefreshAsync delay timing is increased to avoid transient failures caused by slow machines used in the gates.

Internal TestTokenCredentialBackgroundRefreshAsync: Fixes timing failures 

---

Microsoft.Azure.Cosmos/src/GatewayStoreClient.cs

This reverts gateway store ExtractResponseHeaders to use DictionaryNameValueCollection which is needed because some compute scenarios have duplicate header values which causes an exception for StoreResponseNameValueCollection. A bug will be filed against the service to remove the duplicate value to reduce overhead.

Internal Headers: Fixes ExtractResponseHeaders

---

Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/PartitionMapper.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/ContinuationResumeLogicTests.cs

Suppose the partition spans epk range A to E
And the user send a query with partition key that hashes to C
When we query the results the continuation token will look something like:
```JSON
{
"token": "blah",
"range": {
"min": "A",
"max": "E"
}
}
```
Now suppose there is a split that creates two partitions A to B and B to E
Now C will map to the partition that goes from B to E
When we run the following code:
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/PartitionMapper.cs#L68
We are going to hit an exception, since the code looks for a partition to resume from which in this case should be B to E, but we have the value A to E and we are checking to see if a partition matches the start of range (in this case A). …

Query: Fixes split proofing logic for queries with logical partition key

---

Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/Fx/ParallelExecutionStrategy.cs
Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/Program.cs
Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/RunSummary.cs

This adds the Azure VM instance info the run summary, and the location. This will make it easier to run in multiple regions.
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/instance-metadata-service

Benchmark: Adds Azure VM info to summary

---

Microsoft.Azure.Cosmos/src/Pagination/CrossPartitionRangePageAsyncEnumerator.cs
Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/OrderBy/OrderByCrossPartitionQueryPipelineStage.cs

We noticed that for read feed requests we always start off the feed ranges using the full range. This leads to an issue where the code detects that a split has happened (which it has, since it's no longer one partition), but we technically don't need to do a cache refresh in these scenarios, since the partition topology is up to date. In general the partition topology could have gotten updated by another request, which means we shouldn't update the cache in these scenarios. 
The code now optimistically assumes that the cache is already updated and in the event that we only get back one child range / the range that know to have split (since we got a 410 / 1002) then we will update the cache.

Routing Map: Adds Non Aggressive Cache Refresh

---

Microsoft.Azure.Cosmos/src/ReadFeed/ReadFeedIteratorCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/FeedToken/ReadFeedTokenTests.cs

Before the ReadFeedIterator was not special casing partition key requests. It was fanning out to all ranges with the partition key header meaning that all but one range would return empty streams. This change special cases the logical partition key input and filters out the other partitions.

Internal ReadFeed: Adds Partition Elimination 

---

Microsoft.Azure.Cosmos/src/BulkPartitionKeyRangeGoneRetryPolicy.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncBatcherTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncOperationContextTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BulkPartitionKeyRangeGoneRetryPolicyTests.cs

This PR adds a retry when the backend returns CompletingSplit and CompletingPartitionMigration, to process it the same way as PartitionKeyRangeGone and retry the operation.

[Internal] Bulk: Adds retry on CompletingSplit

---

Directory.Build.props
Microsoft.Azure.Cosmos/src/AssemblyInfo.cs

Add InternalsVisibleTo Microsoft.Azure.Cosmos.Analytics.Core and bump Direct version which I already released.
Microsoft.Azure.Cosmos.Analytics.Core uses the SDK to create the required request to call the Snapshot API which is not part of the public API.

Internal InternalsVisibleTo: Adds Microsoft.Azure.Cosmos.Analytics.Core 

---

Microsoft.Azure.Cosmos/src/HttpClient/TransientHttpClientRetryPolicy.cs
Microsoft.Azure.Cosmos/src/Util/Extensions.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosDiagnosticsUnitTests.cs

The PointOperationStatistic was recording the default substatus code instead of getting the value from the exception. 

Diagnostics: Fixes substatuscode when recording internal DocumentClientException

---

Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GlobalEndpointManagerTest.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/LocationCacheTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/testhost.dll.config

When users are using PreferredRegions, and an HttpException arises that marks the current region unavailable, the region is marked unavailable, which moves it to the bottom of the priority list. 
In a scenario where the account has 2 regions marked as preferred, and a read request failed with HttpException, the algorithm was, after marking the region unavailable, selecting to retry on the second region in the list, which is basically the one that failed because marking it unavailable moved it to the bottom of the list.
This PR slightly changes the logic to always pick the first preferred region on this scenario, which would be the next preferred region after the current one is marked unavailable.

Availability: Fixes retry behavior on HttpException

---

Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/PartitionKeyRangeCacheTests.cs

In GetRoutingMapAsync, we read the RID from cache & then look up the associated collection routing map.
In the case where the RID is stale & the collection routing map is not found, the stale RID should be invalidated & the operation retried.
I am also switching a method written using ContinueWith to be async instead as I found during testing that this style can cause AggregateException to be thrown which callers do not typically expect (e.g. a NotFound would end up as a 500 because of that).
Triage source is CRI.

Internal PartitionKeyRangeCache: Adds RID refresh on NotFound in GetRoutingMapAsync

---

Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticsContextCore.cs
Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticsSerializerVisitor.cs
Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryContextCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDiagnosticsTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/DiagnosticValidators.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosDiagnosticsUnitTests.cs

To avoid any IndexOutOfRangeException the CosmosDiagnostics is refactored to remove the AddRange call. This will avoid any indexing issues caused by the possibility of the CosmosDiagnosticsContext getting modified in another task at the same time it is getting append to a parent CosmosDiagnosticContext.
This should also help improve performance by reducing the number of copies required when combining multiple CosmosDiangosticsContext.
To automatically close an issue: closes https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2075

CosmosDiagnostics: Fixes IndexOutOfRangeException

---

Directory.Build.props
Microsoft.Azure.Cosmos.Encryption/changelog.md
Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj

This fixes the issue of Encryption package not picking up Cryptography.dll when building the Nuget package.

Client Side Encryption : Adds fix for Encryption Package not picking up Cryptography DLL.

---

Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticsContextCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosDiagnosticsUnitTests.cs

This makes the CosmosDiagnostics thread safe by adding a lock to adding information to the diagnostic list.  Benchmarks showed no changes from adding the lock which is likely because most of the diagnostics is not done concurrently.

CosmosDiagnostics: Fixes concurrent operations

---

Microsoft.Azure.Cosmos/src/Headers/Headers.cs
Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosExceptionFactory.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/HttpHandlerHelper.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosExceptionTests.cs

The document client exception that is thrown internally will return default value if the SubStatusCode is not defined in the enum. This changes the logic to parse and use the int from the headers so the exception always shows the correct value. This allows the SDK to properly handle unexpected or newer substatuscodes that it is not aware of.

CosmosException: Fixes substatuscode to get the correct value instead of 0 when it is not in the enum.

---

Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/LocationCacheTests.cs

When the account is set as Multi master and preferred regions are provided (either through CosmosClientOptions.ApplicationRegion or CosmosClientOptions.ApplicationPreferredRegions), the first retry on a ReadSessionNotAvailable (HTTP 404 / substatus 1002) would retry on the same region that got the original error.
> On every region, there is 5 seconds of local retries before the failure bubbles up to the ClientRetryPolicy
For example, if the client has regions A, B, and C as preferred regions. The current retry mechanism would do:
1. Original request goes to A, and fails
2. First retry goes again to A
3. Second retry goes to B
4. Third retry goes to C
With this PR, this is fixed to direct the first retry to the second region instead:
1. Original request goes to A, and fails
2. First retry …

Availability: Fixes read session not available retries on multi master accounts

---

Microsoft.Azure.Cosmos/src/Batch/BatchAsyncContainerExecutor.cs
Microsoft.Azure.Cosmos/src/BulkExecutionRetryPolicy.cs
Microsoft.Azure.Cosmos/src/BulkPartitionKeyRangeGoneRetryPolicy.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncBatcherTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncOperationContextTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BulkPartitionKeyRangeGoneRetryPolicyTests.cs

When Bulk mode is turned on, and the user is using it for Read operations, it is possible to request a volume of documents which total size is larger than the 4Mb service limit.
In that case, the backend will return HTTP 200 for those operations within the boundary, but 413 for those that exceed it.
This PR adds the behavior of retrying those operations that exceed the boundary limit into another Bulk request.

Bulk: Adds retry on RequestEntityTooLarge

---

Microsoft.Azure.Cosmos.Samples/Tools/CTL/Dockerfile
Microsoft.Azure.Cosmos.Samples/Tools/CTL/run_ctl.sh

This PR adds a Dockerfile and shell file that can be used to containerize the CTL project into a docker image.
Running `docker build -t <my-image-name> -f Dockerfile . ` on the CTL project folder will build the docker image. The build process will run `dotnet publish` on the CTL project and also copy the required Shell file.
After the image is built, it can be run by:
`docker run -it -e ctl_endpoint="<endpoint>" -e ctl_key="<key>" --rm <my-image-name>`

[Internal] CTL: Adds Dockerfile to produce a docker image to run

---

Microsoft.Azure.Cosmos/src/Authorization/AuthorizationHelper.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Authorization/AuthorizationHelperTests.cs

Removing URL encoding for Authorization Token Helper used by compute

[Internal] Authorization : Refactors Authorization Token Helper to remove URL encoding used by compute

---

Microsoft.Azure.Cosmos.Samples/Tools/CTL/Dockerfile
azure-pipelines-ctl-publishing.yml
templates/build-ctl.yml

This PR automates the generation of the Docker image for CTL runs using a YML Azure Pipelines job.
The Azure Pipelines job by default pushes the image to a default container in Azure Container Registry, but can be customized in case we want to push a new image for a particular test case (for example, testing if a particular set of changes would generate an image with any issues).

[Internal] CTL: Adds yml automation for daily image build

---

Directory.Build.props
Microsoft.Azure.Cosmos/src/Diagnostics/BoundedList.cs
Microsoft.Azure.Cosmos/src/Diagnostics/CircularQueue.cs
Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticsContextCore.cs
Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnosticsSerializerVisitor.cs
Microsoft.Azure.Cosmos/src/Diagnostics/StoreResponseStatistics.cs
Microsoft.Azure.Cosmos/src/Diagnostics/StoreResultStatistics.cs
Microsoft.Azure.Cosmos/src/Regions.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/SanityQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/DiagnosticValidators.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosDiagnosticsUnitTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Diagnostics/BoundedListTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Diagnostics/CircularQueueTests.cs

NetworkAttachedDocumentContainer holds on to a single CosmosDiagnostics context, and adds diagnostics for each response to this context. for long running queries, this amounts to growing the size of CosmosDiagnostics without bound.
In addition StoreResponseStatistics was holding on the entire StoreResult object including the response stream, which leads to the very high memory consumption.
This change severs the link between StoreResponseStatistics and the StoreResult, and it also uses a bounded circular buffer instead of a list to store child contexts in CosmosDiagnosticsCore

CosmosDiagnostics: Fixes memory leak due to unbounded growth of CosmosDiagnosticsContextCore and removes reference to response stream.

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/BatchAsyncContainerExecutorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/BatchTestBase.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/CosmosItemBulkTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/ChangeFeedAsyncEnumerableTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Contracts/ContractTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContentResponseTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDiagnosticsTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosGatewayTimeoutTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosHandlersTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosHeaderTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemChangeFeedTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemLinqTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosJsonSerializerTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosOperationCanceledExceptionTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/FeedToken/ChangeFeedIteratorCoreTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/FeedToken/FeedRangeTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/FeedToken/ReadFeedTokenTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/NameRoutingTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ReadFeed/ReadFeedAsyncEnumerableTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/SynchronizationContextTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TriggersTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/UserDefinedFunctionsTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/ToDoActivity.cs

1. Removed multiple duplicate ToDoActivity objects so all test use same version.
2. ToDoActivity partition key from "status" to "pk" to make it clear that the value is the partition key.

[Internal] Emulator Tests: Refactors the ToDoActivity object to use pk instead of status

---

Microsoft.Azure.Cosmos/src/ConnectionMode.cs

Our intellisense docs were incorrectly stating that Gateway was the default, and referencing internal classes and old samples.

Documentation: Fixes ConnectionMode intellisense

---

Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/Fx/Summary.cs

The RPS in the summary should only include success operations. There was a bug that caused failures on the client side which cause the RPs to increase significantly, but most of them were client side failures.

[Internal] Benchmark: Fixes RPs in summary to only be success operations

---

Microsoft.Azure.Cosmos.Samples/Tools/CTL/CTLConfig.cs
Microsoft.Azure.Cosmos.Samples/Tools/CTL/Program.cs
Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedProcessorScenario.cs
Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ICTLScenario.cs
Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ReadWriteQueryScenario.cs
Microsoft.Azure.Cosmos.Samples/Tools/CTL/WorkloadType.cs

This PR extends CTL scenarios by adding a scenario for Change Feed Processor. The scenario can optionally initialize by creating a document load or take a pre-existing collection. It will start CFP from the beginning and generate metrics of the received documents during the running time.
After the running time is done, it will emit metrics for the existing leases and verify that all the effective ranges are covered (no gaps), this will help to verify split or merge mechanics.
The PR additionally adds Instance gauges (CPU and Memory) to be emitted during the run.
Example of gauges for the instance metrics:
```
"gauges": [
{
"value": 0.03890632844138315,
"name": "Priviledged CPU",
"tags": {},
"unit": "percent"
},
{
"value": 200855552,
"name": "Process Working Set",
"tags": {},
"unit": "B" …
```

[Internal] CTL: Adds Change Feed Processor scenario

---

Microsoft.Azure.Cosmos/src/Json/IJsonReader.cs
Microsoft.Azure.Cosmos/src/Json/Interop/NewtonsoftToCosmosDBReader.cs
Microsoft.Azure.Cosmos/src/Json/JsonReader.JsonBinaryReader.cs
Microsoft.Azure.Cosmos/src/Json/JsonReader.JsonTextReader.cs
Microsoft.Azure.Cosmos/src/Json/JsonReader.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonReaderTests.cs

Removes `GetUtf8StringValue`, since users should just go through `GetStringValue` from `IJsonReader`. The reasoning is, because `GetStringValue` returns `UtfAnyString`, which is as good as `string` and `utf8String`. It will also defer the actual transcoding.

Internal Json: Fixes double API of GetUtf8StringValue and GetStringValue

---

Microsoft.Azure.Cosmos/src/Handler/RequestMessage.cs
Microsoft.Azure.Cosmos/src/Pagination/NetworkAttachedDocumentContainer.cs
Microsoft.Azure.Cosmos/src/RequestOptions/QueryRequestOptions.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/QueryTestsBase.cs

QueryRequestOption is cloned while executing the request. This limits the applications to extend QueryRequestOptions to populate extra headers
- 

QueryRequestOption: Adds optimization to avoid duplicating QueryRequestOption

---

Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/Take/TakeQueryPipelineStage.Client.cs
Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/Take/TakeQueryPipelineStage.Compute.cs
Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/Take/TakeQueryPipelineStage.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/MockQueryPipelineStage.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/TakeQueryPipelineStageTests.cs

Currently, the TakeQueryPipelineStage drains the entire query pipeline instead of stopping eagerly. We fix this so that we only drain as many records as have been requested by the user.
closes #1979 

Query: Fixes Take operator from enumerating all pages.

---

Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedMode.cs
Microsoft.Azure.Cosmos/src/Fluent/Settings/ChangeFeedPolicyDefinition.cs
Microsoft.Azure.Cosmos/src/Fluent/Settings/ContainerBuilder.cs
Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInlineCore.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInternal.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/ChangeFeedPolicy.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/ContainerProperties.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SettingsContractTests.cs

This PR enables the APIs to support Change Feed in Full Fidelity mode. Building on top of the Retention API exposed at #2020 and #2109, once a container has been created with Change Feed retention, Change Feed iterators can be created with Full Fidelity.
Full Fidelity Change Feed exposes creates, replaces, delete operations, including metadata.
The PR exposes a new `ChangeFeedMode` as a **required parameter** to initiate any Change Feed iterator. This prompts the user to make a conscious choice of the mode they want to use.
Current Change Feed (the one available until now) is called `ChangeFeedMode.Incremental`, while the new one is called `ChangeFeedMode.FullFidelity`. 
```
ContainerProperties containerProperties = new ContainerProperties("myContainer", "/pk"); …
```

[Preview] Change Feed: Adds Full Fidelity support

---

Microsoft.Azure.Cosmos/src/Resource/Settings/ContainerProperties.cs

The code example on documentation for ContainerProperties class has some syntax errors.
Closes https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2185

Documentation: Fixes documentation issue Azure/azure-sdk-for-net#18305

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryTests.cs

Update existing maxPageSize and continuationTokenLimitInKb tests. MaxPageSize will have corrected expectations and continuationTokenLimitInKb will be aware of the Compute continuation tokens

[Internal] QueryTests: Fixes maxPageSize and continuationTokenLimitInKb tests

---

Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/BenchmarkConfig.cs

Recent benchmarking is showing issues that are likely caused by the default MaxRequestsPerTcpConnection. This setting allows us to override and test different configuration.

Benchmark: Adds the ability to configure MaxRequestsPerTcpConnection and MaxTcpConnectionsPerEndpoint

---

Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/BenchmarkConfig.cs
Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/Program.cs
Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/RunSummary.cs

This PR adds the MaxTcpConnectionsPerEndpoint and MaxRequestsPerTcpConnection to summary output so different value are recorded. This will allow reports to compare the impact of the different values changing.

Benchmark: Adds MaxTcpConnectionsPerEndpoint and MaxRequestsPerTcpConnection to Summary output

---

Microsoft.Azure.Cosmos.Encryption/src/Custom/DataEncryptionKeyContainer.cs
Microsoft.Azure.Cosmos.Encryption/src/Custom/DataEncryptionKeyContainerCore.cs
Microsoft.Azure.Cosmos.Encryption/src/Custom/DataEncryptionKeyContainerInlineCore.cs
Microsoft.Azure.Cosmos.Encryption/src/Custom/EncryptionProcessor.cs
Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/MdeEncryptionTests.cs
Microsoft.Azure.Cosmos.Encryption/tests/Microsoft.Azure.Cosmos.Encryption.Tests/Contracts/DotNetSDKEncryptionAPI.json
Microsoft.Azure.Cosmos.Encryption/tests/Microsoft.Azure.Cosmos.Encryption.Tests/LegacyEncryptionProcessorTests.cs
Microsoft.Azure.Cosmos.Encryption/tests/Microsoft.Azure.Cosmos.Encryption.Tests/MdeEncryptionProcessorTests.cs

This PR  brings in the following changes/Features. 
- Migrating Legacy Keys which are wrapped using Legacy Algorithm/Lib and configured to Encrypt data using legacy algorithm to MDE based algorithm/Lib by rewrapping and updating the Data Encryption Key properties.
- If EncryptionOption is configured with an Invalid path we now ignore this path and continue rather than throw an Exception.
- Serialization change from SqlNvarcharSerializer ( UTF-16 encoding ) to SqlVarcharSerializer ( with UTF-8 encoding ).

Client Encryption : Adds support to Migrate Data Encryption Key via Rewrap from Legacy Algorithm to MDE Algorithm

---

Microsoft.Azure.Cosmos/src/Diagnostics/CosmosTraceDiagnostics.cs
Microsoft.Azure.Cosmos/src/Handler/TransportHandler.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.BatchOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.BulkOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ChangeFeedAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.MiscellanousAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.PointOperationsExceptionsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.QueryAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ReadFeedAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.StreamPointOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.TypedPointOperationsAsync.xml

Adds the user agent to the trace datum for network requests. 
Current trace string looks like this:
```
.
└── CreateItemStreamAsync(6e383ac9-8568-4ab6-8aa4-8315034d4850)  Transport-Component  08:06:34:437  10.79 milliseconds  
└── Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler(a1b4d817-8daa-408f-9c84-e73975b15d66)  RequestHandler-Component  08:06:34:438  9.37 milliseconds  
└── Microsoft.Azure.Cosmos.Handlers.RequestInvokerHandler(4ec9e1d8-e690-477d-bda8-2f67ccf14e5f)  RequestHandler-Component  08:06:34:438  9.33 milliseconds  
└── Send Async(10007cbe-2e9d-48fa-a530-ea96f824c51c)  RequestHandler-Component  08:06:34:438  9.28 milliseconds  
│   (
│       [CPU Load History]
│       (2021-02-12T20:06:31.0931288Z 100.000)
│   )
└── Send Async(3e62d468-06f1-453c-99dd-2e8aa938558b) …
```

Internal ITrace: Adds UserAgent

---

Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceJsonWriter.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/TraceWriterBaselineTests.TraceData.xml

Adding some missing json visitor code. 
Resolves https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2228

Preview ITrace: Fixes JsonTraceWriter to include address resolution and store response stats.

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/DocumentContainerTests.cs

- This change adds a test that validates the changes made in the following PR: https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2218
- Adding this test in place so that the contract does not regress.

[Internal] ChangeFeed: Adds a Unit Test For ChangeFeed Response Headers

---

Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceJsonWriter.cs
Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceTextWriter.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/TraceWriterBaselineTests.TraceData.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Tracing/TraceWriterBaselineTests.cs

The trace datum classes don't have a strong contract with null. Values like endpoint are sometimes allowed to be null. In the old trace writer we would call on Newtonsoft's JsonWriter.WriteValue(value), which is tolerant of null values. Currently we use Cosmos.Json.JsonWriter.WriteStringValue() which does not handle null. The fix is to just handle null in the writer. We can not push the invariants up to the type, since we don't know what code in production might set a value to null and don't want to cause a NullArgumentException at runtime. As we see diagnostics with nulls we can investigate what caused it and hunt down the values.

Preview TraceWriter: Fixes Argument Null Exception / Null Reference Exception

---

Microsoft.Azure.Cosmos/src/Util/ServicePointAccessor.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ServicePointAccessorTests.cs

Disable Nagle for HTTP gateway mode requests;
this improves latency/throughput for Gatewaymode customers on .net Framework.
This is already the default on .net core so they should be no-op for those customers.

Performance: Adds an optimization to disable Nagle Algorithm for HttpRequest on NetFx

---

Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceJsonWriter.cs
Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceTextWriter.cs
Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.BatchOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.BulkOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ChangeFeedAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.MiscellanousAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.PointOperationsExceptionsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.QueryAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ReadFeedAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.StreamPointOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.TypedPointOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/TraceWriterBaselineTests.ScenariosAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/TraceWriterBaselineTests.Serialization.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/TraceWriterBaselineTests.TraceData.xml

Adds back the line numbers. Uses a cache for the name.

Internal ITrace: Adds back Line Numbers

---

Microsoft.Azure.Cosmos.Samples/Tools/CTL/CTLConfig.cs
Microsoft.Azure.Cosmos.Samples/Tools/CTL/Program.cs
Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedProcessorScenario.cs

CTL default configuration was throwing on throttled requests with no retries.
On CFP scenarios, the Lease Container initialization when the number of partitions is really high, could generate 429s on the lease collection with the default provisioned RU.
This PR also adds some extra logging that help to debug scenarios and tell apart where a particular issue might have occurred.

[Internal] CTL: Fixes retry configuration

---

Microsoft.Azure.Cosmos/src/Resource/Settings/PermissionProperties.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosPermissionTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosPermissionUnitTests.cs

This PR removes ContainerInlineCore dependency from PermissionProperties.
To automatically close an issue: closes #2266

PermissionProperties: Fixes ContainerInlineCore dependency from PermissionProperties

---

changelog.md

Adds missing changefeed pr to the public changelog
Change Feed Estimator API was missed when doing the initial changelog generation. This adds the necessary change.

Changelog: Adds missing change feed PR to 3.17.0

---

Microsoft.Azure.Cosmos/src/Spatial/Converters/GeometryJsonConverter.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Spatial/CommonSerializationTest.cs

When deserializing a Spatial type, if the raw Json was valid but did not contain a `type` property, a `NullReferenceException` was being thrown.
Closes #2304

Spatial: Fixes deserialization when Json does not represent a Spatial type

---

Directory.Build.props
Microsoft.Azure.Cosmos/src/Routing/AddressResolver.cs
Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayAddressCacheTests.cs

The Cosmos DB Service returns a header to specify if a request is within the same Azure region. These changes are to the AddressResolver and GatewayAddressCache to consume this header and pass it along to the PartitionAddressInformation object during address resolution.

[Internal] LocalRegionRequest: Adds the ability to pass location header during Address Resolution. 

---

Microsoft.Azure.Cosmos/src/Query/Core/QueryClient/CosmosQueryClient.cs
Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPartitionProvider.cs
Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPlanHandler.cs
Microsoft.Azure.Cosmos/src/Query/v2Query/DefaultDocumentQueryExecutionContext.cs
Microsoft.Azure.Cosmos/src/Query/v2Query/DocumentQueryExecutionContextBase.cs
Microsoft.Azure.Cosmos/src/Query/v2Query/DocumentQueryExecutionContextFactory.cs
Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
Microsoft.Azure.Cosmos/src/Routing/PartitionRoutingHelper.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/DistinctQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Query/ParsingBenchmark.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/FullPipelineTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPlanBaselineTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Tracing/TraceWriterBaselineTests.cs

This change upgrades the Direct package so that we can use the new functionality in ServiceInterop.dll to enable the proper computation of COUNT(DISTINCT) in the V3 SDK.

Query: Fixes COUNT(DISTINCT) in V3 SDK by upgrading Direct package version

---

Microsoft.Azure.Cosmos.Samples/Tools/CTL/run_ctl.sh

The new parameters were not being wired correctly, so were not being picked up when using `docker run`

[Internal] CTL: Fixes wiring of docker parameters into execution

---

Directory.Build.props
Microsoft.Azure.Cosmos.Encryption/changelog.md
Microsoft.Azure.Cosmos.Encryption/src/Custom/EncryptionContainer.cs
Microsoft.Azure.Cosmos.Encryption/src/Custom/EncryptionTransactionalBatch.cs
Microsoft.Azure.Cosmos.Encryption/src/EncryptionContainer.cs
Microsoft.Azure.Cosmos.Encryption/src/EncryptionTransactionalBatch.cs
Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj

1. This PR will upgrade the dependent CosmosDB Preview Package to 3.18.0-preview.
2. Updates the Encryption preview release version to 1.0.0-previewV13 and the change log.
Note:
PatchItemAsync<T>(...) and  PatchItemStreamAsync(...)  for Container and TransactionalBatch operations introduced as part of 3.18.0-preview is not supported by the Encryption Package and will throw NotImplementedException.

Client Encryption: Adds integration with latest CosmosDb Preview Package - 3.18.0-preview.

---

Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/Fx/ParallelExecutionStrategy.cs
Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/RunSummary.cs

This adds additional percentages to the summary output. This will help give better insights into the latency.

CosmosBenchmarks: Adds additional percentages to summary output

---

Microsoft.Azure.Cosmos.Samples/Usage/BulkExecutorMigration/Program.cs

Current example from migration from V2 Bulk to V3 Bulk has ContinueWith in the code, ideally we should remove ContinueWith to avoid new Task allocations.

Samples: Fixes bulk migration sample to remove ContinueWith

---

Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedProcessorScenario.cs
Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ReadWriteQueryScenario.cs
Microsoft.Azure.Cosmos.Samples/Tools/CTL/Utils.cs
Microsoft.Azure.Cosmos.Samples/Tools/CTL/run_ctl.sh

Moving duplicated code into a single utility to avoid scenarios potentially using different configurations to pre-populate containers.

[Internal] CTL: Fixes code duplication and unifies logic

---

Microsoft.Azure.Cosmos/src/Pagination/NetworkAttachedDocumentContainer.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/FeedToken/FeedRangeTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/NetworkAttachedDocumentContainerTests.cs

The NetworkAttachedDocumentContainer is calling the PartitionKeyRangeCache refresh with the collection route instead of the collection ResourceId. This breaks cache refresh logic in Gateway mode.
Example of exception message:
BadRequest (400); Substatus: 0; ActivityId: 89fa45ee-30a5-44b4-92aa-a6b0872f9e85; Reason: (Failed to parse the value 'dbs/testdb/colls/testContainer' as ResourceId.
Introduced in 3.14.0 from PR #1812

Query: Fixes BadRequest with "Failed to parse ... as ResourceId" for gateway mode on splits

---

Directory.Build.props
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TransportWrapperTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/TraceWriterBaselineTests.TraceData.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Tracing/TraceWriterBaselineTests.cs

Direct: Adds direct package 3.18.0 and backend latency to diagnostic

---

Microsoft.Azure.Cosmos/src/Handler/AbstractRetryHandler.cs
Microsoft.Azure.Cosmos/src/Handler/RequestHandler.cs
Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
Microsoft.Azure.Cosmos/src/Handler/RouterHandler.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.BatchOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.BulkOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ChangeFeedAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.MiscellanousAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.PointOperationsExceptionsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.QueryAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ReadFeedAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.StreamPointOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.TypedPointOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/EndToEndTraceWriterBaselineTests.cs

1. Removes an unnecessary ITrace 
2. Fixes the nesting by resetting the request.Trace back to the original one the handler got. The previous logic left the request always at the child even after the child/transport handler before it was done. This caused the nesting to happen on the child trace rather than the correct parent trace.
3. Fixed the handler naming
4. Added tests to verify the handler name matches the latency
Regression introduced in 3.17.0 from PR #2097
To …

CosmosDiagnostics: Fixes invalid nesting and handler names in ITrace

---

Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimatorCore.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimatorIterator.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimatorRunner.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedProcessing/FeedEstimatorRunner.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseStoreManagerBuilder.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/EstimatorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/ChangeFeedEstimatorIteratorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/FeedEstimatorRunnerTests.cs

#1830 introduced a regression on the refactoring of the Change Feed Estimator push model, where cases where the monitored or lease container did not exist were not throwing on StartAsync but rather failed and were captured during the initialization task and only surfaced when trying to StopAsync.
This PR fixes the scenario by moving the initialization back to the StartAsync flow and before the runner task is initiated.
Also improving performance by using the Cached Container Properties when initializing the lease store manager, this way if a customer is sharing the Lease Container object across many estimators/processors, we don't do another request to fetch the Partition Key (since it cannot be changed at any point).
Closes #2389

Change Feed Estimator: Fixes exception propagation

---

Directory.Build.props
Microsoft.Azure.Cosmos/src/DocumentClient.cs
Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientSideRequestStatisticsTraceDatum.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Mocks/MockDocumentClient.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ExceptionlessTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/RequestEventHandlerTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/StoreReaderTest.cs

1. Bump direct version from 3.18.0 to 3.19.0
2. wire up new API change for StoreReader and StoreReaderTest
3. wire up new API change for adding rntbdMaxConcurrentOpeningConnectionCount
Adds:
* Improved allocations on Direct/TCP
Fixes:
* Fixed race condition in direct + tcp mode causing SDK generated internal server errors and invalid operation exceptions 
* Fixed race condition in direct + tcp mode causing unnecessary connections to be created by concurrent requests 
closes https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2370

Direct: Adds direct version 3.19 which includes improvements and fixes

---

Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/MdeEncryptionTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Fluent/ContainerSettingsTests.cs

This is to unblock the gate from known regressions from adding new restrictions in the latest emulator. These tests will be fixed in a future PR. 

[Internal] Tests: Fixes adding ignore flag to failing tests from new emulator 

---

Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Bootstrapping/PartitionSynchronizerCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/PartitionSynchronizerCoreTests.cs

The current logic forces a cache refresh for each change feed processor. This adds additional overhead and latency. It now uses the cached value to avoid the gateway network calls. Changefeed already handles split logic if the cache is stale.

ChangeFeedProcessor: Adds optimization to use cached partition key ranges

---

Directory.Build.props

Fixes NRE happening on Connection closing/disposing.
Reference stack:
```
System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.Azure.Documents.Rntbd.Connection.Dispose()
at Microsoft.Azure.Documents.Rntbd.Dispatcher.CloseConnection()
at Microsoft.Azure.Documents.Rntbd.Dispatcher.Dispose()
at Microsoft.Azure.Documents.Rntbd.Channel.System.IDisposable.Dispose()
at Microsoft.Azure.Documents.Rntbd.LoadBalancingPartition.RequestAsync(DocumentServiceRequest request, TransportAddressUri physicalAddress, ResourceOperation resourceOperation, Guid activityId)
at Microsoft.Azure.Documents.Rntbd.TransportClient.InvokeStoreAsync(TransportAddressUri physicalAddress, ResourceOperation resourceOperation, DocumentServiceRequest request)
```

Connection: Fixes NullReference on connection disposing

---

Directory.Build.props
Microsoft.Azure.Cosmos.Encryption/changelog.md
Microsoft.Azure.Cosmos.Encryption/src/Custom/EncryptionContainer.cs
Microsoft.Azure.Cosmos.Encryption/src/EncryptionContainer.cs
Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj
Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/MdeEncryptionTests.cs

1. This PR will upgrade the dependent CosmosDB Preview Package to 3.19.0-preview.
1. Updates the Encryption preview release version to 1.0.0-previewV14 and the change log.
1. Adds implementation for new methods.
Closes #2432

Client Encryption: Adds integration with latest CosmosDb Preview Package 3.19.0-preview

---

Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj
templates/build-preview.yml

This adds a gate to prevent SDK changes that break encryption project. This way it is always safe to do an encryption release.

[Internal] Encryption project: Adds gates to prevent breaking changes

---

Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Utils/CosmosContainerExtensions.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/BaseChangeFeedClientHelper.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/BaseCosmosClientHelper.cs

When `EnableContentResponseOnWrite` is configured at the client level, it affects all operations. 
Change Feed Processor uses point create/replace to interact with the leases. 
When setting `EnableContentResponseOnWrite` to `false` at the client level, all lease interactions were failing.
This PR changes the interactions so we just use the input (body) for the write operation in the `ItemResponse` because really that is the same as what we would've gotten from the response if it had body, and applies the optimization to always mark `EnableContentResponseOnWrite` as `false` at the request level. So even if the customer is not setting the client-level flag, lease store interactions are optimized.
It also adjusts the Change Feed tests to execute with this client-level setting as `false` so …

Change Feed Processor: Fixes initialization when client is set with EnableContentResponseOnWrite

---

Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/OrderBy/OrderByCrossPartitionQueryPipelineStage.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/OrderByCrossPartitionQueryPipelineStageTests.cs

Currently we throw a NotImplementedException in OrderByCrossPartitionQueryPipelineStage if the continuation token contains any of the extended types like CosmosBinary and CosmosGuid. This visitor that throws was added so that we correctly handle continuation from undefined values. This change will cause us to use a coarse grained IS_DEFINED filter if we encounter these extended types instead of throwing. Currently, the extended types are only used by Cassandra which is schematized, so this should not have a performance penalty. We can look into adding more system functions like IS_BINARY etc. if we decide to expose these types through the SQL api.

Query: Fixes NotImplementedException in OrderByCrossPartitionQueryPipelineStage

---

Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
Microsoft.Azure.Cosmos/src/DocumentClient.cs
Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
Microsoft.Azure.Cosmos/src/Routing/IGlobalEndpointManager.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CancellationTokenTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GlobalEndpointManagerTest.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/LocationCacheTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyRangeFailoverTests/GlobalPartitionEndpointManagerTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyRangeFailoverTests/MockSetupsHelper.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyRangeFailoverTests/RegionFailoverTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Utils/MockDocumentClient.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Utils/ToDoActivity.cs

The previous behavior would not refresh the account information if there was a gateway outage, and it would depend on the background refresh to update the information. The background refresh can take up to 5 minutes before detecting a change.
1. HttpRequestExceptions will trigger an account refresh every 15 seconds. A config was added to override the minimum time between refreshes.
2. Account refresh will be a no-op if a different thread is already updating the information
3. Updated the traces to include the name to make it easier to discover
4. GlobalEndpointManager is refactored to use 2 methods instead of different overloads on 1 method. This makes it clear that 1 method loads the account information and starts the background refresh. The other is forcing a refresh outside the …

Availability: Fixes account refresh logic on gateway outage

---

Microsoft.Azure.Cosmos/src/Batch/BatchAsyncBatcher.cs
Microsoft.Azure.Cosmos/src/Batch/BatchAsyncContainerExecutor.cs
Microsoft.Azure.Cosmos/src/Batch/ItemBatchOperationContext.cs
Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
Microsoft.Azure.Cosmos/src/Tracing/ITrace.cs
Microsoft.Azure.Cosmos/src/Tracing/NoOpTrace.cs
Microsoft.Azure.Cosmos/src/Tracing/Trace.cs
Microsoft.Azure.Cosmos/src/Tracing/TraceJoiner.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.BulkOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/BatchAsyncContainerExecutorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/EndToEndTraceWriterBaselineTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncBatcherTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncContainerExecutorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncOperationContextTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncStreamerTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosItemUnitTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Tracing/TraceTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Tracing/TraceWriterBaselineTests.cs

After https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2097 the diagnostics for Bulk operations have been incomplete and missing retry information.
The first scenario (incomplete) is due to the root trace being created on the Context level not being properly wired down into the Bulk pipeline, so we were missing things like item serialization, or anything happening previous to the actual Network call.
For example, the current traces would show:
```
├── Batch Dispatch Async(00000000-0000-0000-0000-000000000000)  Batch-Component  MemberName@FilePath:42  12:00:00:000  0.00 milliseconds  
│   │   (
│   │       [Client Configuration]
│   │       Redacted To Not Change The Baselines From Run To Run
│   │   )
│   ├── Using Wait(00000000-0000-0000-0000-000000000000)  Batch-Component …
```

Bulk: Fixes diagnostic traces by removing redundant info and adding correct retry context

---

Microsoft.Azure.Cosmos/src/Resource/Permission/Permission.cs

ResourceToken has a minimum expiry period of 10 minutes (or 600 seconds). In the current code documentation, it is captured as 10 seconds, which is not in parity with CosmosDB limits. Aim of the change, is to update the correct range in code documentation.
Supporting detail for 10 minutes:
1. https://github.com/Azure/azure-sdk-for-js/issues/10077
2. https://docs.microsoft.com/en-us/azure/cosmos-db/concepts-limits#per-request-limits
- [Non Breaking] Documentation update

Permission: Fixes documentation on resource token range limits

---

Directory.Build.props
Microsoft.Azure.Cosmos.Encryption/changelog.md
Microsoft.Azure.Cosmos.Encryption/src/Constants.cs
Microsoft.Azure.Cosmos.Encryption/src/EncryptionSettings.cs
Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj
Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/MdeEncryptionTests.cs

This PR integrates the encryption package with the latest CosmosDb preview package and adds a check for Client Encryption
Policy format version.

Client Encryption: Adds integration with latest CosmosDb package 3.19.0-preview1 and check for Client Encryption Policy format version.

---

Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
Microsoft.Azure.Cosmos/src/UserAgentContainer.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/UserAgentTests.cs

Do to recent outages and customer issues a flag is being added to the user agent to show if a client is properly configure to failover to new region in the case of a region outage.
D - Endpoint discovery disabled
S - Single application region is configured
L - List of regions specified
N - No regions specified
Default:
`cosmos-netstandard-sdk/3.18.0|3.19.1|02|X64|Microsoft Windows 10.0.19043 |.NET Core 4.6.30015.01|N|`
Endpoint discovery disabled with no region specified
`cosmos-netstandard-sdk/3.18.0|3.19.1|05|X64|Microsoft Windows 10.0.19043 |.NET Core 4.6.30015.01|DN|`
Endpoint discovery disabled with application region set
`cosmos-netstandard-sdk/3.18.0|3.19.1|05|X64|Microsoft Windows 10.0.19043 |.NET Core 4.6.30015.01|DS|`
Endpoint discovery enabled with application region set …

UserAgent: Adds flag to user agent to show if region failover is configured

---

Microsoft.Azure.Cosmos/src/CosmosClient.cs
Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/TraceWriterBaselineTests.ScenariosAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json

This change the Azure Active Directory APIs to the GA SDK.

Azure Active Directory: Adds CosmosClient TokenCredential APIs to GA SDK

---

Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedIteratorCore.cs
Microsoft.Azure.Cosmos/src/ChangeFeed/Pagination/CrossPartitionChangeFeedAsyncEnumerator.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/FeedToken/ChangeFeedIteratorCoreTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/FeedRange/ChangeFeedIteratorCoreTests.cs

After the refactoring in #1933, the user CancellationToken on ReadNexAsync is not flowing into the pipeline.
The current nested Enumerator design requires enumerators to pass down the CancellationToken through calls to `SetCancellationToken` to the next Enumerator.
Since the Enumerators are following the `IAsyncEnumerator` API, it does not pass a CancellationToken on the `MoveNext` API call.
The `CrossPartitionChangeFeedAsyncEnumerator` was missing the `SetCancellationToken` implementation required to pass down the token.
This PR fixes the `ChangeFeedIteratorCore` to invoke the `CrossPartitionChangeFeedAsyncEnumerator.SetCancellationToken` to pass the token, if any, down the pipeline. 
Closes #2478

Change Feed: Fixes CancellationToken support on ChangeFeedIterator

---

Microsoft.Azure.Cosmos/src/Tracing/TraceData/ConsistencyConfig.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientConfigurationDiagnosticTest.cs

When serializing ConsistencyConfig class, if the user is not setting the ConsistencyLevel, we defaulted it to Strong. This PR adds "NotSet" to such cases.

Diagnostics: Fixes default setting in Consistency Config Serialization

---

Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLease.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseCheckpointerCore.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseCore.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseCoreEpk.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseManagerCosmos.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseStoreCosmos.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseStoreManagerBuilder.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/PartitionedByIdCollectionRequestOptionsFactory.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/PartitionedByPartitionKeyCollectionRequestOptionsFactory.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/RequestOptionsFactory.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/BaseChangeFeedClientHelper.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/GremlinSmokeTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/SmokeTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentServiceLeaseManagerCosmosTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentServiceLeaseStoreManagerBuilderTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentServiceLeaseTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/RequestOptionsFactoryTests.cs

Graph API accounts are allowed to perform operations through the SQL API and as such, can also read the Change Feed.
Change Feed Processor uses a Lease Container that has, by default, a Partition Key Definition of `/id` . But `/id` is not allowed in Graph API accounts, so Graph API users could not leverage Change Feed Processor even though they could do any SQL API operation.
https://github.com/Azure/azure-documentdb-changefeedprocessor-dotnet/pull/158 added Graph API support to the V2 Change Feed Processor.
This PR aims to port the same capability to V3 SDK to allow for users to migrate from V2 to V3 without any blocking issues.
The PR does not modify the public surface but just enables users to use Lease Containers that are partitioned by `/id` (current behavior) or partitioned by …

Change Feed Processor: Adds support for Graph API accounts

---

Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs

This was introduced in PR #2165
The issue is when one client deletes and recreates a container, any request on another client gives a NullReferenceException.

Gateway: Fixes container recreate scenarios for Gateway Mode in session consistency

---

Microsoft.Azure.Cosmos/src/Pagination/CrossPartitionRangePageAsyncEnumerator.cs
Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/OrderBy/OrderByCrossPartitionQueryPipelineStage.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/TraceWriterBaselineTests.ScenariosAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/CrossPartitionPartitionRangeEnumeratorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/InMemoryContainer.cs

The `CrossPartitionRangePageAsyncEnumerator` when facing a merge, was adding the merge result as part of the list of Enumerators, instead of maintaining the current Range and draining it.
In this sample scenario, let's assume a 2 partition collection (partition A and B).
When the query pipeline starts, it generates a queue with 2 enumerators, one for A, one for B. Assume each partition has 10 documents.
Assume we fetch the first page which contains 10 documents from A, which returns a ContinuationToken like:
`{token: null, range {B}}`
Which normally would make the query continue with B and drain it.
If there is a merge and A and B merge into C (with C having all the 20 documents), the current logic adds a new enumerator for C in the queue copying the continuation from the parent (B), so …

Query: Fixes handling of pipeline execution on partition merge

---

Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/MdeEncryptionTests.cs
Microsoft.Azure.Cosmos/src/Pagination/CrossPartitionRangePageAsyncEnumerator.cs
Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/OrderBy/OrderByCrossPartitionQueryPipelineStage.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Fluent/ContainerSettingsTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TestCommon.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/TraceWriterBaselineTests.ScenariosAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/CrossPartitionPartitionRangeEnumeratorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/FlakyDocumentContainer.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/InMemoryContainer.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/FullPipelineTests.cs

Cherry-pick of:
#2510
#2531
Into 3.18.0-preview release branch

3.18.1-preview: Adds release notes and ports hotfixes for query

---

Microsoft.Azure.Cosmos/src/Json/JsonWriter.JsonBinaryWriter.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonRoundtripTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Microsoft.Azure.Cosmos.Tests.csproj

JsonBinaryWriter was writing four byte offsets as IEEE 754 floats instead of simple ints. This was due to a missing cast in the writer.

[INTERNAL] Query: Fixes corruption in JsonBinaryWriter while writing four byte offsets for shared strings

---

Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/README.md
Microsoft.Azure.Cosmos/src/Resource/Settings/IncludedPath.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosContainerSettingsTests.cs

IsFullIndex was introduced to the IncludedPath, which is only used for Collection column types. The previous implementation was to make the IncludedPath unsealed and we added InteropIncludedPath class. ref: https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2059.
That approach works for creating full collection column index, but fails when we need to update container properties containing full collection index.
That is because when Compute service reads the Container Properties back from backend, the deserialization code uses IndexPolicy which references IncludedPath. As a result, after reading from backend response, we lose the content of IsFullIndex, and when we update ContainerProperties, backend is expecting IsFullIndex flag but missing.
The correct way of handling it is to expose …

[INTERNAL] IncludedPath: Adds IsFullIndex for compute

---

Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientSideRequestStatisticsTraceDatum.cs
Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceJsonWriter.cs
Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceTextWriter.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/GatewayClientSideRequestStatsTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/TraceWriterBaselineTests.TraceData.xml

This PR replaces the EndTimeUtc with a Duration field in HttpResponseStats, which makes it easier to read.

Diagnostics: Adds Duration field to HttpResponseStatistics in Diagnostics

---

Microsoft.Azure.Cosmos/src/ReadManyQueryHelper.cs
Microsoft.Azure.Cosmos/src/ReadManyRequestOptions.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosReadManyItemsTests.cs

1. Fixes custom headers via AddRequestHeaders in ReadManyRequestOptions
2. Fixes the ResponseMessage in failure scenarios to have the exception and headers.

ReadMany: Fixes AddRequestHeaders request option and missing headers and message on failure scenarios.

---

Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/Fx/CosmosDiagnosticsLogger.cs

The v2 SDK does not have a Cosmos Diagnostics so it causes a null reference exception. This fixes the null reference exception be simply not logging the CosmosDiagnostics for the v2 SDK.

Benchmark: Fixes null reference exception when executing v2 SDK

---

Microsoft.Azure.Cosmos/src/Batch/BatchAsyncContainerExecutor.cs
Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
Microsoft.Azure.Cosmos/src/CosmosClient.cs
Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
Microsoft.Azure.Cosmos/src/UserAgentContainer.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/HeadersValidationTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/UserAgentTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncContainerExecutorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayAddressCacheTests.cs

Issue introduced in #2552
The cap on the ClientId was removed in the above PR, as a result there was a increase in size of the Kusto tables.
The ClientId is also being made thread safe by introducing a clientId ref for every CosmosClient instance

UserAgent: Fixes race condition in ClientId and max value for UserAgentString

---

Directory.Build.props
Microsoft.Azure.Cosmos.Encryption/src/Custom/DecryptableFeedResponse.cs
Microsoft.Azure.Cosmos.Encryption/src/Custom/EncryptionContainer.cs
Microsoft.Azure.Cosmos.Encryption/src/EncryptionContainer.cs
Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj
Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/LegacyEncryptionTests.cs
Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/MdeCustomEncryptionTests.cs
Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/MdeEncryptionTests.cs

https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2499 introduced a behavior change for Change Feed responses where exceptions are no longer thrown.
The Encryption package runs on top of these responses and had logic that was throwing on NotModified still.
The PR bumps the Encryption package version and increases the dependency to 3.20.0.

[Encryption] Change Feed: Fixes change feed decryptableresponse to not throw exceptions on NotModified

---

Microsoft.Azure.Cosmos/src/Query/v3Query/QueryDefinition.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemLinqTests.cs

This fixes ArguementNullException in ToQueryDefinition for read feed scenarios where there has been no filters applied to the linq query.
To automatically close an issue: closes #1438

LINQ : Fixes ArgumentNullException while calling ToQueryDefinition()

---

Microsoft.Azure.Cosmos/src/DocumentClient.cs
Microsoft.Azure.Cosmos/src/Query/v2Query/PartitionKeyRangeGoneRetryPolicy.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyRangeHandlerTests.cs

DocumentClient and PartitionKeyRangeGoneRetryPolicy were hardcoding the trace to NoOpTrace.Singleton. allow consumers to pass in a real trace instead.

[INTERNAL] Diagnostics: Adds ITrace overload to ProcessRequestAsync to get trace for a collection and PKRange refresh calls

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/AggregateQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/OrderByQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/SanityQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/SkipTakeQueryTests.cs

Add coverage for gateway mode in the emulator tests for query. This will be used in the Compute test pipelines as well.

[Internal] Query: Adds coverage for gateway mode to the query emulator tests

---

Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Utils/CosmosContainerExtensions.cs
Microsoft.Azure.Cosmos/src/Linq/CosmosLinqExtensions.cs
Microsoft.Azure.Cosmos/src/Linq/CosmosLinqQuery.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ItemResponse.cs
Microsoft.Azure.Cosmos/src/Resource/CosmosResponseFactoryCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosJsonSeriliazerUnitTests.cs

Use Diagnostics instead of Trace while creating ItemResponse from ResponseMessage. The other methods in the ResponseFactory are using Diagnostics except for the this one CreateItemResponse method.

[PREVIEW] Diagnostics : Fixes CosmosResponseFactory.CreateItemResponse to use ResponseMessage.Diagnostics instead of creating a new instance

---

Microsoft.Azure.Cosmos/src/Query/v2Query/DefaultDocumentQueryExecutionContext.cs
Microsoft.Azure.Cosmos/src/Routing/PartitionRoutingHelper.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/QueryPlanBaselineTests.Negative.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/FullPipelineTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPlanBaselineTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Routing/PartitionRoutingHelperTest.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Tracing/TraceWriterBaselineTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Utils/QueryPartitionProviderTestInstance.cs

Currently PartitionRoutingHelper.GetProvidedPartitionKeyRanges does not correctly set the substatus code for group by queries. This change also exposes allowNonValueAggregates as a parameter in this method, whereas it was previously hardcoded to false. This meant that Non value aggregate queries would not get back a proper substatus code either. This new parameter will be used by the Compute Gateway.
Other SDKs are supposed to use this substatus code to fetch a query plan. In the absence of this, certain hacks have been put into the NodeJS SDk for example where they check if the error text contains certain strings. as we move from Routing gateway to compute Gateway, some of these strings may change since the v3 sdk has slightly different code paths from the v2 sdk and it also localizes …

Query: Fixes substatus code for GROUP BY queries in PartitionRoutingHelper

---

Microsoft.Azure.Cosmos/src/RequestOptions/ChangeFeedRequestOptions.cs

This PR updates the intellisense documentation to cover scenarios where the volume of items could be higher than the hint.
Closes #2644

[Documentation] Change Feed: Fixes remark on page size hint

---

Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosOperationCanceledException.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CancellationTokenTests.cs

internal CosmosOperationCanceledException constructor lost cancellationToken of original exception

OperationCanceledException: Fixes lost CancellationToken on CosmosOperationCanceledException 

---

changelog.md

The wrong status code was put in the changelog. This is fixing the changelog to use 403 instead of 401.
To automatically close an issue: closes #2658

Changelog: Fixes status code for 2511

---

Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryFeature.cs
Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPlanRetriever.cs
Microsoft.Azure.Cosmos/src/Routing/PartitionRoutingHelper.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/DistinctQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Routing/PartitionRoutingHelperTest.cs

1. DCount has special logic that doesn't block the query unless the flag is set to false. The flag missing will not block the query. This is necessary to avoid any breaking changes where the old SDKs did not set the flag.
2.  The PartitionRoutingHelper is only used by compute and not by any of the v3 query code.
3.  Adding the query plan info to the additional info is for back compatibility with the old SDKs that do the try execute instead of the get query plan call.

[INTERNAL] Query: Adds additional error info on unsupported cross partition queries for compute paths

---

Microsoft.Azure.Cosmos.Samples/Usage/AzureFunctions/AzureFunctions.csproj
Microsoft.Azure.Cosmos.Samples/Usage/AzureFunctions/Startup.cs
azure-pipelines.yml
templates/build-samples.yml

CI was not validating Usages building and there was an older Functions reference that stopped building at some point.
The PR fixes the reference and also makes sure the Samples build is gated.
Closes #2699

Samples: Fixes samples references and adds CI validation

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/BatchSinglePartitionKeyTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/CosmosItemBulkTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosContainerTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosThroughputTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/FeedToken/ReadFeedTokenTests.cs

1. If the CreateContainerAsync fails the container delete operation throws an exception causing the test to hide the original exception.
2. Applied several Visual Studio suggestions about code formatting

[INTERNAL] EmulatorTests: Fixes tests to use DeleteStreamAsync to avoid throwing on test cleanup

---

Microsoft.Azure.Cosmos/src/Handler/ClientPipelineBuilder.cs
Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryHelper.cs
Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryOptions.cs
Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProperties.cs
Microsoft.Azure.Cosmos/src/Telemetry/MetricInfo.cs
Microsoft.Azure.Cosmos/src/Telemetry/OperationInfo.cs
Microsoft.Azure.Cosmos/src/Telemetry/SystemInfo.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ClientTelemetryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/HandlerTests.cs

This PR has following changes:
1. Improved precision of all the metrics:
So we are collecting different kind of metrics, Somewhere using conversion as a precision factor and if value needs not to be converted then using HistogramPrecisionfactor to preserve data precision.
2. Move telemetry handler before retry handler:
Telemetry should be collected from the toppest layer of the operation.
3. Test cases improvement : 
There were chances that test cases started failing due to thread starvation or related issues. So added waiting till 30 sec.
4. Upper Case Connection Mode and Consistency : Just like Java 

Client Telemetry : Fixes data precision and telemetry handler position

---

Directory.Build.props
Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryHelper.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DirectContractTests.cs

This bump includes:
* Security: Fixed ServiceInterop.dll to be BinSkim compliant by adding /guard /Qspectre flags
* Diagnostics: Fixed memory consumption metric in Linux to match Windows unit
Closes #1724

Security: Fixes ServiceInterop.dll to be BinSkim compliant by adding /guard /Qspectre flags

---

Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/OrderBy/OrderByQueryPartitionRangePageAsyncEnumerator.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/BufferedPartitionRangeEnumeratorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/CrossPartitionPartitionRangeEnumeratorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/InMemoryContainer.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/PartitionRangeEnumeratorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/SinglePartitionPartitionRangeEnumeratorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OrderByQueryPartitionRangePageAsyncEnumeratorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPartitionRangePageEnumeratorTests.cs

I expect OperationCancelledException not AggregateException If operation is cancelled
- use GetAwaiter() to avoid AggregateException
- pass CancellationToken to Continue to avoid start continuation if not needed
- fix typo

Query: Fixes order by logic to throw original exception instead of AggregateException

---

Directory.Build.props
Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj
Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/Microsoft.Azure.Cosmos.Encryption.EmulatorTests.csproj
Microsoft.Azure.Cosmos.Encryption/tests/Microsoft.Azure.Cosmos.Encryption.Tests/Microsoft.Azure.Cosmos.Encryption.Tests.csproj
Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/CosmosBenchmark.csproj
Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Microsoft.Azure.Cosmos.Performance.Tests.csproj
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Microsoft.Azure.Cosmos.Tests.csproj

This is bumping the C# language version to 9. This matches the internal Cosmos DB projects.
C# 9.0 features:
https://docs.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-9

[INTERNAL] C# LangVersion: Adds version 9 to all projects

---

Microsoft.Azure.Cosmos.Samples/Usage/ChangeFeed/Program.cs

Now that 3.21.0 is out, update the samples to use the more detailed delegate.

Samples: Adds Change Feed Processor delegate context usage

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/FeedToken/ChangeFeedIteratorCoreTests.cs

Add tests for emulator change feed fix. 
1. Validates Incremental Change Feed by inserting and deleting documents and verifying nothing reported
2. Validates error message with Full Fidelity Change Feed and start from beginning.
To automatically close an issue: closes #2194

[Internal] Change Feed: Adds emulator tests

---

Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchOperationResult.cs
Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchResponse.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/CosmosItemBulkTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchOperationResultTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchSchemaTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/PartitionKeyRangeBatchExecutionResultTests.cs

Bulk operations, when un-packed from the Bulk response, were not wiring the Session Token and ActivityId into the respective resulting operations.
All the operations included in a Bulk response contain the same Session Token and ActivityId as they were all committed in the same transaction.
Closes #2738

Bulk: Adds SessionToken and ActivityId to item responses

---

Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedPullScenario.cs
Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/QueryScenario.cs

The new Change Feed Pull scenario and Query scenario were creating containers but not cleaning them up afterwards. 
This made it so the first run would work, but a next run would fail because the container already existed, we would populate the container again and then the comparison with the results would fail:
1. Create container
2. Populate X documents
3. Run queries, results Y match X
4. Run the workload again
5. Populate X documents (now container has 2X)
6. Run queries, results Y does not match X (it matches 2X)
Finally, the Query workload was not gating the volume of operations on concurrency configuration, we should honor concurrency to avoid hitting 429s.

[Internal] CTL: Fixes container lifetime and parallelism on Query scenario

---

Microsoft.Azure.Cosmos/src/Batch/BatchAsyncContainerExecutor.cs
Microsoft.Azure.Cosmos/src/ClientResources.Designer.cs
Microsoft.Azure.Cosmos/src/ClientResources.resx
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/BatchAsyncContainerExecutorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/CosmosItemBulkTests.cs

Bulk operations by design do not map 1:1 to network operations. `ItemRequestOptions.Properties` does not flow to the actual network requests Properties, and we should be validating that to avoid wrong expectations, just like we validate other attributes on ItemRequestOptions.
Closes #2741

Bulk: Adds validation for ItemRequestOptions.Properties

---

Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs

Updates the docs on `ApplicationRegion` and `ApplicationPreferredRegions`, clarifying fallbacks and linking to more in-depth docs.
Closes #2733.

Documentation: Fixes ApplicationRegion comments and links for region settings in CosmosClientOptions.

---

Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientSideRequestStatisticsTraceDatum.cs

Fixes a null reference for internal teams using the SDK. Internal teams do not want to collect system usage.

[INTERNAL] ClientSideRequestStatisticsTraceDatum: Fixes system usage causing null reference on INTERNAL build

---

Microsoft.Azure.Cosmos/src/Handler/TelemetryHandler.cs
Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryHelper.cs
Microsoft.Azure.Cosmos/src/Telemetry/OperationInfo.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryTests.cs

1. Right now, if user is not sending consistency level in the request but sending request option with other configuration. Telemetry is logging Consistency level as "Strong" which is wrong. So fixing it as part of this PR.
2. Optimizing getting consistency level information in telemetry by removing blocking call.
3. Add consistency related tests in client telemetry.
4. Making sure that if user is not passing consistency level (in request or client), it will be stored as NULL in telemetry data.

Client Telemetry: Fixes consistency level issue

---

Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs

Invalid Trailing Semicolon (Reported over here - https://github.com/Azure/azure-sdk-for-net/issues/24381)
Fixes documentation syntax in ContainerProperties examples
Closes #2770

Documentation: Fixes syntax in ContainerProperties example

---

Microsoft.Azure.Cosmos.Samples/Usage/PowerShellRestApi/PowerShellScripts/MigrateToAnalyticalStore.ps1

Change default polling interval to 60 seconds as per customer 

[Internal] MigrateToAnalyticalStore: Fixes script to use default polling interval to 60 seconds

---

azure-pipelines.yml

It appears that Azure DevOps no longer supports the wild card /*.  It has been this way since 2018. My only guess is there was some breaking change done on Azure DevOps side.
I updated it to use the wild card I found in the documentation which now causes the gates to trigger correctly.
- '*'  # must quote since "*" is a YAML reserved character; we want a string
https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#branches
To …

[INTERNAL] Pipeline: Fixes PR triggers

---

Microsoft.Azure.Cosmos.Samples/Tools/CTL/CTLOperationHandler.cs
Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ReadWriteQueryScenario.cs
Microsoft.Azure.Cosmos/src/Diagnostics/CosmosTraceDiagnostics.cs
Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs

This logs all diagnostics that hit a 410 gone exception. This will allow us to better determine how many requests hit a 410 and how long it took the request to complete.

[INTERNAL] CTL: Adds diagnostic logging if request hit a 410 gone exceptions

---

Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Exceptions/ChangeFeedProcessorUserException.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json

https://github.com/Azure/azure-cosmos-dotnet-v3/pull/2787 missed adding `ChangeFeedProcessorUserException` to the GA package.
This type is useful to distinguish internal from user-related errors when creating on error notifications:
```
var notifyErrorAsync = (string LeaseToken, Exception exception) =>
{
if (exception is ChangeFeedProcessorUserException userException)
{
Console.WriteLine($"Lease {LeaseToken} processing failed with unhandled exception {userException.InnerException}");
Console.WriteLine($"Diagnostics {userException.ExceptionContext.Diagnostics}");
Console.WriteLine($"Headers {userException.ExceptionContext.Headers}");
}
else
{
// This could be matched for CosmosException to decide importance based in our guidelines
Console.WriteLine($"Lease {LeaseToken} failed with …
```

ChangeFeedProcessor: Adds ChangeFeedProcessorUserException for detailed error notification

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Contracts/PerformanceValidation.cs

Disabling performance test from the gates as they are broken.
There was fluctuation in numbers upto 25%. Tried below things:
1. Fix it by upgrading benchmarknotnet but it didn't work.
2. Different combinations of run strategies like medium with 2 iteration, medim wit 3 iteration, short with 2 iteration, short with 3 iteration, Custom launchcount, Warmupcount and Iteration Count
Assumption is, something is changed in the machine where these tests runs (because we didn't make any code changes recently in this project).
So as of now planning to disable it to unblock the gates.

[Internal] Performance Test: Removes performance test from the gates temporarily

---

Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProperties.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ClientTelemetryTests.cs

Adding _aggregationIntervalInSec_ column in client telemetry payload which gives configured Aggregation interval in second.

Client Telemetry: Adds aggregationIntervalInSec Information

---

Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/SkipEmptyPageQueryPipelineStage.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/SkipEmptyPageQueryPipelineStageTests.cs

The current implementation of SkipEmptyPageQueryPipelineStage.MoveNextAsync recursively calls itself if the previous pipeline stage emits an empty page. This leads to stack overflow if there are too many empty pages or if an inner pipeline stage throws from a deeply nested stack. This change refactors the implementation to be iterative rather than recursive and adds unit tests for SkipEmptyPageQueryPipelineStage which previously had none.

Query: Fixes stack overflow in SkipEmptyPageQueryPipelineStage

---

Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedPullScenario.cs
Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/QueryScenario.cs
Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ReadManyScenario.cs
Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ReadWriteQueryScenario.cs
Microsoft.Azure.Cosmos.Samples/Tools/CTL/Utils.cs

Adding 410 logging for query, changefeed pull, and read many scenarios. Moved the logic to Util to make it common across all the operations.

[INTERNAL] CTL: Adds 410 logging to other operations

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.PointOperationsExceptionsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/EndToEndTraceWriterBaselineTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TransportClientHelper.cs

The following diagnostics is from the 3.18.1 SDK. This hit an exception which seems to have cause the diagnostics to be improperly nested. The "Microsoft.Azure.Documents.ServerStoreModel Transport Request" should be at the same level but are some how nested. This needs to be root caused and fixed if it hasn't already been fixed in the latest SDK version.
Added Point Operation With Service Unavailable Exception and verified the output json in test method. Now its generating ServerStoreModel  once . There was no nesting issue found.
To automatically close an issue: closes #2809

[Internal] Diagnostics: Adds test for Point Operation With Service Unavailable Exception

---

Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/BenchmarkConfig.cs

Right now, Client Telemetry can be only Enabled or disabled in Performance tests. This PR will give flexibility to pass other configurations related to telemetry i.e ScheduledTimeInSec and EndPointURL
I was able to see data in  ClientRequest table

[Internal] Benchmark: Adds options for ClientTelemetry TelemetryEndpoint and TelemetryScheduleInSec

---

changelog.md

2796 did not actually bump the direct version bump. The linux keep alive was not included until the 3.22.1 release. 

Changelog: Fixes the linux keep a live version

---

Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs

Closes https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2595
Remarks talks about querying with id - there is no id parameter in the method, seems to be a remark whether to use CosmosClient.GetDatabaseQueryIterator or not.
It's not obvious from the documentation why you would use this method at all, since you already have a reference to the database - the sample which show it's use starts with database, then gets another reference to the database from the result, which doesn't seem to do anything useful as you already had a reference to the database.
Removed Remarks from the method  in the comment section.

Documentation: Invalid remark

---

Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/BenchmarkConfig.cs
Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/README.md
Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/RunSummary.cs

It has below changes:
1.  Adds ability to override workloadtype name in the results.: Today if We run same workload with diff configs, it will have same name always.
After this PR, there will be ability to override this name (if you want to)
2. In case of error, it will show all the options available.
After the change, on running a workload with custom name : 
`dotnet run -c Debug --no-build -- -w ReadTExistsV3 -e <cosmosdb account>-k <key> -n 20000 -t 1000000 --workloadname myworkload`

Benchmark : Adds an option to override workloadName 

---

Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/loop.sh
Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/run.sh

This PR adds a loop.sh which is used to update to the latest git commit and execute the run.sh. 
The run.sh script is updated to add scenarios for client telemetry and to make query operations optional. This is necessary because query runs take too long to be included in every run. 

Benchmark: Adds loop script and update run.sh

---

Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs

Closes  https://github.com/Azure/azure-cosmos-dotnet-v3/issues/2520
The code for the example should compile, possible the return type should be `FeedIterator<Book>`. Please verify if the example code compiles.
Change in the Linq query return type should be FeedIterator<Book> to avoid compilation error.

Documentation: Fixes  Error in LINQ

---

Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/BenchmarkConfig.cs
Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/run.sh

1. The query and read feed operations are getting throttled on a 100k RU container. To reduce the number of throttles the concurrency is being reduced. 
2. Fixed a bug in the run.sh where there was an extra $ causing query operations to not run
3. Added the workload name to user agent prefix to make it possible in the backend logs to easily see the different runs.

Benchmark: Fixes throttles, run.sh script, adds unique useragent strings

---

Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/GatewaySessionTokenTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs

Mirror of https://github.com/Azure/azure-sdk-for-java/pull/25555
> :grey_exclamation: The scenario described here does not apply if customers are manually passing session tokens as part of the RequestOptions, it only applies when users are **not passing session tokens as input to operations**.
When a write operation is done through the SDK instance on Session consistency, the SDK stores locally the session token in a cache and also returns the token to the user. When a read operation for the same partition is done, and the user does not pass a session token in the input, we extract the session token from the cache from the write operation and pass it along.
Since the token that travels to the Gateway and is returned is scoped to a partition, the issue arises when a partition split occurs: …

Session: Fixes scoped session token on partition splits and multiple write endpoints enabled

---

Microsoft.Azure.Cosmos/src/Linq/ExpressionToSQL.cs
Microsoft.Azure.Cosmos/src/Linq/TranslationContext.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemLinqTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/ToDoActivity.cs

Uses the configured serializer settings when checking for the special cases of `Nullable<T>.Value` and `Nullable<T>.HasValue`
This allows the use of .HasValue when using camelCase serialization, as it currently translates to `["propName"]["hasValue"]` in the resultant query instead of the intended `IS_DEFINED("propName")`
Closes #2916

LINQ: Adds support for Nullable<T>.Value or Nullable<T>.HasValue when using camelCase serialization

---

Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs

On Gateway mode, if the account is Session consistency but the user is sending a request where the `ItemRequestOptions` has a ConsistencyLevel != Session, we were sending the session token anyway.
This PR makes it so the request level configuration is honored over the account level configuration **only on read requests**.

Session: Fixes token being sent if request had a different consistency level on Gateway mode

---

Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs

`CosmosClientOptions.ApplicationRegion` can be used to define where the current application is running, and the SDK will use that to populate the Preferred Regions based on geographical distance.
For supportability purposes and to provide users with more information when their configuration is invalid, this PR changes the error message produced to include the invalid value.
Since the distance calculation is done using a known list, there could also be scenarios where using a very old SDK version and a very new Azure region name would also face the error, so the message now contains that hint.
Proposed message:
```
ApplicationRegion configuration '{location}' is not a valid Azure region or the current SDK version does not recognize it. If the value represents a valid region, make sure you …
```

Supportability: Refactors error message for invalid ApplicationRegion 

---

Microsoft.Azure.Cosmos/src/Tracing/ITrace.cs
Microsoft.Azure.Cosmos/src/Tracing/NoOpTrace.cs
Microsoft.Azure.Cosmos/src/Tracing/Trace.cs
Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceJsonWriter.cs
Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceTextWriter.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.BatchOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.BulkOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ChangeFeedAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.MiscellanousAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.PointOperationsExceptionsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.QueryAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ReadFeedAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ReadManyAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.StreamPointOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.TypedPointOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/EndToEndTraceWriterBaselineTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/TraceJoiner.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/TraceWriterBaselineTests.ScenariosAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/TraceWriterBaselineTests.Serialization.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/TraceWriterBaselineTests.TraceData.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Tracing/TraceWriterBaselineTests.cs

1) The Trace library always creates a CallerInfo object. This adds overhead to both collecting the trace and the CosmosDiagnostic.ToString() logic. There has been no use case for this information so it should be removed until there is a scenario.
2) IReadOnlyDictionary should be created lazily. In most traces no data is being added. A static singleton could be used by default.
The object removed:
```
"caller info": {
"member": "OperationHelperWithRootTraceAsync",
"file": "/home/askagarw/azure-cosmos-dotnet-v3/Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs",
"line": 244
}
```
To automatically close an issue: closes #2972

CosmosDiagnostics: Removes ITrace Caller Info and makes the Dictionary for Data lazy

---

Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/BenchmarkConfig.cs
Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/CosmosBenchmark.csproj

CopyLocalLockFileAssemblies causes the .NET 6 project to fail at runtime. It throws a FileNotFoundException for the CommandLineParser assembly. Bumping the dependency to the latest version.

Benchmark: Fixes file not found from missing assembly CommandLineParser

---

Microsoft.Azure.Cosmos/src/SessionContainer.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SessionContainerTest.cs

> This PR only applies to users not passing the session token manually through the ItemRequestOptions
When the user does not pass session token but relies on the client to maintain the session, in Gateway mode, the current scoped session token logic uses the current targeted partition to send the cached token, if any.
1. Cache contains entry for Partition 1, which splits into 2 and 3
2. A request comes for Partition 2
3. We lookup the cache entry for 2, and find none, but 2 has 1 as parent, so we use the cache entry for Partition 1.
4. Response comes and we store the response's token as an entry for Partition 2.
1. Cache contains entry for Partition 1 and 2, which both merge into 3.
2. A request comes from Partition 3.
3. We lookup the cache entry for 3, and find none, following the same …

Session: Fixes Gateway session scope during merges

---

Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedEstimator.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedProcessorState.cs
Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs

Improves xmldocs around Change Feed Estimator APIs to cover that it uses transactions and not items in some cases.
Closes #2997

Documentation: Fixes change feed estimator remarks

---

Directory.Build.props
Microsoft.Azure.Cosmos/src/Regions.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/SummaryDiagnosticsTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TransportWrapperTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/TraceWriterBaselineTests.TraceData.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CancellationTokenTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosExceptionTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyRangeFailoverTests/MockSetupsHelper.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Tracing/TraceWriterBaselineTests.cs

- Sub status: Adds SDK generated substatus codes for 503's
- Diagnostics: Captures diagnostics for Splits and RequestTimeoutExcpetion
- Performance: Reduces the size of the Rntbd buffer
- Diagnostics: Adds ServiceEndpoint and Connection Stats to the diagnostics
- Availability: Direct mode removes blocking call on broken connection exception
- Availability: Fixes the SDK to ensure it does not retry on replica that previously failed with 410, 408 and >= 500 status codes
- Session: Fixes scoped session tokens on partition splits and multiple write endpoints enabled.
- DefaultTraceListener: Removes DefaultTraceListener by default unless there is a debugger attached to it.
- Diagnostics: Resetting thread starvation status once it is detected.
- Hierarchical Partitioning: Provides an EPK range …

Direct: Adds direct package version 3.24.1

---

Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryHelper.cs
Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryOptions.cs
Microsoft.Azure.Cosmos/src/Telemetry/MetricInfo.cs
Microsoft.Azure.Cosmos/src/Telemetry/SystemInfo.cs
Microsoft.Azure.Cosmos/src/Telemetry/TelemetrySystemUsage.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryTests.cs

Adding 2 new Thread Starvation metrics in client telemetry:
1. Metrics Name: SystemPool_ThreadWaitInterval
Metrics Unit: MilliSecond
It will tell about how much time a thread creation is taking.
2. Metrics Name: SystemPool_IsThreadStarving_True
Metrics Unit: Count
It will tell, how many times Thread Starvation were Detected. There is no histogram calculation involved.

Client Telemetry: Adds Thread Starvation Information

---

Microsoft.Azure.Cosmos/src/CosmosClient.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/ContractTests.cs

Changing the API version to v2019_10_14, any version greater than or equal to this will indicate to cosmos db that SDK is capable of handling partition merge. We plan to block sdks that do not have support when partitionmerge feature will be turned on in the service.

[Internal] API Version: Updates DefaultAPIVersion to v2019_10_14 to indicate merge support

---

Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs

The [`DeleteItemAsync<T>`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.deleteitemasync?view=azure-dotnet) method never returns the delete item, even when `ItemRequestOptions.EnableContentResponseOnWrite` is set to true. But the return type of the methos is `ItemResponse<T>` which could be confusing to users as pointed out [this issue](https://github.com/Azure/azure-sdk-for-net/issues/26739).
Documentation Update
resolves Azure/azure-sdk-for-net#26739

Documentation: Adds remark to clarify delete behavior

---

Microsoft.Azure.Cosmos/src/CosmosClient.cs
Microsoft.Azure.Cosmos/src/IDocumentClient.cs
Microsoft.Azure.Cosmos/src/Linq/DocumentClientQueryable.cs
Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs
Microsoft.Azure.Cosmos/src/Resource/Scripts/Scripts.cs
Microsoft.Azure.Cosmos/src/Resource/User/User.cs

The description for method overloads that accept a sql query as a `string` vs a `QueryDefinition` object are misleading for some 
as discussed in [this issue](https://github.com/Azure/azure-sdk-for-net/issues/25878).
This PR fixes them.
Documentation
resolves Azure/azure-sdk-for-net#25878

Documentation: Fixes method descriptions with sql query text vs definition

---

Microsoft.Azure.Cosmos/src/DocumentClient.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs

Adds a test based on a github issue. 
Final json after patch:
```json
{
"id": "084995b1-069b-454c-824c-9a6fbf97353e",
"taskNum": 43,
"cost": 1.7976931348623157e+308,
"pk": "TBD1c35b236-20ff-4b0d-bba8-a5aeb8f355fb",
"CamelCase": "camelCase",
"nullableInt": null,
"valid": true,
"children": [
{
"id": "child1",
"taskNum": 30,
"cost": 0,
"description": "testSet",
"pk": null,
"CamelCase": null,
"nullableInt": null,
"valid": false,
"children": null
},
{
"id": "child2",
"taskNum": 40,
"cost": 0,
"description": null,
"pk": "patched",
"CamelCase": null,
"nullableInt": null,
"valid": false,
"children": null
}
],
"_rid": "-+0VAImYn-YBAAAAAAAAAA==",
"_self": "dbs/-+0VAA==/colls/-+0VAImYn-Y=/docs/-+0VAImYn-YBAAAAAAAAAA==/",
"_etag": "\"00000000-0000-0000-1e85-1fcf800401d8\"",
"_attachments": …
```

Patch test: Adds test for set on inner array

---

Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/MdeEncryptionTests.cs
Microsoft.Azure.Cosmos/src/Resource/ClientEncryptionKey/EncryptionKeyWrapMetadata.cs
Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosDatabaseTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TestCommon.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json

Adds algorithm into the EncryptionKeyWrapMetadata to be able to save the algorithm used for key wrapping, instead of assuming a hard coded value. Saving the algorithm since it can vary is mandatory from the security perspective.

ClientEncryption: Adds algorithm to EncryptionKeyWrapMetadata

---

Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInternal.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json

Move the FeedRange API for Query to GA

Query: Adds FeedRange API for Query to GA

---

Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
Microsoft.Azure.Cosmos/src/Query/v2Query/PartitionKeyRangeGoneRetryPolicy.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
Microsoft.Azure.Cosmos/src/Routing/AddressResolver.cs
Microsoft.Azure.Cosmos/src/Routing/GlobalAddressResolver.cs
Microsoft.Azure.Cosmos/src/Routing/ICollectionRoutingMapCache.cs
Microsoft.Azure.Cosmos/src/Routing/PartitionKeyRangeCache.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/PartitionKeyRangeCacheTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Mocks/MockDocumentClient.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyRangeHandlerTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Utils/MockDocumentClient.cs

Issues being fixed:
1. The current implementation is once a refresh occurs all other requests are blocked until the refresh completes. Even if they have 1000 partitions and only 1 is splitting all 999 partitions will be blocked until the refresh completes.
2. If the refresh fails the old cache value is lost. Then the SDK has to reload the entire which cause additional load to the service on the meta data requests.
3. Removed cancellation token being passed in. Most scenario it was already set to none. The cancellation should not be passed into cache because multiple other requests are likely to be waiting on that result. If the first request cancels it would negatively impact the rest of the requests. It's better to let the cache finish then let the request fail after.
Please delete …

Availability: Adds non-blocking cache to partition key ranges

---

Microsoft.Azure.Cosmos/src/DocumentClient.cs
Microsoft.Azure.Cosmos/src/Routing/AsyncCacheNonBlocking.cs
Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
Microsoft.Azure.Cosmos/src/Routing/PartitionKeyRangeCache.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Routing/AsyncCacheNonBlockingTests.cs

Most places don't use the call back and now can be accessed with other methods. Passing in the cached value on the refresh will be used in a future PR to only do network calls if the cache is the same as it was on the request.

[Internal] AsyncCacheNonBlocking: Removes call back on force refresh

---

Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicy.cs
Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyControlPlaneRead.cs
Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyControlPlaneRetriableHotPath.cs
Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyDefault.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/PartitionKeyRangeCacheTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosHttpClientCoreTests.cs

This applies the same retry logic for a 408 from gateway that is already applied if the a timeout occurs trying to connect to the gateway. This will improve availability to customers because the SDK will not automatically retry on a timeout from gateway for metadata operation. This will only be used for cache operations where multiple requests are waiting on the result and a single timeout would result in multiple failures.

Availability: Adds retry on 408s to gateway calls for metadata operations

---

Microsoft.Azure.Cosmos/src/Handler/TransportHandler.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemSessionTokenTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TransportClientHelper.cs

`TransportHandler.ProcessUpsertAsync` was capturing session tokens even for throttled (or failed) requests. Because throttled requests (or 449/410) won't always have a PKRangeId header this resulted in session tokens for PKRangeId 0 being overridden with the session token of another partition. There is no reason to ever capture a session token on a 429, 449 or 410 - and it turned out there was also no need for the special-casing of upserts in `TransportHandler`.
So, this PR is...
- removing the special casing of upserts in `TransportHandler`
- adding regression test (`NoSessionTokenCaptureForThrottledUpsertRequestsTest` failed without the change in `TransportHandler` - now succeeds)
- adding basic coverage to ensure session tokens are captured for point operations (main validation for …

Upsert item: Fixes a bug causing session tokens for PKRangeId 0 to be overridden by session token for another partition on upserts

---

Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedManagement/PartitionControllerCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/PartitionControllerTests.cs

During lease rebalancing, multiple hosts might try to acquire the same lease. Whoever acquires it first wins and the others get a LeaseLostException.
This LeaseLostException was getting sent through the Life Cycle Notifications and bubbled up to users unnecessarily, it is not an error or a condition they need to worry or act upon, but a normal flow of events based on the CFP design.
This PR removes the noisy notification and ensures NotifyRelease is called.

Change Feed Processor: Fixes noisy error notification when lease is stolen by other host

---

Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayAddressCacheTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Utils/MockCosmosUtil.cs

If multiple requests are running it's possible that one request refreshes the cache.
Old:
```mermaid
sequenceDiagram
participant Request1
participant Request2
Request1->>GatewayAddressCache: Force refresh partition key range 0
GatewayAddressCache->>Cosmos Gateway: Get addresses for range 0
Request2->>GatewayAddressCache: Get partition key range 0
GatewayAddressCache->>Request2: Return [1,2,3,4]
Cosmos Gateway->>GatewayAddressCache: Return [1,2,3,5]
GatewayAddressCache->>Request1: Return [1,2,3,5]
Request2->>GatewayAddressCache: Force refresh partition key range 0
GatewayAddressCache->>Cosmos Gateway: Get addresses for range 0
Cosmos Gateway->>GatewayAddressCache: Return [1,2,3,5]
GatewayAddressCache->>Request2: Return [1,2,3,5]
```
New optimized:
```mermaid
sequenceDiagram
participant …
```

Availability: Adds optimization to reduce metadata calls for addresses

---

Microsoft.Azure.Cosmos/src/Resource/Settings/ContainerProperties.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs

1. Adds emulator tests to verify partition key delete operation succeeds for subpartitioned containers.
2. Adds a test to ensure Partition key delete operation fails for prefixed partitioned key.

[Internal] Subpartitioning: Adds a test to verify Partition Key delete operations for subpartitioned containers.

---

changelog.md

The 3.25.0-preview release missed the partition key delete in the changelog. The contract file shows the change. This is just fixing the changelog.
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/releases/3.25.0-preview/Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
Original PR:
https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3041

3.25.0-preview: Adds missing changelog

---

Microsoft.Azure.Cosmos/src/CosmosClient.cs
Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryTests.cs

Right now, new `Guid` has been generated in client telemetry ,every time,  client is initialized and same is getting set as `clientid`.
This PR has minor code changes to move id generation logic to the client object,, instead of generated the new one.
It is to maintain the consistency in the code.

Client Telemetry: Refactors code to generate client unique Id in CosmosClient

---

Microsoft.Azure.Cosmos.Samples/Usage/Encryption/Encryption.csproj
Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPlanRetriever.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqAggregateFunctionBaselineTests.TestAggregateAvg.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqAggregateFunctionBaselineTests.TestAggregateCount.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqAggregateFunctionBaselineTests.TestAggregateMax.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqAggregateFunctionBaselineTests.TestAggregateMin.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqAggregateFunctionBaselineTests.TestAggregateSum.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqAggregateFunctionBaselineTests.TestAny.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestDistinctTranslation.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestSelectMany.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestSimpleSubquery.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestSubquery.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqGeneralBaselineTests.TestThenByTranslation.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqSQLTranslationBaselineTest.ValidateSQLTranslation.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestSelectManyWithFilters.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestSelectTop.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqAggregateFunctionsBaselineTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/LinqTestsCommon.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPlanRetrieverTests.cs

When the SDK is on Direct mode, the SDK attempts to generate the query plan locally (see https://docs.microsoft.com/en-us/azure/cosmos-db/sql/performance-tips-query-sdk?tabs=v3&pivots=programming-language-csharp#use-local-query-plan-generation). If it detects that the query is malformed, it returns a Bad Request (HTTP 400) exception.
The problem was that the code was using Monads and throwing the Monad exception, leaving the InnerException `null` and adding a lot of Monad related information to the exception Message that was irrelevant to the users, making the discovery of the actual parsing error very difficult.
The PR maintains the Stack Trace and Diagnostics, and adds the InnerException pointing to the real error, and reduces the clutter on the Message.
**Message**
```
"Response status …
```

Query: Fixes invalid query text exception losing error details

---

Directory.Build.props
Microsoft.Azure.Cosmos/src/Headers/StoreRequestNameValueCollection.cs
Microsoft.Azure.Cosmos/src/Headers/StoreRequestNameValueCollection.tt

Changes:
784561:  Changing the header name of SDKSupportedCapabilities, as the old header was passed in from V2SDk as well

[Internal] Direct: Adds version 3.27.2

---

Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryTests.cs

Right now, client telemetry get enabled at VM level, so if there are calls to different accounts (which include non-allowed accounts). With current design, Telemetry job will keep running in background even it is failing continuously (for non-allowed accounts).
So, This PR will stop the client telemetry job after 3 continuous failures.
To automatically close an issue: closes #3157

Client Telemetry: Adds a limit on retry count of Job Failure

---

Microsoft.Azure.Cosmos/src/CosmosSqlQuerySpecJsonConverter.cs
Microsoft.Azure.Cosmos/src/Query/v3Query/QueryDefinition.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs

The query definition holds the memory stream passed in by the user (this was introduced to support query on encrypted properties). That stream is then read and disposed to send the query over the wire. The issue is the query plan will be serialized multiple times for cases like cross partition queries and for scenarios where the query plan cannot be generated locally. Reserializing the query plan seems to be by design because the query plan can rewrite the query.
The fix reads the stream upfront to a string which is stored and later passed.
To automatically close an issue: closes #3152

Query: Fixes "System.ArgumentException: Stream was not readable." when using WithParameterStream

---

Microsoft.Azure.Cosmos.Encryption/changelog.md
Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
Microsoft.Azure.Cosmos/src/Query/Core/QueryClient/CosmosQueryClient.cs
Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPartitionProvider.cs
Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPlanHandler.cs
Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPlanRetriever.cs
Microsoft.Azure.Cosmos/src/Query/v2Query/DefaultDocumentQueryExecutionContext.cs
Microsoft.Azure.Cosmos/src/Query/v2Query/DocumentQueryExecutionContextBase.cs
Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
Microsoft.Azure.Cosmos/src/Routing/PartitionRoutingHelper.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosJsonSerializerTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/ToDoActivity.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Query/ParsingBenchmark.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/PassThroughQueryBaselineTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/FullPipelineTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPlanBaselineTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPlanRetrieverTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Routing/PartitionRoutingHelperTest.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Tracing/TraceWriterBaselineTests.cs

Customer can pass a customer serializer in which can apply and data transformation necessary. For example it could convert a int or double to a string. 
Query has 3 different ways to get the query plan.
1. ServiceInterop.dll which requires Windows x64
2. Antlr parser
3. Gateway 
1. ServiceInterop.dll-> Using a random [JsonConvert ](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/c8935ac2f864fb829f5d941dda07c74aec86a677/Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPartitionProvider.cs#L169)instead of the [standard serialization contract](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/c8935ac2f864fb829f5d941dda07c74aec86a677/Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs#L123)
2. Antlr parser -> Does not take in parameters so serialization is not …

Query: Fixes query plan via service interop to use custom serializer

---

changelog.md

This is a hot fix that cherry picks changes to unblock encryption package usage of query.

3.26.2: Adds changelog for 3.26.2

---

Microsoft.Azure.Cosmos/src/EnvironmentInformation.cs
Microsoft.Azure.Cosmos/src/UserAgentContainer.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/UserAgentTests.cs

Remove direct version from user agent to as it is unnecessary. The direct version dll is copied into the nuget folder rather than being referenced as a nuget so customers can not change it.
- New feature (non-breaking change which adds functionality)
closes #3160

UserAgent: Removes direct version

---

Microsoft.Azure.Cosmos/src/ChangeFeed/Pagination/CrossPartitionChangeFeedAsyncEnumerator.cs
Microsoft.Azure.Cosmos/src/Pagination/BufferedPartitionRangePageAsyncEnumerator.cs
Microsoft.Azure.Cosmos/src/Pagination/BufferedPartitionRangePageAsyncEnumeratorBase.cs
Microsoft.Azure.Cosmos/src/Pagination/CrossPartitionRangePageAsyncEnumerator.cs
Microsoft.Azure.Cosmos/src/Pagination/FullyBufferedPartitionRangeAsyncEnumerator.cs
Microsoft.Azure.Cosmos/src/Pagination/PrefetchPolicy.cs
Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/Parallel/ParallelCrossPartitionQueryPipelineStage.cs
Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/PipelineFactory.cs
Microsoft.Azure.Cosmos/src/ReadFeed/Pagination/CrossPartitionReadFeedAsyncEnumerator.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/TraceWriterBaselineTests.ScenariosAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/BufferedPartitionRangeEnumeratorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/CrossPartitionPartitionRangeEnumeratorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/InMemoryContainer.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/PartitionRangeEnumeratorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/SinglePartitionPartitionRangeEnumeratorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OrderByQueryPartitionRangePageAsyncEnumeratorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/AggressivePrefetchPipelineTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/CrossPartitionRangePageAsyncEnumerable.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/FullPipelineTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/ParallelCrossPartitionQueryPipelineStageTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPartitionRangePageEnumeratorTests.cs

The query pipeline incorporates a Parallel Prefetch phase during its creation. After creation, the query pipeline runs sequentially.  for scalar aggregates, we can afford to aggressively prefetch all pages, since the total memory overhead of doing so is very low.
This change implements such functionality.

Query: Adds aggressive prefetching for scalar aggregates

---

Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientConfigurationTraceDatum.cs
Microsoft.Azure.Cosmos/src/Tracing/TraceData/ConsistencyConfig.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientConfigurationDiagnosticTest.cs

Logs the application region into the client configuration trace for diagnostics.
closes #3198

Diagnostics: Adds Application region into Client Configuration Trace

---

Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyNoRetry.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosHttpClientCoreTests.cs

Right Now, NoRetry policy does not have request timeout value which is leading to request cancellation. Fixing this issue as part this PR.

HttpRetryPolicy: Fixes Request Timeout configuration in HttpTimeoutPolicyNoRetry

---

Microsoft.Azure.Cosmos/src/DocumentClient.cs
Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/VmMetadataApiHandlerTest.cs

When a client is initialized without using an Azure VM, an exception is logged that causes confusion for the user. This PR fixes that by logging an informational message instead. It also refactors the use of ContinueWith with await/async in the relevant method.
closes #3220

Telemetry: Fixes Trace error when not using Azure VMs

---

Microsoft.Azure.Cosmos/src/CosmosClient.cs
Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPartitionProvider.cs
Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPlanRetriever.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.QueryAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/EndToEndTraceWriterBaselineTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DirectContractTests.cs

This PR changes the behavior of the SDK on **Windows/x64** scenarios when the ServiceInterop.dll is not available.
Currently when it is not available, we throw:
```
Unhandled exception. System.DllNotFoundException: Unable to load DLL 'Microsoft.Azure.Cosmos.ServiceInterop.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)
at Microsoft.Azure.Documents.ServiceInteropWrapper.CreateServiceProvider(String configJsonString, IntPtr& serviceProvider)
at Microsoft.Azure.Cosmos.Query.Core.QueryPlan.QueryPartitionProvider.Initialize()
at Microsoft.Azure.Cosmos.Query.Core.QueryPlan.QueryPartitionProvider.TryGetPartitionedQueryExecutionInfoInternal(String querySpecJsonString, PartitionKeyDefinition partitionKeyDefinition, Boolean requireFormattableOrderByQuery, …
```

Query: Fixes DllNotFoundException when running on Windows/x64

---

Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/VmMetadataApiHandlerTest.cs

When AzMetadata.Compute is null for the VMMetadataApiHandler, the GetMachineId method does not work as intended. This PR fixes that to not allow a null reference to exist.
closes #3237

CosmosClient Constructor: Fixes NullReferenceException when AzMetadata.Compute is null

---

Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosOperationCanceledException.cs

Cancellation token status is currently evaluated when lazyMessage.value is used. This PR updates this to get the cancellation token during creation of the exception
closes #3248

CosmosOperationCanceledException: Fixes Closure on Cancellation Token status

---

Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientConfigurationTraceDatum.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryTests.cs

VM Metadata is initializes its azMetadata asynchronously, which is used in the Client Configuration Diagnostics to retrieve the machine Id. This fixes that by adding a cached machine Id and updating the serialized json accordingly.
closes #3238

Telemetry: Fixes Inconsistent behavior of VM Metadata Async Initialization

---

Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientConfigurationTraceDatum.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/VmMetadataApiHandlerTest.cs

If the Client is using an Azure VM, we are able to retrieve the VM's region and add it into the client configuration diagnostics. This is useful to determine if cross region operations are being performed.
closes #3247

Diagnostics: Adds VM Region into Client Configuration

---

Directory.Build.props
Microsoft.Azure.Cosmos/src/Query/Core/ExceptionToCosmosException.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TransportWrapperTests.cs

* Adds Direct version 3.28.2 which targets the EN20220301 release branch.
* Diagnostics: Fixes Exception caused when checking OS version of some Android Devices. Closes #3249 
* MalformedContinuationTokenException: Adds the use of a new substatus code when throwing to programmatically determine the cause of the BadRequest. Closes #3074 
* Diagnostics: Fixes CPU NaN value causing broken json formatting on some devices. Closes #3235 
* ServiceUnavailableException: Adds custom messages corresponding to different substatus codes and Creates factory model for exception creation. Closes #3051 and Closes #3098

Direct: Adds version 3.28.2

---

Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedProcessing/FeedProcessorCore.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedProcessing/ProcessorOptions.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/FeedProcessorCoreTests.cs

In some situations, the lease processor gets stuck, but the lease renewer keeps working. To prevent this situation from stalling indefinitely, this PR adds a linked cancellation token source to the cancellation token in order to cancel it after some time.
closes #2466

Change Feed Processor: Adds Task.Delay check to prevent stalling

---

Microsoft.Azure.Cosmos/src/DocumentClient.cs
Microsoft.Azure.Cosmos/src/GatewayAccountReader.cs
Microsoft.Azure.Cosmos/src/Routing/AsyncCacheNonBlocking.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientTests.cs

Adds a cancellation token into DocumentClient that cancels upon disposal. This removes the ObjectDisposedException that gets traced if a CosmosClient is quickly disposed after initialization.
closes #3259 and closes #2619

DocumentClient: Fixes ObjectDisposedException during Background Refresh by adding Cancellation Token

---

Microsoft.Azure.Cosmos/src/DocumentClient.cs

In rare cases, the Debug trace still shows an object disposed exception, causing the test to fail. This fixes that by letting the exception get thrown later on as a different exception getting rid of the race condition.

ObjectDisposedException: Fixes transient test failure thrown in debug trace

---

Microsoft.Azure.Cosmos/src/DocumentClient.cs
Microsoft.Azure.Cosmos/src/GatewayAccountReader.cs

The CosmosClientEarlyDisposeTest is experiencing transient failures, due to potential cases where Http client is being used after disposal. In order to mitigate, we catch the error before it gets logged in the GW AccountReader, which is a part of all stack traces when this test failure occurs.

ObjectDisposedException: Fixes Exception logic by catching the error upon client disposal before it gets traced

---

Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosOperationCanceledException.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientConfigurationDiagnosticTest.cs

In cases where the Diagnostics get truncated, the CosmosOperationCanceledException trace's stack trace can take up most of the space. This can prevent necessary information, such as the network requests, from showing in the diagnostics. This fixes that by adding this exception trace as a child rather than inside the primary data.
closes #3314 
Sample Diagnostics Json after changes:
```{
"Summary": {},
"name": "CreateItemAsync",
"id": "6a73ea1e-78d4-4dc8-827c-b0219b8e86d7",
"start time": "03:21:02:853",
"duration in milliseconds": 18.6144,
"data": {
"Client Configuration": {
"Client Created Time Utc": "2022-06-30T03:21:02.5549268Z",
"MachineId": "hashedMachineName:36958ae9-96cf-5367-78eb-c36b4d8d0517",
"NumberOfClientsCreated": 2,
"NumberOfActiveClients": 1,
"ConnectionMode": "Gateway", …
```

OperationCanceledException: Adds Exception Trace as Child 

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemIdEncodingTestsBase.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DirectCosmosItemIdEncodingTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/GatewayCosmosItemIdEncodingTests.cs

Got reports that certain valid characters in id were not handled appropriately in node.js SDK (space at the end of id for example). When testing I realized inconsistency across SDKs and even Gateway vs. Direct - so I will go through and create a baseline with end-to-end tests in all SDKs and then see how we can fix this situation (and whether we think it is important to fix vs. just better and more clear document the various constraints)
Overview is here: https://microsofteur-my.sharepoint.com/:x:/g/personal/fabianm_microsoft_com/EdA2zPvwjfxCo05SKu4FQXMBpnt_8HpDgSIOxWZqpjkikQ?e=6hX4ud
- [] …

[Internal] Tests: Adds unit test covering the Id-encoding end-to-end

---

Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs

Modify retry time in seconds to timespan of parameter maxRetryWaitTimeOnThrottledRequests (Method: [WithThrottlingRetryOptions](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.fluent.cosmosclientbuilder.withthrottlingretryoptions?view=azure-dotnet#feedback))
Resolves https://github.com/Azure/azure-sdk-for-net/issues/29567
- [] Breaking change (fix or feature that would cause existing functionality to not work …

Documentation: Fixes retry time to timespan

---

Microsoft.Azure.Cosmos/src/RequestOptions/ItemRequestOptions.cs
Microsoft.Azure.Cosmos/src/RequestOptions/QueryRequestOptions.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/DedicatedGatewayRequestOptions.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json

DedicatedGatewayRequestOptions type is made public (part of DedicatedCache GA)
closes #3363

Integrated cache: Adds DedicatedGatewayRequestOptions for public release

---

Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryOptions.cs
Microsoft.Azure.Cosmos/src/Telemetry/Compute.cs
Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
Microsoft.Azure.Cosmos/src/Util/CosmosUtils.cs
Microsoft.Azure.Cosmos/src/Util/HashingExtension.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/VmMetadataApiHandlerTest.cs

Compute Hash of below 2 values to avoid saving PII data
1) VM Id
2) Process Name
To automatically close an issue: closes #3372

Client Telemetry : Refactors code to compute hash of VM ID and Process Name information

---

Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientConfigurationTraceDatum.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientCreateAndInitializeTest.cs

The cachedSerializedJson from the client configuration was getting updated before the connection mode was initialized, so the default connection mode was getting output instead of the one set in the client options
To automatically close an issue: closes #3387

Diagnostics: Fixes Ordering of ClientConfiguration Initialization

---

Microsoft.Azure.Cosmos/src/Resource/FullFidelity/ChangeFeedMetadata.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/FeedToken/ChangeFeedIteratorCoreTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json

Contract changes to rename `TimeToLiveExpired` field to `IsTimeToLiveExpired`. This changes is required to make the variable naming consistent across the Java SDK.
To automatically close an issue: closes #3393

[Preview] Change Feed: Refactors Change Feed Contract to rename TimeToLiveExpired

---

Directory.Build.props
Microsoft.Azure.Cosmos/contracts/API_3.30.0-preview.txt
Microsoft.Azure.Cosmos/contracts/API_3.30.0.txt
changelog.md

This bumps the SDK version from 3.29.0 to 3.30.0. Please see the below changes in the GA public contract.

3.30.0: Adds new SDK versions and contract files

---

Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedManagement/PartitionControllerCore.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseManagerCosmos.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseUpdaterCosmos.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentServiceLeaseManagerCosmosTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentServiceLeaseUpdaterCosmosTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/PartitionControllerTests.cs

There were 3 conditions on which the Notification APIs were surfacing `LeaseLostException` to the user:
1. If the lease is not found (the document was deleted, which would indicate an invalid state): https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseUpdaterCosmos.cs#L66-L70
2. If there are constant conflicts beyond the retry scope (basically getting 412, which would indicate a very high concurrency of workers) https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseUpdaterCosmos.cs#L35
3. When a worker processed a batch and was about to checkpoint but the lease was stolen …

Change Feed Processor: Fixes LeaseLostException leaks on notification APIs

---

Microsoft.Azure.Cosmos/src/Authorization/TokenCredentialCache.cs
Microsoft.Azure.Cosmos/src/CosmosClient.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientCreateAndInitializeTest.cs

- Code changes to make `InitializeContainersAsync` method asynchronous. This will make sure the `Dispose()` method will be called, in the event there are any exception occurs.
- Updated `TokenCredentialCache` to use the current context cancellation token.
To automatically close an issue: closes #3392

CosmosClient Initialization: Fixes TokenCredentialCache to respect cancellation token

---

azure-pipelines-functional.yml
azure-pipelines.yml

This PR changes the YML definitions to avoid triggering on PRs that are simply modifying documentation or contract files (like release PRs).
This would reduce time-to-release and reduce instance usage on the pipelines (we have a limited number of agents so anything that reduces unnecessary runs allows other PRs to execute faster and not block).
The following patterns will be ignored:
- Modifications of MD files
- Files inside the `docs` folder
- Contract files inside `Microsoft.Azure.Cosmos/contracts`

[Internal] Pipelines: Fixes pipeline to not run on documentation

---

Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/PipelineFactory.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/InMemoryContainer.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/AggressivePrefetchPipelineTests.cs

Previously, we had enabled aggressive prefetching for scalar aggregates. This change enables it for `GROUP BY` and `COUNT(DISTINCT)`

Query: Adds aggressive prefetching for GROUP BY and COUNT(DISTINCT)

---

Microsoft.Azure.Cosmos/src/Patch/PatchOperationType.cs

This PR adds a link the official doc for supported operations to the [`PatchOperationType` Enum reference doc](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.patchoperationtype?view=azure-dotnet).
resolves Azure/azure-sdk-for-net#30972

Documentation: Adds link to supported operations doc for PatchOperationType Enum

---

.github/workflows/prlint.yml

Right now the PR-Lint cannot undo the review due to permissions issues, following https://github.com/MorrisonCole/pr-lint-action/issues/371#issuecomment-1250011920, we are setting `on-failed-regex-request-changes` to `false` and `on-failed-regex-fail-action` to true.

[Internal] PRLint: Fixes configuration to avoid PR being blocked

---

Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs

NameValueCollectionWrapperFactory is dead code and getting removed.
ClientTelemetry is using NameValueCollectionWrapperFactory for auth header related generation. Its usage moved to StoreResponseNameValueCollection.

Internal: Fixes ClientTelemetry to use StoreResponseNameValueCollection

---

Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ClientRetryPolicyTests.cs

https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3008 introduced a regression on the cross-region handling for 503s.
This PR added different substatus codes for 503s to identify different scenarios (was the 503 from client side connectivity issues, did the 503 came from the service, was it due to quorum loss, etc) which gives actionable details to components and consumers of these 503s.
But the `ClientRetryPolicy` was not adjusted to reflect this behavior with the new combination of substatus codes, the code is still checking for substatus 0. Changed the behavior to handle the new 503 status codes along with tests to avoid future regressions.
To automatically close an issue: closes …

ClientRetryPolicy: Fixes behavior to handling of 503 HTTP errors

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.BulkOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.PointOperationsExceptionsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/EndToEndTraceWriterBaselineTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/OpenTelemetryListener.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TransportClientHelper.cs

Fixes some of the critical flakey test failures for preview build, in our build pipeline. `PointOperationsExceptionsAsync` expects to wait for the Initialization of document client to complete, which sometimes finishes the initialization before executing the test, due to a shared code. This change takes the pieces from the shared code and make it a part of the individual test so that each test can initialize the document client separately.
To automatically close an issue: closes #3489

[Internal] EmulatorTest: Fixes flakey test failures in `PointOperationsExceptionsAsync()` observed in preview release pipeline

---

Microsoft.Azure.Cosmos/src/FeedRange/FeedRanges/FeedRangePartitionKey.cs
Microsoft.Azure.Cosmos/src/PartitionKey.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyTests.cs

Missing ToString() handling for PartitionKey.None results in NullRef Exception as opposed to more useful content.  Breaks some logging scenarios.  Identified by @ray2k.
This bugfix is similar to the one merged from: #3480 

PartitionKey: Fixes NullRef in toString handling for None for PartitionKey.ToString()

---

Microsoft.Azure.Cosmos/src/Telemetry/Models/Compute.cs
Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/VmMetadataApiHandlerTest.cs

Before this PR, we were hashing VM ID due to security concern but in recent talk with security team it is decided that VM ID is not PII hence can be store as it is without Hashing.

[Internal]Client Telemetry: Refactors code to remove hashing from VM Id

---

Directory.Build.props
Microsoft.Azure.Cosmos/src/CosmosClient.cs
Microsoft.Azure.Cosmos/src/DocumentClient.cs
Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
Microsoft.Azure.Cosmos/src/Resource/CosmosClientContext.cs
Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
Microsoft.Azure.Cosmos/src/Routing/GlobalAddressResolver.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientCreateAndInitializeTest.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosBasicQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DocumentClientUnitTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Mocks/MockDocumentClient.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayAddressCacheTests.cs

**Background:**
Currently, during the `CosmosClient.CreateAndInitializeAsync()`, the .net SDK uses a method called `InitializeContainerAsync()`, which leverages dummy query on all feed ranges to open connection, with retry capability to increase the chances of touching max replica. However, there are few drawbacks with current approach, which are highlighted below.
- It requires unnecessary query plan request to the gateway.
- This approach doesn't guarantee to touch all secondary replicas.
- Does not open connection to primary.
- Expensive in latency and RU.
**The Solution:**
Instead of using the dummy query during the initialization, we could leverage the Rntbd context negotiation to finish the connection establishment. This PR is adding the necessary implementation in the v3 SDK …

CosmosClient Initialization: Adds implementation for opening Rntbd connections to backend replica nodes in Direct mode.

---

Microsoft.Azure.Cosmos/src/DocumentClient.cs
Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPartitionProvider.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPartitionProviderTests.cs

When DocumentClient refreshes the database account and gets updates, query configuration changes need to be updated on the QueryPartitionProvider.
The Update() method is not being called, so when configuration changes are made, they are not being picked up by the query partition provider, and not making it into the service provider used by the query interop.
This change adds the call to Update so that configuration changes will be reflected in the query partition provider.

[Internal] Query: Fixes DocumentClient to update QueryPartitionProvider with configuration changes

---

Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/OrderBy/OrderByCrossPartitionQueryPipelineStage.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/OrderByCrossPartitionQueryPipelineStageTests.cs

Fixes performance regression introduced by #1289
The lack of query filters being sent to the target partition can cause excess round trips as the sdk tries to skip over values that have already been seen.
In case of CRM ([ICM 342678670](https://portal.microsofticm.com/imp/v3/incidents/details/342678670/home)) it lead to over 12k round trips. After the fix, there were only 31 round trips.

Query: Fixes performance regression on target partition on some ORDER BY queries with continuation

---

docs/SdkDesign.md

Add address caches conceptual flow with code links directly from the nodes/components

[Internal] docs: Add address caches conceptual flow

---

Directory.Build.props
Microsoft.Azure.Cosmos/contracts/API_3.31.2.txt
changelog.md

Hotfix release for [#3525](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3525) Query: Fixes performance regression on target partition on some ORDER BY queries with continuation

Release: Adds SDK version and changelog for 3.31.2

---

Microsoft.Azure.Cosmos/src/Resource/Database/Database.cs

Reference: https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3496#issuecomment-1289888018
The method throws if the throughput is not assigned, it doesn't return `null`

[Internal] Documentation: Removes invalid comment from ReadThroughputAsync

---

CONTRIBUTING.md
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ComputeGatewayCosmosItemIdEncodingTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemIdEncodingTestsBase.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/RoutingGatewayCosmosItemIdEncodingTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/BaseCosmosClientHelper.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TestCommon.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/settings.json
README.md
templates/emulator-setup.yml

Adds unit test coverage for the different id-encoding test cases in ComputeGateway in addition to Routing Gateway

[Internal] Emulator unit tests: Adds IdEncoding unit tests for ComputeGateway

---

Microsoft.Azure.Cosmos/src/Query/v3Query/QueryResponse.cs
Microsoft.Azure.Cosmos/src/Serializer/CosmosElementSerializer.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/CosmosUndefinedQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/QueryTestsBase.cs

Do not maintain an independent count on QueryResponse that can go out of sync with the actual resource count.
Fixes [Incident 349270178](https://portal.microsofticm.com/imp/v3/incidents/details/349270178/home) : Identified bug in Microsoft.Azure.Cosmos 3.31.2 feedResponse.Count

Query: Fixes incorrect FeedResponse.Count when result contains undefined elements

---

Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/CosmosDbEventSource.cs
Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/DistributedTracingOptions.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.BulkOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.PointOperationsExceptionsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/EndToEndTraceWriterBaselineTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs

Removed EnableDiagnosticsTraceForAllRequests from Distributing Tracing options

AI Integration: Removed EnableDiagnosticsTraceForAllRequests Config

---

Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/BenchmarkConfig.cs
Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/JsonHelper.cs

Below exception has been thrown when serialized string size is more than default capacity(i.e 1024 bytes). As part of this PR increasing this limit only for the part where we are printing configs (for which below exception was thrown).
```
Unhandled exception. System.NotSupportedException: Memory stream is not expandable.
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(ReadOnlySpan`1 buffer)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Flush()
   at Newtonsoft.Json.JsonTextWriter.Flush()
   at CosmosBenchmark.JsonHelper.ToStream[T](T input) in /home/debdattakunda/stash/azure-cosmos-dotnet-v3/Microsoft.Azure.Cosmos.Samples/Tools/Ben …
```

[Internal] Benchmark: Refactors code to make Memory Stream capacity configurable.

---

Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/Distinct/DistinctMap.UnorderedDistinctMap.cs
Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/Distinct/DistinctMap.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/CosmosUndefinedQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/DistinctQueryPipelineStageTests.cs

DistinctMap.UnorderedDistinctMap was missing code paths for handling some CosmosElement types like CosmosUndefined, CosmosGuid and CosmosBinary. This change adds the missing code paths to prevent `ArgumentOutOfRangeException`s on queries where these elements are encountered.

Query: Fixes handling of CosmosUndefined, CosmosGuid and CosmosBinary in unordered DISTINCT

---

Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs

The documentation for `CosmosClientBuilder.WithConnectionModeGateway` is a bit confuse. This one is saying that the parameter `maxConnectionLimit` is the time that the client will wait, however, in the end, it is saying about number of connections. I've analyzed and this value is used on `HttpMessageHandler.MaxConnectionsPerServer`.
By the way, it's saying that the default value is 60, but, analyzing the code, this value is 50. 
To automatically close an issue: closes #3641

Fixed CosmosClientBuilder.WithConnectionModeGateway documentation

---

Directory.Build.props
Microsoft.Azure.Cosmos/src/Regions.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json

This PR makes the `Poland Central` region available for public usage.
To automatically close an issue: closes #3655

Region Availability: Adds Poland Central Region For Public Usage.

---

Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
Microsoft.Azure.Cosmos/src/Query/Core/TestInjections.cs
Microsoft.Azure.Cosmos/src/Query/v3Query/QueryIterator.cs
Microsoft.Azure.Cosmos/src/RequestOptions/QueryRequestOptions.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/OptimisticDirectExecutionQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/QueryTestsBase.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs

Adds new flag to QueryRequestOptions to allow customers to use the OptimisticDirectExecution pipeline.

Query: Adds EnableOptimisticDirectExecution flag to QueryRequestOptions

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/GatewayTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/HeadersValidationTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/NameRoutingTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/QueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/SmokeTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/Util.cs
templates/emulator-setup.yml

Direct/HTTPS is not a mode that users can set on the V3 SDK, these tests are just adding execution time on the CI without adding any value.
Also disabling Windows Defender on the Emulator folder.

[Internal] Tests: Removes Direct/HTTPS emulator tests

---

Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/BenchmarkConfig.cs
templates/build-benchmark.yml
templates/build-preview.yml

Benchmark project was not referencing master cosmos db code in build pipeline. Hence, even if there is compilation error in Benchmark project due to a latest change in cosmosdb repo, it was not failing the pipeline.
As part of this PR fixing this.

[Internal] Benchmark : Fixes issue with dependency on Cosmos Project

---

Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
Microsoft.Azure.Cosmos/src/ValidationHelpers.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ValidationHelpersTests.cs

New Feature: Allow Strong Consistency reads (local minority reads, quorum reads from 2 replicas) for Consistent Prefix accounts. This feature can only be enabled when explicitly opting in for the consistency upgrade during the client initialization.

LocalQuorum: Adds Quorum reads on Consistent Prefix Accounts

---

Directory.Build.props
Microsoft.Azure.Cosmos/contracts/API_3.32.0-preview.txt
Microsoft.Azure.Cosmos/contracts/API_3.32.0.txt
changelog.md

This bumps the SDK version from 3.31.2 to 3.32.0. Please see the below changes in the GA public contract.

3.32.0: Adds new SDK version and contract files

---

.github/ISSUE_TEMPLATE/bug_report.md

By default, all "Bug report" issues will have "needs-investigation"

[Internal] GitHub Template: Adds needs-investigation label

---

Directory.Build.props

Bumped the DirectVersion from 3.30.1 to 3.30.2. 
This update changes the value of "Low" PriorityLevel parsed in the backend from 0 to 2. This is just a convention change and the PriorityLevel header is currently not being used by anyone.

[Internal] PriorityRequests: Fixes header value

---

Microsoft.Azure.Cosmos.Samples/Tools/CTL/CTLConfig.cs
Microsoft.Azure.Cosmos.Samples/Tools/CTL/ReservoirProvider.cs
Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ChangeFeedPullScenario.cs
Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ReadManyScenario.cs
Microsoft.Azure.Cosmos.Samples/Tools/CTL/Scenarios/ReadWriteQueryScenario.cs

Fixes the reservoir sampling logic in CTL. This will help to fix the percentiles measurement reported to CTL graphana dashboards.
To better understand the problem, please take a look at the Graphana dashboards snapshots during two runs. The first one was triggered with a reservoir type `Sliding Window` where as the second one was triggered with `Uniform`. The p999 fluctuations are clearly visible in the first one, compared to the later one.
**Sliding Window Reservoir:**
**Uniform Reservoir:**
To automatically close an issue: closes #3647

[Internal] CTL: Fixes Reservoir Sampling Logic

---

Microsoft.Azure.Cosmos/src/Handler/TelemetryHandler.cs
Microsoft.Azure.Cosmos/src/Routing/ClientCollectionCache.cs
Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryHelper.cs
Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryOptions.cs
Microsoft.Azure.Cosmos/src/Telemetry/Models/ClientTelemetryProperties.cs
Microsoft.Azure.Cosmos/src/Telemetry/Models/RequestInfo.cs
Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientSideRequestStatisticsTraceDatum.cs
Microsoft.Azure.Cosmos/src/Tracing/TraceData/SummaryDiagnostics.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ClientTelemetryTests.cs

As part of this PR, Network Information is also included into the client telemetry payload.
```
"RequestInfo": [ 
{ 
"url": "<rntbd>/<http regional> url, it will contain information till replica", 
"operation": "Create", 
"resource": "Document", 
"statusCode": 201, 
“subStatusCode”: 0 <applicable only on rntbd calls>, 
“databaseName”: databaseName, 
“containerName”: containerName, 
"metricInfo": [count P90, P99]Notice: this is an array of metrics 
} 
] 
```
Collects only for request failed request and high latency request. Right now, covering only RNTBD requests
0-3% of performance impact is there.
https://microsoftapc-my.sharepoint.com/:w:/g/personal/sourabhjain_microsoft_com/EfdDbQm27gZDpRGWMli0tO0Be4B_VS_A_GzIXf3ovabvjQ?e=LkmlfP
Updated this design doc with the approach taken as part …

[Internal] Client Telemetry: Adds network information in the payload

---

templates/static-tools.yml

Builds are issuing this warning:
For BinSkim:
```
##[warning]* Please upgrade the version of this build task in your build to major version: 4. For more information, please see: https://aka.ms/gdn-v1-deprecation
* Secure Development Tools (Guardian v1) is on the path to deprecation.
* Based on usage telemetry, this message will increase in build severity in the near future.
```
For AutoApplicability:
```
##[warning]* This tool is no longer supported. Please remove this build task from your build definition. For more information, please see: https://aka.ms/gdn-v1-deprecation
* Secure Development Tools (Guardian v1) is on the path to deprecation.
* Based on usage telemetry, this message will increase in build severity in the near future.
*
```
Following https://aka.ms/gdn-v1-deprecation, …

[Internal] Build: Fixes static tool analysis versions

---

Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
Microsoft.Azure.Cosmos/src/Query/v3Query/QueryIterator.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/BypassQueryParsingTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/OptimisticDirectExecutionQueryTests.cs

Microsoft.Azure.Documents.PartitionKeyInternal has the following method:
`public string GetEffectivePartitionKeyString(PartitionKeyDefinition partitionKeyDefinition, bool strict = true)`
Unfortunately, this is a broken contract, since it also has members:
```
private static readonly PartitionKeyInternal NonePartitionKey = new PartitionKeyInternal();
public static PartitionKeyInternal None
{
get
{
return PartitionKeyInternal.NonePartitionKey;
}
}
```
This implies that  `GetEffectivePartitionKeyString` throws an `System.ArgumentException` when `this` evaluates to `PartitionKeyInternal.None`.
The higher layer at `Microsoft.Azure.Cosmos.PartitionKey` is also broken since it exposes a `PartitionKey.None` member that maps to `PartitionKeyInternal.None`, instead of mapping to one of …

Query: Fixes System.ArgumentException when using PartitionKey.None on x86, Linux or in Optimistic Direct Execution

---

Microsoft.Azure.Cosmos/src/ValidationHelpers.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ValidationHelpersTests.cs

- Localquorum override (i.e. strong) to allow from any account consistency
- Facilitates no-downtime downgrade of existing accounts (i.e. existing Strong/bounded accounts migration to Eventual)

[Internal] LocalQuorum: Refactors override (i.e. strong) to allow from any account consistency

---

Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseManagerCosmos.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/DocumentServiceLeaseManagerCosmosTests.cs

https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3401 covered the most common cases reported for LeaseLostException leaks, including the case where `AcquireAsync` would fail because of lease rebalancing.
From personal testing, there was another case that was discovered: When a lease is Renewed on the background on scenarios where there is **no activity**, and during the no activity period, the lease is rebalanced, the exception that gets sent to the Notification APIs is a LeaseLostException (internal).
Because the Notification APIs will inspect the LeaseLostException.InnerException to log that if present, this PR covers all the other cases in `DocumentServiceLeaseManagerCosmos` where there is lease rebalancing (Renew, UpdateProperties, Release) to avoid throwing the …

Change Feed Processor: Fixes LeaseLostException leaks on notification APIs for Renew scenarios

---

Directory.Build.props
Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
Microsoft.Azure.Cosmos/src/Routing/GlobalAddressResolver.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayAddressCacheTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Tracing/TraceTests.cs

- This PR refactors the code in `GatewayAddressCache` to mark a `TransportAddress` to `Unhealthy` when a connection reset event occurs through the `ConnectionStateListener`.
To automatically close an issue: closes #3738

Upgrade Resiliency: Refactors GatewayAddressCache to Mark TransportAddresses to Unhealthy when Connection Reset Event Occurs

---

Directory.Build.props

When enabling Burst Capacity on an account, a client running on Direct mode can encounter:
```
Microsoft.Azure.Documents.TransportException: A client transport error occurred: The connection failed. (Time: 2023-03-28T05:20:21.3266713Z, activity ID: 814c6f9a-6413-4152-bbbe-29cdd33ef362, error code: ConnectionBroken [0x0012], base error: HRESULT 0x80131508, URI: rntbd://10.0.2.32:14300/apps/f9e22fdc-bc10-4c67-a092-e0e3791b7ab3/services/df313d2f-cdf3-4ebf-a5ff-e58ff1e6596c/partitions/f4ef0a42-650c-4ef2-9aff-081c993080cd/replicas/133045491009455711p, connection: 10.0.1.5:59554 -> 10.0.2.32:14300, payload sent: True) --->
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.Azure.Documents.RntbdTokenStream`1.ParseFrom(BytesDeserializer& reader)
   at …
```

Connectivity: Fixes ConnectionBroken and adds support for Burst Capacity

---

Microsoft.Azure.Cosmos/src/Tracing/TraceData/SummaryDiagnostics.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/SummaryDiagnosticsTests.cs

When trying to log cosmos exception, by doing `cosmosException.ToString()` is causing `IndexOutOfRangeException` and the stack trace points out to `HttpResponseHeadersWrapper` constructor. This PR fixes the bug by removing the dependency of `HttpResponseHeadersWrapper` and fetching the required headers from http response/ content message headers.
To automatically close an issue: closes #3765

SummaryDiagnostics: Refactors Code to Remove Dependency of HttpResponseHeadersWrapper to fetch Sub Status Codes

---

azure-pipelines-ctl-publishing.yml

Docker image pipeline is failing due to deprecated VM image:
```
The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04 or ubuntu-22.04 (ubuntu-latest). For more details, see https://github.com/actions/runner-images/issues/6002
```
In order to be future-proof, we should be using `ubuntu-latest`

[Internal] CTL: Fixes docker image pipeline

---

Microsoft.Azure.Cosmos/src/GatewayStoreClient.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs

An operation is mapped to a DocumentServiceRequest. When the DocumentServiceRequest is sent through Gateway mode, it is converted to an HttpRequestMessage.
The DocumentServiceRequest contains a list of Headers and Properties. 
Today we are just copying the Headers but not the Properties on the HttpRequestMessage.

HttpClient: Adds Properties to the Http messages if available

---

.github/fabricbot.json

When auto-closing Issues, the `${issueAuthor}` does not automatically add `@`, so the original author does not receive a notification that they are being mentioned on the message.
This PR fixes it by adding the `@`.

[Internal] MerlinBot: Fixes text used for auto-close

---

Directory.Build.props
Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
Microsoft.Azure.Cosmos/src/Routing/GlobalAddressResolver.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayAddressCacheTests.cs

The purpose of this PR is to validate the `Unknown` replicas aggressively, only for all read regions and modify the AddressEnumerator sorting logic as `Connected` > `Unknown` > `UnhealthyPending` > `Unhealthy`. Because validating the Unknown replicas are aggressive in nature, our concurrency logic in `RntbdOpenConnectionHandler` should handle it gracefully.
To automatically close an issue: closes #3740

[Internal] Upgrade Resiliency: Adds Logic to Validate `Unknown` Replicas along with `Unhealthy`.

---

docs/builds-and-pipelines.md
templates/build-benchmark.yml
templates/build-preview.yml

This PR adds a public doc that describes all existing Azure Pipelines integrated into this repository for reference.
Useful for team discoverability and documentation.
File preview -> https://github.com/Azure/azure-cosmos-dotnet-v3/blob/7646c59d659ebf49a9c6a011f4e6338df0b31071/docs/builds-and-pipelines.md
While reviewing pipeline YML files, I found that the Benchmark project was being built in 2 templates, when conceptually it makes sense to be built in 1 (both non-preview and preview Benchmark builds on the `build-benchmark.yml` template)

[Internal] Documentation: Adds documentation covering build pipelines

---

Directory.Build.props
Microsoft.Azure.Cosmos/contracts/API_3.33.0-preview.txt
Microsoft.Azure.Cosmos/contracts/API_3.33.0.txt
changelog.md

This bumps the SDK version 3.33.0. 
Contract changes: 
Preview contract changes:

SDK 3.33.0 : Adds version bump and changelog

---

Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj

This originated from an [3582](https://github.com/Azure/azure-cosmos-dotnet-v3/issues/3582) issue where the license was using an Url and not showing up in _Nuget.org_ in the details of the package. **PackageLicenseUrl** was deprecated and it was recommended to use either **PackageLicenseFile** or **PackageLicenseExpression** for immutability reasons. I am providing link to the original issue and [discussion](https://github.com/NuGet/Home/issues/4628). 
There was an option to leave LICENSE without extension or rename with .TXT extension. I opted to use the original without the .TXT as I do not see either a PRO or a CON to one over the other, but I have no qualms with either option.
In regard to not using **PackageLicenseExpression**. I am not really seeing a PRO or a CON on the surface as …

PackageLicense: Removes PackageLicenseUrl and Adds PackageLicenseFile since PackageLicenseUrl is deprecated

---

Microsoft.Azure.Cosmos/src/ChangeFeed/ChangeFeedMode.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json

Making _ChangeFeedMode_ **LatestVersion** public for GA. **LatestVersion** has the same functionality as **Incremental**.

Full Fidelity Change Feed: Adds LatestVersion to ChangeFeedMode

---

Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj

Removing ThirdPartyNotice.txt from content and contentfiles nuget folder. Unless there is a reason this needs to remain in the content and contentFiles Nuget folders, it seems fine to move it to the root.
Before:
After:
To automatically close an issue: closes #3667

NugetPackage: Removes ThirdPartyNotice.txt from content and contentFiles folders

---

Microsoft.Azure.Cosmos/src/Batch/TransactionalBatch.cs
Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs

Linking limit documentation to [Container.CreateTransactionalBatch(PartitionKey) method](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.cosmos.container.createtransactionalbatch?view=azure-dotnet)
- This change requires a documentation update
To automatically close an issue: closes #3853

Documentation: Adds see also link to Container.CreateTransactionalBatch

---

docs/SdkDesign.md

Added AppInsights Integration/Open Telemetry/Distributed Tracing Design.
- [] Documentation

[Internal] AI Integration or Open Telemetry: Design Document

---

docs/SdkDesign.md
docs/observability.md

Distributed Tracing/Open Telemetry/AI Integration: Design Document
@ealsur @kirankumarkolli 

Distributed Tracing: Fixes design issues

---

Directory.Build.props
Microsoft.Azure.Cosmos/src/DocumentClient.cs
Microsoft.Azure.Cosmos/src/Regions.cs
Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/Util.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json

It has 3 minor changes:
1. Upgrade Direct Package to 3.31.0, As side effect of this, made below changes.
2. Use correct function GatewayCache to get environment variable as boolean
3. Pass DistributedTracing Options instead of flag directly in Store factory
4. Added 2 new regions "_Malaysia South_", "_Italy North_".
5. Enable Distributing Tracing only for Operations. Request level tracing will be enabled as separate PR.

Direct Package Upgrade 3.31.0: Refactors code to make compatible with latest direct

---

Microsoft.Azure.Cosmos.Samples/Usage/OpenTelemetry/AppSettings.json
Microsoft.Azure.Cosmos.Samples/Usage/OpenTelemetry/OpenTelemetry.csproj
Microsoft.Azure.Cosmos.Samples/Usage/OpenTelemetry/Program.cs

In the sample of Open Telemetry with cosmos DB SDK, Logger Factory is not reading configuration from `appsettings` for Loglevel which is leading to generate events for Warning and Error both, even if LogLevel is configured as Error.
There are 2 ways to fix it:
1. Use `AddFilter()` and filter out only desired event level (doesn't matter what is event name).
2. `LoggerFactory `should read `appsettings `and emit only events with configured level
> Note: `AzureEventSourceLogForwarder` change this `Azure-Cosmos-Operation-Request-Diagnostics` to `Azure.Cosmos.Operation.Request.Diagnostics`

AI Integration: Fixes Open Telemetry Example

---

docs/observability.md

Addressed @kirankumarkolli comments mentioned in this PR https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3590

[Internal] Design Docs: Adds Design Document for Client Telemetry Part 2

---

Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs

- **Reduce Default Timeout to 6 Seconds:** This change primarily refactors the `ConnectionPolicy` class in the v3 SDK to reduce the default request timeout to `6` seconds from `10` seconds.
To automatically close an issue: closes #3895

ConnectionPolicy: Refactors Code to Reduce Default Request Timeout to 6 Seconds.

---

Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
Microsoft.Azure.Cosmos/src/Query/Core/QueryClient/CosmosQueryClient.cs
Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
Microsoft.Azure.Cosmos/src/SqlObjects/SqlPropertyName.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosGatewayTimeoutTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/BypassQueryParsingTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/MockCosmosQueryClient.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs

Updates property name parsing checks to allow for empty and whitespace property names.  These types of property names are currently allowed via the portal. Previously, an exception would be thrown upon parsing empty/whitespace property names when the gateway was bypassed and routing logic performed on the client side. Specifically, this would be the case when using macOS or Linux.
closes #2879

[Query] Fixes empty property name parsing exception

---

Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInternal.cs

Added links of supported patch modes as part of the API documentation on Container.PatchItem methods.
To automatically close an issue: close #3898

Documentations: Adds links to PatchItems docs

---

Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/AzureVmBenchmark/azuredeploy.json
Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/BenchmarkConfig.cs

There is an ARM template for Cosmos DB Benchmark Application Insights Dashboard with percentiles.
Dashboard just after the start of Azure CosmosDB Benchmarking:
Dashboard 7 min after the start:
Dashboard 15 min after the start:
After 30 min after start:

Benchmark metrics dashboard

---

Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayAddressCacheTests.cs

This PR optimizes the Rntbd open connection logic in the `GatewayAddressCache` by doing the following:
- Refactors the open connection logic to get partition addresses and open Rntbd connections in parallel, instead of invoking sequentially. This will help the `CosmosClient.CreateAndInitializeAsync()` flow to initialize and warm up the caches much faster for a large number of partitions, as compared with the previous counterpart.
- Utilizes the provided `cancellationToken` to cancel the `OpenConnection()` flow, so that the control of the time taken to initialize the cosmos client, remains to the caller.
To automatically close an issue: closes #3518, #3923

[Internal] Upgrade Resiliency: Adds Code to Optimize Rntbd Open Connection Logic to Open Connections in Parallel.

---

Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicy.cs
Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyControlPlaneRead.cs
Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyControlPlaneRetriableHotPath.cs
Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyDefault.cs
Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyNoRetry.cs

Current HttpTimeoutPolicies had too short MaxRetryTime - effectively suppressing any retries

HttpTransport: Fixes HttpTimeoutPolicies to not accidentally suppress retries

---

Directory.Build.props
Microsoft.Azure.Cosmos/contracts/API_3.35.1-preview.txt
Microsoft.Azure.Cosmos/contracts/API_3.35.1.txt
Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicy.cs
Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyControlPlaneRead.cs
Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyControlPlaneRetriableHotPath.cs
Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyDefault.cs
Microsoft.Azure.Cosmos/src/HttpClient/HttpTimeoutPolicyNoRetry.cs
changelog.md

Cherry-picks for hotfix release

Release: Adds commits for 3.35.1-preview hotfix release

---

Microsoft.Azure.Cosmos.Encryption.Custom/tests/EmulatorTests/Microsoft.Azure.Cosmos.Encryption.Custom.EmulatorTests.csproj
Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/Microsoft.Azure.Cosmos.Encryption.EmulatorTests.csproj
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj

`System.Linq.Dynamic.Core` was not really being used anywhere but we had the dependency on our Test projects.
There is now a security alert for this: https://github.com/Azure/azure-cosmos-dotnet-v3/security/dependabot/23 so might as well clean this up.

[Internal] Dependencies: Fixes dependabot alert for System.Linq.Dynamic.Core

---

Microsoft.Azure.Cosmos/src/ResourceThrottleRetryPolicy.cs

Changed verbose levels for some "Operation will NOT be retried" messages in the ResourceThrottleRetryPolicy to be able to suppress it in the traces.
To automatically close an issue: closes #3964

Diagnostics: Fixes verbose levels for "Operation will NOT be retried"

---

Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
Microsoft.Azure.Cosmos/src/DocumentClient.cs
Microsoft.Azure.Cosmos/src/Routing/GlobalAddressResolver.cs
Microsoft.Azure.Cosmos/src/Util/ConfigurationManager.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosReadManyItemsTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosBadReplicaTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs

In reference to a recent conversation with the compute gateway team, we agreed to add an `internal` Boolean flag in `CosmosClientOptions` to programmatically enable (or disable) the feature. This PR adds the flag in `CosmosClientOptions` to enable or disable the replica validation using the cosmos client options. Additionally, it keeps the ability for the external customers, to use the environment variable `AZURE_COSMOS_REPLICA_VALIDATION_ENABLED` to enable or disable the feature. 
To automatically close an issue: closes #3922

[Internal] Upgrade Resiliency: Refactors Code to Enable Replica Validation Feature Through `CosmosClientOptions` And Environment Variable

---

Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/CosmosDbEventSource.cs
Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/Filters/DiagnosticsFilterHelper.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.BatchOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Telemetry/DiagnosticsFilterHelperTest.cs
docs/observability.md

Right now, High Latency and Request Failures are generating event with same name i.e `LatencyOverThreshold`, It is confusing for customer for latency threshold was not crossed but was request failure due to some reason.
As part of this PR, generating event with event name as `FailedRequest` if there is request failure.
Below Status codes are considered as "Successful" requests:
1. StatusCode = System.Net.HttpStatusCode.NotFound and SubStatusCode = 0
2. StatusCode = System.Net.HttpStatusCode.NotModified and SubStatusCode = 0
3. StatusCode = System.Net.HttpStatusCode.Conflict and SubStatusCode = 0
4. StatusCode = System.Net.HttpStatusCode.PreconditionFailed and SubStatusCode = 0
To automatically close an issue: closes #3972

AI Integration: Fixes event generation for failed requests

---

Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/OptimisticDirectExecution/OptimisticDirectExecutionContinuationToken.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosBasicQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs
changelog.md

With Optimistic Direct Execution (ODE) being enabled by default in preview mode, a certain concern is brought up. 
What happens if an ODE continuation token goes into a non-ODE pipeline?
This would happen for 2 reasons:
1: Customer has multiple SDKs which are not all of the same version. The newer SDK generates an ODE continuation token and sends it to an older SDK that does not have ODE capabilities. In such a case, a different pipeline would have to handle this ODE token.
2: Customer gets an ODE continuation token, turns off ODE from QueryRequestOptions, and then passes the continuation token back to the SDK. With ODE turned off, a non-ODE pipeline would have to handle this token. 
The first case gets handled by a continuation token check which confirms that the incoming continuation …

Query: Adds ODE continuation token support for non-ODE pipelines

---

Directory.Build.props
Microsoft.Azure.Cosmos/contracts/API_3.35.3-preview.txt
Microsoft.Azure.Cosmos/contracts/API_3.35.3.txt
changelog.md

This bumps the SDK version from `3.35.2` to `3.35.3`. No changes in the GA public and preview contract/s.

3.35.3: Adds new SDK versions and contract files

---

Directory.Build.props

This PR fixes a bug #4013 that causes intermittent errors in the `CosmosClient.Dispose()`, with multiple parallel requests.
To automatically close an issue: closes #4013

Upgrade Resiliency: Fixes Race Condition by Calling Dispose Too Early.

---

changelog.md

This PR updates the change log to reflect the correct items, for release `3.35.3` and `3.35.3-preview`.

[Internal] Change Log: Fixes Change Log to Reflect Correct Items for Release `3.35.3`

---

Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
Microsoft.Azure.Cosmos/src/CosmosClient.cs
Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
Microsoft.Azure.Cosmos/src/Diagnostics/CosmosDiagnostics.cs
Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/DedicatedGatewayRequestOptions.cs
Microsoft.Azure.Cosmos/src/RetryOptions.cs

1. Fixes incorrect documentation links (the performance guide links lead to the V2 SDK article instead of V3 SDK).
2. Fixes typo "Azure CosmosDB"→"Azure Cosmos DB" as per #4029

Documentation: Fixes article links (replaced links V2 to V3 SDK version) + Azure Cosmos DB typo

---

Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs

During the background address refresh stage to validate all the `Unhealthy` replicas which remained unhealthy for a period of `1` minute or more, the SDK doesn't act on a potential exception thrown while resolving the addresses from gateway, and instead throws it from the background task. This essentially causes the exceptions to be unmonitored and unobserved.
This PR fixes the above behavior.
To automatically close an issue: closes #4010

GatewayAddressCache: Fixes Unobserved Exception During Background Address Refresh

---

Microsoft.Azure.Cosmos/src/DocumentClient.cs
Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
Microsoft.Azure.Cosmos/src/Handler/ClientPipelineBuilder.cs
Microsoft.Azure.Cosmos/src/Handler/TelemetryHandler.cs
Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj
Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
Microsoft.Azure.Cosmos/src/Routing/ClientCollectionCache.cs
Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
Microsoft.Azure.Cosmos/src/Telemetry/Collector/ITelemetryCollector.cs
Microsoft.Azure.Cosmos/src/Telemetry/Collector/TelemetryCollector.cs
Microsoft.Azure.Cosmos/src/Telemetry/Collector/TelemetryCollectorNoOp.cs
Microsoft.Azure.Cosmos/src/Telemetry/Collector/TelemetryInformation.cs
Microsoft.Azure.Cosmos/src/Telemetry/TelemetryToServiceHelper.cs
Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.BatchOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.BulkOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ChangeFeedAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.MiscellanousAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.PointOperationsExceptionsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.QueryAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ReadFeedAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ReadManyAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.StreamPointOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.TypedPointOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryTestsBase.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Contracts/BenchmarkResults.json
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Mocks/MockDocumentClient.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/HandlerTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Utils/MockCosmosUtil.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Utils/MockDocumentClient.cs

This PR is part 1/3 of this https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3816 PR.
As part of PR, refactoring client telemetry code to add Collector abstraction.

[Internal] Client Telemetry: Refactors code for collectors

---

Microsoft.Azure.Cosmos.Samples/Tools/Benchmark/BenchmarkConfig.cs
Microsoft.Azure.Cosmos.Samples/Tools/CTL/CTLConfig.cs
Microsoft.Azure.Cosmos.Samples/Tools/CTL/Program.cs
Microsoft.Azure.Cosmos/src/ConnectionPolicy.cs
Microsoft.Azure.Cosmos/src/Handler/DiagnosticsHandler.cs
Microsoft.Azure.Cosmos/src/Handler/DiagnosticsHandlerHelper.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/AccountClientConfiguration.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/ClientTelemetryConfiguration.cs
Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryOptions.cs
Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetryProcessor.cs
Microsoft.Azure.Cosmos/src/Telemetry/TelemetryToServiceHelper.cs
Microsoft.Azure.Cosmos/src/Tracing/TraceData/ClientSideRequestStatisticsTraceDatum.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryReleaseTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryTestsBase.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/SynchronizationContextTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/HttpHandlerHelper.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/Util.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Mocks/HttpHandlerHelper.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Mocks/MockDocumentClient.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Diagnostics/DiagnosticHandlerHelperTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Telemetry/ClientTelemetryTests.cs

This PR is part 2/3 of this https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3816 PR.
As part of PR, Removing Environment variable configs and using client config API response to enable or disable client telemetry job.
**What is not covered?** dynamically switching on/off client telemetry flag and start/stop job in sdk accordingly.
**Why so many files are touched?**
As part of this PR, changing the way we enabled telemetry feature. Since Previously, it was only possible from Environment Variable, But now **ClientConfig** API gives this information.
Hence summary of the change is :
1. `ConnectionPolicy.EnableClientTelemetry` and `CosmosClientOptions.EnableClientTelemetry` (Internal Options) is now a feature flag. It just unlocks this whole feature which includes calling client config …

[Internal] Client Telemetry: Adds client config api call to get latest flag status

---

Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/CosmosDbEventSource.cs
Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/Filters/DiagnosticsFilterHelper.cs
Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/AssertActivity.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Telemetry/DiagnosticsFilterHelperTest.cs

Right now, 404 and other non failure status are marked as failed dependency on Appinsights. Although it is already handled while generating request diagnostics.
As part of this PR, Putting a condition around it to make sure activities are not getting marked as failure for such requests.
Before this PR:
After this PR:
To automatically close an issue: closes #4095

Distributed Tracing: Fixes dependency failure on appinsights

---

Microsoft.Azure.Cosmos/src/Query/Core/Metrics/ServerSidePartitionedMetrics.cs

Adds remark to expect null values for `PartitionKeyRangeId` in Gateway Mode.

Query : Adds Missing QueryMetrics Documentation

---

Microsoft.Azure.Cosmos/src/Resource/Settings/TriggerOperation.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TriggersTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SettingsContractTests.cs

Added Upsert trigger operation with test.
To automatically close an issue: closes #4104

TriggerOperation: Adds Upsert Operation Support

---

azure-pipelines-official.yml

During release, it was found that recent changes in release pipeline is breaking because it is not able to resolve a variable as boolean.
As part of this PR, removing this variable as it is not adding any value and it will unblock the release.
JFYI : here is the difference between master and release 3.35.4 changes, in this particular block

Release 3.36.0: Fixes pipeline by removing ReleasePackage variable

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryReleaseTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryTestsBase.cs
azure-pipelines-official.yml

Client Telemetry Release Test was added as part of PR https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3900, during that time, client telemetry service URL was configured as environment variable and for Integration and emulator tests, we had corresponding URL configured.
But during PR https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4050 when environment variable was removed at that time emulator test were fixed but it broke integration test as assertion code of these tests is common and No url was configured for Integration test.
We don't run integration tests as part of PR pipeline, hence it never got caught. Now found this issue while running release pipeline where we run this integration test also.

Release 3.36.0 : Fixes Client Telemetry Release Test

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs

Fixes flaky `QuerySinglePartitionItemStreamTest` in `CosmosItemTests`.

[Internal] Query: Fixes flaky test

---

Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs

Changes made to the Ode code path have caused existing behavior to break with the Passthrough pipeline.
This is because, queries that the Passthrough pipeline would support are no longer supported due to Ode causing customer queries to suddenly stop working.

[Internal] Query: Removes Ode changes which rejected certain types of queries which were previously supported on 3.36.0

---

Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs

Changes made to the Ode code path have caused existing behavior to break with the Passthrough pipeline. 
This is because, queries that the Passthrough pipeline would support are no longer supported due to Ode causing customer queries to suddenly stop working. 

[Internal] Query: Removes Ode changes which rejected certain types of queries which were previously supported on 3.36.0-preview

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientConfigurationDiagnosticTest.cs
azure-pipelines-official.yml

As part of this PR, we are fixing below 2 things:
1. Fixing preview release pipeline where it is find out that, this pipeline was never taking the passed variables.
2. ClientConfig test is fixed on preview package. As distributedtracingId is also added.

Release 3.36.0: Fixes client config test and preview pipeline

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientConfigurationDiagnosticTest.cs
azure-pipelines-official.yml

As part of this PR, we are fixing below 2 things:
1. Fixing preview release pipeline where it is find out that, this pipeline was never taking the passed variables.
2. ClientConfig test is fixed on preview package. As distributedtracingId is also added.

Release 3.36.0: Fixes Preview Pipeline and Client Config Test

---

Microsoft.Azure.Cosmos/src/DocumentClient.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/InterfaceParityTest.cs

The CosmosClient performs a deferred initialization that obtains the Account Properties (Consistency, Read/Write regions, etc). 
This deferred initialization happens on two cases:
* If `CosmosClient.CreateAndInitialize` is used, the returned `CosmosClient` instance is already initialized.
* If any operation is performed on the client, the client will first initialize, and then execute the operation.
After any of these steps, the proposed API would return the AccountProperties it knows about.
Starting with this as an internal API, that if valuable can be proposed as public.

[Internal] DocumentClient: Adds TryGetAccountProperties

---

Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj

VS 17.8 auto runs NuGetAudit and flagging 10.0.2, CosmosDB SDK already mitigated it by changing the MAXDEPATH
Adding a NoWarn for Newtonsoft package. 
Reference SDK fix: https://github.com/Azure/azure-cosmos-dotnet-v3/pull/3313

[Internal] Security: Fixes NuGetAudit fail on VS 17.8 for Newtonsoft 10.0.2

---

Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
Microsoft.Azure.Cosmos/src/Util/ConfigurationManager.cs

UPSERT documentation update to include status codes for Created vs Replaced

Documentation: Adds Upsert documentation to include status codes for Created vs Replaced

---

README.md
docs/versioning.md

The following PR adds a versioning guideline that clarifies which are the released versions.
The current SDK release method is to always release version `X` and `X-preview` but this causes a wide range of issues with Nuget and chained dependencies (package A depends on SDK version `X`, if the user wants to use `X-preview` they can't because Nuget would attempt to use `X` because `X` is semantically newer than `X-preview`).
The goal is to improve the release methodology to address the versioning issues arising in tooling used by our customers.
Preview of the document: https://github.com/Azure/azure-cosmos-dotnet-v3/blob/users/ealsur/versioning/docs/versioning.md
Closes #4169

[Internal] Versioning: Adds guidance for versioning SDK releases

---

Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedManagement/PartitionControllerCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/PartitionControllerSplitTests.cs

Once a lease is finished processing, due to split or merge happening or any of the known conditions:
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/ea269c99b54a2ac2a4394edbcb50b2ed0cb6c0b0/Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/FeedManagement/PartitionSupervisorCore.cs#L52-L80
The PartitionSupervisor variable is no longer used and goes out of scope to be GCed.
The PartitionSupervisor implements `IDisposable` but there is no path that explicitly calls Dispose when the supervisor is no longer used.
Closes #4208

Change Feed Processor: Fixes disposal of unused CancellationTokenSource

---

Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs

This will fix the memory leak in `GlobalEndpointManager` where `CancellationTokenSources` are not disposed. 

[Internal] GlobalEndpointManager: Fixes Memory Leak

---

Directory.Build.props
Microsoft.Azure.Cosmos/contracts/API_3.37.1-preview.txt
Microsoft.Azure.Cosmos/contracts/API_3.37.1.txt
Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
changelog.md

Cherry-picks #4226 and #4231 for 3.37.1 release. 

3.37.1: Adds cherry-picks to release branch

---

Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchOperationResult.cs
Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchResponse.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/BatchAsyncContainerExecutorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Batch/CosmosItemBulkTests.cs

This PR adds the `PartitionKeyRangeId` in both Bulk mode and Transactional Batch response headers.
To automatically close an issue: closes #4235

BulkMode: Adds PartitionKeyRangeId in Bulk Mode and TransactionalBatch Response Headers

---

.github/workflows/prlint.yml

Security notice indicates that `permissions` will be a required field for GitHub workflows: https://docs.opensource.microsoft.com/github/apps/permission-changes/
We only have 1 GitHub flow, which is the PR Linter.
After the permissions scope, the action keeps working as expected:

[Internal] Pipelines: Adds permissions to workflow

---

Microsoft.Azure.Cosmos/src/DocumentClient.cs
Microsoft.Azure.Cosmos/src/FaultInjection/IChaosInterceptorFactory.cs

When creating the `IChaosInterceptor`, there must be async calls. This PR refactors the `IChaosInterceptorFactory` class so that the method is now asynchronous.

[Internal] Fault Injection: Refactors CreateInterceptor to Async Method

---

Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs

As part of this PR, validating `DisableServerCertificateValidation` flag and `ServerCertificateCustomValidationCallback` option are set together. Throws `ArgumentException` if it is true.

CosmosClientOptions: Adds validation to check DisableServerCertificateValidation and ServerCertificateCustomValidationCallback are set together

---

Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs

Documentation refresh: Fix DeleteItem API will not return context in response
ref: https://github.com/Azure/azure-cosmos-dotnet-v3/issues/1273#issuecomment-1917959931
closes: #1273

Documentation refresh: Fixes DeleteItem API will not return context in response

---

Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs

When `DisableServerCertificateValidation` is set:
`ServerCertificateCustomValidationCallback` is conditionally set after validation when ConnectionPolicy is created. But HttpClient is created before ConnectionPolicy creation resulting in the configuration getting ignored. 
- Make CosmosClientOptions.ServerCertificateCustomValidationCallback immutable post initialization. 
- New internal API GetServerCertificateCustomValidationCallback() which abstracts the certificate validation callback definition. 
- Supporting the combination of both DisableServerCertificateValidation and ServerCertificateCustomValidationCallback combination
- Supporting test hook for DisableServerCertificateValidationInvocationCallback (specifically for only Disable checking)
Please delete options that are not …

DisableServerCertificateValidation: Fixes Default HttpClient to honor DisableServerCertificateValidation

---

Directory.Build.props
changelog.md

This bumps the SDK GA version from `3.38.0` to `3.38.1` and preview version from `3.39.0-preview.0` to `3.39.0-preview.1`. No changes in the GA public and preview contract/s.

3.38.1: Adds new SDK versions and contract files

---

Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/Aggregate/AggregateQueryPipelineStage.Client.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/IndexMetricsParserBaselineTest.IndexUtilizationClientSideExistenceTest.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/IndexMetricsParserBaselineTest.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Microsoft.Azure.Cosmos.EmulatorTests.csproj

The AggregateQueryPipelineStageClient after aggregating results erroneously removed all additional headers in the response message, resulting in a loss of IndexMetrics advice from the SDK side. This is repro-able on all Aggregate queries.
This PR adds back the additional headers in the final aggregated Query Page. 
To automatically close an issue: closes #4210

[Internal] Query: Fixes Aggregate Pipelines resetting headers

---

Directory.Build.props
changelog.md

This PR cherry-picks the [`3.38.1` version bump PR](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4305)  and resolves the conflict by manual intervention, by downgrading the `Cosmos.Direct` package version.

[Hotfix] 3.38.1: Fixes Change Log and Bumps Up Release Versions

---

Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs

As reported in the issue below, the remark for GetItemQueryStreamIterator overloads is stale. Removing it.
To automatically close an issue: closes #4159

[Internal] Query: Fixes stale code comment for GetItemQueryStreamIterator 

---

Microsoft.Azure.Cosmos/src/CosmosThresholdOptions.cs

Fixing code documentation.
To automatically close an issue: closes #4351

Distributed Tracing Documentation : Fixes the default value mentioned in code doc

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TestCommon.cs
azure-pipelines.yml
templates/build-test.yml

Adds inclusion of multi-region account connection string to pipeline environment variables

[Internal] Pipelines: Fixes Multi-Region CI pipeline to include env variable

---

Microsoft.Azure.Cosmos.Encryption.Custom/src/EncryptionContainer.cs
Microsoft.Azure.Cosmos.Encryption/src/EncryptionContainer.cs
Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInlineCore.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInternal.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json

Adding **AllVersionsAndDeletes** to `ChangeFeedProcessor`.

ChangeFeedProcessor: Adds AllVersionsAndDeletes support to ChangeFeedProcessor

---

Microsoft.Azure.Cosmos.Encryption.Custom/src/EncryptionContainer.cs
Microsoft.Azure.Cosmos.Encryption/src/EncryptionContainer.cs
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/Observers/ChangeFeedObserverFactoryCore.cs
Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInternal.cs
Microsoft.Azure.Cosmos/src/Resource/FullFidelity/ChangeFeedItem.cs
Microsoft.Azure.Cosmos/src/Resource/FullFidelity/ChangeFeedMetadata.cs
Microsoft.Azure.Cosmos/src/Serializer/CosmosSerializerCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/GetChangeFeedProcessorBuilderWithAllVersionsAndDeletesTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/FeedToken/ChangeFeedIteratorCoreTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json

ChangeFeedProcessor: Refactors AVAD metadata Contract

---

Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/Parallel/ParallelCrossPartitionQueryPipelineStage.cs
Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/Parallel/QueryPartitionRangePageAsyncEnumerator.cs
Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/OptimisticDirectExecution/OptimisticDirectExecutionQueryPipelineStage.cs
Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/PipelineFactory.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/SubpartitionTests.TestQueriesOnSplitContainer.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Microsoft.Azure.Cosmos.Tests.csproj
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/InMemoryContainer.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/FactoryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/FullPipelineTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/ParallelCrossPartitionQueryPipelineStageTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPartitionRangePageEnumeratorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/SubpartitionTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Tracing/TraceWriterBaselineTests.cs

This change contains the fix for occasional hang that can occur while querying using partition partition key against a sub-partitioned container. Let's assume a container with partition key definition "/id", "/value1", "/value2". Unlike single-key partition definition, for hierarchical partitions, partition splits occurs such that for a certain value of "/id" (say 2), more than one partition contains the data for this (partial) partition value. When a query is issued with partial partition key ("/id" = 2 in this case), query enumerator (QueryPartitionRangePageAsyncEnumerator L50) attempts to query a feedrange based on this partial value that isn't fully contained inside a single physical partition in the backend. Since such a range cannot be resolved to any single physical partition, …

[Internal] Query: Fixes occasional hang while querying using partial partition key against a sub-partitioned container

---

Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/OptimisticDirectExecution/OptimisticDirectExecutionQueryPipelineStage.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/OptimisticDirectExecutionQueryTests.cs

.NET SDK currently doesn't need to request the query distribution plan. This change stops requesting it in the response and also avoids occasional failure that may be observed in the backend.

[Internal] Query: Fixes Client QL exception by dropping ClientQLCompatibilityLevel

---

Microsoft.Azure.Cosmos.Samples/Tools/FaultInjection/src/implementataion/FaultInjectionServerErrorResultInternal.cs

Changes FaultInjection responses so headers are set with `Set` rather than `Add`. `Add` works for the original request however, when the SDK retries the 429s it subsequently throws because the header is already present. 

[Internal] FaultInjection: Fixes Bug with Headers for TooManyRequests

---

Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryRecorderFactory.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientConfigurationDiagnosticTest.cs

**What is the change?**
Added "back", logic to generate activity id, even if customer is not subscribed to any source.
**Why is change required?**
As part of PR https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4333, I removed network level traces generation, along with that, this code was also removed where we were making sure that _traceid_ is generated, even if customer is not subscribed to the any traces.
**Why was it not caught in PR pipelines?**
It is part of emulator test, and we don't run emulator test in "preview" mode, in our PR pipelines.
This would unblock 3.39.0 release

[Internal] Distributed Tracing: Fixes Client Config Test

---

Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/OrderBy/OrderByCrossPartitionQueryPipelineStage.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/OrderByQueryTests.cs

Fixes bug in OrderByCrossPartitionQueryPipelineStage to ensure that errors in inner pipeline creation are bubbled up to the higher stages

Query: Fixes bug in OrderByCrossPartitionQueryPipelineStage to ensure that errors in inner pipeline creation are bubbled up

---

Microsoft.Azure.Cosmos.Encryption.Custom/src/Microsoft.Azure.Cosmos.Encryption.Custom.csproj

There is a security vulnerability disclosed for Azure.Identity which was fixed in Azure.Identity 1.11.0.
This was reported by Dependabot: https://github.com/Azure/azure-cosmos-dotnet-v3/security/dependabot/32
This PR updates the `Azure.Identity` dependency to `1.11.0` and `Azure.Core` to `1.38.0` for the Microsoft.Azure.Cosmos.Encryption.Custom package

[Internal] Security: Fixes Azure.Identity dependency on Microsoft.Azure.Cosmos.Encryption.Custom

---

Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseManager.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/GetChangeFeedProcessorBuilderWithAllVersionsAndDeletesTests.cs

Refer to #4423 for details
To automatically close an issue: closes #4423

ChangeFeedProcessor: Fixes a bug properly when dealing with Legacy lease incremental documents that do not have a Mode property

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayAddressCacheTests.cs

This PR fixes the following test `TryGetAddressesAsync_WhenReplicaVlidationEnabledAndCSListenerMarksReplicaUnhealthyWithParallelInvocation_ShouldValidateUnhealthyReplicasOnce` in `GatewayAddressCacheTests`.

[Internal] Flakey Tests: Fixes few Tests in `GatewayAddressCacheTests` 

---

Directory.Build.props
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseManager.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/GetChangeFeedProcessorBuilderWithAllVersionsAndDeletesTests.cs
changelog.md

SDK 3.40.0-preview.1: Adds version bump and changelog.

---

Directory.Build.props
Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/LeaseManagement/DocumentServiceLeaseManager.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/GetChangeFeedProcessorBuilderWithAllVersionsAndDeletesTests.cs
changelog.md

SDK 3.39.1: Adds version bump and changelog.

---

Microsoft.Azure.Cosmos.Samples/Usage/SystemTextJson/CosmosSystemTextJsonSerializer.cs
Microsoft.Azure.Cosmos.Samples/Usage/SystemTextJson/Program.cs
Microsoft.Azure.Cosmos.Samples/Usage/SystemTextJson/SystemTextJson.csproj
Microsoft.Azure.Cosmos/src/Serializer/CosmosLinqSerializer.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqTestsCommon.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Linq/CosmosLinqJsonConverterTests.cs

Adds usage of CosmosLinqSerializer in Samples and removes documentation for previous limitations.  Also updates STJ CosmosLinqSerializer implementation to cover more possible serializer options in SerializeMemberName.

Samples: Adds STJ LINQ Serializer Example

---

docs/SdkDesign.md

To provide more clarity to the reader and avoid having to read the source code, we are adding the backoff default values to the document.

[Internal] Documentation: Adds details about retry backoff for 410/449

---

Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryFeature.cs
Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryInfo.cs

Adds:
These will be used by the Compute gateway to fail queries that require non streaming order by but do not pass this capability

Query: Adds a new capability for non streaming order by in QueryFeatures

---

Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/OrderBy/OrderByCrossPartitionQueryPipelineStage.cs
Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/PipelineFactory.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Query/OrderByPipelineStageBenchmark.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/NonStreamingOrderByQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/OrderByCrossPartitionQueryPipelineStageTests.cs

The contract with the backend for non streaming order by has changed. The backend response will no longer have _streaming. Instead there is a new flag on the query plan to indicate the presence of a non streaming order by. This PR switches non streaming order by to use flag from query plan instead of _streaming in the backend response.
This PR does not do any code cleanup, since the SDK is required for integration testing of the backend. The cleanup PR will follow this change.

Query: Fixes non streaming order by to use flag from query plan

---

azure-pipelines-rolling.yml
templates/build-test.yml

This PR adds the YML file for a pipeline to be executed 4 times a day, only from the content of `master`.
The pipeline will run at 7AM, 1PM, 12AM and 5AM UTC (which is ~ 12AM, 6AM, 5PM, 10PM PDT) and execute only the tests suites:
* Unit and Emulator tests for Microsoft.Azure.Cosmos
* Emulator tests for Microsoft.Azure.Cosmos.Encryption
* Emulator tests for Microsoft.Azure.Cosmos.Encryption.Custom

[Internal] Pipelines: Adds rolling pipeline

---

Microsoft.Azure.Cosmos/src/CosmosClientTelemetryOptions.cs
Microsoft.Azure.Cosmos/src/CosmosThresholdOptions.cs
Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/CosmosDbEventSource.cs
Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/Filters/DiagnosticsFilterHelper.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.BulkOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ChangeFeedAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.MiscellanousAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.QueryAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ReadFeedAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ReadManyAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.StreamPointOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.TypedPointOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Telemetry/DiagnosticsFilterHelperTest.cs

As part of this PR, providing Request Charge threshold and Payload load size threshold options to customers.It would generate request diagnostics if these thresholds were crossed,
To automatically close an issue: closes #4385

Distributed Tracing: Adds Request charge and Payload size Threshold options

---

templates/nuget-pack.yml

AzCopy needs to be updated to 6 to work with the new security workflows.
Reference: https://github.com/microsoft/azure-pipelines-tasks/pull/19650

[Internal] Engineering: Fixes Nuget generation and copy process

---

Directory.Build.props

This PR bumps up the `Cosmos.Direct` package version to `3.34.0` which is released on top of `EN20240415` release. In a nut-shell, the change is focused on reducing the number of barrier requests issued for Global Strong in the Microsoft Azure Documents project.
The fix modifies the logic for issuing barrier requests, introducing a delay mechanism to reduce the number of requests and improve efficiency. The changes also include additional status codes for better error handling.
- In `QuorumReader.cs`, the retry loop logic has been modified to include a delay mechanism based on the `defaultBarrierRequestDelays` array and `remainingDelay` variable. The logic for handling responses has also been updated.
- In `BarrierRequestHelper.cs`, new methods have been added to determine if a delay …

[Internal] Direct Package Upgrade: Refactors Code to Bump Up `Cosmos.Direct` Package to `3.34.0`

---

Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPlanRetriever.cs
Microsoft.Azure.Cosmos/src/Query/v3Query/QueryIterator.cs
Microsoft.Azure.Cosmos/src/RequestOptions/QueryRequestOptions.cs
Microsoft.Azure.Cosmos/src/Util/ConfigurationManager.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/NonStreamingOrderByQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/FullPipelineTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/SubpartitionTests.cs
templates/build-test.yml

In order to retrieve a query plan for non streaming order by queries, the sdk must send NonStreamingOrderBy in the list of supported query features to the gateway. However, older gateways will not recognize this new value, causing the query plan request to fail with a 400. To mitigate this edge case, we add a check for an environment variable `AZURE_COSMOS_NON_STREAMING_ORDER_BY_FLAG_DISABLED`, which when set to `True`  will suppress sending NonStreamingOrderBy in the list of supported query features.
A note about the naming
It is named as `DISABLED` by design for two reasons:
- Since we decided to have this functionality enabled by default, if the environment variable is set, then the functionality would be disabled. This is reflected in the name of the environment variable.
- The …

Query: Adds an environment config to suppress sending NonStreamingOrderBy in the list of query features sent to the gateway

---

Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/SubpartitionTests.TestQueriesOnSplitContainer.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Pagination/InMemoryContainer.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/SubpartitionTests.cs

If partial partition key is specified during query execution and the container partition is split at the top level of the partition key, ORDER BY query results may be wrong. This happens because query is incorrectly treated as a streaming ORDER BY query, even though it spans across multiple physical partitions. The fix is to ensure cross-partition ORDER BY pipeline gets used, which applies global sort on results obtained from each backend partition (using k-way merge). Since the physical partitions are already resolved by the time this determination is made (they just happen to get ignored at the moment), the fix is straightforward and bulk of the change is test related.
- [] New feature …

Query : Fixes ORDER BY query issue when partial partition key is specified with hierarchical partition

---

Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/MdeEncryptionTests.cs
Microsoft.Azure.Cosmos.Encryption/tests/EmulatorTests/Microsoft.Azure.Cosmos.Encryption.EmulatorTests.csproj
Microsoft.Azure.Cosmos/src/Query/v2Query/DocumentQueryExecutionContextBase.cs
Microsoft.Azure.Cosmos/src/RequestOptions/QueryRequestOptions.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/HeadersValidationTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/SupportedSerializationFormatsTest.cs

This change restricts use of SupportedSerializationFormats header to query scenarios only. Technically, this header is only used by QueryRequestOptions, however, the QueryRequestOptions (and therefore this header) also get invoked for ReadFeed. There is no direct API for ReadFeed, instead any of the query APIs (GetItemLinqQueryable, GetItemQueryIterator<T>, GetItemStreamQueryIterator) invoke ReadFeed operation (instead of Query operation) if supplied query (or QueryDefinition) is null.
ReadFeed API in the backend currently doesn't support this header and returns the response in text. However as it turns out, if this API is invoked with a specific partition key in the request options, backend honors the header. This is an issue, since SDK doesn't support handling of binary response in …

[Internal] Query : Fixes response parsing error for ReadFeed by limiting binary format to query operations

---

azure-pipelines-ctl-publishing.yml
azure-pipelines-encryption-custom.yml
azure-pipelines-encryption.yml
azure-pipelines-official.yml
templates/build-benchmark.yml
templates/build-ctl.yml
templates/build-internal.yml
templates/build-preview.yml
templates/build-samples.yml
templates/build-test.yml
templates/nuget-pack.yml
templates/static-tools.yml

As a commitment to make Microsoft and its products more secure, we will be transferring to using OneES pools for our pipelines. 

[Internal] Pipelines: Refactors YML files to use OneES Pools for pipelines

---

Microsoft.Azure.Cosmos.Samples/Tools/FaultInjection/src/FaultInjectionServerErrorResult.cs
Microsoft.Azure.Cosmos.Samples/Tools/FaultInjection/src/FaultInjectionServerErrorResultBuilder.cs
Microsoft.Azure.Cosmos.Samples/Tools/FaultInjection/src/implementataion/FaultInjectionRuleProcessor.cs
Microsoft.Azure.Cosmos.Samples/Tools/FaultInjection/src/implementataion/FaultInjectionServerErrorResultInternal.cs
Microsoft.Azure.Cosmos.Samples/Tools/FaultInjection/src/implementataion/FaultInjectionServerErrorRule.cs
Microsoft.Azure.Cosmos.Samples/Tools/FaultInjection/tests/FaultInjectionDirectModeTests.cs

Changed the name of the ApplyPercentage feature to InjectionRate. This should make the function of the feature clearer to users.  This will also be the name of the feature in the Java SDK. 

FaultInjection: Refactors applyPercentage name to injectionRate to make feature clearer.  

---

Microsoft.Azure.Cosmos/src/AssemblyInfo.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/ContractTests.cs

Portal team is migrating our backend to new infrastructure. As a part of this change the service will need access to `AuthorizationHelper`'s [GenerateKeyAuthorizationSignature](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/18a677ace9998450f22598efe43cecb20dea079e/Microsoft.Azure.Cosmos/src/Authorization/AuthorizationHelper.cs#L108C30-L108C63). We are adding Portal Backend to `Microsoft.Azure.Cosmos`'s `InternalsVisibleTo`

[Internal] Visibility: Adds new Portal Backend to Microsoft.Azure.Cosmos InternalsVisibleTo

---

Directory.Build.props

Upgrade Direct package version to 3.34.4
This upgrade contains the following changes:
Pull Request 1350393: Service interop change to utilize the vectorEmbeddings
Pull Request 1364446: Additional checks when parsing the vector embed policy
Pull Request 1359906: Baseline tests added for embedding and vector index parsing
Pull Request 1354385: FaultInjection: Refactors IChaosInterceptor to allow Gateway mode compatibility
Pull Request 1338135: Add in support for MakeList and MakeSet in QueryInfoExtractor

Query: Adds new Direct package version

---

Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/Parallel/ParallelCrossPartitionQueryPipelineStage.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs

Addresses identified performance issue in ParallelCrossPartitionQueryPipelineStage.
Testing of simple cross partition scenario showed up to 4x speedup for the modified code block. More details from internal performance team can be found in #3470.
closes #3470

[Internal] Query: Refactors ParallelCrossPartitionQueryPipelineStage to improve perf

---

Directory.Build.props
Microsoft.Azure.Cosmos.Encryption.Custom/changelog.md
Microsoft.Azure.Cosmos.Encryption.Custom/src/EncryptionContainer.cs
Microsoft.Azure.Cosmos.Encryption.Custom/src/Microsoft.Azure.Cosmos.Encryption.Custom.csproj
Microsoft.Azure.Cosmos.Encryption.Custom/tests/EmulatorTests/LegacyEncryptionTests.cs
Microsoft.Azure.Cosmos.Encryption.Custom/tests/EmulatorTests/MdeCustomEncryptionTests.cs
Microsoft.Azure.Cosmos.Encryption.Custom/tests/Microsoft.Azure.Cosmos.Encryption.Custom.Tests/CosmosEncryptorTests.cs

Adds support for the latest Cosmos Package.
To automatically close an issue: closes #4509

[Client Encryption]: Adds support for latest Cosmos Package.

---

Microsoft.Azure.Cosmos/src/Query/Core/ExceptionToCosmosException.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs

Added `MalformedContinuationToken` Substatus code to BadRequest (400:20007) to exception to clarify why there is a bad request. 
To automatically close an issue: closes #4366

ChangeFeed: Adds MalformedContinuationToken SubstatusCode to exception

---

Microsoft.Azure.Cosmos/src/Telemetry/ClientTelemetry.cs
Microsoft.Azure.Cosmos/src/Telemetry/Collector/TelemetryCollector.cs
Microsoft.Azure.Cosmos/src/Telemetry/NetworkDataRecorder.cs
Microsoft.Azure.Cosmos/src/Telemetry/TelemetryToServiceHelper.cs
Microsoft.Azure.Cosmos/src/Telemetry/VmMetadataApiHandler.cs

This PR would fix this issue: https://github.com/Azure/azure-cosmos-dotnet-v3/issues/4592
To automatically close an issue: closes #4592

[Internal] Client Telemetry: Fixes loggers

---

Microsoft.Azure.Cosmos/src/ChangeFeedProcessor/ChangeFeedProcessorBuilder.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ChangeFeed/GetChangeFeedProcessorBuilderWithAllVersionsAndDeletesTests.cs

Details contained at #4604 
To automatically close an issue: closes #4604

CFP AVAD: Fixes issue where customers are allowed to use WithStartTime and WithStartFromBeginning with CFP AVAD.

---

Microsoft.Azure.Cosmos/src/Resource/Settings/ContainerProperties.cs

For `AnalyticalStoreTimeToLiveInSeconds` there are 3 valid **input** values:
* `0` - disables analytical store
* `-1` - enabled without default
* `>0` - enabled with default value
When reading the value as a service response, `null` is possible if the account has no Analytical Store enabled.
Closes #4634

Documentation: Fixes AnalyticalStoreTimeToLiveInSeconds API documentation to list correct values

---

Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/FeedRange/FeedRangeTests.cs

`Container.GetFeedRangesAsync` performs a read on PartitionKeyRanges leveraging the `PartititonKeyRangeCache`. This translates into an HTTP operation to Gateway.
In cases where Gateway returns a failure (see linked issue), the `GatewayStoreClient` will fail creating a `DocumentClientException`.
In normal circumstances, `PartitionKeyRangeCache` is used within the scope of the Handler pipeline, on which any `DocumentClientException` is converted to `CosmosException`, but because this is a direct invocation, there is nothing doing the conversion and **`DocumentClientException` ends up being thrown to the user**.
The proposed solution applies the conversion at the method level (`GetFeedRangesAsync`) to ensure the `DocumentClientException` is not received by the user.
An alternative that was …

FeedRanges: Fixes GetFeedRangesAsync throwing DocumentClientException

---

Directory.Build.props

This PR is bumping up the `Cosmos.Direct` package version from `3.35.0` to `3.36.0`, which includes the below changes:
- QuorumReader: Strong consistency with invalid (LSN -1) service responses: Adds the LSN verification to the path that `ReadsMultipleReplicas` and `ReadPrimary` involved in Strong/Bounded quorum to make sure that the responses are treated as errors and propagated above.
- Fixes an use case where `PartitionKey.None.GetHashCode()` throws `NullReferenceException`.
- `GoneAndRetryWithRequestRetryPolicy` - Refactors policy to throw `503` Service Unavailable when a `410` Gone Exception with Sub-Status code 1022 is Received.
**Background:** In general `410/1022` is used as a signal to indicate that a region is not part of the dynamic quorum - meaning in global strong with …

Direct Package Upgrade: Fixes `Cosmos.Direct` Package to `3.36.0`

---

Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json

`CosmosClientBuilder.WithAvailibilityStrategy` contains a typo in the word availability and it is inconsistent with `AvailabilityStrategy`.
To automatically close an issue: closes #4668

Hedging: Fixes Typo (WithAvailibilityStrategy -> WithAvailabilityStrategy) in CosmosClientBuilder

---

Microsoft.Azure.Cosmos/src/Routing/RangeJsonConverter.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/FeedRange/FeedRangeTests.cs

[RangeJsonConverter](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Routing/RangeJsonConverter.cs) current defaults are `minInclusive=true` and `maxInclusive=false` 
Fix: For non-defaults the minInclusive and maxInclusive are captured part of the FeedRange serialization

INTERNAL Range: Fixes Range serialization to include minInclusive and maxInclusive

---

Microsoft.Azure.Cosmos/src/ReadManyRequestOptions.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ContainerInlineCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosMultiRegionDiagnosticsTests.cs

Routing: Fixes `ExcludeRegions` for `ReadMany` operation.

---

Microsoft.Azure.Cosmos/src/Resource/Container/Container.cs

Documentation shows **ReadItemAsync** is returning type _ToDoActivity_ instead of _ItemResponse<ToDoActivity>_

Documentation: Fixes ReadItemAsync to show return ItemResponse<ToDoActivity> instead of ToDoActivity

---

azure-pipelines-rolling.yml
azure-pipelines.yml
templates/build-test.yml

[INTERNAL] CI: Fixes excluding performance and code coverage jobs from CI
Performance job: ~36Minutes
Code coverage debug build: 35Minutes
Tests with-out test coverage: 18Minutes
Changes: 
- CI pipeline: Excluded performance and Codecoverage
- Rolling: Will include performance and codecoverage (no change here same as earlier)
Overall long pole is still EmulatorTests but at-least will help us on concurrency.
https://cosmos-db-sdk-public.visualstudio.com/cosmos-db-sdk-public/_build/results?buildId=51336&view=results
https://cosmos-db-sdk-public.visualstudio.com/cosmos-db-sdk-public/_build/results?buildId=51339&view=results

[INTERNAL] CI: Fixes CI excluding performance and codecoverage jobs

---

Microsoft.Azure.Cosmos/src/ActivityScope.cs
templates/build-test.yml

[INTERNAL] CI: Fixes adding auto-retries for tests
Only the failed tests are re-run. Its still possible that that re-run tests might see the state of the container at that time. 
Test needs to be proofed in future.

[INTERNAL] CI: Fixes adding auto-retries for tests

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/EndToEndTraceWriterBaselineTests.cs
azure-pipelines-rolling.yml

- Rolling runs: Flaky ones are excluded (except some emulator issues remaining all failures are from them)
- EndToEndTraceWriterBaselineTests: Making them idempotent (retries are failing)

[INTERNAL] CI: Fixes gates reliability issues

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTelemetryTestsBase.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/InternalFriendsTest.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/HttpHandlerHelper.cs

Removing dependency on `Task.Delay()
`
To automatically close an issue: closes #4731

[Internal] Flaky Test: Fixes Client Telemetry Flaky tests

---

Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosException.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosExceptionTests.cs

Added a check on Cosmos Exception to make sure events are generated only for the allowed status and substatuscode
To automatically close an issue: closes #4735

Open Telemetry Traces: Fixes filtering of event on 404/0 or similar non failure status codes

---

templates/static-tools.yml

[INTERNA] CI: Fixes disabling Binskim as nuget repo failing

[INTERNA] CI: Fixes disabling Binskim as nuget repo failing

---

Microsoft.Azure.Cosmos.Samples/Usage/OpenTelemetry/OpenTelemetry.csproj

Current OpenTelemetry sample gives runtime error due to mismatched OpenTelemetry version. This is tracked in the Otel repo here: https://github.com/open-telemetry/opentelemetry-dotnet/issues/5741
There is no GA Azure Monitor Otel exporter version that uses OpenTelemetry 1.9.0, so we need to manually lift the version to avoid runtime errors.

[Internal] Samples: Fixes OpenTelemetry sample package references

---

Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/AppInsightClassicAttributeKeys.cs
Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryStablityModes.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.BatchOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.BulkOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ChangeFeedAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.MiscellanousAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.PointOperationsExceptionsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.QueryAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ReadFeedAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ReadManyAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.StreamPointOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.TypedPointOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/AssertActivity.cs

As part of this PR, adding back attributes required by appinsights sdk. It broke the customer experience with appinsight as Appinsight SDK supports very specific set of attributes.
This implementation will change in future release, where open telemetry attributes will be controlled by Env Variable as mentioned here.
https://github.com/open-telemetry/semantic-conventions/blob/main/docs/database/database-spans.md#semantic-conventions-for-database-client-calls
**4.42.3**
**v4.43.0**
**v4.43.1**
After this PR:
After this change, customer has to set `OTEL_SEMCONV_STABILITY_OPT_IN` to `database/dup`, in order to see the otel (new and old) attributes. otherwise SDK will emit only classic attributes which would be compatible with appinsights sdk also.
- [] Bug fix (non-breaking change which fixes …

Cherry-Pick Appinsights: Adds classic attribute back to cosmos db to support appinsights sdk (#4781)

---

Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/AppInsightClassicAttributeKeys.cs
Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryCoreRecorder.cs
Microsoft.Azure.Cosmos/src/Telemetry/OpenTelemetry/OpenTelemetryStablityModes.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.BatchOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.BulkOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ChangeFeedAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.MiscellanousAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.PointOperationsExceptionsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.QueryAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ReadFeedAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.ReadManyAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.StreamPointOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/EndToEndTraceWriterBaselineTests.TypedPointOperationsAsync.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/AssertActivity.cs

As part of this PR, adding back attributes required by appinsights sdk. It broke the customer experience with appinsight as Appinsight SDK supports very specific set of attributes.
This implementation will change in future release, where open telemetry attributes will be controlled by Env Variable as mentioned here.
https://github.com/open-telemetry/semantic-conventions/blob/main/docs/database/database-spans.md#semantic-conventions-for-database-client-calls
**4.42.3**
**v4.43.0**
**v4.43.1**
After this PR:
After this change, customer has to set `OTEL_SEMCONV_STABILITY_OPT_IN` to `database/dup`, in order to see the otel (new and old) attributes. otherwise SDK will emit only classic attributes which would be compatible with appinsights sdk also.
- [] Bug fix (non-breaking change which fixes …

Cherry-Pick Appinsights: Adds classic attribute back to cosmos db to support appinsights sdk (#4781) (#4799)

---

Microsoft.Azure.Cosmos/src/Fluent/Settings/ContainerBuilder.cs
Microsoft.Azure.Cosmos/src/Fluent/Settings/IndexingPolicyDefinition.cs
Microsoft.Azure.Cosmos/src/Fluent/Settings/VectorEmbeddingPolicyDefinition.cs
Microsoft.Azure.Cosmos/src/Fluent/Settings/VectorIndexDefinition.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/ContainerProperties.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/DistanceFunction.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/Embedding.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/IndexingPolicy.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/VectorDataType.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/VectorEmbeddingPolicy.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/VectorIndexPath.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/VectorIndexType.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/SettingsContractTests.cs

The purpose of this PR is to mark the new `VectorEmbeddingPolicy` in the `ContainerProperties` as a public surface interface for `GA` release, and introducing new `VectorIndexes` in the `IndexingPolicy` to enable Vector Similarity Search in Cosmos DB ecosystem.
Relevant PRs for the vector similarity work: 
- [ContainerProperties: Adds Vector Embedding and Indexing Policy](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4379)
- [ContainerProperties: Refactors Vector Embedding and Indexing Policy Interfaces to Mark Them as Public for Preview](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4486)
- [VectorIndexDefinition: Adds Support for Partitioned DiskANN](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4792)
To automatically …

ContainerProperties: Refactors Vector Embedding and Indexing Policy Interfaces to Mark Them as Public for GA

---

Microsoft.Azure.Cosmos/src/Fluent/Settings/ContainerBuilder.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Fluent/ContainerSettingsTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/ContainerDefinitionForCreateTests.cs

This PR fixes an issue in the `ContainerBuilder` that was preventing setting the Full Text Policy in Container Properties.
To automatically close an issue: closes #4820

[Internal] ContainerBuilder: Fixes Builder to Set Full Text Policy

---

Microsoft.Azure.Cosmos/src/Fluent/Settings/VectorIndexDefinition.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/VectorIndexPath.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json

This PR removes support for `VectorIndexShardKey` from Preview Contract.

VectorIndexDefinition: Refactors Code to Remove Support for `VectorIndexShardKey` from Preview Contract

---

Directory.Build.props
Microsoft.Azure.Cosmos/contracts/API_3.45.1.txt
Microsoft.Azure.Cosmos/contracts/API_3.46.0-preview.1.txt
changelog.md

This bumps the SDK GA version from `3.45.0` to `3.45.1` and preview version from `3.46.0-preview.0` to `3.46.0-preview.1`. No changes in the public GA contract. The preview contract changes are given below:
This version also bumps up the `Cosmos.Direct` package to `3.37.1`, which includes the below changes:
- Currently Gateway is running into a `NullReferenceException` when hybrid query is supplied for execution. This is because for hybrid queries, `QueryInfo` in the plan is null (and instead `HybridSearchQueryInfo` is non-null). This is resulting in `500 (InternalServerError`) for JS SDK scenarios. The fix adds a `null` check for this.

3.45.1: Adds new SDK versions and contract files

---

Directory.Build.props
Microsoft.Azure.Cosmos/contracts/API_3.45.2.txt
Microsoft.Azure.Cosmos/contracts/API_3.46.0-preview.2.txt
Microsoft.Azure.Cosmos/src/Json/IJsonBinaryWriterExtensions.cs
Microsoft.Azure.Cosmos/src/Json/IJsonWriter.cs
Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.Enumerator.cs
Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.NodeTypes.cs
Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.Numbers.cs
Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.TypeMarker.cs
Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.UniformArrays.cs
Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.ValueLengths.cs
Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.cs
Microsoft.Azure.Cosmos/src/Json/JsonNavigator.JsonBinaryNavigator.cs
Microsoft.Azure.Cosmos/src/Json/JsonReader.JsonBinaryReader.cs
Microsoft.Azure.Cosmos/src/Json/JsonTokenType.cs
Microsoft.Azure.Cosmos/src/Json/JsonWriteOptions.cs
Microsoft.Azure.Cosmos/src/Json/JsonWriter.JsonBinaryWriter.cs
Microsoft.Azure.Cosmos/src/Json/JsonWriter.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Microsoft.Azure.Cosmos.Performance.Tests.csproj
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonNavigatorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonReaderTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonRoundtripTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonTestUtils.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonTokenInfo.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonWriterTests.cs
changelog.md

- JSON Binary Encoding: Adds support for encoding uniform arrays.

[Hotfix] JSON Binary Encoding: Adds support for encoding uniform arrays

---

Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/HybridSearch/FullTextStatistics.cs
Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/HybridSearch/HybridSearchCrossPartitionQueryPipelineStage.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/HybridSearchQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/NonStreamingOrderByQueryTests.cs

During query plan generation, we were using the loop index index over order by expressions as the index for placeholders within component queries. However, VectorDistance expressions do not require placeholders. As a result the output placeholder indexes may not always start at 0. The fix for this is currently in PR on the gateway.
We are putting this workaround in the SDK until the gateway fix is deployed.

Query: Fixes (workaround) for query plan issue where placeholder index does not start at zero

---

Microsoft.Azure.Cosmos/FaultInjection/README.md
Microsoft.Azure.Cosmos/FaultInjection/changelog.md

Adds readme and changelog for FaultInjection Project

[Internal| FaultInjection: Adds docs

---

Microsoft.Azure.Cosmos/FaultInjection/src/FaultInjection.csproj

When generating the package to publish to nuget currently the package has the following error
```
D:\a\_work\1\s\azure-sdk-build-tools\scripts\partition-by-strongname.ps1 : D:\a\_work\1\s\artifacts\temp\ContainerSigning\413018FAC2A26C5052D565C2510DF95BA666EB9BA502E69A99D0F762E02A0FFF\lib\net6.0\Microsoft.Azure.Cosmos.FaultInjection.dll-69c3241e6f0468ca with public key token 69c3241e6f0468ca is NOT strong name signed! (sn returned 1)
```
This should allow it to publish with the a strong named signed 

[Internal] FaultInjection: Fixes csproj so it will generate with a strong signed package name

---

changelog.md

Fixed property name in changelog from DisableNewtonsoftJsonCheck to  AzureCosmosDisableNewtonsoftJsonCheck property name. This change provides the correct property name for disabling newtonsoft dependency build check.
Reference PR: https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4839
To automatically close an issue: closes #4912

Documentation: Fixes changelog for AzureCosmosDisableNewtonsoftJsonCheck property name.

---

Directory.Build.props
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ClientRetryPolicyTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/StoreReaderTest.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Tracing/TraceWriterBaselineTests.cs

This PR bumps up the `Cosmos.Direct` package version to `3.37.3` which is released on top of `EN20241007` release. In a nut-shell, the change is focused on cleaning up the unhealthy dangling connections, that were created as a part of the "Advanced Replica Selection" flow.
**Problem:** One or our recent conversations with the IC3 team has helped us unveiling a potential issue with the RNTBD connection creation and management flow in the `LoadBalancingPartition`. The team is using the .NET SDK version `3.39.0-preview` to connect to cosmos db. Recently they encountered a potential memory leak in some of their clusters and upon investigation, it appeared that one of the root cause is the underlying `CosmosClient` is keeping a high number of unhealthy and unused `LbChannelState`s.
In a nut …

Upgrade Resiliency: Fixes Code to Clean-up Unhealthy Connection and LbChannelState Object.

---

Microsoft.Azure.Cosmos/src/RequestOptions/RequestOptions.cs

RequestOptions: Fixes Etag code documentation

RequestOptions: Fixes Etag code documentation

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosBufferedStreamWrapperTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Utils/JsonGenerator.cs

The tests for CosmosBufferedStreamWrapper ensure it correctly handles complex JSON with nested objects, arrays, GUIDs, and mixed data by testing serialization and deserialization. They check that the wrapper preserves JSON integrity, supports stream reading and resetting, and works reliably for various JSON scenarios.
To automatically close an issue: closes #4719

[Internal] Binary Encoding: Adds unit tests with binary encoding enabled for CosmosBufferedStreamWrapper.

---

Microsoft.Azure.Cosmos/src/DocumentClient.cs
Microsoft.Azure.Cosmos/src/Linq/ExpressionToSQL.cs
Microsoft.Azure.Cosmos/src/Routing/LocationHelper.cs
Microsoft.Azure.Cosmos/src/Telemetry/Collector/TelemetryCollector.cs

Avoid allocating new arrays for separators when splitting strings.
Related code analysis warning https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1861.
Small performance-related change.

Use static readonly arrays for separators

---

Microsoft.Azure.Cosmos.sln
Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
Microsoft.Azure.Cosmos/src/DocumentClient.cs
Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
Microsoft.Azure.Cosmos/src/Handler/ClientPipelineBuilder.cs
Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
Microsoft.Azure.Cosmos/src/RequestOptions/RequestOptions.cs
Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/HandlerTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/RetryHandlerTests.cs

This PR add ThroughputBucket in RequestOptions and ClientOptions to support Throughput Bucketing

ThroughputBucketing: Adds Throughput Bucket to RequestOptions and ClientOptions

---

Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs

Recently during our v3 sdk CI rolling runs, we observed some performance regressions on the `ItemStreamAsync()` APIs. They regressed beyond 5%.
Upon doing further investigation, we figured out that during the non-binary flow, we end up converting the incoming stream into `CloneableStream` which might be the reason for this regression. Please note that the reason this was not caught during the [original version of the binary encoding
PR](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4652) was that the performance test used to capture the benchmark for the original PR, was targeted a real cosmos container, where for the CI runs, we use our mocked containers.
This PR skips `CloneableStream` conversation for non-binary encoding flow.
With the above change in place, our CI builds …

[Hotfix] Binary Encoding: Fixes Performance Regression on CI Pipeline

---

Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
Microsoft.Azure.Cosmos/src/DocumentClient.cs
Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
Microsoft.Azure.Cosmos/src/Routing/AvailabilityStrategy/AvailabilityStrategy.cs
Microsoft.Azure.Cosmos/src/Routing/AvailabilityStrategy/CrossRegionHedgingAvailabilityStrategy.cs
Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
Microsoft.Azure.Cosmos/src/Routing/IGlobalEndpointManager.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosAvailabilityStrategyTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/AvailabilityStrategyUnitTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json

This PR cherry-picks the following commits:
- https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4706
- https://github.com/Azure/azure-cosmos-dotnet-v3/pull/4869

[Hotfix] CrossRegionHedging: Fixes NullReference Exception Bug

---

templates/static-tools.yml

Disabling Post-analysis sub stage in the "Static Analysis" precommit pipeline
Disabling Post-analysis sub stage in the "Static Analysis" precommit pipeline

[Internal] Disable: Removes Post-analysis sub stage in the "Static Analysis" precommit pipeline

---

Directory.Build.props
Microsoft.Azure.Cosmos/src/DocumentClient.cs
Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
Microsoft.Azure.Cosmos/src/Routing/GlobalAddressResolver.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ConnectionStateMuxListenerTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayAddressCacheTests.cs

This PR is for upgrading Direct stack version 3.37.6 the V3 codebase with 3.37.6. 
It contains two changes,
https://msdata.visualstudio.com/CosmosDB/_git/CosmosDB/pullrequest/1505615
: QuorumReader: Fixes bug with BoundedStaleness
https://msdata.visualstudio.com/CosmosDB/_git/CosmosDB/pullrequest/1529101
ConnectionStateListener multiplexing: support multiple CosmosClients (Sharing StoreClient)
It also brings in a dependent change done in OSS codebase 
https://msdata.visualstudio.com/CosmosDB/_git/CosmosSdkOSSClone/pullrequest/1532400?_a=files&path=/Microsoft.Azure.Cosmos/src/DocumentClient.cs

[Internal] Direct: Adds Direct stack 3.37.6 upgrade

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosAvailabilityStrategyTests.cs

Adds test coverage for TooManyRequest scenario

[Internal] Request Hedging: Adds test coverate for TooManyRequestScenario

---

Directory.Build.props

Upgrades SDK Direct package version from 3.37.7 to 3.37.9. 
This version fixes a null reference exception in the Quorum Reader

[Internal] Direct Package: Adds support for direct package version 3.37.9

---

Microsoft.Azure.Cosmos/src/Routing/AvailabilityStrategy/AvailabilityStrategy.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json

Makes `AvailabilityStrategy.DisableAvailabilityStrategy` public for GA consumption. This API is used to override the client level `AvailabilityStrategy`. 

Hedging: Adds GA for DisableAvailabilityStrategy

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Metrics/OpenTelemetryMetricsTest.cs
templates/build-test.yml

As part of this PR, fixing test pipeline.
**Root Cause:** Metrics generation tests were designed to validate only metrics functionality with dimensions. However, with distributed tracing enabled by default in the preview package, the test began asserting traces generated by the distributed tracing feature.
**Resolution:** Disabled the distributed tracing feature in tests to ensure compatibility.

[Internal] Open Telemetry : Fixes preview pipeline test for open telemetry

---

templates/build-test.yml

Updating performance tests timeout period to 120 minutes as now all existing performance tests for point operations run with binary encoding flags enabled and disabled.

[Internal] Binary Encoding: Refactors performance tests timeout period.

---

templates/build-test.yml

Binary Encoding: Refactors performance tests timeout period. (#5009)
Updating performance tests timeout period to 120 minutes as now all existing performance tests for point operations run with binary encoding flags enabled and disabled.
- [] Breaking change (fix or feature that would cause existing functionality to not work as …

[Internal] 3.47.0: Fixes Perf test in release

---

Directory.Build.props
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/ClientTests.cs

- Direct package upgrade to 3.37.10
- Also contains an emulator test to verify connection management during aggressive timeouts.
Brings in the fix from Direct package:
https://msdata.visualstudio.com/CosmosDB/_git/CosmosDB/pullrequest/1574317?_a=files
To automatically close an …

Direct Package: Adds upgrade to 3.37.10

---

Microsoft.Azure.Cosmos/src/Batch/TransactionalBatchOperationResult.cs
Microsoft.Azure.Cosmos/src/Json/Interop/CosmosDBToNewtonsoftReader.cs
Microsoft.Azure.Cosmos/src/Json/Interop/CosmosDBToNewtonsoftWriter.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemIntegrationTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchSchemaTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchUnitTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/NewtonsoftInteropTests.cs

This PR fixes the following:
- Fixes the serialization Gaps on `CosmosDBToNewtonsoftReader` and `CosmosDBToNewtonsoftWriter` for byte[] array read and write respectively.
- Wraps the transactional batch operation result output stream into a `CloneableStream` to de-serialize accurately, when binary encoding is enabled.
To automatically close an issue: closes #5021

[Internal] Binary Encoding: Fixes Serialization Gaps on Newtonsoft Reader/Writer for Transactional Batch

---

Microsoft.Azure.Cosmos/src/Routing/LocationCache.cs
Microsoft.Azure.Cosmos/src/Util/ServicePointAccessor.cs

Don't use ServicePoint at all on Browser.
in net9.0 all of [ServicePoint throws PlatformNotSupported](https://github.com/dotnet/runtime/issues/113174) so don't attempt to use it there.
closes: #5029

.NET9: Fixes WebAssembly or browser scenarios by conditionally setting the ConnectionLimit

---

Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
Microsoft.Azure.Cosmos/src/Serializer/CosmosSerializerCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosReadManyItemsTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/TriggersTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/TestCommon.cs

In the current code, CosmosClient used a default version of CosmosJsonDotNetSerializer as a propertiesSerializer which used the ConfigurationManager.IsBinaryEncodingEnabled() to determine whether to use binary encoding during serialization and de-serialization.
This propertiesSerializer is hooked into multiple serializers to use as internal serializers and caused unexpected behaviors for APIs like ReadManyItems, ChangeFeed and caused a regression.
There are 3 parts of the change:
- As part of this change we are introducing a binary serializer. The default serializer will not just use `propertySerializer` but it will check if the binary encoding flag is enabled and accordingly assign the serializer.
- When a custom serializer is present, on the response path, no matter what we always …

[Internal] Binary Encoding: Fixes serializer for non-point operations. 

---

Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/HybridSearch/HybridSearchCrossPartitionQueryPipelineStage.cs
Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryFeature.cs
Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPlanRetriever.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/HybridSearchQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/NonStreamingOrderByQueryTests.cs

This change adds support for weighted RRF in hybrid search.
We allow weights to be negative but the negative sign is used to signal that we should sort scores in ascending order for the corresponding component. The final WRRF score is then computed using the absolute value of the weight.
In this approach, the sign of the weight indicates the interpretation of the ranking itself rather than directly affecting the calculated score:
`WRRF(d) = ∑ |w_i| × 1/(k + r_i'(d))`
Where:
|w_i| is the absolute value of the weight for the i-th component
r_i'(d) is the rank of document d in the i-th component, with a crucial difference:
- If w_i > 0: r_i'(d) is the original rank (descending order, where 1 is best)
- If w_i < 0: r_i'(d) is the inverted rank (ascending order, where higher number is better) …

Query: Adds support for weighted RRF in hybrid search

---

Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
Microsoft.Azure.Cosmos/src/DocumentClient.cs
Microsoft.Azure.Cosmos/src/Resource/ClientContextCore.cs
Microsoft.Azure.Cosmos/src/Routing/AsyncCache.cs
Microsoft.Azure.Cosmos/src/Routing/AsyncCacheNonBlocking.cs
Microsoft.Azure.Cosmos/src/Routing/ClientCollectionCache.cs
Microsoft.Azure.Cosmos/src/Routing/CollectionCache.cs
Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
Microsoft.Azure.Cosmos/src/Routing/GlobalAddressResolver.cs
Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
Microsoft.Azure.Cosmos/src/Routing/PartitionKeyRangeCache.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Mocks/MockDocumentClient.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncBatcherTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncContainerExecutorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Batch/BatchAsyncOperationContextTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BulkPartitionKeyRangeGoneRetryPolicyTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CancellationTokenTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ChangeFeed/PartitionSynchronizerCoreTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayAddressCacheTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/GatewayStoreModelTest.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyRangeCacheTest.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyRangeHandlerTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Routing/AsyncCacheNonBlockingTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Utils/MockDocumentClient.cs

This PR enables `AsyncCache` and `AsyncCacheNonBlocking` Exception Handling Using `CosmosClientOptions`. This new client option will eventually used to get exception handling optimization (see PR #5069) shipped behind this new client option: `EnableAsyncCacheExceptionSharing`.
By default this option is set to `true`.

[INTERNAL] AsyncCache: Adds Parameter to Enable Exception Handling Using `CosmosClientOptions`

---

Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs
Microsoft.Azure.Cosmos/src/RequestOptions/RequestOptions.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetPreviewSDKAPI.json

This PR Adds changes to make ThroughputBucket RequestOption public for preview SDK

ThroughputBucketing: Adds changes to make ThroughputBucket public for preview SDK

---

.globalconfig
Microsoft.Azure.Cosmos.Encryption.Custom/src/Microsoft.Azure.Cosmos.Encryption.Custom.csproj
Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj
Microsoft.Azure.Cosmos.sln
Microsoft.Azure.Cosmos/FaultInjection/src/FaultInjection.csproj
Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj

In order to detect and prevent certain usages of exceptions within the codebase, analyzers have been added to show messages related to potentially incorrect usage.
Added `Microsoft.Codex.Analyzers` v1.0.5 nuget package
Added .globalconfig file as a baseline configuration

[Internal] Code Quality: Adds Exception Analyzers

---

Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
Microsoft.Azure.Cosmos/src/Handler/AbstractRetryHandler.cs
Microsoft.Azure.Cosmos/src/Routing/GlobalPartitionEndpointManagerCore.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ClientRetryPolicyTests.cs

**Background:**
During one of the backend drills, it was identified that when the following quorum loss condition is met, and the user provides a cancellation token, SDK honors the token, however doesn't apply the partition level fail over for the offending partition:
- Quorum loss injected with the quorum replicas (3 out of 4 replicas are down).
- The primary replica is specifically down.
- A cancellation token with 5 seconds of timeout value is provided.
**Observation:**
- SDK doesn't apply the partition level override and the subsequent write requests fails on the current faulty region/ partition.
**Fix:**
This PR is fixing the above behavior to apply partition level override, when a cancellation token gets expired. In order to avoid false positives, the cancellation token based …

[Internal] ClientRetryPolicy: Adds Code to Apply Partition Level Override When a Requested Cancellation Token Expires

---

Microsoft.Azure.Cosmos/src/Json/IJsonBinaryWriterExtensions.cs
Microsoft.Azure.Cosmos/src/Json/IJsonStringDictionary.cs
Microsoft.Azure.Cosmos/src/Json/JsonBinaryEncoding.Strings.cs
Microsoft.Azure.Cosmos/src/Json/JsonNavigator.JsonBinaryNavigator.cs
Microsoft.Azure.Cosmos/src/Json/JsonNavigator.cs
Microsoft.Azure.Cosmos/src/Json/JsonReader.JsonBinaryReader.cs
Microsoft.Azure.Cosmos/src/Json/JsonReader.cs
Microsoft.Azure.Cosmos/src/Json/JsonStringDictionary.cs
Microsoft.Azure.Cosmos/src/Json/JsonWriter.JsonBinaryWriter.cs
Microsoft.Azure.Cosmos/src/Json/JsonWriter.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Json/JsonRoundTripBenchmarks.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Json/PocoDeserializerBenchmark.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonNavigatorTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonReaderTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonStringDictionaryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonTestUtils.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Json/JsonWriterTests.cs

[Internal] Binary Encoding: Fixes User String Dictionary Interface Name

---

Microsoft.Azure.Cosmos/src/ThinClientStoreClient.cs

Adding ResourceId as the proxy expects the ResourceId in the RNTBD headers otherwise the requests will start to fail.
By seting request.ResourceId = containerRid, TransportSerialization.cs will automatically add the ResourceID header.
To automatically close an issue: closes #5107

[Internal]Thin Client Integration: Adds containerId to ThinClient request.

---

Microsoft.Azure.Cosmos/src/DocumentClient.cs
Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs

Fixing two issues found during testing:
- Fixing the issue of getting thinclient readable and writeable locations through `ParseThinClientLocationsFromAdditionalProperties`. Need this call at `GlobalEndpointManager`. `InitializeAccountPropertiesAndStartBackgroundRefresh()` stage as well otherwise the returned endpoint returned is a stale value.
- Fixing the thinclient mode check so that if thinclient flag is enabled then thinclient mode is be used during gateway mode and direct mode. 
To automatically close an issue: closes #5116

[Internal] Thin Client Integration: Fixes config refresh and gateway mode check.

---

Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CosmosQueryExecutionContextFactory.cs
Microsoft.Azure.Cosmos/src/Query/Core/QueryClient/CosmosQueryClient.cs
Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPartitionProvider.cs
Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPlanHandler.cs
Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPlanRetriever.cs
Microsoft.Azure.Cosmos/src/Query/v2Query/DocumentQueryExecutionContextBase.cs
Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
Microsoft.Azure.Cosmos/src/Query/v3Query/QueryIterator.cs
Microsoft.Azure.Cosmos/src/RequestOptions/QueryRequestOptions.cs
Microsoft.Azure.Cosmos/src/Routing/PartitionRoutingHelper.cs
Microsoft.Azure.Cosmos/src/Util/ConfigurationManager.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/NonStreamingOrderByQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Tracing/EndToEndTraceWriterBaselineTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Performance.Tests/Query/ParsingBenchmark.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/OptimisticDirectExecutionQueryBaselineTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/FullPipelineTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPartitionProviderTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPlanBaselineTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPlanRetrieverTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/SubpartitionTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Routing/PartitionRoutingHelperTest.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Tracing/TraceWriterBaselineTests.cs

This change adds a configuration whose value will be read from the environment variable `AZURE_COSMOS_HYBRID_SEARCH_QUERYPLAN_OPTIMIZATION_DISABLED`. If this evaluates to true, then the optimization for skipping the order by rewrite for hybrid search is disabled.
The environment variable is read, and the value is propagated as an internally visible query request option. This is plumbed down in the query plan APIs where it is either used to populate the supported query features header in case of a gateway or it is used as a flag passed into ServiceInterop.

Query: Adds an environment variable for disabling the hybrid search query plan optimization

---

Directory.Build.props
Microsoft.Azure.Cosmos/FaultInjection/src/FaultInjectionRuleBuilder.cs
Microsoft.Azure.Cosmos/FaultInjection/src/FaultInjectionServerErrorType.cs
Microsoft.Azure.Cosmos/FaultInjection/src/implementation/FaultInjectionServerErrorResultInternal.cs
Microsoft.Azure.Cosmos/contracts/API_3.48.1.txt
Microsoft.Azure.Cosmos/contracts/API_3.49.0.preview.1.txt
Microsoft.Azure.Cosmos/src/ClientRetryPolicy.cs
Microsoft.Azure.Cosmos/src/MetadataRequestThrottleRetryPolicy.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemIntegrationTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/PartitionKeyRangeCacheTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ClientRetryPolicyTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/LocationCacheTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/MetadataRequestThrottleRetryPolicyTests.cs
changelog.md

Currently, there is a bug in the SDK where upon a cold start of the SDK and rare edge cases involving online/offline-ing regions, where only query requests are made, the SDK will not retry certain status code responses from metadata requests causing the entire request to fail. The correct behavior would be for the SDK to do cross region retries on these metadata requests.
This pulls request includes several updates to enhance error handling and retry logic in the Cosmos DB SDK. The changes mainly focus on extending support for additional server error types and improving retry policies for various scenarios.
*
[`ClientRetryPolicy.cs`](diffhunk://#diff-2b056512ca285b1d95e025e31f60345059fa92d958becc38f90a6fb54ce1bbb4R331-R341): Enhanced retry logic to handle `InternalServerError` , …

[Internal] Release: Adds Cherry-Pick Metadata PR Fix to release branch

---

Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
Microsoft.Azure.Cosmos/src/Resource/Container/ContainerCore.Items.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemTests.cs

Create a new internal cosmos client options: `EnableStreamPassThrough` to enable or disable the request/ response stream conversation. When enabled, the request and/or response stream would not be converted to the desired target serialization type and would act just like a pass-through. The default value for this parameter is `False`.
**Usage:**
```
CosmosClientOptions clientOptions = new CosmosClientOptions()
{
EnableStreamPassThrough = true,
};
CosmosClient cosmosClient = new (
endpoint,
authKey,
clientOptions);
```
To automatically close an issue: closes #5122

[Internal] Binary Encoding: Adds Client Option to Enable/Disable Request and Response Stream Conversation

---

Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/PartitionedQueryExecutionInfoInternal.cs
Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPartitionProvider.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPlanRetrieverTests.cs

Fixes flip of boolean switch for hybridSearchSkipOrderByRewrite. Adds test coverage to ensure that we catch stuff like this in the future.

Query: Fixes flip of boolean switch for hybridSearchSkipOrderByRewrite

---

Microsoft.Azure.Cosmos/src/Routing/LocationCache.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/LocationCacheTests.cs

The location cache overrides the thinclient read and write endpoint value with default endpoint value after GetDatabaseAccount refresh call is made. This leads to 410 error getting generated on create and read item requests via thinclient mode due to wrong endpoint value.
As part of the fix, updating the location cache code logic for setting thinclient read and write endpoint location.
To automatically close an issue: closes #5151

[Internal] Thin Client Integration: Fixes location cache update for thinclient read and write locations.

---

Microsoft.Azure.Cosmos/src/Linq/BuiltinFunctions/OtherBuiltinSystemFunctions.cs
Microsoft.Azure.Cosmos/src/Linq/CosmosLinqExtensions.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestFullTextScoreOrderByRankFunction.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/BaselineTest/TestBaseline/LinqTranslationBaselineTests.TestRRFOrderByRankFunction.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Linq/LinqTranslationBaselineTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json

This PR changes the function signature for RRF, OrderByRank and FullTextScore for LINQ extension methods to more closely align with vector distance

Query: Fixes function signature for RRF, OrderByRank and FullTextScore LINQ extension methods

---

Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/HybridSearch/HybridSearchCrossPartitionQueryPipelineStage.cs
Microsoft.Azure.Cosmos/src/Query/Core/Pipeline/CrossPartition/HybridSearch/HybridSearchQueryResult.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/Pipeline/NonStreamingOrderByQueryTests.cs

Adds support for the optimized query plan that skips the order by rewrite. The new hybrid search component query plan "lies" to the SDK about there being no ORDER BY on the component queries. However, the hybrid search query pipeline stage knows that the component scores need to be sorted. Since there is no information about this sorting on the query plan anymore, the hybrid search query pipeline stage will always sort descending in this scenario. The component score projections are rewritten to safeguard this assumption.
This change is backward compatible so that the SDK can accept both the old style query plan with rewritten ORDER BY as well as the new one that skips the order by rewrite.
The end user can disable the optimized query plan by setting the environment variable …

Query: Adds support for the optimized query plan that skips the order by rewrite

---

Microsoft.Azure.Cosmos/src/RequestOptions/QueryRequestOptions.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/NonStreamingOrderByQueryTests.cs

#5120 enabled the switch to ask for the optimized query plan by default. However, the pipeline support for the optimized query plan is in #5121. This will lead to exceptions in the hybrid search query pipeline in version 3.49.0 if the SDK talks to a newer gateway that can return the optimized query plan. To prevent this, we change this optimization to be disabled by default.

Query: Fixes default for the query plan optimization for Hybrid Search to be disabled

---

Microsoft.Azure.Cosmos/src/Resource/Settings/FullTextPath.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Fluent/ContainerSettingsTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Contracts/DotNetSDKAPI.json
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosContainerSettingsTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Fluent/ContainerDefinitionForCreateTests.cs

Query: Fixes FullText Policy API by making language optional

---

Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
Microsoft.Azure.Cosmos/src/Routing/GlobalPartitionEndpointManagerCore.cs
Microsoft.Azure.Cosmos/src/Util/ConfigurationManager.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemIntegrationTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyRangeFailoverTests/GlobalPartitionEndpointManagerTests.cs

This PR does the following two things:
- Enables Cross Regional Hedging by default with a threshold of either `1` second or half of the request timeout value provided, whichever is minimum, when PPAF is enabled. Note that the default availability strategy can be opted out by setting the `AvailabilityStrategy` to `DisabledAvailabilityStrategy` in the `CosmosClientOptions`. To understand this better, please take a look at the example below:
CosmosClientOptions cosmosClientOptions = new CosmosClientOptions()
{
EnablePartitionLevelFailover = true,
ConsistencyLevel = Cosmos.ConsistencyLevel.Strong,
AvailabilityStrategy = new DisabledAvailabilityStrategy(),
};
- As of today, during the cosmos client initialization, with PPAF enabled we ensure that either the `ApplicationRegion` or …

[Internal] PPAF: Adds Code to Enable Read Hedging By Default

---

Microsoft.Azure.Cosmos/src/Routing/AvailabilityStrategy/CrossRegionHedgingAvailabilityStrategy.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosAvailabilityStrategyTests.cs

This pull request refactors the `CrossRegionHedgingAvailabilityStrategy` class in the Azure Cosmos SDK to fix a rare concurrency issue regarding session tokens and improve diagnostics for improved debugging.. It also updates related tests to align with the changes. The most important changes include replacing the `Response Region` diagnostic with a new `Hedge Config` diagnostic, modifying the `HedgingResponse` class, and updating test cases to validate the new behavior. the `Response Region` field can sometimes be inaccurate with internal cross regional retries so it has been removed. To find the response region, you can look at the existing store response to see where the response came from. 
- [] Bug fix (non-breaking change which fixes an …

Hedging: Fixes Concurrency Issue

---

Microsoft.Azure.Cosmos/src/CosmosClientOptions.cs
Microsoft.Azure.Cosmos/src/Fluent/CosmosClientBuilder.cs

This is a public documentation update for the Session Consistency Retries policy in the CosmosClientOption and CosmosClientBuilder to provide clarity on what the EnableRemoteRegion bool does for the client in terms of retries.

[Internal]API-Documentation: Fixes session retry optimization public docs

---

Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs

Internal: Fixes the race condition where a background tasks fails and try to access a disposed object.

[Internal]: Fixes the Observed exception (ObjectDisposedException) in GlobalEndpointManager

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemThinClientTests.cs
azure-pipelines.yml
templates/build-test.yml
templates/build-thinclient.yml

Adds pipeline to allow integration tests to run for thinclient test scenarios. Creating a separate pipeline which does not impact the main PR pipeline as the thinclient tests are still unstable. Adding new endpoint variable dotnet-v3-CI pipeline $(COSMOSDB_THINCLIENT).
Test Results:
- When Thinclient category tests are failing, it does not impact the entire pipeline(optional) and allows PR merge.
https://cosmos-db-sdk-public.visualstudio.com/cosmos-db-sdk-public/_build/results?buildId=55136&view=results
- Pipeline failing when tests other than thinclient tests fail.
To automatically close an issue: closes #5144

[Internal] Thin Client Integration: Adds runner tests for thinclient test scenarios.

---

Directory.Build.props
Microsoft.Azure.Cosmos.Encryption/changelog.md
Microsoft.Azure.Cosmos.Encryption/src/EncryptionContainer.cs
Microsoft.Azure.Cosmos.Encryption/src/Microsoft.Azure.Cosmos.Encryption.csproj

Adds support for latest Cosmos package and bumps up Encryption package for nuget release.

Client Encryption: Adds support for latest Cosmos package and bumps up Encryption package for nuget release.

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemIntegrationTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyRangeFailoverTests/GlobalPartitionEndpointManagerTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyRangeFailoverTests/MockSetupsHelper.cs

Recently, we started observing in our CI pipeline gates that, the gateway started returning the ppaf enablement flag as `False` (instead of `null`) for the account used for end to end test. Below are the significance of the values returned from the gateway:
| Flag    | GW Response | Description |
| -------- | ------- | ------- |
| `enablePerPartitionFailoverBehavior`  | `True`    | PPAF was enabled for the account.
| `enablePerPartitionFailoverBehavior`  | `False`    | PPAF was manually disabled for the account.
| `enablePerPartitionFailoverBehavior`  | `null`     | PPAF was never set for the account.
| `enablePerPartitionFailoverBehavior`  | flag not present     | PPAF was never set for the account.
This PR fixes the integration test by intercepting the …

[Internal] PPAF: Fixes Integration Tests to Intercept Gateway Response

---

Microsoft.Azure.Cosmos/src/Diagnostics/UserAgentFeatureFlags.cs
Microsoft.Azure.Cosmos/src/DocumentClient.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs

This PR adds the following new features in the [UserAgentFeatureFlags](https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/src/Diagnostics/UserAgentFeatureFlags.cs), so that the diagnostics user agent can contain the thin client enablement flag:
- A new Feature Flag for Thin Client.
- A new Feature Flag for Binary Encoding.
- A new Feature Flag for Http 2.0.
```csharp
internal enum UserAgentFeatureFlags
{
PerPartitionAutomaticFailover = 1,
PerPartitionCircuitBreaker = 2,
ThinClient = 4,
BinaryEncoding = 8,
Http2 = 16
}
```
An updated user agent will look like the following: 
`"User Agent": "cosmos-netstandard-sdk/3.51.0|1|X64|Microsoft Windows 10.0.26100|.NET 6.0.36|L|F4|"` if only thin-client is enabled.
To …

[Internal] Thin Client Integration: Adds Diagnostics User Agent info for Thin Client Feature

---

Directory.Build.props
Microsoft.Azure.Cosmos/contracts/API_3.52.1.txt
Microsoft.Azure.Cosmos/contracts/API_3.53.0-preview.1.txt
Microsoft.Azure.Cosmos/src/Handler/RequestInvokerHandler.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemIntegrationTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/RetryHandlerTests.cs
changelog.md

Includes the following commit in the patch version release besides the required file changes for version upgrade to 3.52.1
QueryPlan : Fixes 410 Gone Exception on non-x64 platforms https://github.com/Azure/azure-cosmos-dotnet-v3/pull/5257

3.52.1: Adds Patch release 3.52.1 

---

Microsoft.Azure.Cosmos/src/Query/Core/QueryPlan/QueryPlanRetriever.cs
Microsoft.Azure.Cosmos/src/Query/v2Query/DefaultDocumentQueryExecutionContext.cs
Microsoft.Azure.Cosmos/src/Query/v2Query/DocumentQueryExecutionContextFactory.cs
Microsoft.Azure.Cosmos/src/Query/v3Query/CosmosQueryClientCore.cs
Microsoft.Azure.Cosmos/src/Util/ConfigurationManager.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/SanityQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/SmokeTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/Query/QueryPlanRetrieverTests.cs

This change adds an override for bypassing query parsing using environment variable.
To leverage this switch, one can set AZURE_COSMOS_BYPASS_QUERY_PARSING set to true in process' environment variables.

[Internal] Query: Adds override for bypassing query parsing using environment variable

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/HybridSearchQueryTests.cs

The most recent emulator release has backend fixes for phrase search. Earlier the search phrase "United States" would match any documents that had the token "United". This was recently fixed so that the backend returns only those documents that have the complete phrase "United States". This change modifies the test expectations accordingly.

Query: Fixes HybridSearchQueryTests to account for backend changes in phrase search

---

Microsoft.Azure.Cosmos/src/AppConfig.cs
Microsoft.Azure.Cosmos/src/Authorization/AuthorizationTokenProviderMasterKey.cs
Microsoft.Azure.Cosmos/src/DocumentClient.cs
Microsoft.Azure.Cosmos/src/Routing/GatewayAddressCache.cs
Microsoft.Azure.Cosmos/src/Routing/GlobalEndpointManager.cs
Microsoft.Azure.Cosmos/src/Routing/LocationCache.cs
Microsoft.Azure.Cosmos/src/TrimmingAttributes/FeatureSwitchDefinitionAttribute.cs
Microsoft.Azure.Cosmos/src/direct/ReplicatedResourceClient.cs

Certain code paths check settings using ConfigurationManager APIs that are not trim-compatible.
This adds a feature switch that can be used to disable this behavior in trimmed apps.
There's precedent for ignoring these config options as indicated by the existing checks for `GetEntryAssembly()`.
Fixes this warning from Azure MCP, which was coming a transitive reference to ConfigurationManager through CosmosDB.
```
ILC : Trim analysis warning IL2067: System.Configuration.TypeUtil.CreateInstance(Type): 'type' argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicParameterlessConstructor', 'DynamicallyAccessedMemberTypes.NonPublicConstructors' in call to 'System.Activator.CreateInstance(Type,Boolean)'. The parameter 'type' of method …
```

[msdata/direct] Add feature switch to disable ConfigurationManager

---

Microsoft.Azure.Cosmos/src/Authorization/TokenCredentialCache.cs
Microsoft.Azure.Cosmos/src/Util/ConfigurationManager.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosAadTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Query/HybridSearchQueryTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/Utils/LocalEmulatorTokenCredential.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosAuthorizationTests.cs

This PR is a hotfix and cherry picks this commit:
[TokenCredentialCache: Adds an options to override AAD audience scope](https://github.com/Azure/azure-cosmos-dotnet-v3/commit/d301474cf895270ba6e710698daf5d5166a3b66f)
[Initial PR](https://github.com/Azure/azure-cosmos-dotnet-v3/pull/5252)
Add AAD audience scope override functionality when this environment variable is set AADScopeOverride = "AZURE_COSMOS_AAD_SCOPE_OVERRIDE". If no environment variable is et then it uses the existing default scope value.
This will help clients in accessing applications which have a different scope.

[Hotfix] TokenCredentialCache: Adds an options to override AAD audience scope.

---

Microsoft.Azure.Cosmos/src/FeedRange/Continuations/FeedRangeCompositeContinuation.cs
Microsoft.Azure.Cosmos/src/HttpClient/CosmosHttpClientCore.cs
Microsoft.Azure.Cosmos/src/Resource/CosmosExceptions/CosmosExceptionFactory.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/CosmosSerializerContext.cs
Microsoft.Azure.Cosmos/src/Serializer/FeedRange/FeedRangeCompositeContinuationConverter.cs
Microsoft.Azure.Cosmos/src/Serializer/FeedRange/FeedRangeInternalConverter.cs
Microsoft.Azure.Cosmos/src/direct/JSonSerializable.cs

- Fixes 6 AOT violations from `FeedRangeInternalConverter`, `CosmosExceptionFactory` and `CosmosHttpClientCore`

[Internal] Feed Range: Fixes 6 AOT violations from `FeedRangeInternalConverter`, `CosmosExceptionFactory` and `CosmosHttpClientCore`

---

templates/build-preview-msdata.yml

Removing Microsoft.Azure.Cosmos.Encryption.Custom Project Ref build pipeline from msdata-preview list

[Internal] msdata/direct: Removes encryption.custom from pipeline runs

---

azure-pipelines-msdata-aot.yml
templates/build-internal-aot.yml

[Internal]AOT: Fixes build steps by creating a new build template

---

Microsoft.Azure.Cosmos/src/GatewayStoreModel.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/CosmosItemThinClientTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/PartitionKeyRangeFailoverTests/RegionFailoverTests.cs
azure-pipelines-msdata-direct.yml
azure-pipelines.yml
templates/build-thinclient.yml

With the existing code, query requests are getting 400/1041 error response which indicates that proxy is returning an error due to missing headers. This is happening because it appears that the .NET SDK is not sending the startepk and endEpk headers, as the resolved partition key range is appearing to be null. So, these required headers are appearing missing at the proxy layer and hence the operation fails.
Updated the check in GatewayStoreModel to ensure that it resolves partitionKeyRange and added more tests to cover different consistencies for query operations.
To automatically close an issue: closes #5343

[Internal] Thin Client Integration: Fixes 400/1041 Error for Query Operations in Thin Client Mode.

---

Microsoft.Azure.Cosmos.sln
Microsoft.Azure.Cosmos/src/AssemblyInfo.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests.Aot/Common/ConfigurationManager.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests.Aot/Common/RestHelper.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests.Aot/Common/TestUtil.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests.Aot/MSTestSettings.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests.Aot/Microsoft.Azure.Cosmos.Tests.Aot.csproj
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests.Aot/Query/QueryTest.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests.Aot/RestHelperTest.cs

This change adds a new test project for AOT purposes. Existing test projects are not AOT compliant. They are also unable to reference the AOT product dll, since much of the functionality has been removed (for e.g. database and collection CRUD API, LINQ, ChangeFeed to name a few). This generates over 1000 errors on the emulator test project alone and it's not tenable at the moment to address those all in time.
The purpose of this new dll is to serve as a smoke test/validation. Over time, it is expected to contain a subset of tests that are required to have sufficient confidence in quality of AOT flavor of product code.
Since database/collection CRUD functionality is not available in the AOT SDK, the test dll contains a ```RestHelper``` to facilitate common management operations at …

[Internal] Query : Adds new test project for AOT

---

Microsoft.Azure.Cosmos/src/DocumentClientEventSource.cs

Same idea as https://github.com/Azure/azure-cosmos-dotnet-v3/pull/5388, but this provides appropriate attributes to mark the use as safe.
The long-term goal here should be to add a net8 target to validate that this is correct.

Add annotations and suppressions for safe EventSource usage

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/GatewayTests.cs

Our emulator tests
ValidateUserDefinedFunctionsBlacklisting
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/GatewayTests.cs#L2422
ValidateUserDefinedFunctionsBlacklistingInternal
https://github.com/Azure/azure-cosmos-dotnet-v3/blob/master/Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/GatewayTests.cs#L2251
These tests rely on the config `StoredProcedureMaximumChargeInSeconds`  and as a threshold value for the number of times an overcharged script will be run before its Blacklisted by Foreboding it. This config max default value has been changed from 2 to 5 and the emulator uses the default value in the pipeline.
https://msdata.visualstudio.com/_git/CosmosDB/commit/549cf989d273604e42023dcf3c1210 …

[Internal] Pipeline: Fixes pipelines by fixing the StoredProc and UserDefined Script Blacklisting emulator tests

---

Directory.Build.props

- Fixes Newtonsoft package latest version to avoid CVE Vulnerability #5407

[Internal] AOT: Adds 0.1.3-preview.1 release

---

Directory.Build.props
Microsoft.Azure.Cosmos/src/DocumentClient.cs
Microsoft.Azure.Cosmos/src/Resource/Settings/AccountProperties.cs
Microsoft.Azure.Cosmos/src/ThinClientTransportSerializer.cs
Microsoft.Azure.Cosmos/src/Tracing/TraceWriter.TraceJsonWriter.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.EmulatorTests/DocumentClientUnitTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/BaselineTest/TestBaseline/TraceWriterBaselineTests.TraceData.xml
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosJsonSerializerUnitTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosSerializerCoreTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/StoreReaderTest.cs

Feature: N-region synchronous commit support for < Strong consistency in SDK)
This PR brings in N region syncrhonous commit for accounts that have this feature enabled. The feature primarly brings in Barrier requests for Writes for less than Strong consistencies
The change contains two parts (one part is in this PR and other is done in Msdata/released as Direct package version 3.41.0 which is consumed in this PR)
Part 2 **THIS PR** : V3 Repo changes which include changes in AccountProperties to read the support for Nregion Commit .
-Adds support for including nregioncommit account feature while creating StoreClient within DocumentClient
Part 1 CHanges to ConsistencyWriter for adding Barrier requests and StoreResult to support the new NRegionCommittedGLSN which is critical to performing …

[Internal]Nregion: Adds support for including nregioncommit synchronous for less than Strong Consistency

---

Microsoft.Azure.Cosmos/src/Resource/Settings/VectorDataType.cs

This PR fixes the enum ordering for `Float16` value in `VectorDataType` to avoid any unnecessary issues in the future.
To automatically close an issue: closes #5367

VectorDataType: Fixes Enum Ordering for `Float16` Data Type

---

Directory.Build.props
Microsoft.Azure.Cosmos/src/Microsoft.Azure.Cosmos.csproj

- Upgraded Newtonsoft to latest version 13.0.4 that support Trim Annotations
- Directory.build.props changes

[Internal] AOT: Adds version bump up to 0.1.4-preview.2 release

---

Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/ActiveClientDiagnosticTest.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientOptionsUnitTests.cs
Microsoft.Azure.Cosmos/tests/Microsoft.Azure.Cosmos.Tests/CosmosClientTests.cs

Renaming cosmos endpoints and keys to dummy endpoint in unit tests. So that it won't be caught up in MSRC.

MSRC: Fixes dummy account endpoint and keys in tests
